Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2020-05, with the labels that each got.

#827 CMS Export System (CEX, formerly known as Tome Sync)
  composer.json
  composer.lock
  config/sync/core.extension.yml
  docroot/modules/custom/va_gov_content_export/src/AddBreadcrumbToEntity.php
  docroot/modules/custom/va_gov_content_export/src/Archive/ArchiveArgs.php
  docroot/modules/custom/va_gov_content_export/src/Archive/ArchiveArgsFactory.php
  docroot/modules/custom/va_gov_content_export/src/Archive/ArchiveDirectory.php
  docroot/modules/custom/va_gov_content_export/src/Controller/ContentExport.php
  docroot/modules/custom/va_gov_content_export/src/Normalizer/ContentEntityNormalizer.php
  docroot/modules/custom/va_gov_content_export/src/TarAdapter.php
  docroot/modules/custom/va_gov_content_export/src/TarStrategy.php
  docroot/modules/custom/va_gov_content_export/src/TomeExporter.php
  docroot/modules/custom/va_gov_content_export/src/TomeFileSync.php
  docroot/modules/custom/va_gov_content_export/src/VaGovContentExportServiceProvider.php
  docroot/modules/custom/va_gov_content_export/va_gov_content_export.info.yml
  docroot/modules/custom/va_gov_content_export/va_gov_content_export.module
  docroot/modules/custom/va_gov_content_export/va_gov_content_export.routing.yml
  docroot/modules/custom/va_gov_content_export/va_gov_content_export.services.yml
  docroot/modules/custom/zippylib/README.md
  docroot/modules/custom/zippylib/composer.json
  docroot/modules/custom/zippylib/src/ZippyFactory.php
  docroot/modules/custom/zippylib/zippylib.info.yml
  docroot/modules/custom/zippylib/zippylib.services.yml
  docroot/sites/default/settings.devshop.php
  docroot/sites/default/settings.php
Labels: ⭐️ Infrastructure

#1755 VACMS-1753 Webform Drupal SA-2020-018
  composer.lock
  config/sync/webform.webform.request_cms_user.yml
Labels: Drupal engineering, security

#1772 Remove --verbose from sync-files.sh, way too many files now, crashes browser in Jenkins.
  scripts/sync-files.sh
Labels: DevOps

#1804 VACMS-1797 Security update SA-CORE-2020-002
  composer.json
  composer.lock
Labels: Unplanned work, security

#1806 VAGOV-1657: Increase PerformanceLoginTest ceiling from 2 to 3.
  tests/phpunit/CreateMediaTest.php
  tests/phpunit/CreateTaxonomyTermTest.php
  tests/phpunit/PerformanceCreateNodeTest.php
  tests/phpunit/PerformanceEditNodeTest.php
  tests/phpunit/PerformanceLoginTest.php
  tests/phpunit/PerformancePreviewTest.php
Labels: DevOps, Performance

#1807 VACMS-000: Remove outdated /docker folder and settings.test.php.
  docker/config/certs/ca-setup.yml
  docker/config/certs/lndo.site.key
  docker/config/certs/lndo.site.pem
  docker/config/certs/lndo.srl
  docker/config/certs/vagov-trusted-ca.pem
  docker/config/engine/scripts/add-cert.sh
  docker/config/engine/scripts/check-health-cms-service.sh
  docker/config/engine/scripts/lando-entrypoint-app.sh
  docker/config/engine/scripts/lando-entrypoint.sh
  docker/config/engine/scripts/load-keys.sh
  docker/config/engine/scripts/refresh-certs.sh
  docker/config/engine/scripts/setup-ca.sh
  docker/config/engine/scripts/user-perms.sh
  docker/config/engine/scripts/wait-for-it.sh
  docker/config/services/config/drupal7/drupal7.conf
  docker/config/services/config/drupal7/mysql/my.cnf
  docker/config/services/config/drupal7/php.ini
  docker/config/services/config/drupal8/drupal8.conf
  docker/config/services/config/drupal8/mysql/my.cnf
  docker/config/services/config/drupal8/php.ini
  docker/config/services/config/php/5.3-apache/apache2.conf
  docker/config/services/config/php/5.3-fpm/php-fpm.conf
  docker/config/services/config/php/default-ssl.conf
  docker/config/services/config/php/default.conf
  docker/config/services/config/php/httpd-ssl.conf
  docker/config/services/config/php/httpd.conf
  docker/config/services/config/php/php.ini
  docker/config/services/config/php/zz-lando.conf
  docker/config/services/helpers/sql-export.sh
  docker/config/services/helpers/sql-import.sh
  docker/env_files/common.env
  docker/images/va-socks-proxy/Dockerfile
  docker/images/va-socks-proxy/entrypoint.sh
  docker/templates/settings.lando.php.tpl
  docker/templates/ssmtp.ini.tpl
  docker/templates/ssmtp.revaliases.tpl
  docker/templates/ssmtp.tpl
  docroot/sites/default/settings/settings.test.php
Labels: DevOps

#1827 [docs] Add initial CMS Export documentation.
  README.md
  READMES/cms-export.md
Labels: content-export, documentation
