Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2020-12, with the labels that each got.

#3611 Restore vets-website to use version in composer instead of commit
  composer.json
  composer.lock
Labels: Core Application Team, Product Support Team

#3620 Add code scanning
  .github/workflows/codeql.yml
Labels: Core Application Team, security

#3613 VACMS-2260-CLP-Stories-Panel
  config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_form_display.paragraph.link_teaser_with_image.default.yml
  config/sync/core.entity_view_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_view_display.node.campaign_landing_page.teaser.yml
  config/sync/core.entity_view_display.paragraph.link_teaser_with_image.default.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_stories_cta.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_stories_header.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_stories_intro.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_stories_panel.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_stories_teasers.yml
  config/sync/field.field.paragraph.link_teaser_with_image.field_link_teaser.yml
  config/sync/field.field.paragraph.link_teaser_with_image.field_media.yml
  config/sync/field.storage.node.field_clp_stories_cta.yml
  config/sync/field.storage.node.field_clp_stories_header.yml
  config/sync/field.storage.node.field_clp_stories_intro.yml
  config/sync/field.storage.node.field_clp_stories_panel.yml
  config/sync/field.storage.node.field_clp_stories_teasers.yml
  config/sync/field.storage.paragraph.field_link_teaser.yml
  config/sync/paragraphs.paragraphs_type.link_teaser_with_image.yml
  tests/behat/drupal-spec-tool/content_model_bundles.feature
  tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature
Labels: Product Support Team

#3599 VACMS-3555: Limit tz choices.
  config/sync/core.entity_form_display.node.event.default.yml
  config/sync/core.entity_form_display.paragraph.situation_update.default.yml
Labels: Product Support Team

#3582 VACMS-3569: Added Editorial workflow to VAMC Facility Health Service
  config/sync/core.entity_form_display.node.health_care_local_health_service.default.yml
Labels: Product Support Team

#3581 VACMS-3467: CLP Video Panel
  composer.json
  composer.lock
  config/sync/core.entity_form_display.media.video.default.yml
  config/sync/core.entity_form_display.media.video.media_browser.yml
  config/sync/core.entity_form_display.media.video.media_library.yml
  config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_view_display.media.video.default.yml
  config/sync/core.entity_view_display.media.video.embedded.yml
  config/sync/core.entity_view_display.media.video.thumbnail.yml
  config/sync/core.entity_view_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_view_display.node.campaign_landing_page.teaser.yml
  config/sync/core.extension.yml
  config/sync/field.field.media.video.field_description.yml
  config/sync/field.field.media.video.field_duration.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_spotlight_panel.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_video_panel.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_video_panel_header.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_video_panel_more_video.yml
  config/sync/field.field.node.campaign_landing_page.field_media.yml
  config/sync/field.storage.media.field_duration.yml
  config/sync/field.storage.node.field_clp_spotlight_panel.yml
  config/sync/field.storage.node.field_clp_video_panel.yml
  config/sync/field.storage.node.field_clp_video_panel_header.yml
  config/sync/field.storage.node.field_clp_video_panel_more_video.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  tests/behat/drupal-spec-tool/content_model_campaign_landing_page_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_media_fields.feature
Labels: Product Support Team

#3627 VACMS_3616: Add html table field html removal script.
  scripts/content/VACMS-3616-remove-tablefield-tags-2020-12.php
Labels: Product Support Team

#3587 VACMS-3451: Make link_field required on link_teaser paragraph type.
  config/sync/field.field.paragraph.link_teaser.field_link.yml
  tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature
  tests/behat/features/save_and_continue.feature
Labels: Core Application Team

#3649 VACMS-3633: Do not set va build flag on devshop front end builds
  docroot/modules/custom/va_gov_build_trigger/src/Form/BuildTriggerForm.php
  docroot/modules/custom/va_gov_build_trigger/src/Service/BuildFrontend.php
Labels: Core Application Team

#3612 VACMS-3246: enable performance modules
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/system.performance.yml
  docroot/themes/custom/vagovadmin/assets/css/styles.css
  docroot/themes/custom/vagovadmin/assets/css/styles.css.map
  docroot/themes/custom/vagovadmin/assets/css/styles.min.css
  docroot/themes/custom/vagovadmin/assets/css/styles.min.css.map
  docroot/themes/custom/vagovadmin/assets/scss/_toolbar.scss
  docroot/themes/custom/vagovadmin/templates/big-pipe-interface-preview--block--node-link-report.html.twig
  tests/behat/Drupal/BigPipeContext.php
  tests/behat/behat.yml
Labels: Core Application Team

#3630 VACMS-3629: automatically lint custom (s)css
  .github/workflows/stylelint-modules.yml
  .github/workflows/stylelint-themes.yml
  .stylelintrc
  READMES/code-review.md
  READMES/local.md
  composer.json
  docroot/modules/custom/va_gov_backend/css/system_style.css
  docroot/modules/custom/va_gov_user/css/sections_accordion.css
  docroot/themes/custom/vagovadmin/assets/css/proofing.css
  docroot/themes/custom/vagovadmin/assets/css/proofing.css.map
  docroot/themes/custom/vagovadmin/assets/css/styles.css
  docroot/themes/custom/vagovadmin/assets/css/styles.css.map
  docroot/themes/custom/vagovadmin/assets/css/styles.min.css
  docroot/themes/custom/vagovadmin/assets/css/styles.min.css.map
  docroot/themes/custom/vagovadmin/assets/css/user_guides.css
  docroot/themes/custom/vagovadmin/assets/css/user_guides.css.map
  docroot/themes/custom/vagovadmin/assets/css/wysiwyg.css
  docroot/themes/custom/vagovadmin/assets/css/wysiwyg.css.map
  docroot/themes/custom/vagovadmin/assets/scss/_external_content.scss
  docroot/themes/custom/vagovadmin/assets/scss/_mixins.scss
  docroot/themes/custom/vagovadmin/assets/scss/_paragraphs.scss
  docroot/themes/custom/vagovadmin/assets/scss/_services.scss
  docroot/themes/custom/vagovadmin/assets/scss/_toolbar.scss
  docroot/themes/custom/vagovadmin/assets/scss/_tooltip.scss
  docroot/themes/custom/vagovadmin/assets/scss/_undo_field_styling.scss
  docroot/themes/custom/vagovadmin/assets/scss/proofing.scss
  docroot/themes/custom/vagovadmin/assets/scss/styles.scss
  docroot/themes/custom/vagovadmin/assets/scss/user_guides.scss
  docroot/themes/custom/vagovadmin/assets/scss/wysiwyg.scss
  hooks/git/pre-commit
  package-lock.json
  package.json
Labels: Core Application Team

#3656 VACMS-3655: Use github action for phpcs static analysis
  .github/workflows/phpcs.yml
  tests.yml
Labels: Core Application Team

#3673 VACMS-3672: Fix linting issues
  docroot/themes/custom/vagovadmin/assets/css/styles.css
  docroot/themes/custom/vagovadmin/assets/css/styles.css.map
  docroot/themes/custom/vagovadmin/assets/css/styles.min.css
  docroot/themes/custom/vagovadmin/assets/css/styles.min.css.map
  docroot/themes/custom/vagovadmin/assets/scss/_toolbar.scss
Labels: Core Application Team

#3704 Use the correct method to the the message
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRD.php
Labels: Core Application Team, Drupal engineering

#3722 Change Tugboat online step to not report status to github outside of PRs
  .tugboat/config.yml
Labels: DevOps

#3614 VACMS-3378: Selecting and unselecting "Reusable" shows and hides the "Save and select" button...
  docroot/modules/custom/va_gov_backend/js/media_library_add_form_upload.js
  docroot/modules/custom/va_gov_backend/va_gov_backend.libraries.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Core Application Team

#3653 VACMS-3607: Disables grid view in Media Library.
  config/sync/views.view.media_library.yml
  tests/behat/Drupal/FeatureContext.php
  tests/behat/features/user.feature
Labels: Core Application Team

#3637 VACMS-3436: Improves link experience on help center pages.
  config/sync/field.field.paragraph.downloadable_file.field_media.yml
  config/sync/paragraphs.paragraphs_type.downloadable_file.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  docroot/themes/custom/vagovadmin/assets/css/styles.css
  docroot/themes/custom/vagovadmin/assets/css/styles.css.map
  docroot/themes/custom/vagovadmin/assets/scss/styles.scss
  docroot/themes/custom/vagovadmin/images/icons/download-000000.svg
  docroot/themes/custom/vagovadmin/images/icons/play-000000.svg
  docroot/themes/custom/vagovadmin/templates/paragraph/paragraph--downloadable-file--documentation-page.html.twig
  docroot/themes/custom/vagovadmin/templates/paragraph/paragraph--downloadable-file.html.twig
  tests/behat/Drupal/FeatureContext.php
  tests/behat/features/downloadable_file.feature
  tests/behat/features/perms.feature
  tests/behat/features/save_and_continue.feature
Labels: Core Application Team

#3732 VACMS-3731 Add content newer content types to alert block scope.
  config/sync/field.field.block_content.alert.field_node_reference.yml
Labels: Product Support Team

#3661 VACMS-3603: Remove dupes from tag view.
  config/sync/views.view.taxonomy_term.yml
Labels: Product Support Team

#3712 VACMS-3674: Add new field to R&S terms.
  config/sync/core.entity_form_display.taxonomy_term.audience_beneficiaries.default.yml
  config/sync/core.entity_form_display.taxonomy_term.audience_non_beneficiaries.default.yml
  config/sync/core.entity_view_display.taxonomy_term.audience_beneficiaries.default.yml
  config/sync/core.entity_view_display.taxonomy_term.audience_non_beneficiaries.default.yml
  config/sync/field.field.taxonomy_term.audience_beneficiaries.field_audience_rs_homepage.yml
  config/sync/field.field.taxonomy_term.audience_non_beneficiaries.field_audience_rs_homepage.yml
  config/sync/field.storage.taxonomy_term.field_audience_rs_homepage.yml
  tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature
Labels: Product Support Team

#3728 VACMS-3535: Rename old lc labels to R and S.
  config/sync/node.type.support_resources_detail_page.yml
  config/sync/paragraphs.paragraphs_type.lists_of_links.yml
  config/sync/taxonomy.vocabulary.lc_categories.yml
  docroot/themes/custom/vagovadmin/images/screenshots/three-column-layout-revised.jpg
  tests/behat/drupal-spec-tool/content_model_bundles.feature
  tests/behat/drupal-spec-tool/content_model_lc_content_type_fields.feature
Labels: Product Support Team

#3730 VACMS-3608: Applies upstream patch to change button label in entity_clone confirmation form.
  composer.json
Labels: Core Application Team

#3739 VACMS-000: Add tugboat-grant-all-users-all-projects.sh crontab script.
  .tugboat/tugboat-grant-all-users-all-projects.sh  
Labels: tugboat

#3742 VACMS-000: Remove ie unfriendly presence check and replace with standard old school check
  docroot/modules/custom/va_gov_backend/js/script.js
Labels: Product Support Team

#3741 VACMS-3703: Fix broken tab click behavior.
  composer.json
  composer.lock
Labels: Product Support Team

#3751 Use upstream stylelint action
  .github/workflows/stylelint-modules.yml
  .github/workflows/stylelint-themes.yml
Labels: Core Application Team

#3523 VACMS-3487: remove system fields step 2 of 3
  config/sync/core.entity_form_display.node.health_care_region_page.default.yml
  config/sync/core.entity_view_display.node.health_care_region_page.default.yml
  config/sync/core.entity_view_display.node.health_care_region_page.teaser.yml
  config/sync/field.field.node.health_care_region_page.field_featured_content_healthser.yml
  config/sync/field.field.node.health_care_region_page.field_press_release_blurb.yml
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
Labels: Product Support Team

#3718 VACMS-3694: Fixes GTM contentOwner reporting.
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  tests/behat/Drupal/FeatureContext.php
  tests/behat/features/google_tag_manager.feature
Labels: Core Application Team

#3524 VACMS-3487 remove system fields step 3 of 3
  docroot/modules/custom/va_gov_backend/va_gov_backend.install
Labels: Product Support Team

#3769 VACMS-3757_3758: Change eb perms and cta cardinality.
  config/sync/field.storage.node.field_clp_video_panel_more_video.yml
  config/sync/user.role.authenticated.yml
  tests/behat/drupal-spec-tool/content_model_campaign_landing_page_content_type_fields.feature
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Product Support Team

#3811 VACMS-3810: Fixes GTM dataLayer issues and adds tests.
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  tests/behat/Drupal/FeatureContext.php
  tests/behat/features/google_tag_manager.feature
Labels: Core Application Team

#3819 VACMS-3688: Covid Vaccine system and facility services
  config/sync/migrate_plus.migration.facility_health_care_service_covid.yml
  config/sync/migrate_plus.migration.regional_health_care_service_covid.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.facility_health_care_service_covid.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.regional_health_care_service_covid.yml
  docroot/modules/custom/va_gov_migrate/data/health-care-region-page.csv
  docroot/modules/custom/va_gov_migrate/data/health-care-service-covid.csv
Labels: Product Support Team

#3711 VACMS-3710: Add eslint action and update existing js to pass linting
  .eslintrc.json
  .github/workflows/eslint.yml
  .github/workflows/phpcs.yml
  .lando.yml
  READMES/code-review.md
  READMES/local.md
  READMES/workflow.md
  composer.json
  docroot/modules/custom/va_gov_backend/js/audience_topics.es6.js
  docroot/modules/custom/va_gov_backend/js/audience_topics.js
  docroot/modules/custom/va_gov_backend/js/contact_paragraphs_interactions.es6.js
  docroot/modules/custom/va_gov_backend/js/contact_paragraphs_interactions.js
  docroot/modules/custom/va_gov_backend/js/gtm_tag_push.es6.js
  docroot/modules/custom/va_gov_backend/js/gtm_tag_push.js
  docroot/modules/custom/va_gov_backend/js/gtm_tag_trackers.es6.js
  docroot/modules/custom/va_gov_backend/js/gtm_tag_trackers.js
  docroot/modules/custom/va_gov_backend/js/media_library_add_form_upload.es6.js
  docroot/modules/custom/va_gov_backend/js/media_library_add_form_upload.js
  docroot/modules/custom/va_gov_backend/js/script.es6.js
  docroot/modules/custom/va_gov_backend/js/script.js
  docroot/modules/custom/va_gov_backend/js/service_location_address.es6.js
  docroot/modules/custom/va_gov_backend/js/service_location_address.js
  docroot/modules/custom/va_gov_backend/js/smart_date_interactions.es6.js
  docroot/modules/custom/va_gov_backend/js/smart_date_interactions.js
  docroot/modules/custom/va_gov_user/js/sections_accordion.es6.js
  docroot/modules/custom/va_gov_user/js/sections_accordion.js
  docroot/themes/custom/vagovadmin/assets/js/anchor_links.es6.js
  docroot/themes/custom/vagovadmin/assets/js/anchor_links.js
  docroot/themes/custom/vagovadmin/assets/js/vagovadmin.theme.help.es6.js
  docroot/themes/custom/vagovadmin/assets/js/vagovadmin.theme.help.js
  docroot/themes/custom/vagovadmin/gulp-tasks/build.js
  docroot/themes/custom/vagovadmin/gulp-tasks/default.js
  docroot/themes/custom/vagovadmin/gulp-tasks/js-lint.js
  docroot/themes/custom/vagovadmin/gulp-tasks/pattern-lab.js
  docroot/themes/custom/vagovadmin/gulp-tasks/sass-for-build.js
  docroot/themes/custom/vagovadmin/gulp-tasks/sass-lint.js
  docroot/themes/custom/vagovadmin/gulp-tasks/sass.js
  docroot/themes/custom/vagovadmin/gulp-tasks/watch.js
  docroot/themes/custom/vagovadmin/gulpfile.es6.js
  docroot/themes/custom/vagovadmin/gulpfile.js
  hooks/git/pre-commit
  package-lock.json
  package.json
  scripts/js/babel-es6-build.js
  scripts/js/babel-es6-watch.js
  scripts/js/changeOrAdded.js
  scripts/js/check.js
  scripts/js/compile.js
  scripts/js/log.js
  scripts/lando-precommit.sh
Labels: Core Application Team, Product Support Team

#3827 VACMS-3825: Add manilla option to date fields.
  config/sync/core.entity_form_display.node.event.default.yml
  config/sync/core.entity_form_display.paragraph.situation_update.default.yml
Labels: Product Support Team

#3831 Add a message after a content release
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Lando.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Tugboat.php
Labels: Core Application Team

#3828 Add nvm and pin node version to be compatible with vets-website
  .nvmrc
  package.json
Labels: Core Application Team

#3837 VACMS-3717: Changes event default timezone to America/New_York.
  config/sync/core.entity_form_display.node.event.default.yml
  tests/behat/features/content_editing.feature
Labels: Core Application Team

#3839 VACMS-3774: Add tagging to clp.
  config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_view_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_view_display.node.campaign_landing_page.teaser.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_audience.yml
  config/sync/field.storage.node.field_clp_audience.yml
  config/sync/taxonomy.vocabulary.audience_tags.yml
  config/sync/user.role.authenticated.yml
  tests/behat/drupal-spec-tool/content_model_bundles.feature
  tests/behat/drupal-spec-tool/content_model_campaign_landing_page_content_type_fields.feature
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Product Support Team

#3812 VACMS-3790: Facility status permissions, and some permissions cleanup
  config/sync/user.role.content_editor.yml
  config/sync/user.role.content_publisher.yml
  config/sync/user.role.content_reviewer.yml
  config/sync/views.view.facility_governance.yml
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Core Application Team, Product Support Team

#3843 VACMS-3840: Add new leadin field to services.
  config/sync/core.entity_form_display.node.support_service.default.yml
  config/sync/core.entity_form_display.node.support_service.inline_entity_form.yml
  config/sync/core.entity_view_display.node.support_service.default.yml
  config/sync/core.entity_view_display.node.support_service.support_services_listing.yml
  config/sync/core.entity_view_display.node.support_service.teaser.yml
  config/sync/field.field.node.support_service.field_health_service_appt_leadin.yml
  config/sync/field.storage.node.field_health_service_appt_leadin.yml
  tests/behat/drupal-spec-tool/content_model_benefits_hubs_content_type_fields.feature
Labels: Product Support Team

#3844 VACMS-3766: CTA Paragraph Text URL Order
  config/sync/core.entity_form_display.paragraph.button.default.yml
  config/sync/core.entity_view_display.paragraph.button.default.yml
Labels: Product Support Team

#3853 VACMS-3826: Updates Drupal Core 8.9.10 -> 8.9.11.
  composer.lock
Labels: Core Application Team

#3848 VACMS 3680: What's new in the CMS
  .github/workflows/phpcs.yml
  composer.json
  config/sync/block.block.entitymetadisplay.yml
  config/sync/block.block.va.govcmsdocumentation.yml
  config/sync/block.block.views_block__right_sidebar_latest_revision_block_1.yml
  config/sync/block.block.whatsnewinthecms.yml
  config/sync/core.date_format.standard.yml
  config/sync/core.entity_form_display.node.support_service.inline_entity_form.yml
  docroot/modules/custom/va_gov_backend/src/Plugin/Block/WhatsNew.php
  docroot/themes/custom/vagovadmin/assets/css/user_guides.css.map
  docroot/themes/custom/vagovadmin/assets/css/whats_new.css
  docroot/themes/custom/vagovadmin/assets/css/whats_new.css.map
  docroot/themes/custom/vagovadmin/assets/scss/user_guides.scss
  docroot/themes/custom/vagovadmin/assets/scss/whats_new.scss
  docroot/themes/custom/vagovadmin/images/icons/bullhorn-000000.svg
  docroot/themes/custom/vagovadmin/vagovadmin.libraries.yml
  scripts/lando-precommit.sh
Labels: Core Application Team

#3867 VACMS-3436: Fixes some failing Behat tests.
  tests/behat/features/save_and_continue.feature
Labels: Core Application Team

#3865 VACMS-3387: Schemata entries pollute dblog.
  composer.json
  composer.lock
Labels: Core Application Team

#3866 VACMS-3852: QA Form Save
  config/sync/core.entity_form_display.node.q_a.default.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Product Support Team

#3875 VACMS-3791: Add advancedqueue module and associated config
  composer.json
  composer.lock
  config/sync/advancedqueue.advancedqueue_queue.command_runner.yml
  config/sync/core.extension.yml
  config/sync/views.view.advancedqueue_jobs.yml
  tests/behat/drupal-spec-tool/views.feature
Labels: Core Application Team

#3845 VACMS 3509: Video embeds for CMS Help Center pages
  config/sync/core.entity_view_display.media.video.user_guides.yml
  config/sync/core.entity_view_display.paragraph.downloadable_file.user_guides.yml
  config/sync/core.entity_view_display.paragraph.media_list_videos.user_guides.yml
  config/sync/core.entity_view_mode.media.user_guides.yml
  config/sync/field.field.node.documentation_page.field_content_block.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  docroot/themes/custom/vagovadmin/assets/css/proofing.css.map
  docroot/themes/custom/vagovadmin/assets/css/styles.css
  docroot/themes/custom/vagovadmin/assets/css/styles.css.map
  docroot/themes/custom/vagovadmin/assets/css/user_guides.css
  docroot/themes/custom/vagovadmin/assets/css/user_guides.css.map
  docroot/themes/custom/vagovadmin/assets/css/wysiwyg.css
  docroot/themes/custom/vagovadmin/assets/css/wysiwyg.css.map
  docroot/themes/custom/vagovadmin/assets/scss/_mixins.scss
  docroot/themes/custom/vagovadmin/assets/scss/user_guides.scss
  docroot/themes/custom/vagovadmin/templates/paragraph/paragraph--downloadable-file--user-guides.html.twig
  docroot/themes/custom/vagovadmin/templates/paragraph/paragraph--media-list-videos--user-guides.html.twig
Labels: Core Application Team

#3914 VACMS 3570: Remove obsolete displays in right-sidebar-latest-revision view.
  config/sync/views.view.right_sidebar_latest_revision.yml
  tests/behat/drupal-spec-tool/views.feature
Labels: Core Application Team

#3911 VACMS-3667: bulk user import
  READMES/user_import.md
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/migrate_plus.migration.user_import.yml
  docroot/modules/custom/va_gov_user/src/EventSubscriber/PostRowSave.php
  docroot/modules/custom/va_gov_user/src/Form/VaGovUserMigrateSourceUiForm.php
  docroot/modules/custom/va_gov_user/src/Routing/RouteSubscriber.php
  docroot/modules/custom/va_gov_user/va_gov_user.services.yml
Labels: Core Application Team
