Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2020-03, with the labels that each got.

#1177 VAGOV-1176 Fix "Cannot find profiles directory ./profiles".
  composer.json
Labels: Infrastructure

#1174 VACMS-1120 Make table field not required.
  config/sync/field.field.paragraph.table.field_table.yml
  tests/behat/drupal-spec-tool/content_model.feature
Labels: All products, Defect

#1182 VACMS-000 Break content model feature into two
  tests/behat/drupal-spec-tool/content_model_bundles.feature
  tests/behat/drupal-spec-tool/content_model_fields.feature
Labels: Drupal engineering

#1183 VACMS-1116 restore missing libraries
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/slick.optionset.default.yml
  config/sync/slick.settings.yml
  docroot/modules/custom/va_gov_db/va_gov_db.install
Labels: Defect, Drupal engineering

#1274 VACMS-1273: Entity browser for alert block, and improved view display.
  config/sync/core.entity_form_display.node.page.default.yml
  config/sync/core.entity_form_display.paragraph.alert.default.yml
  config/sync/core.entity_view_display.block_content.alert.default.yml
  config/sync/core.entity_view_display.node.page.default.yml
  config/sync/entity_browser.browser.alert_blocks.yml
  config/sync/user.role.content_admin.yml
  config/sync/user.role.content_creator_benefits_hubs.yml
  config/sync/user.role.content_editor.yml
  config/sync/user.role.content_publisher.yml
  config/sync/user.role.content_reviewer.yml
  config/sync/user.role.vamc_content_creator.yml
  config/sync/views.view.custom_block_entity_browsers.yml
  tests/behat/drupal-spec-tool/content_model_fields.feature
  tests/behat/drupal-spec-tool/views.feature
  tests/phpunit/SecurityRolesPermissionsTest.php
Labels: Release notes

#1320 VACMS-1319 Change entity browser to media_library on block:promo.
  config/sync/core.entity_form_display.block_content.promo.default.yml
  tests/behat/drupal-spec-tool/content_model_fields.feature
Labels: All products, Defect

#1309 VACMS-1172 Update node_link_report to get 1.13.
  composer.json
  composer.lock
Labels: All products
