Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2020-11, with the labels that each got.

#3259 VACMS-3197 aliases part b
  README.md
  READMES/cms-content-workflow.md
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  scripts/content/VACMS-3197-bulk_update_lc_path_aliases-2020-10.php
Labels: Product Team Support

#3255 VACMS-2861: entity meta display block updates
  docroot/modules/custom/va_gov_backend/modules/va_gov_backend_http_client/src/VaGovBackendHttpClient.php
  docroot/modules/custom/va_gov_backend/modules/va_gov_backend_http_client/va_gov_backend_http_client.info.yml
  docroot/modules/custom/va_gov_backend/modules/va_gov_backend_http_client/va_gov_backend_http_client.services.yml
  docroot/modules/custom/va_gov_backend/src/Form/ExclusionTypesAdminForm.php
  docroot/modules/custom/va_gov_backend/src/Service/ExclusionTypes.php
  docroot/modules/custom/va_gov_backend/src/Service/ExclusionTypesInterface.php
  docroot/modules/custom/va_gov_backend/src/Service/VaGovUrl.php
  docroot/modules/custom/va_gov_backend/src/Service/VaGovUrlInterface.php
  docroot/modules/custom/va_gov_backend/va_gov_backend.services.yml
  docroot/modules/custom/va_gov_workflow_assignments/css/ewa_style.css
  docroot/modules/custom/va_gov_workflow_assignments/src/Plugin/Block/EntityMetaDisplay.php
  docroot/modules/custom/va_gov_workflow_assignments/src/Service/EditorialWorkflowContentRepository.php
  docroot/modules/custom/va_gov_workflow_assignments/src/Service/EditorialWorkflowContentRepositoryInterface.php
  docroot/modules/custom/va_gov_workflow_assignments/va_gov_workflow_assignments.libraries.yml
  docroot/modules/custom/va_gov_workflow_assignments/va_gov_workflow_assignments.services.yml
  docroot/sites/default/settings/settings.dev.php
  docroot/sites/default/settings/settings.staging.php
  tests/behat/Drupal/ContextBase.php
  tests/behat/features/content_editing.feature
  tests/behat/features/decoupled.feature
  tests/phpunit/EditorialWorkflowContentRepositoryServiceTest.php
  tests/phpunit/ExclusionTypesServiceTest.php
  tests/phpunit/VaGovUrlServiceTest.php
Labels: Core Application team

#3207 VACMS 2912: Force editors to save first as draft or in review, then publish on the proofing pages.
  config/sync/core.entity_view_display.node.landing_page.default.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  tests/behat/Drupal/FeatureContext.php
  tests/behat/features/content_editing.feature
  tests/behat/features/decoupled.feature
  tests/behat/features/perms.feature
Labels: Core Application team

#3334 Blackfire integration with Lando.
  .lando.yml
  .lando/scripts/blackfire-init.sh
  READMES/blackfire.md
Labels: Core Application team

#3310 VACMS 2406: Hide "meta tags" field from all content type forms.
  config/sync/core.entity_form_display.node.event.default.yml
  config/sync/core.entity_form_display.node.event_listing.default.yml
  config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_form_display.node.health_care_region_detail_page.default.yml
  config/sync/core.entity_form_display.node.health_care_region_page.default.yml
  config/sync/core.entity_form_display.node.health_services_listing.default.yml
  config/sync/core.entity_form_display.node.landing_page.default.yml
  config/sync/core.entity_form_display.node.leadership_listing.default.yml
  config/sync/core.entity_form_display.node.locations_listing.default.yml
  config/sync/core.entity_form_display.node.news_story.default.yml
  config/sync/core.entity_form_display.node.office.default.yml
  config/sync/core.entity_form_display.node.outreach_asset.default.yml
  config/sync/core.entity_form_display.node.page.default.yml
  config/sync/core.entity_form_display.node.press_release.default.yml
  config/sync/core.entity_form_display.node.press_releases_listing.default.yml
  config/sync/core.entity_form_display.node.publication_listing.default.yml
  config/sync/core.entity_form_display.node.story_listing.default.yml
  config/sync/core.entity_form_display.node.va_form.default.yml
  tests/behat/Drupal/ContextBase.php
  tests/behat/drupal-spec-tool/content_model_benefits_hubs_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_outreach_hub_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_va_forms_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
  tests/phpunit/VaGovUrlServiceTest.php
Labels: Core Application team

#3409 VACMS-3324: Fix paragraph and Node being out of sync
  composer.json
  scripts/content/VACMS-3325_paragraph_revision-2020-10.php
Labels: Core Application team

#3452 VACMS-3448: add test for revision_log field
  config/sync/core.entity_form_display.node.event_listing.default.yml
  config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_form_display.node.health_care_region_detail_page.default.yml
  config/sync/core.entity_form_display.node.health_care_region_page.default.yml
  config/sync/core.entity_form_display.node.health_services_listing.default.yml
  config/sync/core.entity_form_display.node.landing_page.default.yml
  config/sync/core.entity_form_display.node.leadership_listing.default.yml
  config/sync/core.entity_form_display.node.locations_listing.default.yml
  config/sync/core.entity_form_display.node.office.default.yml
  config/sync/core.entity_form_display.node.outreach_asset.default.yml
  config/sync/core.entity_form_display.node.page.default.yml
  config/sync/core.entity_form_display.node.person_profile.default.yml
  config/sync/core.entity_form_display.node.press_releases_listing.default.yml
  config/sync/core.entity_form_display.node.publication_listing.default.yml
  config/sync/core.entity_form_display.node.story_listing.default.yml
  config/sync/core.entity_form_display.node.va_form.default.yml
  tests.yml
  tests/scripts/check-revision-logs.sh
Labels: Core Application team

#3474 VACMS-3449: Forces paragraphs to clone and hides their checkboxes on the clone form.
  config/sync/entity_clone.settings.yml
Labels: Core Application team

#3464 VACMS-3253 downtime status check
  docroot/modules/custom/va_gov_backend/src/Deploy/DeployService.php
  docroot/modules/custom/va_gov_backend/src/Deploy/Plugin/HealthCheck.php
  docroot/modules/custom/va_gov_backend/src/Test/DeployPluginTest.php
  docroot/modules/custom/va_gov_backend/src/Test/DeployServiceMock.php
  tests/phpunit/Deploy/DeployServiceTest.php
  tests/phpunit/Deploy/Plugins/HealthCheckTest.php
Labels: Core Application team

#3495 VACMS-3485: QA Standalone Fix
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Drupal engineering, Product Support Team

#3506 VACMS-2982: Remove duplicate pathauto pattern config
  config/sync/pathauto.pattern.taxonomy_terms.yml
Labels: Core Application Team

#3483 VACMS-3480: Updated Archive transition settings.
  config/sync/workflows.workflow.editorial.yml
  tests/behat/drupal-spec-tool/workflow.feature
Labels: Core Application Team

#3368 VACMS-2896 System Service migration for VISN 2,6,16,21, 23
  config/sync/migrate_plus.migration.regional_health_care_service_region_keyed.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.regional_health_care_service_region_keyed.yml
  docroot/modules/custom/va_gov_migrate/data/regional-health-care-service-region-keyed.csv
Labels: Migration, Product Support Team

#3477 VACMS-3167: Add clp content type.
  config/sync/core.base_field_override.node.campaign_landing_page.promote.yml
  config/sync/core.base_field_override.node.campaign_landing_page.title.yml
  config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_form_display.paragraph.button.default.yml
  config/sync/core.entity_view_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_view_display.node.campaign_landing_page.teaser.yml
  config/sync/core.menu.static_menu_link_overrides.yml
  config/sync/entity_browser.browser.promo_blocks_browser.yml
  config/sync/field.field.node.campaign_landing_page.field_administration.yml
  config/sync/field.field.node.campaign_landing_page.field_benefit_categories.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_what_you_can_do_header.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_what_you_can_do_intro.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_what_you_can_do_promos.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_why_this_matters.yml
  config/sync/field.field.node.campaign_landing_page.field_hero_blurb.yml
  config/sync/field.field.node.campaign_landing_page.field_hero_image.yml
  config/sync/field.field.node.campaign_landing_page.field_primary_call_to_action.yml
  config/sync/field.field.node.campaign_landing_page.field_secondary_call_to_action.yml
  config/sync/field.storage.node.field_clp_what_you_can_do_header.yml
  config/sync/field.storage.node.field_clp_what_you_can_do_intro.yml
  config/sync/field.storage.node.field_clp_what_you_can_do_promos.yml
  config/sync/field.storage.node.field_clp_why_this_matters.yml
  config/sync/field.storage.node.field_hero_blurb.yml
  config/sync/field.storage.node.field_hero_image.yml
  config/sync/field.storage.node.field_primary_call_to_action.yml
  config/sync/field.storage.node.field_secondary_call_to_action.yml
  config/sync/node.type.campaign_landing_page.yml
  config/sync/user.role.content_admin.yml
  config/sync/views.view.custom_block_entity_browsers.yml
  config/sync/workbench_access.access_scheme.section.yml
  config/sync/workflows.workflow.editorial.yml
  tests/behat/drupal-spec-tool/content_model_bundles.feature
  tests/behat/drupal-spec-tool/views.feature
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Product Support Team

#3447 VACMS-3332: Add logic to toggle standalone qa entity view display.
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Product Support Team

#3457 VACMS-2982: Remove legacy fields from db.
  docroot/modules/custom/va_gov_backend/va_gov_backend.install
Labels: Product Support Team

#3505 VACMS-3038: LC Remove Field Related Links
  config/sync/core.entity_form_display.node.checklist.default.yml
  config/sync/core.entity_form_display.node.faq_multiple_q_a.default.yml
  config/sync/core.entity_form_display.node.media_list_images.default.yml
  config/sync/core.entity_form_display.node.media_list_videos.default.yml
  config/sync/core.entity_form_display.node.q_a.default.yml
  config/sync/core.entity_form_display.node.step_by_step.default.yml
  config/sync/core.entity_view_display.node.checklist.default.yml
  config/sync/core.entity_view_display.node.checklist.teaser.yml
  config/sync/core.entity_view_display.node.faq_multiple_q_a.default.yml
  config/sync/core.entity_view_display.node.faq_multiple_q_a.teaser.yml
  config/sync/core.entity_view_display.node.media_list_images.default.yml
  config/sync/core.entity_view_display.node.media_list_images.teaser.yml
  config/sync/core.entity_view_display.node.media_list_videos.default.yml
  config/sync/core.entity_view_display.node.media_list_videos.teaser.yml
  config/sync/core.entity_view_display.node.q_a.default.yml
  config/sync/core.entity_view_display.node.q_a.support_services_listing.yml
  config/sync/core.entity_view_display.node.q_a.teaser.yml
  config/sync/core.entity_view_display.node.step_by_step.default.yml
  config/sync/core.entity_view_display.node.step_by_step.teaser.yml
  config/sync/field.field.node.checklist.field_related_links.yml
  config/sync/field.field.node.faq_multiple_q_a.field_related_links.yml
  config/sync/field.field.node.media_list_images.field_related_links.yml
  config/sync/field.field.node.media_list_videos.field_related_links.yml
  config/sync/field.field.node.q_a.field_related_links.yml
  config/sync/field.field.node.step_by_step.field_related_links.yml
  tests/behat/drupal-spec-tool/content_model_lc_content_type_fields.feature
Labels: Product Support Team

#3302 VACMS 3223: User Role dimension for the CMS Google Analytics data
  docroot/modules/custom/va_gov_backend/js/gtm_tag_trackers.js
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  tests/behat/Drupal/FeatureContext.php
  tests/behat/features/google_tag_manager.feature
Labels: Core Application Team

#3476 VACMS-3182: Paragraph Remove Button
  composer.json
  composer.lock
  config/sync/field.field.node.checklist.field_alert_single.yml
  config/sync/field.field.node.faq_multiple_q_a.field_alert_single.yml
  config/sync/field.field.node.media_list_images.field_alert_single.yml
  config/sync/field.field.node.media_list_videos.field_alert_single.yml
  config/sync/field.field.node.q_a.field_alert_single.yml
  config/sync/field.field.node.step_by_step.field_alert_single.yml
  config/sync/field.field.node.support_resources_detail_page.field_alert_single.yml
  tests/behat/drupal-spec-tool/content_model_lc_content_type_fields.feature
Labels: Product Support Team

#3511 VACMS-2934: Add html cleanup to table field.
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Core Application Team, Product Support Team

#3514 VACMS-3445: Remove section fields from checklist paragraph.
  config/sync/core.entity_form_display.paragraph.checklist.default.yml
  config/sync/core.entity_view_display.paragraph.checklist.default.yml
  config/sync/field.field.paragraph.checklist.field_section_header.yml
  config/sync/field.field.paragraph.checklist.field_section_intro.yml
  tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature
  tests/behat/features/content_editing.feature
  tests/behat/features/save_and_continue.feature
Labels: Product Support Team

#3518 VACMS-3513: Update Drupal core to 8.8.11 for SA-CORE-2020-012
  composer.json
  composer.lock
Labels: Core Application Team

#3499 VACMS-2002: Allow searching for multiple facility owners
  config/sync/views.view.facility_governance.yml
Labels: Core Application Team

#3492 VACMS-3370: Updated character limit for meta description field
  config/sync/core.entity_form_display.node.basic_landing_page.default.yml
Labels: Drupal engineering, Product Support Team

#3517 VACMS-3510: Updated Smart Date Timezone Configuration
  config/sync/smart_date.smart_date_format.default.yml
Labels: Product Support Team

#3497 VACMS 3450: Repair improperly-parented paragraphs resulting from entity_clone operations.
  scripts/content/VACMS-3450-paragraphs-should-have-a-single-parent.php
  scripts/content/VACMS-3450-testing.sh
Labels: Core Application Team, Needs PO review

#3549 VACMS-3240: Content Creator Office Role
  config/sync/system.action.user_add_role_action.office_content_creator.yml
  config/sync/system.action.user_remove_role_action.office_content_creator.yml
  config/sync/user.role.office_content_creator.yml
  tests/behat/drupal-spec-tool/access_control.feature
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Product Support Team

#3541 VACMS-3507: implement alternative publishing workflow (copy)
  config/sync/core.entity_form_display.node.event.default.yml
  config/sync/core.entity_form_display.node.event_listing.default.yml
  config/sync/core.entity_form_display.node.health_care_region_detail_page.default.yml
  config/sync/core.entity_form_display.node.health_services_listing.default.yml
  config/sync/core.entity_form_display.node.landing_page.default.yml
  config/sync/core.entity_form_display.node.leadership_listing.default.yml
  config/sync/core.entity_form_display.node.locations_listing.default.yml
  config/sync/core.entity_form_display.node.news_story.default.yml
  config/sync/core.entity_form_display.node.office.default.yml
  config/sync/core.entity_form_display.node.outreach_asset.default.yml
  config/sync/core.entity_form_display.node.page.default.yml
  config/sync/core.entity_form_display.node.person_profile.default.yml
  config/sync/core.entity_form_display.node.press_release.default.yml
  config/sync/core.entity_form_display.node.press_releases_listing.default.yml
  config/sync/core.entity_form_display.node.publication_listing.default.yml
  config/sync/core.entity_form_display.node.story_listing.default.yml
  config/sync/core.entity_form_display.node.va_form.default.yml
  config/sync/core.entity_view_display.node.basic_landing_page.default.yml
  config/sync/core.entity_view_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_view_display.node.checklist.default.yml
  config/sync/core.entity_view_display.node.documentation_page.default.yml
  config/sync/core.entity_view_display.node.event.default.yml
  config/sync/core.entity_view_display.node.event_listing.default.yml
  config/sync/core.entity_view_display.node.faq_multiple_q_a.default.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_view_display.node.health_care_local_health_service.default.yml
  config/sync/core.entity_view_display.node.health_care_region_detail_page.default.yml
  config/sync/core.entity_view_display.node.health_care_region_page.default.yml
  config/sync/core.entity_view_display.node.health_services_listing.default.yml
  config/sync/core.entity_view_display.node.landing_page.default.yml
  config/sync/core.entity_view_display.node.leadership_listing.default.yml
  config/sync/core.entity_view_display.node.locations_listing.default.yml
  config/sync/core.entity_view_display.node.media_list_images.default.yml
  config/sync/core.entity_view_display.node.media_list_videos.default.yml
  config/sync/core.entity_view_display.node.nca_facility.default.yml
  config/sync/core.entity_view_display.node.news_story.default.yml
  config/sync/core.entity_view_display.node.office.default.yml
  config/sync/core.entity_view_display.node.outreach_asset.default.yml
  config/sync/core.entity_view_display.node.page.default.yml
  config/sync/core.entity_view_display.node.person_profile.default.yml
  config/sync/core.entity_view_display.node.press_release.default.yml
  config/sync/core.entity_view_display.node.press_releases_listing.default.yml
  config/sync/core.entity_view_display.node.publication_listing.default.yml
  config/sync/core.entity_view_display.node.q_a.default.yml
  config/sync/core.entity_view_display.node.regional_health_care_service_des.default.yml
  config/sync/core.entity_view_display.node.step_by_step.default.yml
  config/sync/core.entity_view_display.node.story_listing.default.yml
  config/sync/core.entity_view_display.node.support_resources_detail_page.default.yml
  config/sync/core.entity_view_display.node.support_service.default.yml
  config/sync/core.entity_view_display.node.va_form.default.yml
  config/sync/core.entity_view_display.node.vamc_operating_status_and_alerts.default.yml
  config/sync/core.entity_view_display.node.vba_facility.default.yml
  config/sync/core.entity_view_display.node.vet_center.default.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  tests/behat/features/content_editing.feature
  tests/behat/features/decoupled.feature
  tests/behat/features/perms.feature
Labels: Core Application Team

#3564 VACMS-3508: Use revision creation time for right sidebar view sort
  config/sync/views.view.right_sidebar_latest_revision.yml
Labels: Core Application Team

#3589 VACMS-3542: update revision log permissions
  config/sync/user.role.authenticated.yml
  tests/behat/features/perms.feature
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Core Application Team

#3554 VACMS-3468: Collect User ID via GA/GTM
  docroot/modules/custom/va_gov_backend/js/gtm_tag_trackers.js
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  tests/behat/Drupal/FeatureContext.php
  tests/behat/features/google_tag_manager.feature
Labels: Core Application Team

#3595 VACMS-1949: upgrade to drupal core 8.9.10 (SA-CORE-2020-013)
  .gitignore
  composer.json
  composer.lock
  docroot/modules/custom/va_gov_build_trigger/src/Form/BuildTriggerForm.php
  docroot/modules/custom/va_gov_content_export/src/TomeFileSync.php
  docroot/modules/custom/va_gov_content_export/va_gov_content_export.services.yml
  docroot/modules/custom/va_gov_govdelivery/src/Service/ProcessStatusBulletin.php
  docroot/modules/custom/va_gov_govdelivery/va_gov_govdelivery.module
  docroot/modules/custom/va_gov_migrate/src/Paragraph/Base/QABase.php
  docroot/modules/custom/va_gov_migrate/src/ParagraphMigrator.php
  docroot/modules/custom/va_gov_migrate/src/ParagraphType.php
  docroot/modules/custom/va_gov_preview/src/Encoder/StaticEncoder.php
  docroot/modules/custom/va_gov_preview/src/EventSubscriber/DeployStatusMessagesSubscriber.php
  docroot/modules/custom/va_gov_preview/src/EventSubscriber/StaticSubscriber.php
  docroot/modules/custom/va_gov_preview/va_gov_preview.services.yml
  docroot/sites/default/default.settings.php
  docroot/sites/default/settings.php
  docroot/sites/example.settings.local.php
Labels: Core Application Team, Product Support Team

#3592 VACMS-3591: Fix parent and revision ids on paragraphs
  scripts/content/VACMS-3591-fix-parent-and-revision-ids-on-paragraphs.php
Labels: Core Application Team

#3565 VACMS-3465: Add spotlight panel.
  config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_view_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_view_display.node.campaign_landing_page.teaser.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_spotlight_cta.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_spotlight_header.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_spotlight_intro_text.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_spotlight_link_teasers.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_spotlight_opt_in.yml
  config/sync/field.storage.node.field_clp_spotlight_cta.yml
  config/sync/field.storage.node.field_clp_spotlight_header.yml
  config/sync/field.storage.node.field_clp_spotlight_intro_text.yml
  config/sync/field.storage.node.field_clp_spotlight_link_teasers.yml
  config/sync/field.storage.node.field_clp_spotlight_opt_in.yml
  config/sync/paragraphs.paragraphs_type.button.yml
  docroot/modules/custom/va_gov_backend/js/script.js
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  tests/behat/drupal-spec-tool/content_model_bundles.feature
  tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature
Labels: Product Support Team
