Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2020-02, with the labels that each got.

#906 Increase local lando max_execution_time from 90 > 190
  .lando.yml
  .lando/zzz-lando-my-custom.ini
Labels: DevOps, ⭐️ Infrastructure

#986 VACMS-980 Unset deploy pending flag on failure.
  docroot/modules/custom/va_gov_build_trigger/src/Form/BuildTriggerForm.php
  docroot/modules/custom/va_gov_build_trigger/src/Service/BuildFrontend.php
Labels: Defect, Drupal engineering

#1014 VACMS-844 Update node_link_report to reduce false failures.
  composer.json
  composer.lock
  config/sync/node_link_report.settings.yml
Labels: All products, Content proofing, ⭐️ CMS UX
