Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2020-10, with the labels that each got.

#3177 VACMS-1298 fix duplicate id accessibility test failure
  composer.json
  composer.lock
  package-lock.json
  package.json
  tests/accessibility/aXeAccessibilityCheck.js
Labels: Automated testing

#3180 VACMS-3176: Add R&S content types to linkit profile
  config/sync/linkit.linkit_profile.default.yml
Labels: Product Team Support, Search

#3321 VACMS-3254: Update R&S term page views.
  config/sync/taxonomy_entity_index.settings.yml
  config/sync/views.view.taxonomy_term.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  tests/behat/drupal-spec-tool/views.feature
Labels: Product Team Support

#3291 VACMS_3265: Format situation update time field widget.
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Product Team Support

#3309 VACMS-3308: Add file_public_base_url for devshop settings
  docroot/sites/default/settings.devshop.php
  docroot/sites/default/settings.php
Labels: Core Application team
