Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2020-07, with the labels that each got.

#1577 Improve DevOps Documentation
  READMES/access.md
  READMES/environments.md
Labels: Product documentation

#2206 VISN 19 SECOND GROUP SYSTEM MENUS
  config/sync/core.menu.static_menu_link_overrides.yml
  config/sync/node.type.event.yml
  config/sync/node.type.event_listing.yml
  config/sync/node.type.health_care_local_facility.yml
  config/sync/node.type.health_care_region_detail_page.yml
  config/sync/node.type.health_care_region_page.yml
  config/sync/node.type.health_services_listing.yml
  config/sync/node.type.leadership_listing.yml
  config/sync/node.type.locations_listing.yml
  config/sync/node.type.news_story.yml
  config/sync/node.type.person_profile.yml
  config/sync/node.type.press_release.yml
  config/sync/node.type.press_releases_listing.yml
  config/sync/node.type.publication_listing.yml
  config/sync/node.type.story_listing.yml
  config/sync/node.type.vamc_operating_status_and_alerts.yml
  config/sync/system.menu.va-eastern-oklahoma-health-care.yml
  config/sync/system.menu.va-oklahoma-health-care.yml
  config/sync/system.menu.va-salt-lake-city-health-care.yml
  config/sync/system.menu.va-sheridan-health-care.yml
  tests/behat/drupal-spec-tool/menus.feature
Labels: VAMC system

#2241 VACMS-000 Update va-gov/web
  composer.lock
Labels: Unplanned work

#2431 Update PHP max_execution_time from 190 > 300 in Lando.
  .lando/zzz-lando-my-custom.ini
Labels: DevOps

#2492 VACMS-000 Update va_form migration to overwrite revision date not admin.
  config/sync/migrate_plus.migration.va_node_form.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_form.yml
Labels: Unplanned work

#2371 VAMC-11201: VISN 1, VISN 5 and VISN 6 systems menus.
  config/sync/core.menu.static_menu_link_overrides.yml
  config/sync/menu_breadcrumb.settings.yml
  config/sync/node.type.event.yml
  config/sync/node.type.event_listing.yml
  config/sync/node.type.health_care_local_facility.yml
  config/sync/node.type.health_care_region_detail_page.yml
  config/sync/node.type.health_care_region_page.yml
  config/sync/node.type.health_services_listing.yml
  config/sync/node.type.leadership_listing.yml
  config/sync/node.type.locations_listing.yml
  config/sync/node.type.news_story.yml
  config/sync/node.type.person_profile.yml
  config/sync/node.type.press_release.yml
  config/sync/node.type.press_releases_listing.yml
  config/sync/node.type.publication_listing.yml
  config/sync/node.type.story_listing.yml
  config/sync/node.type.vamc_operating_status_and_alerts.yml
  config/sync/system.menu.va-asheville-health-care.yml
  config/sync/system.menu.va-beckley-health-care.yml
  config/sync/system.menu.va-bedford-health-care.yml
  config/sync/system.menu.va-boston-health-care.yml
  config/sync/system.menu.va-central-western-massachusetts.yml
  config/sync/system.menu.va-clarksburg-health-care.yml
  config/sync/system.menu.va-connecticut-health-care.yml
  config/sync/system.menu.va-durham-health-care.yml
  config/sync/system.menu.va-fayetteville-coastal-health-c.yml
  config/sync/system.menu.va-hampton-health-care.yml
  config/sync/system.menu.va-huntington-health-care.yml
  config/sync/system.menu.va-maine-health-care.yml
  config/sync/system.menu.va-manchester-health-care.yml
  config/sync/system.menu.va-martinsburg-health-care.yml
  config/sync/system.menu.va-maryland-health-care.yml
  config/sync/system.menu.va-providence-health-care.yml
  config/sync/system.menu.va-richmond-health-care.yml
  config/sync/system.menu.va-salem-health-care.yml
  config/sync/system.menu.va-salisbury-health-care.yml
  config/sync/system.menu.va-washington-dc-health-care.yml
  config/sync/system.menu.va-white-river-junction-health-c.yml
  tests/behat/drupal-spec-tool/menus.feature
Labels: vsa-vamc-upgrade
