Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2020-04, with the labels that each got.

#1399 VACMS-1359 Use correct Slack channel for PROD deploy failures, add success message.
  Jenkinsfile.cd
Labels: DevOps

#1401 Send Slack on PROD deploy success & improve failure message of deploy slack failure send.
  Jenkinsfile.cd
Labels: DevOps

#1402 VACMS-1359 - Remove success Slack notify on CD to DEV/STAGING job, it is a false positive as it is a wrapper job.
  Jenkinsfile.cd
Labels: DevOps

#1429 composer update va-gov/web
  composer.lock
Labels: Defect

#1423 VACMS-1422 Restrict NCA facility migration of State Cemeteries.
  config/sync/migrate_plus.migration.va_node_facility_nca.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_nca.yml
Labels: Migration

#1435 Use CMS_VAGOV_API_URL/KEY ENV variable in settings.php.
  docroot/sites/default/settings.php
Labels: DevOps

#1599 Clear yarn cache on `composer nuke`.
  composer.json
Labels: cms

#1635 Parameterize the Jenkinsfile.cd file to work with cms or cms-test.
  Jenkinsfile.cd
Labels: cms

#1634 Get dependabot working again with just security updates (no va-gov/web)
  .dependabot/config.yml
Labels: dependencies

#1559 VACMS-1572: Fixing update hook to set text format for benefits field.
  docroot/modules/custom/va_gov_db/va_gov_db.install
Labels: Critical defect

#1648 Parameterize the jenkinsfile.cd
  Jenkinsfile.cd
Labels: DevOps
