Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2021-01, with the labels that each got.

#3906 VACMS-3813: disable select admin menu items
  config/sync/core.menu.static_menu_link_overrides.yml
  tests/phpunit/Performance/LoginTest.php
Labels: Core Application Team

#3873 VACMS-3872: Content publisher can not VBO modify field values.
  config/sync/user.role.content_publisher.yml
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Product Support Team

#3864 [DO NOT MERGE] VACMS-3791: built front-end PRs
  .tugboat/config.yml
  composer.json
  composer.lock
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  docroot/modules/custom/va_gov_build_trigger/src/Controller/FrontEndBranchAutocompleteController.php
  docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentDiscovery.php
  docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentInterface.php
  docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentPluginBase.php
  docroot/modules/custom/va_gov_build_trigger/src/Form/BrdBuildTriggerForm.php
  docroot/modules/custom/va_gov_build_trigger/src/Form/BuildTriggerForm.php
  docroot/modules/custom/va_gov_build_trigger/src/Form/DevShopBuildTriggerForm.php
  docroot/modules/custom/va_gov_build_trigger/src/Form/LandoBuildTriggerForm.php
  docroot/modules/custom/va_gov_build_trigger/src/Form/TugboatBuildTriggerForm.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/AdvancedQueue/JobType/WebBuildJobType.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRD.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/DevShop.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Lando.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Tugboat.php
  docroot/modules/custom/va_gov_build_trigger/src/Routing/RouteSubscriber.php
  docroot/modules/custom/va_gov_build_trigger/src/Service/BuildFrontend.php
  docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.routing.yml
  docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.services.yml
  docroot/modules/custom/va_gov_consumers/src/Git/Git.php
  docroot/modules/custom/va_gov_consumers/src/Git/GitInterface.php
  docroot/modules/custom/va_gov_consumers/src/Git/GithubAdapter.php
  docroot/modules/custom/va_gov_consumers/src/Git/GithubFactory.php
  docroot/modules/custom/va_gov_consumers/src/Git/GithubInterface.php
  docroot/modules/custom/va_gov_consumers/va_gov_consumers.services.yml
  scripts/queue_runner/queue_runner.sh
  tests/phpunit/FrontendBuild/BuildTriggerFormTest.php
Labels: Core Application Team

#3940 VACMS-3577: content release job status block
  config/sync/block.block.content_release_status_block.yml
  config/sync/block.block.node_link_report.yml
  config/sync/block.block.user_sections.yml
  config/sync/block.block.vagovadmin_content.yml
  config/sync/block.block.vagovadmin_local_actions.yml
  config/sync/block.block.views_block__services_block_1.yml
  config/sync/block.block.wheredoesthisappear.yml
  docroot/modules/custom/va_gov_build_trigger/css/content_release_status_block.css
  docroot/modules/custom/va_gov_build_trigger/js/content_release_status_block.es6.js
  docroot/modules/custom/va_gov_build_trigger/js/content_release_status_block.js
  docroot/modules/custom/va_gov_build_trigger/src/Controller/ContentReleaseStatusBlockController.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/AdvancedQueue/JobType/WebBuildJobType.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/Block/ContentReleaseStatusBlock.php
  docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.libraries.yml
  docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.routing.yml
Labels: Core Application Team

#3957 VACMS-3937: Replace tests for downloadable_file paragraphs.
  tests/phpunit/Content/DownloadableFileTest.php
Labels: Core Application Team

#3855 VACMS-3011: Optimize Composer install
  .lando/zzz-lando-my-custom.ini
  .tugboat/config.yml
  composer.json
  docroot/sites/default/settings.php
Labels: Core Application Team

#3956 VACMS-3291: CLP Spotlight Link Teaser Validation
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Product Support Team

#3963 VACMS 3960: Updates va-gov/web to v0.1.1217
  composer.lock
Labels: Core Application Team

#3794 VACMS-3682 push facility covid service status
  READMES/migrations-facility.md
  READMES/vamc-facilities.md
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.health_care_region_page.yml
  docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityService.php
  docroot/modules/custom/va_gov_post_api/va_gov_post_api.module
  docroot/modules/custom/va_gov_post_api/va_gov_post_api.services.yml
Labels: Core Application Team, Product Support Team

#3964 VACMS-3924: Add benefit limit validation to clp.
  docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/BenefitsSelectionLimit.php
  docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/BenefitsSelectionLimitValidator.php
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Product Support Team

#3966 VACMS-3926: Media Link Check
  config/sync/core.entity_view_display.media.image.default.yml
  config/sync/core.entity_view_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_view_display.node.event.default.yml
  config/sync/node_link_report.settings.yml
Labels: Product Support Team

#3951 VACMS-3915: Type Of Care
  config/sync/core.entity_form_display.taxonomy_term.health_care_service_taxonomy.default.yml
  config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.default.yml
  config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_service_type_of_care.yml
  config/sync/field.storage.taxonomy_term.field_service_type_of_care.yml
  config/sync/views.view.vha_health_service_taxonomy.yml
  tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature
Labels: Product Support Team

#3970 VACMS-3840: Appt Intro Select Logic Fix
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Product Support Team

#3979 VACMS-3908 update clp panel layout and text
  config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_events_panel.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_faq_panel.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_resources_panel.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_spotlight_panel.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_stories_panel.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_video_panel.yml
  docroot/themes/custom/vagovadmin/assets/css/styles.css
  docroot/themes/custom/vagovadmin/assets/css/styles.css.map
  docroot/themes/custom/vagovadmin/assets/scss/styles.scss
  tests/behat/drupal-spec-tool/content_model_campaign_landing_page_content_type_fields.feature
Labels: Product Support Team

#3965 VACMS-3563: Populates og:image:alt and twitter:image:alt.
  config/sync/metatag.metatag_defaults.node.yml
  tests/phpunit/Content/MetaTagTest.php
Labels: Core Application Team

#3976 VACMS-3974: Updates What's new in the CMS Block to appear on main Help page but not Announcements
  config/sync/block.block.whatsnewinthecms.yml
  docroot/modules/custom/va_gov_backend/src/Plugin/Block/WhatsNew.php
  tests/behat/features/cms_whats_new_block.feature
Labels: Core Application Team

#3985 VACMS-3923: Limit qa's in FAQ panel to 10.
  composer.json
  composer.lock
  config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
  config/sync/core.extension.yml
  config/sync/field.storage.node.field_clp_spotlight_link_teasers.yml
  tests/behat/drupal-spec-tool/content_model_campaign_landing_page_content_type_fields.feature
Labels: Product Support Team

#4006 VACMS-3917 linkit widget updates
  config/sync/core.entity_form_display.media.document_external.default.yml
  config/sync/core.entity_form_display.menu_link_content.footer-bottom-rail.default.yml
  config/sync/core.entity_form_display.menu_link_content.footer.default.yml
  config/sync/core.entity_form_display.menu_link_content.header-megamenu.default.yml
  config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_form_display.node.event.default.yml
  config/sync/core.entity_form_display.node.health_care_region_page.default.yml
  config/sync/core.entity_form_display.node.support_service.default.yml
  config/sync/core.entity_form_display.node.va_form.default.yml
  config/sync/core.entity_form_display.node.vamc_operating_status_and_alerts.default.yml
  config/sync/linkit.linkit_profile.default.yml
  tests.yml
  tests/behat/drupal-spec-tool/content_model_benefits_hubs_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_campaign_landing_page_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_media_fields.feature
  tests/behat/drupal-spec-tool/content_model_va_forms_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
  tests/scripts/check-linkit-logs.sh
Labels: Product Support Team

#3733 VACMS-3289: implement cypress-axe accessibility testing
  .gitignore
  .lando.yml
  .tugboat/.env.j2
  .tugboat/config.yml
  composer.json
  docroot/modules/custom/va_gov_backend/js/script.es6.js
  docroot/modules/custom/va_gov_backend/js/script.js
  package-lock.json
  package.json
  scripts/tests/cypress-axe.sh
  tests.yml
  tests/accessibility/README.md
  tests/accessibility/aXeAccessibilityCheck.js
  tests/accessibility/axeReport/.gitkeep
  tests/cypress.json
  tests/cypress/README.md
  tests/cypress/integration/homepageAccessibility.spec.js
  tests/cypress/integration/nodeCreationAccessibility.spec.js
  tests/cypress/plugins/index.js
  tests/cypress/support/commands.js
  tests/cypress/support/index.js
Labels: Core Application Team

#4023 VACMS-4022: Fix accessibility test failure
  .tugboat/.env.j2
  .tugboat/config.yml
  config/sync/block.block.whatsnewinthecms.yml
  docroot/modules/custom/va_gov_backend/js/script.es6.js
  docroot/modules/custom/va_gov_backend/js/script.js
  docroot/modules/custom/va_gov_backend/va_gov_backend.libraries.yml
Labels: Automated testing, Core Application Team, Unplanned work

#4012 VACMS-3342: Extend Disable Auto Alias
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  tests/behat/Drupal/FeatureContext.php
  tests/behat/features/content_editing.feature
  tests/traits/ContentTrait.php
Labels: Product Support Team

#3850 VACMS-3792: JSD in CMS + help center updates
  config/sync/core.extension.yml
  config/sync/editor.editor.rich_text.yml
  config/sync/filter.format.rich_text.yml
  config/sync/toolbar_menu.toolbar_menu_element.cms_help_center.yml
  docroot/modules/custom/va_gov_help_center/va_gov_help_center.info.yml
  docroot/modules/custom/va_gov_help_center/va_gov_help_center.libraries.yml
  docroot/modules/custom/va_gov_help_center/va_gov_help_center.module
  docroot/modules/custom/va_gov_login/va_gov_login.module
  docroot/sites/default/settings/settings.tugboat.php
  tests/cypress/integration/homepageAccessibility.spec.js
Labels: Core Application Team, DO NOT MERGE

#4038 VACMS-2824: Add patched flood_control module & configure user block expiration
  READMES/user_management.md
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/user.flood.yml
Labels: Core Application Team

#4008 VACMS-3420 Add transformer support to composer build scripts
  composer.json
  docroot/modules/custom/va_gov_build_trigger/src/CommandExportable.php
  docroot/modules/custom/va_gov_build_trigger/src/Controller/FrontEndBranchAutocompleteController.php
  docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentDiscovery.php
  docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentInterface.php
  docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentPluginBase.php
  docroot/modules/custom/va_gov_build_trigger/src/Form/LandoBuildTriggerForm.php
  docroot/modules/custom/va_gov_build_trigger/src/Form/TugboatBuildTriggerForm.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/AdvancedQueue/JobType/WebBuildJobType.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRD.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/DevShop.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Lando.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/QueueHelper.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Tugboat.php
  docroot/modules/custom/va_gov_build_trigger/src/Service/BuildFrontend.php
  docroot/modules/custom/va_gov_build_trigger/src/WebBuildCommandBuilder.php
  docroot/modules/custom/va_gov_build_trigger/src/WebBuildStatus.php
  docroot/modules/custom/va_gov_build_trigger/src/WebBuildStatusInterface.php
  docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.services.yml
  docroot/sites/default/settings.php
  docroot/sites/default/settings/settings.lando.php
  docroot/sites/default/settings/settings.tugboat.php
  scripts/queue_runner/queue_runner.sh
  tests/phpunit/FrontendBuild/WebBuildCommandBuilderTest.php
Labels: Core Application Team

#4001 VACMS-3693: Adds userSection to GTM dataLayer.
  docroot/modules/custom/va_gov_backend/js/gtm_tag_trackers.es6.js
  docroot/modules/custom/va_gov_backend/js/gtm_tag_trackers.js
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  tests/behat/Drupal/FeatureContext.php
  tests/behat/features/google_tag_manager.feature
Labels: Core Application Team, DO NOT MERGE

#4061 VACMS-3910: Add details with image fieldgroup formatter type.
  config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
  docroot/modules/custom/va_gov_backend/src/Plugin/field_group/FieldGroupFormatter/DetailsWithImage.php
  docroot/themes/custom/vagovadmin/assets/css/styles.css
  docroot/themes/custom/vagovadmin/assets/css/styles.css.map
  docroot/themes/custom/vagovadmin/assets/scss/styles.scss
Labels: Product Support Team

#4037 VACMS-4024: Closed-Field-Group-Validation
  composer.json
Labels: Product Support Team

#4067 VACMS-4035: Add removal logic for service locations.
  config/sync/core.entity_form_display.node.health_care_local_health_service.default.yml
  config/sync/field.storage.node.field_service_location.yml
  docroot/modules/custom/va_gov_backend/js/service_location_hours.es6.js
  docroot/modules/custom/va_gov_backend/js/service_location_hours.js
  docroot/modules/custom/va_gov_backend/va_gov_backend.libraries.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  docroot/themes/custom/vagovadmin/assets/css/styles.css
  docroot/themes/custom/vagovadmin/assets/css/styles.css.map
  docroot/themes/custom/vagovadmin/assets/scss/styles.scss
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
Labels: Product Support Team

#4043 VACMS-3772: A Flag should be created when a user edits a node.
  composer.json
  config/sync/core.extension.yml
  config/sync/flag.flag.edited.yml
  config/sync/system.action.flag_action.edited_flag.yml
  config/sync/system.action.flag_action.edited_unflag.yml
  docroot/modules/custom/va_gov_content_export/src/AddBreadcrumbToEntity.php
  docroot/modules/custom/va_gov_notifications/src/Event/Entity/EditedFlag.php
  docroot/modules/custom/va_gov_notifications/src/Service/Flagging.php
  docroot/modules/custom/va_gov_notifications/src/Service/FlaggingInterface.php
  docroot/modules/custom/va_gov_notifications/va_gov_notifications.info.yml
  docroot/modules/custom/va_gov_notifications/va_gov_notifications.services.yml
  scripts/content/VACMS-3772-set-edited-flags-on-all-existing-content.php
  tests/behat/Drupal/FeatureContext.php
  tests/behat/features/personal_content_flags.feature
Labels: Core Application Team

#4066 VACMS-3916: CLP-Form-Field-Updates
  config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_view_display.node.campaign_landing_page.default.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_events_header.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_events_references.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_resources.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_resources_header.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_resources_intro_text.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_spotlight_header.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_spotlight_intro_text.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_stories_header.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_stories_intro.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_stories_teasers.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_video_panel_header.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_what_you_can_do_header.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_what_you_can_do_intro.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_why_this_matters.yml
  config/sync/field.field.node.campaign_landing_page.field_hero_blurb.yml
  config/sync/field.field.node.campaign_landing_page.field_primary_call_to_action.yml
  config/sync/node.type.campaign_landing_page.yml
  tests/behat/drupal-spec-tool/content_model_campaign_landing_page_content_type_fields.feature
Labels: Product Support Team

#3971 VACMS 2681: Alter Redirect view to work around redirect_options behavior.
  composer.lock
  config/sync/views.view.redirect.yml
Labels: Core Application Team

#4078 VACMS-3925: Update browser to show r&s hub description info.
  composer.json
  composer.lock
  config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
  config/sync/views.view.benefits_hub_categories.yml
  tests/behat/drupal-spec-tool/content_model_campaign_landing_page_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
Labels: Product Support Team

#4093 VACMS-4081: Remove nickname field from config.
  composer.lock
  config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_form_display.node.health_care_local_facility.inline_entity_form.yml
  config/sync/core.entity_form_display.node.health_care_region_page.default.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.ief_table.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.teaser.yml
  config/sync/core.entity_view_display.node.health_care_region_page.default.yml
  config/sync/core.entity_view_display.node.health_care_region_page.teaser.yml
  config/sync/field.field.node.health_care_local_facility.field_nickname_for_this_facility.yml
  config/sync/field.field.node.health_care_region_page.field_nickname_for_this_facility.yml
  config/sync/field.storage.node.field_nickname_for_this_facility.yml
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
Labels: Product Support Team

#4118 VACMS-4117: Updates Tablefield 2.1 -> 2.2 and applies patch.
  composer.json
  composer.lock
Labels: Core Application Team

#4063 VACMS-3986: update content release page UX
  config/sync/block.block.content_release_status_block.yml
  docroot/modules/custom/va_gov_build_trigger/css/build_trigger_form.css
  docroot/modules/custom/va_gov_build_trigger/css/content_release_status_block.css
  docroot/modules/custom/va_gov_build_trigger/js/content_release_status_block.es6.js
  docroot/modules/custom/va_gov_build_trigger/js/content_release_status_block.js
  docroot/modules/custom/va_gov_build_trigger/src/Form/BrdBuildTriggerForm.php
  docroot/modules/custom/va_gov_build_trigger/src/Form/BuildTriggerForm.php
  docroot/modules/custom/va_gov_build_trigger/src/Form/DevShopBuildTriggerForm.php
  docroot/modules/custom/va_gov_build_trigger/src/Form/LandoBuildTriggerForm.php
  docroot/modules/custom/va_gov_build_trigger/src/Form/TugboatBuildTriggerForm.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/Block/ContentReleaseStatusBlock.php
  docroot/modules/custom/va_gov_build_trigger/src/WebBuildCommandBuilder.php
  docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.libraries.yml
  docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.routing.yml
  docroot/sites/default/settings/settings.lando.php
  docroot/sites/default/settings/settings.tugboat.php
  tests/phpunit/FrontendBuild/BuildTriggerFormTest.php
  tests/phpunit/FrontendBuild/WebBuildCommandBuilderTest.php
Labels: Core Application Team

#4086 VACMS-2265: Content proofing for Campaign Landing Page
  composer.json
  composer.lock
  config/sync/core.entity_view_display.block_content.promo.default.yml
  config/sync/core.entity_view_display.media.document_external.default.yml
  config/sync/core.entity_view_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_view_display.node.news_story.default.yml
  config/sync/core.entity_view_display.paragraph.button.default.yml
  config/sync/core.entity_view_display.paragraph.link_teaser.default.yml
  config/sync/core.entity_view_display.paragraph.link_teaser_with_image.default.yml
  config/sync/core.extension.yml
Labels: Product Support Team

#4070 Fix .env file on Tugboat clone.
  .tugboat/config.yml
Labels: tugboat

#4119 VACMS-3910: Update formatter to use unmanaged files.
  config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
  docroot/modules/custom/va_gov_backend/images/connect-guide.svg
  docroot/modules/custom/va_gov_backend/images/downloadable-resources-guide.svg
  docroot/modules/custom/va_gov_backend/images/events-guide.svg
  docroot/modules/custom/va_gov_backend/images/faqs-guide.svg
  docroot/modules/custom/va_gov_backend/images/hero-banner-guide.svg
  docroot/modules/custom/va_gov_backend/images/related-benefits-guide.svg
  docroot/modules/custom/va_gov_backend/images/spotlight-guide.svg
  docroot/modules/custom/va_gov_backend/images/stories-guide.svg
  docroot/modules/custom/va_gov_backend/images/video-guide.svg
  docroot/modules/custom/va_gov_backend/images/what-you-can-do-guide.svg
  docroot/modules/custom/va_gov_backend/images/why-this-matters-guide.svg
  docroot/modules/custom/va_gov_backend/src/Plugin/field_group/FieldGroupFormatter/DetailsWithImage.php
  docroot/themes/custom/vagovadmin/assets/css/styles.css
  docroot/themes/custom/vagovadmin/assets/css/styles.css.map
  docroot/themes/custom/vagovadmin/assets/scss/styles.scss
Labels: Product Support Team

#4123 VACMS-4102 tugboat php settings
  .lando/zzz-lando-my-custom.ini
  .tugboat/config.yml
Labels: Core Application Team

#4124 VACMS-4017: CC-Policies-Proofing
  config/sync/core.entity_form_display.node.vamc_system_policies_page.default.yml
  config/sync/core.entity_view_display.node.vamc_system_policies_page.default.yml
  config/sync/core.entity_view_display.node.vamc_system_policies_page.teaser.yml
  config/sync/field.field.node.vamc_system_policies_page.field_fieldset_markup.yml
  config/sync/field.storage.node.field_fieldset_markup.yml
  config/sync/node.type.vamc_system_policies_page.yml
  docroot/modules/custom/va_gov_backend/js/script.es6.js
  docroot/modules/custom/va_gov_backend/js/script.js
  docroot/themes/custom/vagovadmin/assets/css/styles.css
  docroot/themes/custom/vagovadmin/assets/css/styles.css.map
  docroot/themes/custom/vagovadmin/assets/scss/styles.scss
  docroot/themes/custom/vagovadmin/images/icons/questionmark-disc-000000.svg
  docroot/themes/custom/vagovadmin/templates/layout/fieldset.html.twig
  tests/behat/drupal-spec-tool/content_model_bundles.feature
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
Labels: Product Support Team
