Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2021-02, with the labels that each got.

#4079 VACMS-3962: Updates Drupal to 8.9.13
  composer.json
  composer.lock
Labels: Core Application Team

#4164 VACMS-4158: Add content release logs view
  config/sync/views.view.content_release_logs.yml
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/Block/ContentReleaseStatusBlock.php
  tests/behat/drupal-spec-tool/views.feature
Labels: Core Application Team

#4045 Cypress behavioral testing POC
  .gitignore
  READMES/testing.md
  composer.json
  package-lock.json
  package.json
  scripts/tests/cypress.sh
  tests.yml
  tests/accessibility/cypress.json
  tests/accessibility/cypress/README.md
  tests/accessibility/cypress/integration/homepageAccessibility.spec.js
  tests/accessibility/cypress/integration/nodeCreationAccessibility.spec.js
  tests/accessibility/cypress/plugins/index.js
  tests/accessibility/cypress/support/commands.js
  tests/accessibility/cypress/support/index.js
  tests/behavioral/cypress.json
  tests/behavioral/cypress/fixtures/example.json
  tests/behavioral/cypress/integration/common/i_am_at_url.js
  tests/behavioral/cypress/integration/common/i_should_see_text.js
  tests/behavioral/cypress/integration/common/the_url_for_link_with_text_should_contain.js
  tests/behavioral/cypress/integration/help_center.feature
  tests/behavioral/cypress/plugins/index.js
  tests/behavioral/cypress/support/commands.js
  tests/behavioral/cypress/support/index.js
Labels: Core Application Team

#3675 Add back code scanning
  .github/workflows/codeql.yml
Labels: security

#4186 VACMS-4156: Add pub date to video.
  config/sync/core.entity_form_display.media.video.default.yml
  config/sync/core.entity_form_display.media.video.media_browser.yml
  config/sync/core.entity_form_display.media.video.media_library.yml
  config/sync/core.entity_view_display.media.video.default.yml
  config/sync/core.entity_view_display.media.video.embedded.yml
  config/sync/core.entity_view_display.media.video.thumbnail.yml
  config/sync/core.entity_view_display.media.video.user_guides.yml
  config/sync/field.field.media.video.field_publication_date.yml
  config/sync/field.storage.media.field_publication_date.yml
  tests/behat/drupal-spec-tool/content_model_media_fields.feature
Labels: Product Support Team

#4167 VACMS-4146: Hide blob field on form and page.
  config/sync/core.entity_form_display.node.health_care_local_health_service.default.yml
  config/sync/core.entity_view_display.node.health_care_local_health_service.default.yml
  tests/behat/drupal-spec-tool/content_model_benefits_hubs_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
Labels: Product Support Team

#4188 VACMS-3998: user import improvements
  READMES/user_management.md
  docroot/modules/custom/va_gov_user/src/EventSubscriber/PostRowSave.php
  docroot/modules/custom/va_gov_user/src/EventSubscriber/UserImport.php
  docroot/modules/custom/va_gov_user/va_gov_user.services.yml
Labels: Core Application Team

#4197 VACMS-4194: Require installed yarn version to match vetsweb
  composer.json
  composer.lock
  scripts/composer/check_yarn_version.sh
Labels: Core Application Team

#4157 VACMS-4137: Open-CLP-Field-Groups-With-Required-Empty-Field
  config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
  docroot/modules/custom/va_gov_backend/js/script.es6.js
  docroot/modules/custom/va_gov_backend/js/script.js
  tests/behat/features/content_editing.feature
Labels: Product Support Team

#4149 VACMS-3955: Get Jenkins API Token from SSM
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRD.php
  docroot/sites/default/settings.php
Labels: Core Application Team

#4184 VACMS 4133: Update help text for link-to-file-or-video
  config/sync/field.field.paragraph.downloadable_file.field_title.yml
  config/sync/paragraphs.paragraphs_type.downloadable_file.yml
  docroot/themes/custom/vagovadmin/images/download-map.jpg
  docroot/themes/custom/vagovadmin/images/screenshots/download-map.jpg
  docroot/themes/custom/vagovadmin/images/screenshots/link-to-file-or-video.png
  tests/behat/drupal-spec-tool/content_model_bundles.feature
Labels: Core Application Team

#4187 VACMS-4105: Render JSD Widget on Access-Denied pages
  config/sync/block.block.whatsnewinthecms.yml
  docroot/modules/custom/va_gov_help_center/src/Plugin/Block/WhatsNew.php
  docroot/modules/custom/va_gov_help_center/va_gov_help_center.module
  package-lock.json
  package.json
  tests/behat/features/cms_whats_new_block.feature
  tests/behavioral/cypress/integration/common/i_am_logged_in_as_a_user_with_the_role.js
  tests/behavioral/cypress/integration/common/i_attempt_to_visit_url.js
  tests/behavioral/cypress/integration/common/i_click_the_link.js
  tests/behavioral/cypress/integration/common/i_create_a_node.js
  tests/behavioral/cypress/integration/common/i_fill_in_field_with_value.js
  tests/behavioral/cypress/integration/common/i_scroll_to_position.js
  tests/behavioral/cypress/integration/common/i_should_see.js
  tests/behavioral/cypress/integration/common/i_should_see_text.js
  tests/behavioral/cypress/integration/help_center.feature
  tests/behavioral/cypress/integration/help_center/jsd_widget.js
  tests/behavioral/cypress/integration/help_center/whats_new_in_the_cms_block.js
  tests/behavioral/cypress/support/commands.js
Labels: Core Application Team

#4225 VACMS-4222: Better testing for the BRD environment.
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRD.php
Labels: Core Application Team

#4220 VACMS-3861: upgrade webform to 6.x
  composer.json
  composer.lock
Labels: Core Application Team, Product Support Team

#4218 VACMS-2407: Hides "plain language certified date" field from Benefits…
  config/sync/core.entity_form_display.node.landing_page.default.yml
  config/sync/core.entity_form_display.node.page.default.yml
  tests/behat/drupal-spec-tool/content_model_benefits_hubs_content_type_fields.feature
Labels: Core Application Team

#4224 VACMS-4077 Hide field labels and source data for entity field fetch fields.
  composer.json
  composer.lock
  config/sync/core.entity_form_display.node.vamc_system_policies_page.default.yml
  config/sync/core.entity_view_display.node.vamc_system_policies_page.default.yml
Labels: Product Support Team

#4168 VACMS-1421: Replace non rich text intro field with rich text intro.
  config/sync/core.entity_form_display.node.page.default.yml
  config/sync/core.entity_view_display.node.page.default.yml
  config/sync/core.entity_view_display.node.page.teaser.yml
  config/sync/field.field.node.page.field_intro_text.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  tests/behat/drupal-spec-tool/content_model_benefits_hubs_content_type_fields.feature
  tests/phpunit/API/GraphQLTest.php
Labels: Product Support Team

#4227 VACMS-4139: Reorder national content.
  config/sync/core.entity_form_display.node.vamc_system_policies_page.default.yml
  config/sync/core.entity_view_display.node.vamc_system_policies_page.default.yml
Labels: Product Support Team

#4237 VACMS-4236: Show VAMC system on HC facility entity reference
  config/sync/field.field.node.health_care_local_health_service.field_facility_location.yml
  config/sync/views.view.local_facilities_entity_reference_view.yml
Labels: Core Application Team

#4219 VACMS-2764: Adjusts CMS system update language with faster downtimes.
  docroot/modules/custom/va_gov_backend/src/Deploy/Plugin/MaintenanceMode.php
  docroot/sites/default/maintenance.html
Labels: Core Application Team

#4235 VACMS-4234: Update intro page help text.
  config/sync/field.field.node.page.field_intro_text_limited_html.yml
Labels: Product Support Team

#4189 VACMS-4090: Fix required related info field bug.
  config/sync/core.entity_form_display.node.q_a.default.yml
  docroot/modules/custom/va_gov_backend/js/script.es6.js
  docroot/modules/custom/va_gov_backend/js/script.js
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Product Support Team

#4232 VACMS-4212: Add past events bulk ops view.
  config/sync/views.view.content.yml
  tests/behat/drupal-spec-tool/views.feature
Labels: Product Support Team

#4291 VACMS-4286: Upgrade module to d9 compatibility.
  composer.json
  composer.lock
Labels: Product Support Team

#4298 VACMS-000 Add dependency to va_gov_graphql.
  docroot/modules/custom/va_gov_graphql/va_gov_graphql.info.yml
Labels: Core Application Team

#4247 VACMS-4049: Policy-Tooltips-Accessible
  config/sync/core.entity_form_display.node.vamc_system_policies_page.default.yml
  config/sync/core.entity_view_display.node.vamc_system_policies_page.default.yml
  docroot/modules/custom/va_gov_backend/js/field_group_tooltip.es6.js
  docroot/modules/custom/va_gov_backend/js/field_group_tooltip.js
  docroot/modules/custom/va_gov_backend/js/script.es6.js
  docroot/modules/custom/va_gov_backend/js/script.js
  docroot/modules/custom/va_gov_backend/src/Plugin/field_group/FieldGroupFormatter/Tooltip.php
  docroot/modules/custom/va_gov_backend/va_gov_backend.libraries.yml
  docroot/themes/custom/vagovadmin/assets/css/styles.css
  docroot/themes/custom/vagovadmin/assets/css/styles.css.map
  docroot/themes/custom/vagovadmin/assets/scss/styles.scss
Labels: Product Support Team

#4338 VACMS-4307 restrict va form archiving to cms migrator. 2
  docroot/modules/custom/va_gov_migrate/va_gov_migrate.module
Labels: Product Support Team

#4326 VACMS-4252_4253_4254_4255_4256_4257_4314 module removal and patch update
  composer.json
  composer.lock
  patches/duplicate-row-message.patch
Labels: Core Application Team, Product Support Team

#4321 VACMS-4274: Make custom modules Drupal 9 compatible.
  docroot/modules/custom/disable_node_menu_item/disable_node_menu_item.info.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.info.yml
  docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.info.yml
  docroot/modules/custom/va_gov_bulk/va_gov_bulk.info.yml
  docroot/modules/custom/va_gov_consumers/va_gov_consumers.info.yml
  docroot/modules/custom/va_gov_content_export/va_gov_content_export.info.yml
  docroot/modules/custom/va_gov_db/va_gov_db.info.yml
  docroot/modules/custom/va_gov_db/va_gov_db.install
  docroot/modules/custom/va_gov_flags/va_gov_flags.info.yml
  docroot/modules/custom/va_gov_govdelivery/va_gov_govdelivery.info.yml
  docroot/modules/custom/va_gov_graphql/va_gov_graphql.info.yml
  docroot/modules/custom/va_gov_help_center/va_gov_help_center.info.yml
  docroot/modules/custom/va_gov_login/va_gov_login.info.yml
  docroot/modules/custom/va_gov_migrate/va_gov_migrate.info.yml
  docroot/modules/custom/va_gov_post_api/va_gov_post_api.info.yml
  docroot/modules/custom/va_gov_preview/va_gov_preview.info.yml
  docroot/modules/custom/va_gov_resources_and_support/va_gov_resources_and_support.info.yml
  docroot/modules/custom/va_gov_user/va_gov_user.info.yml
  docroot/modules/custom/va_gov_workflow_assignments/va_gov_workflow_assignments.info.yml
  docroot/modules/custom/zippylib/zippylib.info.yml
Labels: Core Application Team

#4341 VACMS-4313: Use manually created patch for flood control
  composer.json
  composer.lock
Labels: Core Application Team

#4350 Add mailhog service to Lando
  .lando.yml
  READMES/local.md
Labels: Core Application Team, DX, Drupal engineering

#4359 VACMS-4200: d9 compatibility for vagovadmin
  docroot/modules/custom/va_gov_backend/js/gtm_tag_trackers.js
  docroot/themes/custom/vagovadmin/assets/css/proofing.css
  docroot/themes/custom/vagovadmin/assets/css/proofing.css.map
  docroot/themes/custom/vagovadmin/assets/css/styles.min.css
  docroot/themes/custom/vagovadmin/assets/css/styles.min.css.map
  docroot/themes/custom/vagovadmin/assets/js/vagovadmin.theme.help.es6.js
  docroot/themes/custom/vagovadmin/assets/js/vagovadmin.theme.help.js
  docroot/themes/custom/vagovadmin/assets/scss/_tooltip.scss
  docroot/themes/custom/vagovadmin/templates/layout/field--node--page.html.twig
  docroot/themes/custom/vagovadmin/vagovadmin.info.yml
  docroot/themes/custom/vagovadmin/vagovadmin.libraries.yml
Labels: Core Application Team

#4346 VACMS-4347: Add default details class to required fieldsets on clp.
  config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
Labels: Product Support Team

#4372 VACMS-4194: Fail the yaml test when va:web:build errors out
  tests.yml
  tests/scripts/build-web.sh
Labels: Core Application Team

#4358 VACMS-4275: Set status property on migrate rows before user creation
  docroot/modules/custom/va_gov_user/src/EventSubscriber/UserImport.php
Labels: Core Application Team

#4378 VACMS-3904 Remove deploy steps from tests.yml & change order of deploy steps to match `drush deploy`
  .lando.yml
  .tugboat/config.yml
  tests.yml
Labels: DevOps

#4361 VACMS-4147: Add new fields to vha vocab.
  config/sync/core.entity_form_display.taxonomy_term.health_care_service_taxonomy.default.yml
  config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.default.yml
  config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_vet_center_com_conditions.yml
  config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_vet_center_friendly_name.yml
  config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_vet_center_service_descrip.yml
  config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_vet_center_type_of_care.yml
  config/sync/field.storage.taxonomy_term.field_vet_center_com_conditions.yml
  config/sync/field.storage.taxonomy_term.field_vet_center_friendly_name.yml
  config/sync/field.storage.taxonomy_term.field_vet_center_service_descrip.yml
  config/sync/field.storage.taxonomy_term.field_vet_center_type_of_care.yml
  tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature
Labels: Product Support Team

#4366 VACMS-4322_4323_4340 Vet center config
  config/sync/auto_entitylabel.settings.node.vet_center_locations_list.yml
  config/sync/core.entity_form_display.node.vet_center.default.yml
  config/sync/core.entity_form_display.node.vet_center_locations_list.default.yml
  config/sync/core.entity_view_display.node.vet_center.default.yml
  config/sync/core.entity_view_display.node.vet_center.teaser.yml
  config/sync/core.entity_view_display.node.vet_center_locations_list.default.yml
  config/sync/core.entity_view_display.node.vet_center_locations_list.teaser.yml
  config/sync/core.menu.static_menu_link_overrides.yml
  config/sync/field.field.node.vet_center.field_address.yml
  config/sync/field.field.node.vet_center.field_facility_hours.yml
  config/sync/field.field.node.vet_center.field_intro_text.yml
  config/sync/field.field.node.vet_center.field_media.yml
  config/sync/field.field.node.vet_center.field_non_traditional_hours.yml
  config/sync/field.field.node.vet_center.field_phone_number.yml
  config/sync/field.field.node.vet_center.field_vet_center_call_center.yml
  config/sync/field.field.node.vet_center_locations_list.field_administration.yml
  config/sync/field.field.node.vet_center_locations_list.field_vet_center.yml
  config/sync/field.storage.node.field_non_traditional_hours.yml
  config/sync/field.storage.node.field_vet_center.yml
  config/sync/field.storage.node.field_vet_center_call_center.yml
  config/sync/node.type.locations_listing.yml
  config/sync/node.type.vet_center_locations_list.yml
  config/sync/pathauto.pattern.vba_facility_nca_facility_veterans_center.yml
  config/sync/pathauto.pattern.vet_center.yml
  config/sync/pathauto.pattern.vet_center_locations_list.yml
  config/sync/user.role.content_editor.yml
  config/sync/user.role.content_publisher.yml
  config/sync/user.role.content_reviewer.yml
  config/sync/workbench_access.access_scheme.section.yml
  config/sync/workflows.workflow.editorial.yml
  tests/behat/drupal-spec-tool/content_model_bundles.feature
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Product Support Team

#3516 VACMS-2860: Remove Old Date Field
  config/sync/core.entity_form_display.node.event.default.yml
  config/sync/core.entity_form_display.node.press_release.default.yml
  config/sync/core.entity_form_display.paragraph.situation_update.default.yml
  config/sync/core.entity_view_display.node.event.default.yml
  config/sync/core.entity_view_display.node.event.teaser.yml
  config/sync/core.entity_view_display.node.press_release.default.yml
  config/sync/core.entity_view_display.node.press_release.teaser.yml
  config/sync/core.entity_view_display.paragraph.situation_update.default.yml
  config/sync/core.entity_view_display.paragraph.situation_update.preview.yml
  config/sync/field.field.node.event.field_date.yml
  config/sync/field.field.node.press_release.field_datetime_range_timezone.yml
  config/sync/field.field.paragraph.situation_update.field_date_and_time.yml
  config/sync/field.storage.node.field_date.yml
  config/sync/field.storage.paragraph.field_date_and_time.yml
  config/sync/views.view.date_fields.yml
  config/sync/views.view.listing_page_dashboard.yml
  docroot/modules/custom/va_gov_govdelivery/src/Service/ProcessStatusBulletin.php
  tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
  tests/behat/drupal-spec-tool/views.feature
  tests/phpunit/Content/BulletinQueueTest.php
Labels: Product Support Team

#4403 VACMS-4258: update entity_reference_validators
  composer.json
  composer.lock
  package-lock.json
  package.json
  tests/behavioral/cypress.json
  tests/behavioral/cypress/integration/common/i_click_the_edit_tab.js
  tests/behavioral/cypress/integration/common/i_create_a_node.js
  tests/behavioral/cypress/integration/common/i_save_the_node.js
  tests/behavioral/cypress/integration/common/i_select_the_benefits_hub.js
  tests/behavioral/cypress/integration/common/i_wait_seconds.js
  tests/behavioral/cypress/integration/entity_reference_validation.feature
  tests/behavioral/cypress/support/commands.js
Labels: Core Application Team

#4348 VACMS-2743: Fix image cropping issues.
  .lando.yml
  config/sync/core.extension.yml
  config/sync/image_style_warmer.settings.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  docroot/modules/custom/va_gov_media/va_gov_media.info.yml
  docroot/modules/custom/va_gov_media/va_gov_media.module
  package-lock.json
  package.json
  scripts/tests/cypress.sh
  tests/behavioral/cypress.json
  tests/behavioral/cypress/fixtures/images/polygon_image.png
  tests/behavioral/cypress/fixtures/images/polygon_image2.png
  tests/behavioral/cypress/fixtures/images/polygon_image3.png
  tests/behavioral/cypress/fixtures/images/polygon_image4.png
  tests/behavioral/cypress/fixtures/images/polygon_image5.png
  tests/behavioral/cypress/fixtures/images/polygon_image_crop.png
  tests/behavioral/cypress/integration/common/i_am_logged_in_as_a_user_with_the_role.js
  tests/behavioral/cypress/integration/common/i_create_a_media.js
  tests/behavioral/cypress/integration/common/i_create_a_node.js
  tests/behavioral/cypress/integration/common/i_delete_the_derivative_of_the_media_image.js
  tests/behavioral/cypress/integration/common/i_select_option_from_dropdown.js
  tests/behavioral/cypress/integration/common/i_select_the_benefits_hub.js
  tests/behavioral/cypress/integration/common/i_should_see.js
  tests/behavioral/cypress/integration/common/i_view_the_derivative_of_the_media_image.js
  tests/behavioral/cypress/integration/common/the_derivative_of_the_media_image_should_match_the_fixture.js
  tests/behavioral/cypress/integration/image_crop.feature
  tests/behavioral/cypress/plugins/index.js
  tests/behavioral/cypress/support/commands.js
Labels: Core Application Team, Planned work

#4364 VACMS-4203: remove computed fields and dependent code
  composer.json
  composer.lock
  config/sync/core.entity_form_display.node.full_width_banner_alert.default.yml
  config/sync/core.entity_form_display.node.full_width_banner_alert.inline_entity_form.yml
  config/sync/core.entity_view_display.node.full_width_banner_alert.default.yml
  config/sync/core.entity_view_display.node.full_width_banner_alert.ief_table.yml
  config/sync/core.entity_view_display.node.full_width_banner_alert.teaser.yml
  config/sync/core.extension.yml
  config/sync/field.field.node.full_width_banner_alert.field_banner_alert_computdvalues.yml
  config/sync/field.storage.node.field_banner_alert_computdvalues.yml
  docroot/modules/custom/va_gov_govdelivery/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_govdelivery/src/Service/ProcessStatusBulletin.php
  docroot/modules/custom/va_gov_govdelivery/templates/va-gov-body-alert.html.twig
  docroot/modules/custom/va_gov_govdelivery/va_gov_govdelivery.module
  docroot/modules/custom/va_gov_govdelivery/va_gov_govdelivery.services.yml
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
  tests/phpunit/Content/BulletinQueueTest.php
Labels: Core Application Team

#4377 VACMS-4355 VC facility health service
  config/sync/auto_entitylabel.settings.node.vet_center_facility_health_servi.yml
  config/sync/core.entity_form_display.node.vet_center_facility_health_servi.default.yml
  config/sync/core.entity_view_display.node.vet_center_facility_health_servi.default.yml
  config/sync/core.entity_view_display.node.vet_center_facility_health_servi.teaser.yml
  config/sync/core.menu.static_menu_link_overrides.yml
  config/sync/field.field.node.vet_center_facility_health_servi.field_administration.yml
  config/sync/field.field.node.vet_center_facility_health_servi.field_body.yml
  config/sync/field.field.node.vet_center_facility_health_servi.field_service_name_and_descripti.yml
  config/sync/field.field.node.vet_center_facility_health_servi.field_vet_center.yml
  config/sync/field.storage.node.field_vet_center.yml
  config/sync/node.type.vet_center_facility_health_servi.yml
  config/sync/pathauto.pattern.vet_center_facility_health_service.yml
  config/sync/user.role.content_admin.yml
  config/sync/user.role.content_editor.yml
  config/sync/user.role.content_publisher.yml
  config/sync/user.role.content_reviewer.yml
  config/sync/workflows.workflow.editorial.yml
  tests/behat/drupal-spec-tool/content_model_bundles.feature
  tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Product Support Team

#4433 VACMS-4405: Disable facility api tablefield cells.
  docroot/themes/custom/vagovadmin/assets/css/styles.css
  docroot/themes/custom/vagovadmin/assets/css/styles.css.map
  docroot/themes/custom/vagovadmin/assets/scss/styles.scss
Labels: Product Support Team

#4436 VACMS-000: Upgrade web version.
  composer.lock
Labels: Product Support Team

#4388 VACMS-4387: Inline entity forms on CLP.
  config/sync/auto_entitylabel.settings.block_content.promo.yml
  config/sync/core.entity_form_display.block_content.promo.default.yml
  config/sync/core.entity_form_display.media.document_external.default.yml
  config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_view_display.block_content.promo.default.yml
  config/sync/entity_browser.browser.downloadable_resources.yml
  config/sync/field.field.block_content.promo.field_instructions.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_resources.yml
  config/sync/views.view.custom_block_entity_browsers.yml
  config/sync/views.view.va_blocks_admin.yml
  tests.yml
  tests/behat/drupal-spec-tool/content_model_campaign_landing_page_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_custom_block_fields.feature
  tests/behat/drupal-spec-tool/content_model_media_fields.feature
  tests/scripts/check-linkit-logs.sh
Labels: Product Support Team

#4450 VACMS-4279: remove markdown dependencies and disable module
  config/sync/core.extension.yml
  config/sync/filter.format.rich_text.yml
  config/sync/filter.format.rich_text_limited.yml
  config/sync/markdown.settings.yml
  docroot/modules/custom/va_gov_consumers/src/GithubConsumer.php
  docroot/modules/custom/va_gov_consumers/va_gov_consumers.info.yml
  docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
  docroot/modules/custom/va_gov_db/va_gov_db.install
Labels: Core Application Team

#4449 VACMS-4259: Removes field_formatter module.
  config/sync/core.extension.yml
Labels: Core Application Team

#4455 VACMS-000: Disable layout builder in favor of fields | Remove Layout Builder
  config/sync/core.entity_view_display.media.video.user_guides.yml
  config/sync/core.entity_view_display.node.event_listing.default.yml
  config/sync/core.entity_view_display.node.landing_page.support_services_listing.yml
  config/sync/core.entity_view_display.node.q_a.support_services_listing.yml
  config/sync/core.entity_view_display.node.support_service.support_services_listing.yml
  config/sync/core.entity_view_display.node.va_form.external_content.yml
  config/sync/core.entity_view_display.node.vet_center_cap.ief_table.yml
  config/sync/core.entity_view_display.paragraph.downloadable_file.user_guides.yml
  config/sync/core.entity_view_display.paragraph.email_contact.ief_table.yml
  config/sync/core.entity_view_display.paragraph.link_teaser.user_guides.yml
  config/sync/core.entity_view_display.paragraph.list_of_link_teasers.user_guides.yml
  config/sync/core.entity_view_display.paragraph.list_of_links.user_guides.yml
  config/sync/core.entity_view_display.paragraph.lists_of_links.user_guides.yml
  config/sync/core.entity_view_display.paragraph.media_list_videos.user_guides.yml
  config/sync/core.entity_view_display.paragraph.phone_number.ief_table.yml
  config/sync/core.extension.yml
Labels: Product Support Team

#4456 VACMS-4280: Disable mass_pwreset module
  config/sync/core.extension.yml
Labels: Core Application Team

#4406 VACMS-4260 4264 4265 4266 4267 4276 4277 4278 D9 upgrades
  composer.json
  composer.lock
  config/sync/admin_toolbar_tools.settings.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  tests.yml
  tests/behat/features/hms.feature
  tests/scripts/check-cer.sh
Labels: Core Application Team, Planned work

#4452 VACMS-4443_4444 vc mobile & outstation
  config/sync/core.entity_form_display.node.vet_center_mobile_vet_center.default.yml
  config/sync/core.entity_form_display.node.vet_center_outstation.default.yml
  config/sync/core.entity_view_display.node.vet_center_mobile_vet_center.default.yml
  config/sync/core.entity_view_display.node.vet_center_mobile_vet_center.teaser.yml
  config/sync/core.entity_view_display.node.vet_center_outstation.default.yml
  config/sync/core.entity_view_display.node.vet_center_outstation.teaser.yml
  config/sync/core.menu.static_menu_link_overrides.yml
  config/sync/field.field.node.vet_center_mobile_vet_center.field_address.yml
  config/sync/field.field.node.vet_center_mobile_vet_center.field_administration.yml
  config/sync/field.field.node.vet_center_mobile_vet_center.field_facility_hours.yml
  config/sync/field.field.node.vet_center_mobile_vet_center.field_facility_locator_api_id.yml
  config/sync/field.field.node.vet_center_mobile_vet_center.field_media.yml
  config/sync/field.field.node.vet_center_mobile_vet_center.field_operating_status_facility.yml
  config/sync/field.field.node.vet_center_mobile_vet_center.field_operating_status_more_info.yml
  config/sync/field.field.node.vet_center_mobile_vet_center.field_phone_number.yml
  config/sync/field.field.node.vet_center_mobile_vet_center.field_vet_center.yml
  config/sync/field.field.node.vet_center_outstation.field_address.yml
  config/sync/field.field.node.vet_center_outstation.field_administration.yml
  config/sync/field.field.node.vet_center_outstation.field_facility_hours.yml
  config/sync/field.field.node.vet_center_outstation.field_facility_locator_api_id.yml
  config/sync/field.field.node.vet_center_outstation.field_media.yml
  config/sync/field.field.node.vet_center_outstation.field_operating_status_facility.yml
  config/sync/field.field.node.vet_center_outstation.field_operating_status_more_info.yml
  config/sync/field.field.node.vet_center_outstation.field_phone_number.yml
  config/sync/field.field.node.vet_center_outstation.field_vet_center.yml
  config/sync/node.type.vet_center_mobile_vet_center.yml
  config/sync/node.type.vet_center_outstation.yml
  config/sync/pathauto.pattern.vet_center_mobile_vet_center.yml
  config/sync/pathauto.pattern.vet_center_mobile_vet_center_outstations.yml
  config/sync/user.role.content_editor.yml
  config/sync/user.role.content_publisher.yml
  config/sync/user.role.content_reviewer.yml
  config/sync/workbench_access.access_scheme.section.yml
  config/sync/workflows.workflow.editorial.yml
  tests/behat/drupal-spec-tool/content_model_bundles.feature
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Product Support Team

#4394 VAMS-4305 Migration url csv fetcher hardening
  composer.json
  composer.lock
  config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml
  docroot/modules/custom/va_gov_migrate/src/Plugin/migrate_plus/data_parser/Csv.php
Labels: Migration, Product Support Team, vsa-facilities

#4470 Add clone and scalability readme
  READMES/scalability.md
  scripts/clone.php
Labels: Core Application Team
