Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2021-09, with the labels that each got.

#6326 VACMS-000: Update code to match db state (these changes have appeared in every export for the past month).
  config/sync/core.entity_form_display.media.document.default.yml
  config/sync/core.entity_form_display.media.document.media_library.yml
  config/sync/core.entity_form_display.node.event.default.yml
  config/sync/core.entity_form_display.node.regional_health_care_service_des.inline_entity_form.yml
  config/sync/core.entity_form_display.paragraph.situation_update.default.yml
  config/sync/core.extension.yml
  config/sync/node_link_report.settings.yml
  config/sync/user.mail.yml
  config/sync/views.view.advancedqueue_jobs.yml
Labels: Product Support Team

#6324 VACMS-6304: Sync drupal spec tool with db.
  tests/behat/drupal-spec-tool/access_control.feature
  tests/behat/drupal-spec-tool/content_model_alerts_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_bundles.feature
  tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature
  tests/behat/drupal-spec-tool/content_model_user_guides_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature
  tests/behat/drupal-spec-tool/media.feature
  tests/behat/drupal-spec-tool/views.feature
  tests/behat/drupal-spec-tool/workflow.feature
Labels: Product Support Team

#5249 VACMS-5248: Prevent archiving of certain content types by non-content-admins.
  config/sync/user.role.content_admin.yml
  config/sync/user.role.content_editor.yml
  config/sync/user.role.content_publisher.yml
  config/sync/user.role.content_reviewer.yml
  config/sync/workflows.workflow.content_admin.yml
  config/sync/workflows.workflow.editorial.yml
  tests/behat/drupal-spec-tool/workflow.feature
  tests/behat/features/content_editing.feature
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Product Support Team

#5769 VACMS-5696 remove Erie operating status endpoint.
  config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml
Labels: Product Support Team, DO NOT MERGE

#6308 VACMS-6213: Add logic to handle top task pages.
  config/sync/auto_entitylabel.settings.node.vamc_system_billing_insurance.yml
  config/sync/auto_entitylabel.settings.node.vamc_system_medical_records_offi.yml
  config/sync/auto_entitylabel.settings.node.vamc_system_register_for_care.yml
  docroot/modules/custom/va_gov_vamc/css/set_menu_title.css
  docroot/modules/custom/va_gov_vamc/js/set_menu_title.es6.js
  docroot/modules/custom/va_gov_vamc/js/set_menu_title.js
  docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_vamc/va_gov_vamc.libraries.yml
Labels: Product Support Team

#6366 VACMS-4103: Repairs broken redirects.
  docroot/modules/custom/va_gov_db/va_gov_db.post_update.php
Labels: Core Application Team

#6327 VACMS-6305: Hide paths field for non-admins.
  docroot/modules/custom/va_gov_banner/src/EventSubscriber/EntityEventSubscriber.php
Labels: Product Support Team

#6328 VACMS-6281: Remove content_admin delete perms.
  config/sync/user.role.content_admin.yml
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Product Support Team

#6358 VACMS-6106: Add process list themeing.
  docroot/themes/custom/vagovadmin/assets/css/proofing.css
  docroot/themes/custom/vagovadmin/assets/css/proofing.css.map
  docroot/themes/custom/vagovadmin/assets/css/styles.css
  docroot/themes/custom/vagovadmin/assets/css/styles.css.map
  docroot/themes/custom/vagovadmin/assets/scss/_paragraphs.scss
  docroot/themes/custom/vagovadmin/assets/scss/_process_list.scss
  docroot/themes/custom/vagovadmin/assets/scss/styles.scss
Labels: Product Support Team

#6362 VACMS-6340: Update paragraph form config.
  config/sync/core.entity_form_display.node.centralized_content.default.yml
  tests/behat/drupal-spec-tool/content_model_va_common_content_type_fields.feature
Labels: Product Support Team

#6378 VACMS-6074 Accordions
  docroot/themes/custom/vagovadmin/assets/css/styles.css
  docroot/themes/custom/vagovadmin/assets/css/styles.css.map
  docroot/themes/custom/vagovadmin/assets/scss/_accordions.scss
  docroot/themes/custom/vagovadmin/assets/scss/styles.scss
  docroot/themes/custom/vagovadmin/templates/paragraph/paragraph--collapsible-panel-item.html.twig
  docroot/themes/custom/vagovadmin/templates/paragraph/paragraph--q-a.html.twig
Labels: Product Support Team

#6320 VACMS-6317: Enable style guide for auth and anon users.
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/user.role.anonymous.yml
  config/sync/user.role.authenticated.yml
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Product Support Team

#6338 VACMS-6330: Validation constraint to prevent local file links.
  docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventAbsoluteCmsLinksValidator.php
  docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventLocalFileLinks.php
  docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventLocalFileLinksValidator.php
  docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/Traits/ValidatorContextAccessTrait.php
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  tests/phpunit/Content/PreventAbsoluteCmsLinksValidatorTest.php
  tests/phpunit/Content/PreventLocalFileLinksValidatorTest.php
  tests/traits/ValidatorTestTrait.php
Labels: Core Application Team

#6265 Enable jsonapi modules and openapi endpoint
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/jsonapi.settings.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.access_scheme--access_scheme.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.advancedqueue_queue--advancedqueue_queue.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.block--block.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.config_split--config_split.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.environment_indicator--environment_indicator.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.flag--flag.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.graphql_query_map--graphql_query_map.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.jsonapi_resource_config--jsonapi_resource_config.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.migration--migration.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.migration_group--migration_group.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.password_policy--password_policy.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.pathauto_pattern--pathauto_pattern.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.rdf_mapping--rdf_mapping.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.rest_resource_config--rest_resource_config.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.search_api_index--search_api_index.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.search_api_server--search_api_server.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.search_api_task--search_api_task.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.taxonomy_menu--taxonomy_menu.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.toolbar_menu_element--toolbar_menu_element.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.workflow--workflow.yml
  config/sync/jsonapi_extras.settings.yml
  docroot/modules/custom/va_gov_api/src/Plugin/openapi/OpenApiGenerator/VAOpenApiGenerator.php
  docroot/modules/custom/va_gov_api/va_gov_api.info.yml
  scripts/generate-open-spec.sh
Labels: Core Application Team

#6412 VACMS-000 consolidate user_quide and help_center
  config/sync/core.extension.yml
  docroot/modules/custom/va_gov_db/va_gov_db.install
  docroot/modules/custom/va_gov_help_center/va_gov_help_center.module
  docroot/modules/custom/va_gov_user_guide/va_gov_user_guide.module
Labels: Technical debt, Product Support Team

#6410 VACMS-6370: Hide service selects on vc's for all roles.
  docroot/modules/custom/va_gov_vet_center/js/set_ief_service_selects.es6.js
  docroot/modules/custom/va_gov_vet_center/js/set_ief_service_selects.js
Labels: Product Support Team

#6422 VACMS-4904: Drupal sends number of active users.
  config/sync/prometheus_exporter.settings.yml
  docroot/modules/custom/va_gov_backend/src/Plugin/MetricsCollector/ActiveUserCount.php
Labels: Core Application Team

#6433 Remove fresno and las vegas endpoints
  config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml
Labels: Product Support Team

#6459 VACMS-6448: Add new name field to vc.
  config/sync/core.entity_form_display.node.vet_center.default.yml
  config/sync/core.entity_view_display.node.vet_center.default.yml
  config/sync/core.entity_view_display.node.vet_center.external_content.yml
  config/sync/core.entity_view_display.node.vet_center.ief_table.yml
  config/sync/core.entity_view_display.node.vet_center.teaser.yml
  config/sync/field.field.node.vet_center.field_official_name.yml
  config/sync/field.storage.node.field_official_name.yml
  tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature
Labels: Sitewide CMS Team

#6475 VACMS-6423: Update accordion usage and appearance.
  docroot/themes/custom/vagovadmin/assets/css/styles.css
  docroot/themes/custom/vagovadmin/assets/css/styles.css.map
  docroot/themes/custom/vagovadmin/assets/scss/_accordions.scss
  docroot/themes/custom/vagovadmin/templates/layout/html.html.twig
  docroot/themes/custom/vagovadmin/templates/paragraph/paragraph--documentation-page--collapsible-panel-item.html.twig
  docroot/themes/custom/vagovadmin/templates/paragraph/paragraph--documentation-page--q-a.html.twig
  docroot/themes/custom/vagovadmin/vagovadmin.theme
Labels: Sitewide CMS Team

#6397 VACMS-6396: Add EFF fields to 3 top task pages.
  config/sync/core.entity_form_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_form_display.node.vamc_system_medical_records_offi.default.yml
  config/sync/core.entity_form_display.node.vamc_system_register_for_care.default.yml
  config/sync/core.entity_view_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_view_display.node.vamc_system_medical_records_offi.default.yml
  config/sync/core.entity_view_display.node.vamc_system_register_for_care.default.yml
  config/sync/field.field.node.vamc_system_billing_insurance.field_cc_bottom_of_page_content.yml
  config/sync/field.field.node.vamc_system_billing_insurance.field_cc_related_links.yml
  config/sync/field.field.node.vamc_system_billing_insurance.field_cc_top_of_page_content.yml
  config/sync/field.field.node.vamc_system_medical_records_offi.field_cc_faqs.yml
  config/sync/field.field.node.vamc_system_medical_records_offi.field_cc_get_records_in_person.yml
  config/sync/field.field.node.vamc_system_medical_records_offi.field_cc_get_records_mail_or_fax.yml
  config/sync/field.field.node.vamc_system_medical_records_offi.field_cc_how_we_share_records.yml
  config/sync/field.field.node.vamc_system_medical_records_offi.field_cc_react_widget.yml
  config/sync/field.field.node.vamc_system_medical_records_offi.field_cc_related_links.yml
  config/sync/field.field.node.vamc_system_medical_records_offi.field_cc_top_of_page_content.yml
  config/sync/field.field.node.vamc_system_register_for_care.field_cc_bottom_of_page_content.yml
  config/sync/field.field.node.vamc_system_register_for_care.field_cc_related_links.yml
  config/sync/field.field.node.vamc_system_register_for_care.field_cc_top_of_page_content.yml
  config/sync/field.storage.node.field_cc_faqs.yml
  config/sync/field.storage.node.field_cc_get_records_in_person.yml
  config/sync/field.storage.node.field_cc_get_records_mail_or_fax.yml
  config/sync/field.storage.node.field_cc_how_we_share_records.yml
  config/sync/field.storage.node.field_cc_react_widget.yml
  config/sync/field.storage.node.field_cc_related_links.yml
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
Labels: Sitewide CMS Team

#6483 VACMS-5248: Add logic to prevent non admin archive from node form.
  config/sync/core.extension.yml
  docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_workflow/src/Service/WorkflowContentControl.php
  docroot/modules/custom/va_gov_workflow/va_gov_workflow.info.yml
  docroot/modules/custom/va_gov_workflow/va_gov_workflow.module
  docroot/modules/custom/va_gov_workflow/va_gov_workflow.services.yml
Labels: Sitewide CMS Team

#6495 VACMS-6389: Fix nested bullets.
  docroot/themes/custom/vagovadmin/assets/css/styles.css
  docroot/themes/custom/vagovadmin/assets/css/styles.css.map
  docroot/themes/custom/vagovadmin/assets/scss/_process_list.scss
Labels: Sitewide CMS Team

#6316 VACMS-6015: Add path validation constraint.
  composer.json
  docroot/modules/custom/va_gov_banner/js/fixConstraintJumpLink.es6.js
  docroot/modules/custom/va_gov_banner/js/fixConstraintJumpLink.js
  docroot/modules/custom/va_gov_banner/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_banner/src/Plugin/Validation/Constraint/RequireScope.php
  docroot/modules/custom/va_gov_banner/src/Plugin/Validation/Constraint/RequireScopeValidator.php
  docroot/modules/custom/va_gov_banner/va_gov_banner.libraries.yml
Labels: Sitewide CMS Team

#6511 VACMS-000 Remove facility endpoints.
  config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml
Labels: vsa-facilities, Sitewide CMS Team

#6541 VACMS-6512: Rename Lovell instances.
  config/sync/menu_export.export_data.yml
  config/sync/node.type.event.yml
  config/sync/node.type.event_listing.yml
  config/sync/node.type.health_care_local_facility.yml
  config/sync/node.type.health_care_region_detail_page.yml
  config/sync/node.type.health_care_region_page.yml
  config/sync/node.type.health_services_listing.yml
  config/sync/node.type.leadership_listing.yml
  config/sync/node.type.locations_listing.yml
  config/sync/node.type.news_story.yml
  config/sync/node.type.press_release.yml
  config/sync/node.type.press_releases_listing.yml
  config/sync/node.type.publication_listing.yml
  config/sync/node.type.story_listing.yml
  config/sync/node.type.vamc_operating_status_and_alerts.yml
  config/sync/node.type.vamc_system_billing_insurance.yml
  config/sync/node.type.vamc_system_medical_records_offi.yml
  config/sync/node.type.vamc_system_policies_page.yml
  config/sync/node.type.vamc_system_register_for_care.yml
  config/sync/system.menu.va-lovell-federal-health-care.yml
  docroot/modules/custom/va_gov_migrate/data/health-care-region-page.csv
  docroot/modules/custom/va_gov_migrate/data/lovell-system-services.csv
  docroot/modules/custom/va_gov_migrate/data/regional_health_care_service_covid.csv
  tests/behat/drupal-spec-tool/menus.feature
Labels: Sitewide CMS Team
