Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2021-03, with the labels that each got.

#3946 VACMS-3775: PHP 7.2 updates
  .lando.yml
  .lando/zzz-lando-my-custom.ini
  .tugboat/config.yml
  composer.json
  docroot/modules/custom/va_gov_content_export/src/TomeExporter.php
  docroot/modules/custom/va_gov_user/src/Plugin/Block/UserSections.php
  docroot/modules/custom/va_gov_workflow_assignments/src/Plugin/Block/EntityMetaDisplay.php
  docroot/sites/default/services.yml
  docroot/sites/default/settings/settings.tugboat.php
  tests.yml
Labels: Core Application Team, Planned work

#4304 VACMS-4345: Update Lando from Mysql to MariaDB 10.5
  .lando.yml
Labels: Core Application Team, DevOps, Planned work

#4476 VACMS-4442: Add new vc Prepare for your visit field and paragraph.
  config/sync/core.entity_form_display.node.vet_center.default.yml
  config/sync/core.entity_form_display.paragraph.basic_accordion.default.yml
  config/sync/core.entity_view_display.node.vet_center.default.yml
  config/sync/core.entity_view_display.node.vet_center.teaser.yml
  config/sync/core.entity_view_display.paragraph.basic_accordion.default.yml
  config/sync/field.field.node.vet_center.field_prepare_for_visit.yml
  config/sync/field.field.paragraph.basic_accordion.field_header.yml
  config/sync/field.field.paragraph.basic_accordion.field_rich_wysiwyg.yml
  config/sync/field.storage.node.field_prepare_for_visit.yml
  config/sync/field.storage.paragraph.field_header.yml
  config/sync/field.storage.paragraph.field_rich_wysiwyg.yml
  config/sync/paragraphs.paragraphs_type.basic_accordion.yml
  tests/behat/drupal-spec-tool/content_model_bundles.feature
  tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature
  tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature
Labels: Product Support Team

#4490 VACMS-4368_4389_4390_4393: Add quick clp config related updates.
  config/sync/core.entity_form_display.media.document_external.default.yml
  config/sync/core.entity_view_display.node.campaign_landing_page.default.yml
  config/sync/field.field.node.campaign_landing_page.field_hero_image.yml
  config/sync/workbench_access.access_scheme.section.yml
  tests/behat/drupal-spec-tool/content_model_campaign_landing_page_content_type_fields.feature
Labels: Product Support Team

#4501 VACMS-4499: Fix count() warning in UserSections block.
  docroot/modules/custom/va_gov_user/src/Plugin/Block/UserSections.php
Labels: Core Application Team

#4231 VACMS-4222: Refactor and add tests for BRD frontend build class.
  composer.json
  composer.lock
  docroot/modules/custom/va_gov_build_trigger/src/Exception/JenkinsClientException.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRD.php
  docroot/modules/custom/va_gov_build_trigger/src/Service/BuildTimeRecorder.php
  docroot/modules/custom/va_gov_build_trigger/src/Service/BuildTimeRecorderInterface.php
  docroot/modules/custom/va_gov_build_trigger/src/Service/JenkinsClient.php
  docroot/modules/custom/va_gov_build_trigger/src/Service/JenkinsClientInterface.php
  docroot/modules/custom/va_gov_build_trigger/src/Service/MiddlewareFactory.php
  docroot/modules/custom/va_gov_build_trigger/src/Service/SystemsManagerClient.php
  docroot/modules/custom/va_gov_build_trigger/src/Service/SystemsManagerClientInterface.php
  docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.services.yml
  docroot/sites/default/settings.php
  phpstan.neon
  phpstan_bootstrap.php
  tests/phpunit/FrontendBuild/Brd/BrdEnvironmentTest.php
  tests/phpunit/FrontendBuild/Brd/BuildTimeRecorderTest.php
  tests/phpunit/FrontendBuild/Brd/JenkinsClientTest.php
  tests/phpunit/FrontendBuild/Brd/SystemsManagerClientTest.php
Labels: Core Application Team, Planned work

#3996 Notifications and Events base PR
  .lando.yml
  .tugboat/config.yml
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/flag.flag.edited.yml
  config/sync/system.action.flag_action.edited_flag.yml
  config/sync/system.action.flag_action.edited_unflag.yml
  docroot/modules/custom/va_gov_content_export/src/AddBreadcrumbToEntity.php
  docroot/modules/custom/va_gov_notifications/src/Event/Entity/EditedFlag.php
  docroot/modules/custom/va_gov_notifications/src/Service/Flagging.php
  docroot/modules/custom/va_gov_notifications/src/Service/FlaggingInterface.php
  docroot/modules/custom/va_gov_notifications/va_gov_notifications.info.yml
  docroot/modules/custom/va_gov_notifications/va_gov_notifications.services.yml
  scripts/content/VACMS-3772-set-edited-flags-on-all-existing-content.php
  tests/behat/Drupal/FeatureContext.php
  tests/behat/features/personal_content_flags.feature
Labels: Core Application Team

#4511 VACMS-4446_4508 vc and locations tables
  config/sync/core.entity_form_display.node.health_care_local_health_service.default.yml
  config/sync/core.entity_form_display.node.vet_center_cap.default.yml
  config/sync/core.entity_form_display.node.vet_center_cap.inline_entity_form.yml
  config/sync/core.entity_view_display.node.vet_center_cap.default.yml
  config/sync/core.entity_view_display.node.vet_center_cap.ief_table.yml
  config/sync/core.entity_view_display.node.vet_center_cap.teaser.yml
  config/sync/field.field.node.vet_center_cap.field_address.yml
  config/sync/field.field.node.vet_center_cap.field_facility_hours.yml
  config/sync/field.field.node.vet_center_cap.field_geographical_identifier.yml
  config/sync/field.field.node.vet_center_cap.field_vet_center_cap_location.yml
  config/sync/field.storage.node.field_vet_center_cap_location.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature
Labels: Product Support Team

#4514 VACMS-4418: Content-Creator-Vet-Center-Role
  config/sync/system.action.user_add_role_action.content_creator_vet_center.yml
  config/sync/system.action.user_remove_role_action.content_creator_vet_center.yml
  config/sync/user.role.content_creator_vet_center.yml
  tests/behat/drupal-spec-tool/access_control.feature
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Product Support Team

#4447 VACMS-4429: Remove cms export code
  config/sync/core.extension.yml
  docroot/modules/custom/va_gov_build_trigger/src/Command/CommandRunner.php
  docroot/modules/custom/va_gov_build_trigger/src/Command/ExecutableFinder.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/AdvancedQueue/JobType/WebBuildJobType.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Lando.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Tugboat.php
  docroot/modules/custom/va_gov_build_trigger/src/SiteStatus/SiteStatus.php
  docroot/modules/custom/va_gov_build_trigger/src/SiteStatus/SiteStatusInterface.php
  docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.drush.inc
  docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.services.yml
  docroot/modules/custom/va_gov_content_export/va_gov_content_export.drush.inc
  tests/phpunit/CMSExport/BuildCommandsTest.php
Labels: Core Application Team

#4544 VACMS-4262 Uninstall cms export modules
  docroot/modules/custom/va_gov_db/va_gov_db.install
Labels: Core Application Team

#4534 VACMS-3147: Updates Drush Site Status commands for Drush 10.
  docroot/modules/custom/va_gov_build_trigger/drush.services.yml
  docroot/modules/custom/va_gov_build_trigger/src/Commands/SiteStatusCommands.php
Labels: Core Application Team

#4546 VACMS-4320: Hours-Field-Vet-Center
  composer.json
  composer.lock
  config/sync/core.entity_form_display.node.vet_center.default.yml
  config/sync/core.entity_form_display.node.vet_center_mobile_vet_center.default.yml
  config/sync/core.entity_form_display.node.vet_center_outstation.default.yml
  config/sync/core.entity_view_display.node.vet_center.default.yml
  config/sync/core.entity_view_display.node.vet_center.teaser.yml
  config/sync/core.entity_view_display.node.vet_center_mobile_vet_center.default.yml
  config/sync/core.entity_view_display.node.vet_center_mobile_vet_center.teaser.yml
  config/sync/core.entity_view_display.node.vet_center_outstation.default.yml
  config/sync/core.entity_view_display.node.vet_center_outstation.teaser.yml
  config/sync/core.extension.yml
  config/sync/field.field.node.vet_center.field_facility_hours.yml
  config/sync/field.field.node.vet_center.field_office_hours.yml
  config/sync/field.field.node.vet_center_mobile_vet_center.field_facility_hours.yml
  config/sync/field.field.node.vet_center_mobile_vet_center.field_office_hours.yml
  config/sync/field.field.node.vet_center_outstation.field_facility_hours.yml
  config/sync/field.field.node.vet_center_outstation.field_office_hours.yml
  config/sync/field.storage.node.field_office_hours.yml
  tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature
Labels: Product Support Team

#4549 VACMS-4537 field office vc
  config/sync/auto_entitylabel.settings.node.vet_center_cap.yml
  config/sync/auto_entitylabel.settings.node.vet_center_facility_health_servi.yml
  config/sync/auto_entitylabel.settings.node.vet_center_locations_list.yml
  config/sync/core.entity_form_display.node.vet_center_cap.default.yml
  config/sync/core.entity_form_display.node.vet_center_cap.inline_entity_form.yml
  config/sync/core.entity_form_display.node.vet_center_facility_health_servi.default.yml
  config/sync/core.entity_form_display.node.vet_center_locations_list.default.yml
  config/sync/core.entity_form_display.node.vet_center_mobile_vet_center.default.yml
  config/sync/core.entity_form_display.node.vet_center_outstation.default.yml
  config/sync/core.entity_view_display.node.vet_center_cap.default.yml
  config/sync/core.entity_view_display.node.vet_center_cap.ief_table.yml
  config/sync/core.entity_view_display.node.vet_center_cap.teaser.yml
  config/sync/core.entity_view_display.node.vet_center_facility_health_servi.default.yml
  config/sync/core.entity_view_display.node.vet_center_facility_health_servi.teaser.yml
  config/sync/core.entity_view_display.node.vet_center_locations_list.default.yml
  config/sync/core.entity_view_display.node.vet_center_locations_list.teaser.yml
  config/sync/core.entity_view_display.node.vet_center_mobile_vet_center.default.yml
  config/sync/core.entity_view_display.node.vet_center_mobile_vet_center.teaser.yml
  config/sync/core.entity_view_display.node.vet_center_outstation.default.yml
  config/sync/core.entity_view_display.node.vet_center_outstation.teaser.yml
  config/sync/field.field.node.vet_center_cap.field_office.yml
  config/sync/field.field.node.vet_center_facility_health_servi.field_office.yml
  config/sync/field.field.node.vet_center_locations_list.field_office.yml
  config/sync/field.field.node.vet_center_mobile_vet_center.field_office.yml
  config/sync/field.field.node.vet_center_outstation.field_office.yml
  config/sync/field.storage.node.field_vet_center.yml
  config/sync/pathauto.pattern.vet_center_community_access_point.yml
  config/sync/pathauto.pattern.vet_center_facility_health_service.yml
  config/sync/pathauto.pattern.vet_center_locations_list.yml
  config/sync/pathauto.pattern.vet_center_mobile_vet_center.yml
  config/sync/pathauto.pattern.vet_center_mobile_vet_center_outstations.yml
  config/sync/user.role.administrator.yml
  config/sync/user.role.admnistrator_users.yml
  config/sync/user.role.content_admin.yml
  config/sync/user.role.content_creator_vet_center.yml
  config/sync/user.role.content_editor.yml
  config/sync/user.role.content_publisher.yml
  config/sync/user.role.content_reviewer.yml
  config/sync/user.role.redirect_administrator.yml
  config/sync/user.role.vamc_content_creator.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature
Labels: Product Support Team

#4583 VACMS-4581: Require owner field on vc health service.
  config/sync/field.field.node.vet_center_facility_health_servi.field_administration.yml
  tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature
Labels: Product Support Team

#4532 VACMS-4520 4523 Disable title and display intro
  config/sync/core.entity_view_display.node.page.default.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Product Support Team

#4600 VACMS-4262 Uninstall tome_static and tome_base
  docroot/modules/custom/va_gov_db/va_gov_db.install
Labels: Core Application Team

#4589 VACMS-4586: Move GTM tests to Cypress
  composer.json
  tests/behat/Drupal/FeatureContext.php
  tests/behavioral/cypress/integration/common/i_am_an_anonymous_user.js
  tests/behavioral/cypress/integration/common/i_am_at_url.js
  tests/behavioral/cypress/integration/common/i_clear_field.js
  tests/behavioral/cypress/integration/common/i_create_a_node.js
  tests/behavioral/cypress/integration/common/i_fill_in_field_with_value.js
  tests/behavioral/cypress/integration/common/i_reload_the_page.js
  tests/behavioral/cypress/integration/common/i_save_the_node.js
  tests/behavioral/cypress/integration/common/i_select_option_from_dropdown.js
  tests/behavioral/cypress/integration/google_tag_manager.feature
  tests/behavioral/cypress/integration/google_tag_manager/my_workbench_access_sections_are_not_set.js
  tests/behavioral/cypress/integration/google_tag_manager/my_workbench_access_sections_are_set_to.js
  tests/behavioral/cypress/integration/google_tag_manager/the_gtm_data_layer_user_id_should_be_correctly_hashed.js
  tests/behavioral/cypress/integration/google_tag_manager/the_gtm_data_layer_value_for_key_should_be_set.js
  tests/behavioral/cypress/integration/google_tag_manager/the_gtm_data_layer_value_for_key_should_be_set_correctly.js
  tests/behavioral/cypress/integration/google_tag_manager/the_gtm_data_layer_value_for_key_should_be_set_to_value.js
  tests/behavioral/cypress/integration/google_tag_manager/the_gtm_data_layer_value_for_key_should_be_unset.js
  tests/behavioral/cypress/support/commands.js
Labels: Core Application Team, DO NOT MERGE

#4593 VACMS-1004: Update Composer, Lando, Tugboat to PHP 7.3
  .lando.yml
  .tugboat/config.yml
  composer.json
  composer.lock
Labels: Core Application Team

#4590 VACMS-3868 + VACMS-4281: DRUSH 10 + upgrade migrate plus and add migration tests
  .lando.yml
  .tugboat/config.yml
  READMES/devops/devshop-manually-run-tasks.md
  READMES/environment-variables.md
  READMES/tugboat.md
  composer.json
  composer.lock
  docroot/autoload.php
  docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.module
  docroot/modules/custom/va_gov_migrate/src/Plugin/migrate_plus/data_parser/Csv.php
  docroot/themes/custom/vagovadmin/gulpfile.es6.js
  docroot/themes/custom/vagovadmin/gulpfile.js
  tasks-periodic.yml
  tests.yml
  tests/behavioral/cypress/support/commands.js
  tests/phpunit/Migration/VaFormMigrationTest.php
  tests/phpunit/Migration/VaHealthCareLocalFacilityMigrationTest.php
  tests/phpunit/Migration/VaHealthCareLocalFacilityStatusMigrationTest.php
  tests/phpunit/Migration/fixtures/forms.csv
  tests/phpunit/Migration/fixtures/forms_updated.csv
  tests/phpunit/Migration/fixtures/health_care_local_facility.json
  tests/phpunit/Migration/fixtures/health_care_local_facility_status.html
  tests/phpunit/Migration/fixtures/health_care_local_facility_status_updated.html
  tests/phpunit/Migration/fixtures/health_care_local_facility_updated.json
  tests/phpunit/Support/Entity/Storage.php
  tests/phpunit/Support/Migration/Migrator.php
  tests/phpunit/Support/Mock/HttpClient.php
Labels: Core Application Team

#4605 Updating va-gov/web (v0.1.1376 => v0.1.1385)
  composer.lock
Labels: Core Application Team

#4518 VACMS-4385: Add featured content to vc.
  config/sync/core.entity_form_display.node.vet_center.default.yml
  config/sync/core.entity_form_display.paragraph.featured_content.default.yml
  config/sync/core.entity_view_display.node.vet_center.default.yml
  config/sync/core.entity_view_display.node.vet_center.teaser.yml
  config/sync/core.entity_view_display.paragraph.featured_content.default.yml
  config/sync/field.field.node.vet_center.field_vet_center_feature_content.yml
  config/sync/field.field.paragraph.featured_content.field_cta.yml
  config/sync/field.field.paragraph.featured_content.field_description.yml
  config/sync/field.field.paragraph.featured_content.field_section_header.yml
  config/sync/field.storage.node.field_vet_center_feature_content.yml
  config/sync/field.storage.paragraph.field_cta.yml
  config/sync/field.storage.paragraph.field_description.yml
  config/sync/paragraphs.paragraphs_type.featured_content.yml
  tests/behat/drupal-spec-tool/content_model_bundles.feature
  tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature
  tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature
Labels: Product Support Team

#4635 VACMS-4262: Try uninstalling tome again
  docroot/modules/custom/va_gov_db/va_gov_db.install
Labels: Core Application Team

#4640 VACMS-4262 why no uninstall tome
  config/sync/core.extension.yml
Labels: Core Application Team

#4599 VACMS-3303: Update composer to v2 and update required packages
  .lando.yml
  .tugboat/.env.j2
  .tugboat/config.yml
  READMES/environment-variables.md
  READMES/testing.md
  composer.json
  composer.lock
  patches/allow_updating_easyrdf_8_9_x.patch
  scripts/composer/EnvironmentHandler.php
  tasks-periodic.yml
Labels: Core Application Team

#4622 VACMS-4510 4557 4580 VC's
  config/sync/auto_entitylabel.settings.node.vet_center_locations_list.yml
  config/sync/core.entity_form_display.node.vet_center.default.yml
  config/sync/core.entity_form_display.node.vet_center_cap.default.yml
  config/sync/core.entity_form_display.node.vet_center_cap.inline_entity_form.yml
  config/sync/core.entity_form_display.node.vet_center_locations_list.default.yml
  config/sync/core.entity_form_display.node.vet_center_mobile_vet_center.default.yml
  config/sync/core.entity_view_display.node.vet_center_cap.default.yml
  config/sync/core.entity_view_display.node.vet_center_cap.ief_table.yml
  config/sync/core.entity_view_display.node.vet_center_cap.teaser.yml
  config/sync/core.entity_view_display.node.vet_center_mobile_vet_center.default.yml
  config/sync/core.entity_view_display.node.vet_center_mobile_vet_center.teaser.yml
  config/sync/core.extension.yml
  config/sync/entity_browser.browser.vet_centers.yml
  config/sync/field.field.node.vet_center.field_address.yml
  config/sync/field.field.node.vet_center.field_intro_text.yml
  config/sync/field.field.node.vet_center_cap.field_facility_hours.yml
  config/sync/field.field.node.vet_center_cap.field_facility_locator_api_id.yml
  config/sync/field.field.node.vet_center_cap.field_office_hours.yml
  config/sync/field.field.node.vet_center_locations_list.field_intro_text.yml
  config/sync/field.field.node.vet_center_locations_list.field_nearby_vet_centers.yml
  config/sync/field.field.node.vet_center_locations_list.field_office.yml
  config/sync/field.field.node.vet_center_mobile_vet_center.field_operating_status_facility.yml
  config/sync/field.field.node.vet_center_mobile_vet_center.field_operating_status_more_info.yml
  config/sync/user.role.authenticated.yml
  config/sync/views.view.vet_centers.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  docroot/modules/custom/va_gov_vet_center/templates/va-gov-vet-center.html.twig
  docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.info.yml
  docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.module
  tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature
  tests/behat/drupal-spec-tool/views.feature
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Product Support Team

#4667 VACMS-4641: Update perms config and sync settings from prod.
  config/sync/core.entity_form_display.node.full_width_banner_alert.inline_entity_form.yml
  config/sync/user.role.content_editor.yml
  config/sync/user.role.content_publisher.yml
  config/sync/user.role.content_reviewer.yml
  config/sync/webform.webform.request_cms_user.yml
  config/sync/workbench_access.access_scheme.section.yml
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Product Support Team

#4621 VACMS-4288: Update role_delegation module
  composer.json
  composer.lock
Labels: Core Application Team

#4516 VACMS-4285: upgrade password policy modules
  composer.json
  composer.lock
  config/sync/password_policy.password_policy.va_gov_cms.yml
  docroot/modules/custom/va_gov_db/va_gov_db.install
  tests/behavioral/cypress/integration/common/i_am_logged_in_as_a_user_with_the_role_and_password.js
  tests/behavioral/cypress/integration/common/i_fill_in_field_with_value.js
  tests/behavioral/cypress/integration/common/i_save_the_user.js
  tests/behavioral/cypress/integration/password_policies.feature
Labels: Core Application Team

#4620 VACMS 4110: Improve content release integration with AdvancedQueue Part Deux
  READMES/local.md
  composer.json
  docroot/modules/custom/va_gov_build_trigger/drush.services.yml
  docroot/modules/custom/va_gov_build_trigger/src/Command/CommandRunner.php
  docroot/modules/custom/va_gov_build_trigger/src/CommandExportable.php
  docroot/modules/custom/va_gov_build_trigger/src/Commands/WebBuildCommands.php
  docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentDiscovery.php
  docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentPluginBase.php
  docroot/modules/custom/va_gov_build_trigger/src/Form/PreviewForm.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/AdvancedQueue/JobType/WebBuildJobType.php
  docroot/modules/custom/va_gov_build_trigger/src/Service/BuildFrontend.php
  docroot/modules/custom/va_gov_build_trigger/src/Service/BuildFrontendInterface.php
  docroot/modules/custom/va_gov_build_trigger/src/WebBuildCommandBuilder.php
  docroot/modules/custom/va_gov_build_trigger/src/WebBuildCommandBuilderInterface.php
  docroot/modules/custom/va_gov_build_trigger/src/WebBuildStatus.php
  docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.drush.inc
  tests/behavioral/cypress/integration/content_release.feature
  tests/behavioral/cypress/integration/content_release/i_clear_the_web_build_queue.js
  tests/behavioral/cypress/integration/content_release/i_initiate_a_content_release.js
  tests/behavioral/cypress/integration/content_release/i_initiate_a_content_release_from_the_command_line.js
  tests/behavioral/cypress/integration/content_release/i_initiate_a_content_release_from_the_command_line_with_the_branch.js
  tests/behavioral/cypress/integration/content_release/i_initiate_a_content_release_with_the_branch.js
Labels: Core Application Team

#4703 VACMS-4613 4615 VC config items
  config/sync/core.entity_form_display.node.vet_center.default.yml
  config/sync/core.entity_view_display.node.vet_center.default.yml
  config/sync/core.entity_view_display.node.vet_center.teaser.yml
  config/sync/field.field.node.vet_center.field_cc_non_traditional_hours.yml
  config/sync/field.field.node.vet_center.field_cc_vet_center_call_center.yml
  config/sync/field.field.node.vet_center.field_cc_vet_center_faqs.yml
  config/sync/field.storage.node.field_cc_non_traditional_hours.yml
  config/sync/field.storage.node.field_cc_vet_center_call_center.yml
  config/sync/field.storage.node.field_cc_vet_center_faqs.yml
  tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature
Labels: Product Support Team

#4686 VACMS-4206: Remove views_tree module
  config/sync/core.extension.yml
  config/sync/views.view.health_care_service_names_and_descriptions.yml
  config/sync/views.view.sections_tree.yml
  tests/accessibility/cypress/integration/nodeCreationAccessibility.spec.js
  tests/behat/drupal-spec-tool/views.feature
Labels: Core Application Team

#4684 VACMS-4293: Upgrade taxonomy_menu
  composer.json
  composer.lock
Labels: Core Application Team

#4712 VACMS-4655: Limit selection choice to vc.
  config/sync/field.field.node.vet_center_locations_list.field_office.yml
Labels: Product Support Team

#4714 VACMS-4282: update migrate csv
  composer.json
  composer.lock
  config/sync/migrate_plus.migration.facility_health_care_service.yml
  config/sync/migrate_plus.migration.facility_health_care_service_2.yml
  config/sync/migrate_plus.migration.facility_health_care_service_covid.yml
  config/sync/migrate_plus.migration.health_care_region_page.yml
  config/sync/migrate_plus.migration.regional_health_care_service.yml
  config/sync/migrate_plus.migration.regional_health_care_service_covid.yml
  config/sync/migrate_plus.migration.regional_health_care_service_region_keyed.yml
  config/sync/migrate_plus.migration.user_import.yml
  tests/phpunit/Migration/VaHealthCareLocalFacilityStatusMigrationTest.php
  tests/phpunit/Support/Migration/Migrator.php
Labels: Core Application Team

#4713 VACMS-4453: Update content published perms.
  config/sync/user.role.content_admin.yml
  config/sync/user.role.content_editor.yml
  config/sync/user.role.content_publisher.yml
  config/sync/user.role.content_reviewer.yml
  tests/behat/features/content_editing.feature
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Product Support Team

#4717 VACMS-4261: Update linkit + field config
  composer.json
  composer.lock
  config/sync/core.entity_form_display.node.health_care_region_page.default.yml
  config/sync/core.entity_form_display.node.landing_page.default.yml
  config/sync/core.entity_form_display.paragraph.button.default.yml
  config/sync/core.entity_form_display.paragraph.link_teaser.default.yml
  config/sync/core.entity_form_display.paragraph.list_of_links.default.yml
Labels: Core Application Team, Product Support Team

#4729 VACMS-4728: Restore url perm.
  config/sync/user.role.content_admin.yml
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Product Support Team

#4716 VACMS-4284: Uninstall OpenAPI, OpenAPI UI, ReDoc for OpenAPI UI, and Swagger UI for OpenAPI UI
  .github/dependabot.yml
  README.md
  READMES/cms-export.md
  READMES/devops/deploy-process.md
  READMES/interfaces.md
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/user.role.content_api_consumer.yml
  docroot/modules/custom/va_gov_backend/src/Deploy/DeployService.php
  docroot/modules/custom/va_gov_backend/src/Deploy/Plugin/CMSExport.php
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  docroot/modules/custom/va_gov_build_trigger/src/Command/CommandRunner.php
  docroot/modules/custom/va_gov_build_trigger/src/CommandExportable.php
  docroot/modules/custom/va_gov_build_trigger/src/Commands/WebBuildCommands.php
  docroot/modules/custom/va_gov_build_trigger/src/Form/TugboatBuildTriggerForm.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Lando.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Tugboat.php
  docroot/modules/custom/va_gov_build_trigger/src/Service/BuildFrontendInterface.php
  docroot/modules/custom/va_gov_build_trigger/src/SiteStatus/SiteStatusInterface.php
  docroot/modules/custom/va_gov_build_trigger/src/WebBuildCommandBuilder.php
  docroot/modules/custom/va_gov_build_trigger/src/WebBuildCommandBuilderInterface.php
  docroot/modules/custom/va_gov_build_trigger/src/WebBuildStatus.php
  docroot/modules/custom/va_gov_build_trigger/src/WebBuildStatusInterface.php
  docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.services.yml
  docroot/modules/custom/va_gov_consumers/src/Routing/RouteSubscriber.php
  docroot/modules/custom/va_gov_consumers/va_gov_consumers.info.yml
  docroot/modules/custom/va_gov_consumers/va_gov_consumers.services.yml
  docroot/modules/custom/va_gov_content_export/src/AddBreadcrumbToEntity.php
  docroot/modules/custom/va_gov_content_export/src/Archive/ArchiveArgs.php
  docroot/modules/custom/va_gov_content_export/src/Archive/ArchiveArgsFactory.php
  docroot/modules/custom/va_gov_content_export/src/Archive/ArchiveDirectory.php
  docroot/modules/custom/va_gov_content_export/src/Controller/ContentExport.php
  docroot/modules/custom/va_gov_content_export/src/Event/ContentExportPreTarEvent.php
  docroot/modules/custom/va_gov_content_export/src/EventSubscriber/ContentExportPreTarSubscriber.php
  docroot/modules/custom/va_gov_content_export/src/ExportCommand/BuildCommands.php
  docroot/modules/custom/va_gov_content_export/src/ExportCommand/ExportCommandException.php
  docroot/modules/custom/va_gov_content_export/src/ExportCommand/ExportContentCommand.php
  docroot/modules/custom/va_gov_content_export/src/ListDataCompiler.php
  docroot/modules/custom/va_gov_content_export/src/Normalizer/ContentEntityNormalizer.php
  docroot/modules/custom/va_gov_content_export/src/Normalizer/LinkItemNormalizer.php
  docroot/modules/custom/va_gov_content_export/src/TarAdapter.php
  docroot/modules/custom/va_gov_content_export/src/TarStrategy.php
  docroot/modules/custom/va_gov_content_export/src/TomeExporter.php
  docroot/modules/custom/va_gov_content_export/src/TomeFileSync.php
  docroot/modules/custom/va_gov_content_export/src/VaGovContentExportServiceProvider.php
  docroot/modules/custom/va_gov_content_export/va_gov_content_export.info.yml
  docroot/modules/custom/va_gov_content_export/va_gov_content_export.module
  docroot/modules/custom/va_gov_content_export/va_gov_content_export.routing.yml
  docroot/modules/custom/va_gov_content_export/va_gov_content_export.services.yml
  docroot/modules/custom/va_gov_db/va_gov_db.install
  docroot/modules/custom/zippylib/README.md
  docroot/modules/custom/zippylib/composer.json
  docroot/modules/custom/zippylib/src/ZippyFactory.php
  docroot/modules/custom/zippylib/zippylib.info.yml
  docroot/modules/custom/zippylib/zippylib.services.yml
  docroot/sites/default/settings.devshop.php
  docroot/sites/default/settings.php
  tests/phpunit/FrontendBuild/WebBuildCommandBuilderTest.php
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Core Application Team

#4689 VACMS-864: Update graphql to 3.1
  composer.lock
  config/sync/user.role.content_api_consumer.yml
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Core Application Team

#4760 VACMS-4758: Enable workflow field on node form.
  config/sync/core.entity_form_display.node.regional_health_care_service_des.default.yml
Labels: Product Support Team

#4755 VACMS-4294: Disable and remove simple_oauth.
  config/sync/core.extension.yml
  config/sync/rest.resource.entity.menu_link_content.yml
  config/sync/rest.resource.menu_tree.yml
  config/sync/simple_oauth.oauth2_token.bundle.access_token.yml
  config/sync/simple_oauth.oauth2_token.bundle.auth_code.yml
  config/sync/simple_oauth.oauth2_token.bundle.refresh_token.yml
  config/sync/simple_oauth.settings.yml
  config/sync/simple_oauth_extras.settings.yml
Labels: Core Application Team

#4740 VACMS-4731: Add Vet Center listings view.
  config/sync/block.block.user_sections.yml
  config/sync/block.block.vagovadmin_content.yml
  config/sync/block.block.views_block__services_block_1.yml
  config/sync/filter.format.rich_text.yml
  config/sync/migrate_plus.migration.facility_health_care_service.yml
  config/sync/migrate_plus.migration.facility_health_care_service_2.yml
  config/sync/migrate_plus.migration.facility_health_care_service_covid.yml
  config/sync/migrate_plus.migration.health_care_region_page.yml
  config/sync/migrate_plus.migration.regional_health_care_service.yml
  config/sync/migrate_plus.migration.regional_health_care_service_covid.yml
  config/sync/migrate_plus.migration.user_import.yml
  config/sync/views.view.vet_center_facility_listing.yml
  tests/behat/drupal-spec-tool/views.feature
Labels: Product Support Team

#4762 VACMS-4287: Disables rest_menu_tree module.
  config/sync/core.extension.yml
  config/sync/rest.resource.menu_tree.yml
Labels: Core Application Team

#4764 VACMS-4558 Push Vet Center Outstation status updates to Lighthouse.
  READMES/vamc-facilities.md
  docroot/modules/custom/va_gov_post_api/va_gov_post_api.module
Labels: Product Support Team

#4765 VACMS-4763: CER-D9-Patch-Updated
  composer.json
  composer.lock
Labels: Product Support Team

#4770 VACMS-4296: update vbo
  composer.json
  composer.lock
  config/sync/system.action.pathauto_update_alias_media.yml
  config/sync/system.action.pathauto_update_alias_node.yml
  config/sync/system.action.pathauto_update_alias_taxonomy_term.yml
  config/sync/system.action.pathauto_update_alias_user.yml
  config/sync/views.view.content.yml
  config/sync/views.view.date_fields.yml
  config/sync/views.view.facility_governance.yml
  config/sync/views.view.image_style_warmer_warmup_files.yml
  config/sync/views.view.media.yml
  config/sync/views.view.taxonomy_term.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Core Application Team, Product Support Team

#4776 VACMS-4775: Fix phone fields display.
  docroot/themes/custom/vagovadmin/assets/css/styles.css
  docroot/themes/custom/vagovadmin/assets/css/styles.css.map
  docroot/themes/custom/vagovadmin/assets/scss/styles.scss
Labels: Product Support Team

#4750 VACMS-4415: Add 4 new fields to view.
  config/sync/views.view.vha_health_service_taxonomy.yml
Labels: Product Support Team

#4786 VACMS-4629: Prevent empty resources panel on node view.
  config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_view_display.node.campaign_landing_page.default.yml
Labels: Product Support Team

#4789 VACMS-4588: Rename cc office role.
  config/sync/user.role.office_content_creator.yml
  tests/behat/drupal-spec-tool/access_control.feature
Labels: Product Support Team

#4793 VACMS-4299: Update workbench_access
  composer.json
  composer.lock
  tests/phpunit/Security/SectionAccessTest.php
Labels: Core Application Team

#4779 VACMS-4295: Upgrade views_bulk_edit, apply paragraphs patch.
  composer.json
  composer.lock
Labels: Core Application Team

#2993 VACMS-2991 Add daily periodic task to reindex taxonomy entity index.
  tasks-periodic.yml
Labels: Core Application Team, Product Support Team

#4754 VACMS-4614: Require image field on system nodes.
  composer.json
  config/sync/field.field.node.health_care_region_page.field_media.yml
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
Labels: Product Support Team

#4778 VACMS-4777: Update code & docs to remove devshop CI refs
  .hooks.yml
  .tugboat/config.yml
  README.md
  READMES/environments.md
  READMES/images/devshop-add-environment-form.png
  READMES/images/devshop-add-environment.png
  READMES/images/devshop-demos.png
  READMES/images/devshop-home.png
  READMES/images/devshop-install.png
  READMES/images/devshop-rebuild-form-advanced.png
  READMES/images/devshop-rebuild-form.png
  READMES/images/devshop-rebuild.png
  READMES/images/devshop-web-links.png
  READMES/images/tugboat-clone-preview.png
  READMES/images/tugboat-content-release-status.png
  READMES/images/tugboat-demos.png
  READMES/images/tugboat-home.png
  READMES/images/tugboat-preview-settings.png
  READMES/images/tugboat-preview.png
  READMES/images/tugboat-rebuild.png
  READMES/images/tugboat-release-content-web-branch.png
  READMES/images/tugboat-release-content.png
  READMES/images/tugboat-web-link.png
  READMES/testing.md
  READMES/tugboat.md
  READMES/unity.md
  docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentDiscovery.php
  docroot/modules/custom/va_gov_build_trigger/src/Form/DevShopBuildTriggerForm.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/DevShop.php
  docroot/sites/default/settings.php
  docroot/sites/default/settings/settings.tugboat.php
  tests/behat/features/behat.feature
  tests/phpunit/FrontendBuild/BuildTriggerFormTest.php
Labels: Core Application Team

#4801 VACMS-4513: Disallow wysiwyg on core tax description field.
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Product Support Team

#4851 VACMS-4831: Makes va_gov_notifications D9-compatible.
  docroot/modules/custom/va_gov_notifications/va_gov_notifications.info.yml
Labels: Core Application Team

#4852 VACMS-4832: Make va_gov_migrate D9-compatible.
  docroot/modules/custom/va_gov_migrate/drush.services.yml
  docroot/modules/custom/va_gov_migrate/src/Commands/Commands.php
  docroot/modules/custom/va_gov_migrate/va_gov_migrate.drush.inc
Labels: Core Application Team

#4859 VACMS-4292: Disables schemata and schemata_json_schema modules.
  composer.json
  composer.lock
  config/sync/core.extension.yml
Labels: Core Application Team

#4860 VACMS 4718: Remove media browser dependency on views_infinite_scroll.
  config/sync/core.extension.yml
  config/sync/views.view.media.yml
Labels: Core Application Team

#4862 VACMS-4283 upgrade migration tools
  composer.json
  composer.lock
  config/sync/migrate_plus.migration.va_node_facility_vet_centers.yml
  config/sync/migrate_plus.migration.va_node_facility_vet_centers_mvc.yml
  config/sync/migrate_plus.migration.va_node_facility_vet_centers_os.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers_mvc.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers_os.yml
  docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VASkipOnSubstr.php
Labels: Product Support Team, Vet Center

#4767 VACMS-4766: Improve health service selector.
  config/sync/field.field.node.regional_health_care_service_des.field_service_name_and_descripti.yml
  config/sync/field.field.node.vet_center_facility_health_servi.field_service_name_and_descripti.yml
  config/sync/views.view.health_care_service_names_and_descriptions.yml
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
  tests/behat/drupal-spec-tool/views.feature
Labels: Product Support Team
