Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2021-04, with the labels that each got.

#4883 VACMS-4882: Increase pathauto length limit from 100 to 150.
  config/sync/pathauto.settings.yml
Labels: Product Support Team

#4889 VACMS-4484 and 4901 Send covid appointment data to lighthouse.
  docroot/modules/custom/va_gov_post_api/src/Form/VaGovFacilityForceQueueForm.php
  docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityService.php
  docroot/modules/custom/va_gov_post_api/va_gov_post_api.module
Labels: COVID-19, Product Support Team, vsa-facilities

#4913 VACMS-4845: Update content creator perms.
  config/sync/user.role.vamc_content_creator.yml
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Product Support Team

#4805 VACMS-4451: Remove unused modules and packages.
  composer.json
  composer.lock
Labels: Core Application Team

#4795 VACMS-4296: update vbo
  composer.json
  composer.lock
  config/sync/system.action.pathauto_update_alias_media.yml
  config/sync/system.action.pathauto_update_alias_node.yml
  config/sync/system.action.pathauto_update_alias_taxonomy_term.yml
  config/sync/system.action.pathauto_update_alias_user.yml
  config/sync/views.view.content.yml
  config/sync/views.view.date_fields.yml
  config/sync/views.view.facility_governance.yml
  config/sync/views.view.image_style_warmer_warmup_files.yml
  config/sync/views.view.media.yml
  config/sync/views.view.taxonomy_term.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Core Application Team, Product Support Team

#4914 VACMS-4844: Fix broken events view.
  config/sync/views.view.content.yml
Labels: Product Support Team

#4976 VACMS 4950: Remove devshop/behat-drupal-extension
  composer.json
  composer.lock
  tests/behat/Drupal/FeatureContext.php
Labels: Core Application Team

#4907 VACMS-4541: Prevent non admin user from editing administration.
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.module
Labels: Product Support Team

#4971 VACMS-4970: Create CAP Provide opening hours field.
  config/sync/core.entity_form_display.node.vet_center_cap.default.yml
  config/sync/core.entity_form_display.node.vet_center_cap.inline_entity_form.yml
  config/sync/core.entity_view_display.node.vet_center_cap.default.yml
  config/sync/core.entity_view_display.node.vet_center_cap.external_content.yml
  config/sync/core.entity_view_display.node.vet_center_cap.ief_table.yml
  config/sync/core.entity_view_display.node.vet_center_cap.teaser.yml
  config/sync/field.field.node.vet_center_cap.field_body.yml
  config/sync/field.field.node.vet_center_cap.field_vetcenter_cap_hours_opt_in.yml
  config/sync/field.storage.node.field_vetcenter_cap_hours_opt_in.yml
  config/sync/views.view.content.yml
  tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature
Labels: Product Support Team

#4938 VACMS-4935: Update IEF for Vet Center health services.
  config/sync/core.entity_form_display.node.vet_center.default.yml
  config/sync/core.entity_form_display.node.vet_center_facility_health_servi.inline_entity_form.yml
Labels: Product Support Team

#4984 VACMS-4822 Update drupal entity_fetch_field module.
  composer.json
  composer.lock
Labels: Product Support Team, Vet Center, vsa-facilities

#5013 Add `force-content-build` flag to full web build
  composer.json
Labels: Core Application Team

#4880 VACMS-4871: Switch from Yaml Tasks to Task
  .lando.yml
  .tugboat/.env.j2
  .tugboat/config.yml
  READMES/testing.md
  composer.json
  composer.lock
  package-lock.json
  package.json
  scripts/install_github_commenter.sh
  scripts/install_github_status_updater.sh
  scripts/install_task_runner.sh
  tasks-periodic.yml
  tests.yml
Labels: Core Application Team, DO NOT MERGE

#4853 VACMS-4628: Add revision log message validation to vcs.
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Product Support Team

#5018 VACMS-5014 Remove facility service description from Lighthouse push
  docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityService.php
Labels: COVID-19, Lighthouse Facility API

#4973 VACMS-4807: Update descriptions for 5 Vet Center content types.
  config/sync/node.type.vet_center.yml
  config/sync/node.type.vet_center_cap.yml
  config/sync/node.type.vet_center_facility_health_servi.yml
  config/sync/node.type.vet_center_locations_list.yml
  config/sync/node.type.vet_center_mobile_vet_center.yml
  config/sync/node.type.vet_center_outstation.yml
  tests/behat/drupal-spec-tool/content_model_bundles.feature
  tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature
Labels: Product Support Team

#5065 VACMS-4460: Install and enable Memcache (part 1).
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/memcache_admin.settings.yml
Labels: Core Application Team

#5075 VACMS-5062: Fix date end field display bug.
  config/sync/core.entity_form_display.node.event.default.yml
Labels: Product Support Team

#5079 VACMS-5081: Refine tests taskfile.
  tests.yml
Labels: Core Application Team

#5100 VACMS-5101: Echo task output to stdout.
  tests.yml
Labels: Core Application Team

#5071 VACMS-4460: Configures Memcache on BRD.
  README.md
  READMES/drupal-memcache.md
  composer.lock
  docroot/sites/default/services/services.memcache.yml
  docroot/sites/default/settings.php
  docroot/sites/default/settings/settings.brd_common.php
  docroot/sites/default/settings/settings.dev.php
  docroot/sites/default/settings/settings.prod.php
  docroot/sites/default/settings/settings.staging.php
Labels: Core Application Team, DO NOT MERGE

#5023 VACMS-4927: Configure Memcache support in Tugboat.
  .tugboat/config.yml
  docroot/sites/default/settings/settings.tugboat.php
Labels: Core Application Team

#5145 VACMS-5131: Do not have graphql add node_list cache tag.
  docroot/modules/custom/va_gov_build_trigger/src/GraphQLEntityQuery.php
  docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.module
Labels: Core Application Team

#5015 VACMS 4926: Enables memcache support on Lando.
  .lando.yml
  composer.lock
  docroot/sites/default/settings/settings.lando.php
Labels: Core Application Team

#4994 VACMS-4850 Vet Center dashboard MVP
  README.md
  config/sync/core.entity_form_display.taxonomy_term.administration.default.yml
  config/sync/core.entity_view_display.taxonomy_term.administration.default.yml
  config/sync/core.entity_view_display.taxonomy_term.administration.full.yml
  config/sync/core.entity_view_display.taxonomy_term.administration.vet_center_dashboard.yml
  config/sync/core.entity_view_display.taxonomy_term.audience_beneficiaries.default.yml
  config/sync/core.entity_view_display.taxonomy_term.audience_non_beneficiaries.default.yml
  config/sync/core.entity_view_display.taxonomy_term.audience_tags.default.yml
  config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.default.yml
  config/sync/core.entity_view_display.taxonomy_term.lc_categories.default.yml
  config/sync/core.entity_view_display.taxonomy_term.products.default.yml
  config/sync/core.entity_view_display.taxonomy_term.topics.default.yml
  config/sync/core.entity_view_mode.taxonomy_term.vet_center_dashboard.yml
  config/sync/core.extension.yml
  config/sync/field.field.taxonomy_term.administration.field_acronym.yml
  config/sync/field.field.taxonomy_term.administration.field_description.yml
  config/sync/field.field.taxonomy_term.administration.field_intro_text.yml
  config/sync/field.field.taxonomy_term.administration.field_metatags.yml
  config/sync/field.field.taxonomy_term.administration.field_product.yml
  config/sync/field.storage.taxonomy_term.field_acronym.yml
  config/sync/field.storage.taxonomy_term.field_intro_text.yml
  config/sync/field.storage.taxonomy_term.field_product.yml
  config/sync/filter.format.rich_text.yml
  config/sync/views.view.taxonomy_term.yml
  config/sync/views.view.vet_center_facility_listing.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  docroot/modules/custom/va_gov_dashboards/README.md
  docroot/modules/custom/va_gov_dashboards/css/dashboard_blocks.css
  docroot/modules/custom/va_gov_dashboards/src/Plugin/Block/VcDashboardsBlock.php
  docroot/modules/custom/va_gov_dashboards/src/Plugin/Derivative/VcDashboardsBlock.php
  docroot/modules/custom/va_gov_dashboards/src/Service/VetCenterDashboard.php
  docroot/modules/custom/va_gov_dashboards/templates/vc-dashboards-block.html.twig
  docroot/modules/custom/va_gov_dashboards/va_gov_dashboards.info.yml
  docroot/modules/custom/va_gov_dashboards/va_gov_dashboards.libraries.yml
  docroot/modules/custom/va_gov_dashboards/va_gov_dashboards.module
  docroot/modules/custom/va_gov_dashboards/va_gov_dashboards.services.yml
  docroot/modules/custom/va_gov_vet_center/templates/va-gov-vet-center.html.twig
  docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.module
  docroot/themes/custom/vagovadmin/dashboard-images/vc/featured_content.svg
  docroot/themes/custom/vagovadmin/dashboard-images/vc/locations_page.svg
  docroot/themes/custom/vagovadmin/dashboard-images/vc/main_vet_center_page.svg
  docroot/themes/custom/vagovadmin/dashboard-images/vc/operating_status.svg
  docroot/themes/custom/vagovadmin/dashboard-images/vc/services.svg
  docroot/themes/custom/vagovadmin/dashboard-images/vc/visitor_information.svg
  docroot/themes/custom/vagovadmin/templates/taxonomy-term.html.twig
  tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature
  tests/behat/drupal-spec-tool/views.feature
Labels: Product Support Team

#5164 VACMS-0000: Remove Schemata module.
  composer.json
  composer.lock
Labels: Core Application Team

#5170 VACMS-5169 Restore filters on section View.
  config/sync/views.view.taxonomy_term.yml
Labels: Core Application Team

#5179 VACMS-0000: Removes kint module from dev config_split configuration.
  config/sync/config_split.config_split.dev.yml
Labels: Core Application Team

#5182 VACMS-5178 Disable layout builder for non-dashboard vocabularies.
  config/sync/core.entity_view_display.taxonomy_term.audience_beneficiaries.default.yml
  config/sync/core.entity_view_display.taxonomy_term.audience_non_beneficiaries.default.yml
  config/sync/core.entity_view_display.taxonomy_term.audience_tags.default.yml
  config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.default.yml
  config/sync/core.entity_view_display.taxonomy_term.lc_categories.default.yml
  config/sync/core.entity_view_display.taxonomy_term.products.default.yml
  config/sync/core.entity_view_display.taxonomy_term.topics.default.yml
Labels: Product Support Team

#5191 VACMS-4954: Updates acquia/drupal-spec-tool to ^3.0.
  composer.json
  composer.lock
Labels: Core Application Team

#5197 VACMS-5195 Add -any- to taxonomy term View.
  config/sync/views.view.taxonomy_term.yml
Labels: Product Support Team

#5157 Add team labels to issue templates and update GH action
  .github/ISSUE_TEMPLATE/cms-announcement--fka-release-notes-.md
  .github/ISSUE_TEMPLATE/cms-bug-report.md
  .github/ISSUE_TEMPLATE/cms-devops.md
  .github/ISSUE_TEMPLATE/cms-discovery.md
  .github/ISSUE_TEMPLATE/cms-enhancement.md
  .github/ISSUE_TEMPLATE/cms-epic.md
  .github/ISSUE_TEMPLATE/cms-release-notes.md
  .github/ISSUE_TEMPLATE/cms-section-request.md
  .github/ISSUE_TEMPLATE/cms-support.md
  .github/ISSUE_TEMPLATE/cms-task.md
  .github/ISSUE_TEMPLATE/cms-ux-writing.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/tier-1-or-2-ongoing-work.md
  .github/ISSUE_TEMPLATE/vamc-launch-support.md
  .github/workflows/pull-request-labels.yml
Labels: Core Application Team, Product Support Team

#5175 VACMS-0000: Remove Kint and update Devel
  composer.json
  composer.lock
  config/sync/config_ignore.settings.yml
Labels: Core Application Team

#5143 VACMS-4989: Audience tags hardening.
  config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
  config/sync/entity_browser.browser.audiences_checkboxes.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_audience.yml
  config/sync/user.role.authenticated.yml
  config/sync/user.role.content_admin.yml
  config/sync/user.role.content_creator_benefits_hubs.yml
  config/sync/user.role.content_creator_resources_and_support.yml
  config/sync/user.role.content_editor.yml
  config/sync/user.role.content_publisher.yml
  config/sync/user.role.content_reviewer.yml
  config/sync/user.role.office_content_creator.yml
  config/sync/user.role.vamc_content_creator.yml
  config/sync/views.view.taxonomy_entity_browsers.yml
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Product Support Team

#5152 VACMS-5089: Enable Sections menu breadcrumbs.
  config/sync/menu_breadcrumb.settings.yml
Labels: Product Support Team

#5142 VACMS-5141: Remove health from Vet Center Service content type name.
  config/sync/node.type.vet_center_facility_health_servi.yml
  tests/behat/drupal-spec-tool/content_model_bundles.feature
  tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature
Labels: Product Support Team

#5103 VACMS-5099: Add view of VAMC Top Task revisions.
  config/sync/views.view.vamc_top_task_page_revisions.yml
  tests/behat/drupal-spec-tool/views.feature
Labels: Product Support Team
