Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2021-08, with the labels that each got.

#6000 VACMS-4695: Disable sentry in stage
  config/prod/raven.settings.yml
  config/stg/raven.settings.yml
  config/sync/config_split.config_split.stg.yml
Labels: Core Application Team

#6026 VACMS-4919: Static analysis and deprecated code checks.
  .github/workflows/phpstan.yml
  .lando.yml
  composer.json
  composer.lock
  docroot/modules/custom/va_gov_build_trigger/src/Commands/WebBuildCommands.php
  phpstan-baseline.neon
  phpstan.neon
Labels: Core Application Team

#6024 VACMS-6006: Remove 8 migration endpoints.
  config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml
Labels: Product Support Team

#6023 VACMS-5980: Add address line 2 to entity types.
  config/sync/field.field.node.vet_center_cap.field_address.yml
  config/sync/field.field.paragraph.service_location_address.field_address.yml
Labels: Product Support Team

#6018 VACMS-5974: Prevent inline entity form entity system delete.
  composer.json
Labels: Product Support Team

#6013 VACMS-6007: Add banner content type.
  config/sync/core.base_field_override.node.banner.promote.yml
  config/sync/core.base_field_override.node.banner.title.yml
  config/sync/core.entity_form_display.node.banner.default.yml
  config/sync/core.entity_view_display.node.banner.default.yml
  config/sync/core.entity_view_display.node.banner.teaser.yml
  config/sync/field.field.node.banner.body.yml
  config/sync/field.field.node.banner.field_administration.yml
  config/sync/field.field.node.banner.field_alert_type.yml
  config/sync/field.field.node.banner.field_target_paths.yml
  config/sync/field.storage.node.field_target_paths.yml
  config/sync/node.type.banner.yml
  config/sync/pathauto.pattern.banner.yml
  config/sync/user.role.content_admin.yml
  config/sync/user.role.content_editor.yml
  config/sync/user.role.content_publisher.yml
  config/sync/user.role.content_reviewer.yml
  config/sync/workbench_access.access_scheme.section.yml
  config/sync/workflows.workflow.editorial.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  tests/behat/drupal-spec-tool/content_model_bundles.feature
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Product Support Team

#6047 VACMS-5610: Runs composer va:web:install unconditionally in frontend build.
  docroot/modules/custom/va_gov_build_trigger/src/WebBuildCommandBuilder.php
  tests/phpunit/FrontendBuild/WebBuildCommandBuilderTest.php
Labels: Core Application Team

#6025 VACMS-6004: Replace Wallawalla menu.
  config/sync/system.menu.va-walla-walla-health-care.yml
  config/sync/system.menu.va-wallawalla-health-care.yml
  tests/behat/drupal-spec-tool/menus.feature
Labels: Product Support Team

#6054 VACMS-5931 Add walla walla menu to content types.
  config/sync/node.type.event.yml
  config/sync/node.type.event_listing.yml
  config/sync/node.type.health_care_local_facility.yml
  config/sync/node.type.health_care_region_detail_page.yml
  config/sync/node.type.health_care_region_page.yml
  config/sync/node.type.health_services_listing.yml
  config/sync/node.type.leadership_listing.yml
  config/sync/node.type.locations_listing.yml
  config/sync/node.type.news_story.yml
  config/sync/node.type.person_profile.yml
  config/sync/node.type.press_release.yml
  config/sync/node.type.press_releases_listing.yml
  config/sync/node.type.publication_listing.yml
  config/sync/node.type.story_listing.yml
  config/sync/node.type.vamc_operating_status_and_alerts.yml
  config/sync/node.type.vamc_system_policies_page.yml
Labels: VAMC system, vsa-vamc-upgrade, Product Support Team

#6063 VACMS-6010 Refactor of clone code into drush job
  READMES/scalability.md
  docroot/modules/custom/va_gov_clone/drush.services.yml
  docroot/modules/custom/va_gov_clone/src/CloneEntityFinder/Annotation/CloneEntityFinder.php
  docroot/modules/custom/va_gov_clone/src/CloneEntityFinder/CloneEntityFinderBase.php
  docroot/modules/custom/va_gov_clone/src/CloneEntityFinder/CloneEntityFinderDiscovery.php
  docroot/modules/custom/va_gov_clone/src/CloneEntityFinder/CloneEntityFinderInterface.php
  docroot/modules/custom/va_gov_clone/src/CloneManager.php
  docroot/modules/custom/va_gov_clone/src/CloneManagerInterface.php
  docroot/modules/custom/va_gov_clone/src/Commands/VaGovCloneCommands.php
  docroot/modules/custom/va_gov_clone/src/Plugin/VAGov/CloneHandler/CLP.php
  docroot/modules/custom/va_gov_clone/src/Plugin/VAGov/CloneHandler/Section.php
  docroot/modules/custom/va_gov_clone/va_gov_clone.info.yml
  docroot/modules/custom/va_gov_clone/va_gov_clone.services.yml
  phpstan-baseline.neon
  scripts/clone.php
Labels: Core Application Team

#5968 Upgrade to Drupal 9.2
  composer.json
  composer.lock
  config/sync/views.view.frontpage.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.install
  docroot/sites/default/default.services.yml
  docroot/sites/default/default.settings.php
  docroot/sites/default/services.yml
  docroot/sites/default/settings.php
  docroot/sites/default/settings/settings.brd_common.php
  docroot/sites/default/settings/settings.dev.php
  docroot/sites/default/settings/settings.fast_404.php
  docroot/sites/default/settings/settings.lando.php
  docroot/sites/default/settings/settings.prod.php
  docroot/sites/default/settings/settings.staging.php
  docroot/sites/default/settings/settings.tugboat.php
  docroot/sites/example.settings.local.php
  docroot/sites/example.sites.php
  docroot/web.config
  tests/behat/drupal-spec-tool/views.feature
Labels: Core Application Team, Product Support Team

#6077 VACMS-5788: Fix issues with yarn installed executables.
  .tugboat/config.yml
Labels: Core Application Team

#6022 VACMS-5902: Set alert edit block forms to default draft.
  docroot/modules/custom/va_gov_workflow_assignments/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_workflow_assignments/va_gov_workflow_assignments.services.yml
Labels: Product Support Team

#6094 VACMS-6085: Add fields to banner content type.
  config/sync/core.entity_form_display.node.banner.default.yml
  config/sync/core.entity_view_display.node.banner.default.yml
  config/sync/core.entity_view_display.node.banner.teaser.yml
  config/sync/field.field.node.banner.field_dismissible_option.yml
  config/sync/field.storage.node.field_dismissible_option.yml
Labels: Product Support Team

#5954 VACMS-5912: Limit VAMC options for VAMC banner alerts based on section access.
  docroot/modules/custom/va_gov_menu_access/js/va_gov_menu_access.es6.js
  docroot/modules/custom/va_gov_menu_access/js/va_gov_menu_access.js
  docroot/modules/custom/va_gov_vamc/js/limit_vamcs_to_workbench.es6.js
  docroot/modules/custom/va_gov_vamc/js/limit_vamcs_to_workbench.js
  docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_vamc/va_gov_vamc.libraries.yml
  docroot/modules/custom/va_gov_vamc/va_gov_vamc.services.yml
Labels: Product Support Team

#6038 VACMS-5188: Add office hours module field to facilities.
  composer.json
  config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_form_display.node.health_care_local_facility.inline_entity_form.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.external_content.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.ief_table.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.teaser.yml
  config/sync/field.field.node.health_care_local_facility.field_office_hours.yml
  config/sync/migrate_plus.migration.va_node_health_care_local_facility.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility.yml
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
Labels: Product Support Team

#6090 VACMS-6088: Add buttons for service location deletion.
  docroot/modules/custom/va_gov_backend/js/service_location_address.es6.js
  docroot/modules/custom/va_gov_backend/js/service_location_address.js
  docroot/themes/custom/vagovadmin/assets/css/styles.css
  docroot/themes/custom/vagovadmin/assets/css/styles.css.map
  docroot/themes/custom/vagovadmin/assets/scss/_services.scss
Labels: Product Support Team

#6116 VACMS-6115 Add perms so content_admin can create blocks
  config/sync/user.role.content_admin.yml
  config/sync/user.role.content_creator_vet_center.yml
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: vsa-public-websites, Product Support Team

#6140 VACMS-6113: Automatically fix broken links to email addresses.
  config/sync/filter.format.rich_text.yml
  config/sync/filter.format.rich_text_limited.yml
  docroot/modules/custom/va_gov_backend/src/Plugin/Filter/EmailLinkRepairFilter.php
  tests/phpunit/Content/EmailLinkRepairFilterTest.php
Labels: Core Application Team

#6133 VACMS-6125 Remove hudson valley endpoint.
  config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml
Labels: vsa-facilities, Product Support Team

#6146 Update http timeout to 60 seconds
  docroot/sites/default/settings.php
Labels: Core Application Team

#6165 VACMS-6159: Update ief to use char count on vamc facility form.
  config/sync/core.entity_form_display.node.health_care_local_facility.inline_entity_form.yml
Labels: Product Support Team

#6162 VACMS-4830: Add tests for BuildFrontend.
  tests/phpunit/FrontendBuild/BuildFrontendTest.php
Labels: Core Application Team

#6174 VACMS 6130: Adds functional test for user login with a single assigned section.
  tests/behavioral/cypress/integration/common/i_log_back_in.js
  tests/behavioral/cypress/integration/common/my_workbench_access_sections_are_not_set.js
  tests/behavioral/cypress/integration/common/my_workbench_access_sections_are_set_to.js
  tests/behavioral/cypress/integration/user_login.feature
  tests/behavioral/cypress/support/index.js
Labels: Core Application Team

#6042 VACMS 6033: Fix PHPStan issues with va_gov_backend.module
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  phpstan-baseline.neon
Labels: Core Application Team

#6191 VACMS-6152: Update role label.
  config/sync/user.role.admnistrator_users.yml
  tests/behat/drupal-spec-tool/access_control.feature
Labels: Product Support Team

#6192 VACMS-6186: Enforce wysiwyg char limit.
  config/sync/core.entity_form_display.paragraph.featured_content.default.yml
Labels: Product Support Team

#6154 VACMS-6136: Update staff selection widget to use view.
  config/sync/core.entity_form_display.paragraph.staff_profile.default.yml
  config/sync/field.field.node.leadership_listing.field_leadership.yml
  config/sync/field.field.paragraph.staff_profile.field_staff_profile.yml
  config/sync/views.view.content_entity_reference_source.yml
  tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature
  tests/behat/drupal-spec-tool/views.feature
Labels: Product Support Team

#6142 VACMS-6071: Create three new VAMC Top Task content types.
  config/sync/auto_entitylabel.settings.node.vamc_system_billing_insurance.yml
  config/sync/auto_entitylabel.settings.node.vamc_system_medical_records_offi.yml
  config/sync/auto_entitylabel.settings.node.vamc_system_register_for_care.yml
  config/sync/core.base_field_override.node.vamc_system_billing_insurance.promote.yml
  config/sync/core.base_field_override.node.vamc_system_billing_insurance.status.yml
  config/sync/core.base_field_override.node.vamc_system_medical_records_offi.promote.yml
  config/sync/core.base_field_override.node.vamc_system_medical_records_offi.status.yml
  config/sync/core.base_field_override.node.vamc_system_register_for_care.promote.yml
  config/sync/core.base_field_override.node.vamc_system_register_for_care.status.yml
  config/sync/core.entity_form_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_form_display.node.vamc_system_medical_records_offi.default.yml
  config/sync/core.entity_form_display.node.vamc_system_register_for_care.default.yml
  config/sync/core.entity_view_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_view_display.node.vamc_system_billing_insurance.teaser.yml
  config/sync/core.entity_view_display.node.vamc_system_medical_records_offi.default.yml
  config/sync/core.entity_view_display.node.vamc_system_medical_records_offi.teaser.yml
  config/sync/core.entity_view_display.node.vamc_system_register_for_care.default.yml
  config/sync/core.entity_view_display.node.vamc_system_register_for_care.teaser.yml
  config/sync/field.field.node.vamc_system_billing_insurance.field_administration.yml
  config/sync/field.field.node.vamc_system_billing_insurance.field_enforce_unique_combo.yml
  config/sync/field.field.node.vamc_system_billing_insurance.field_enforce_unique_combo_offic.yml
  config/sync/field.field.node.vamc_system_billing_insurance.field_office.yml
  config/sync/field.field.node.vamc_system_medical_records_offi.field_administration.yml
  config/sync/field.field.node.vamc_system_medical_records_offi.field_enforce_unique_combo.yml
  config/sync/field.field.node.vamc_system_medical_records_offi.field_enforce_unique_combo_offic.yml
  config/sync/field.field.node.vamc_system_medical_records_offi.field_office.yml
  config/sync/field.field.node.vamc_system_register_for_care.field_administration.yml
  config/sync/field.field.node.vamc_system_register_for_care.field_enforce_unique_combo.yml
  config/sync/field.field.node.vamc_system_register_for_care.field_enforce_unique_combo_offic.yml
  config/sync/field.field.node.vamc_system_register_for_care.field_office.yml
  config/sync/field.storage.node.field_enforce_unique_combo_offic.yml
  config/sync/metatag.metatag_defaults.node__vamc_system_billing_insurance.yml
  config/sync/metatag.metatag_defaults.node__vamc_system_medical_records_offi.yml
  config/sync/metatag.metatag_defaults.node__vamc_system_register_for_care.yml
  config/sync/node.type.vamc_system_billing_insurance.yml
  config/sync/node.type.vamc_system_medical_records_offi.yml
  config/sync/node.type.vamc_system_register_for_care.yml
  config/sync/pathauto.pattern.vamc_root_page.yml
  config/sync/pathauto.pattern.vamc_system_policies.yml
  config/sync/user.role.content_admin.yml
  config/sync/user.role.content_editor.yml
  config/sync/workbench_access.access_scheme.section.yml
  config/sync/workflows.workflow.editorial.yml
  tests/behat/drupal-spec-tool/content_model_bundles.feature
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Product Support Team

#6220 VACMS-000 Add Walla walla health care menu to workbench access walla walla section
  config/sync/system.menu.va-walla-walla-health-care.yml
Labels: Product Support Team

#6155 VACMS-6151: Remove va migration endpoints.
  config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml
Labels: Product Support Team, DO NOT MERGE

#6292 VACMS-000 Removed fingerlakes endpoint.
  config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml
Labels: Product Support Team

#6291 VACMS-6098: Allow any user to a workbench access section, regardless of their role.
  config/sync/user.role.authenticated.yml
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Product Support Team

#6045 VACMS-5985 alert block governance
  config/sync/field.field.block_content.alert.field_is_this_a_header_alert_.yml
  config/sync/user.role.content_creator_benefits_hubs.yml
  config/sync/user.role.content_creator_resources_and_support.yml
  config/sync/user.role.content_editor.yml
  config/sync/user.role.content_publisher.yml
  config/sync/user.role.content_reviewer.yml
  config/sync/user.role.office_content_creator.yml
  config/sync/user.role.vamc_content_creator.yml
  docroot/modules/custom/va_gov_workflow_assignments/js/alert_block_treatment.es6.js
  docroot/modules/custom/va_gov_workflow_assignments/js/alert_block_treatment.js
  docroot/modules/custom/va_gov_workflow_assignments/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_workflow_assignments/va_gov_workflow_assignments.libraries.yml
  docroot/modules/custom/va_gov_workflow_assignments/va_gov_workflow_assignments.services.yml
  tests/behat/drupal-spec-tool/content_model_custom_block_fields.feature
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Product Support Team

#6166 VACMS-6148: Prevent non admins from altering banner scope path fields.
  config/sync/core.extension.yml
  docroot/modules/custom/va_gov_banner/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_banner/va_gov_banner.info.yml
  docroot/modules/custom/va_gov_banner/va_gov_banner.module
  docroot/modules/custom/va_gov_banner/va_gov_banner.services.yml
  docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_workflow_assignments/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_workflow_assignments/va_gov_workflow_assignments.services.yml
Labels: Product Support Team

#6303 VACMS-6302: Add content audit view display for content admins.
  config/sync/views.view.content.yml
  tests/behat/drupal-spec-tool/views.feature
Labels: Product Support Team

#6298 VACMS-6185: Remove durham endpoint.
  config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml
Labels: Product Support Team

#6158 VACMS-6135: Make product field multivalue in KB articles.
  config/sync/core.entity_form_display.node.documentation_page.default.yml
  config/sync/core.entity_form_display.taxonomy_term.products.default.yml
  config/sync/core.entity_view_display.node.documentation_page.default.yml
  config/sync/core.entity_view_display.node.documentation_page.teaser.yml
  config/sync/field.field.node.documentation_page.field_products.yml
  config/sync/field.field.taxonomy_term.products.field_kb_landing_page.yml
  config/sync/field.storage.node.field_products.yml
  config/sync/field.storage.taxonomy_term.field_kb_landing_page.yml
  config/sync/views.view.knowledge_base_article_administration.yml
  tests/behat/drupal-spec-tool/content_model_user_guides_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature
Labels: Product Support Team
