Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2021-06, with the labels that each got.

#5487 VACMS-5478: Update linkit config to include additional content type.
  config/sync/linkit.linkit_profile.default.yml
Labels: Product Support Team

#5476 VACMS-5120: Change detail page label to VAMC Detail page.
  config/sync/core.entity_form_display.node.health_care_region_detail_page.default.yml
  config/sync/node.type.health_care_region_detail_page.yml
  tests/behat/drupal-spec-tool/content_model_bundles.feature
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
Labels: Product Support Team

#5484 VACMS-5447: Update content release perms.
  config/sync/user.role.content_publisher.yml
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Product Support Team

#5512 VACMS-5442 Expand link error handling and 508.
  composer.lock
  config/sync/node_link_report.settings.yml
Labels: 508 / Accessibility, Product Support Team

#5489 VACMS-4988: Integration branch for menu IA
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/disable_node_menu_item.settings.yml
  config/sync/node.type.health_care_region_detail_page.yml
  config/sync/pathauto.pattern.health_care_region_detail_page.yml
  config/sync/pathauto.settings.yml
  config/sync/views.view.detail_page_url_audit_and_bulk_udpate.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  docroot/modules/custom/va_gov_db/va_gov_db.install
  docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
  docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
  tests/behat/drupal-spec-tool/views.feature
  tests/behat/features/content_editing.feature
  tests/behavioral/cypress/integration/common/i_create_a_node.js
Labels: DO NOT MERGE

#5424 VACMS-5273 Add system health services for visn 7 and 8
  composer.lock
  config/sync/migrate_plus.migration.facility_health_care_service_visn_7_8.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.facility_health_care_service_visn_7_8.yml
  docroot/modules/custom/va_gov_migrate/data/facility-health-care-service-visn-7-8.csv
  docroot/modules/custom/va_gov_migrate/data/regional-health-care-service-region-keyed.csv
Labels: Product Support Team

#5565 VACMS-4768: Remove parent dependency on health service entity references.
  config/sync/views.view.health_care_service_names_and_descriptions.yml
Labels: Product Support Team

#5588 VACMS-5536 Bump node_link_report.
  composer.lock
Labels: Product Support Team

#5606 [DOCS] VACMS-000 Add documentation for system service migrations.
  READMES/migrations-facility.md
Labels: Migration, documentation

#5549 VACMS-5400: Update audit view to include moderation state.
  config/sync/views.view.detail_page_url_audit_and_bulk_udpate.yml
Labels: Product Support Team

#5561 VACMS-5544: Update vc help link.
  config/sync/field.field.node.vet_center.field_table_of_contents.yml
Labels: Product Support Team

#5589 VACMS-5419: Update clone perms
  config/sync/user.role.content_creator_benefits_hubs.yml
  config/sync/user.role.content_creator_resources_and_support.yml
  config/sync/user.role.office_content_creator.yml
  config/sync/user.role.vamc_content_creator.yml
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Product Support Team

#5591 VACMS-5425: Update vc cap labels.
  config/sync/core.entity_form_display.node.vet_center_cap.default.yml
  config/sync/field.field.node.vet_center_cap.field_operating_status_facility.yml
  config/sync/field.field.node.vet_center_cap.field_operating_status_more_info.yml
  tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature
Labels: Product Support Team

#5592 VACMS-4790: Update admin user perms.
  config/sync/user.role.admnistrator_users.yml
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Product Support Team

#5649 VACMS-000 Fix source of php notice_va_gov_vet_center_require_revision_message
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Product Support Team

#5678 VACMS-5625: Add viewport_width image style.
  config/sync/image.style.viewport_width.yml
  tests/behat/drupal-spec-tool/media.feature
Labels: Product Support Team

#5604 VACMS-5339 vamc meta refactoring
  composer.lock
  config/sync/core.entity_form_display.node.event_listing.default.yml
  config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_form_display.node.health_care_local_facility.inline_entity_form.yml
  config/sync/core.entity_form_display.node.health_care_region_detail_page.default.yml
  config/sync/core.entity_form_display.node.health_care_region_page.default.yml
  config/sync/core.entity_form_display.node.health_services_listing.default.yml
  config/sync/core.entity_form_display.node.leadership_listing.default.yml
  config/sync/core.entity_form_display.node.locations_listing.default.yml
  config/sync/core.entity_form_display.node.press_releases_listing.default.yml
  config/sync/core.entity_form_display.node.regional_health_care_service_des.inline_entity_form.yml
  config/sync/core.entity_form_display.node.story_listing.default.yml
  config/sync/core.entity_view_display.node.event_listing.default.yml
  config/sync/core.entity_view_display.node.event_listing.teaser.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.ief_table.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.teaser.yml
  config/sync/core.entity_view_display.node.health_care_region_detail_page.default.yml
  config/sync/core.entity_view_display.node.health_care_region_detail_page.teaser.yml
  config/sync/core.entity_view_display.node.health_care_region_page.default.yml
  config/sync/core.entity_view_display.node.health_care_region_page.teaser.yml
  config/sync/core.entity_view_display.node.health_services_listing.default.yml
  config/sync/core.entity_view_display.node.health_services_listing.teaser.yml
  config/sync/core.entity_view_display.node.leadership_listing.default.yml
  config/sync/core.entity_view_display.node.leadership_listing.teaser.yml
  config/sync/core.entity_view_display.node.locations_listing.default.yml
  config/sync/core.entity_view_display.node.locations_listing.teaser.yml
  config/sync/core.entity_view_display.node.press_releases_listing.default.yml
  config/sync/core.entity_view_display.node.press_releases_listing.teaser.yml
  config/sync/core.entity_view_display.node.story_listing.default.yml
  config/sync/core.entity_view_display.node.story_listing.teaser.yml
  config/sync/field.field.node.event_listing.field_meta_title.yml
  config/sync/field.field.node.health_care_local_facility.field_meta_title.yml
  config/sync/field.field.node.health_care_region_detail_page.field_meta_title.yml
  config/sync/field.field.node.health_care_region_page.field_meta_title.yml
  config/sync/field.field.node.health_services_listing.field_meta_title.yml
  config/sync/field.field.node.leadership_listing.field_meta_title.yml
  config/sync/field.field.node.locations_listing.field_meta_title.yml
  config/sync/field.field.node.press_releases_listing.field_meta_title.yml
  config/sync/field.field.node.story_listing.field_meta_title.yml
  config/sync/metatag.metatag_defaults.node.yml
  config/sync/metatag.metatag_defaults.node__event_listing.yml
  config/sync/metatag.metatag_defaults.node__health_care_local_facility.yml
  config/sync/metatag.metatag_defaults.node__health_care_region_detail_page.yml
  config/sync/metatag.metatag_defaults.node__health_care_region_page.yml
  config/sync/metatag.metatag_defaults.node__news_story.yml
  config/sync/metatag.metatag_defaults.node__person_profile.yml
  config/sync/metatag.metatag_defaults.node__press_release.yml
  config/sync/metatag.metatag_defaults.node__vamc_operating_status_and_alerts.yml
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
  tests/behat/features/lc_content.feature
  tests/behat/features/save_and_continue.feature
Labels: Product Support Team

#5676 VACMS-5615: Add new migrations for visns 10,17,20.
  config/sync/migrate_plus.migration.facility_health_care_service_visn_10_17_20.yml
  config/sync/migrate_plus.migration.regional_health_care_service_region_keyed_2.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.facility_health_care_service_visn_10_17_20.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.regional_health_care_service_region_keyed_2.yml
  docroot/modules/custom/va_gov_migrate/data/facility-health-care-service-visn-10-17-20.csv
  docroot/modules/custom/va_gov_migrate/data/regional-health-care-service-region-keyed-2.csv
Labels: Product Support Team

#5681 VACMS-4936: Add setter logic to vc ief selects.
  docroot/modules/custom/va_gov_vet_center/js/set_ief_service_selects.es6.js
  docroot/modules/custom/va_gov_vet_center/js/set_ief_service_selects.js
  docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.libraries.yml
  docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.module
Labels: Product Support Team

#5679 VACMS-5320: Remove vbo from section views.
  config/sync/views.view.taxonomy_term.yml
Labels: Product Support Team

#5697 VACMS-5694: Add style to image cache warmer.
  config/sync/image_style_warmer.settings.yml
Labels: Product Support Team

#5689 VACMS-5488: Enable menu force on multiple content types.
  config/sync/node.type.documentation_page.yml
  config/sync/node.type.event_listing.yml
  config/sync/node.type.health_care_local_facility.yml
  config/sync/node.type.health_care_region_page.yml
  config/sync/node.type.health_services_listing.yml
  config/sync/node.type.leadership_listing.yml
  config/sync/node.type.locations_listing.yml
  config/sync/node.type.press_releases_listing.yml
  config/sync/node.type.story_listing.yml
  config/sync/node.type.vamc_operating_status_and_alerts.yml
  config/sync/node.type.vamc_system_policies_page.yml
  tests/behavioral/cypress/integration/common/i_create_a_node.js
Labels: Product Support Team

#5691 VACMS-5671: Add leadership flag.
  config/sync/feature_toggle.features.yml
Labels: Product Support Team

#5645 VACMS-5644: Remove general access to taxonomy overview.
  config/sync/user.role.authenticated.yml
  config/sync/user.role.content_admin.yml
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Product Support Team

#5646 VACMS-4582: Improve taxonomy admin tools.
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/hierarchy_manager.hm_display_profile.default_hierarchy_manager_display_profile.yml
  config/sync/hierarchy_manager.hmconfig.yml
Labels: Product Support Team

#5214 VACMS-5213: Add user admin tab to every Section.
  config/sync/views.view.users_in_section.yml
  tests/behat/drupal-spec-tool/views.feature
Labels: Product Support Team

#5735 VACMS-4056: Add logic to restrict elements to certain roles on centralized content.
  docroot/modules/custom/va_gov_backend/js/script.es6.js
  docroot/modules/custom/va_gov_backend/js/script.js
Labels: Product Support Team
