Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2021-05, with the labels that each got.

#5196 VACMS-5083: Add benchmark scripts and documentation.
  scripts/benchmarks/dump_access_log_request_paths.sh
  scripts/benchmarks/frontend_build/parallel_frontend_build.sh
  scripts/benchmarks/frontend_build/sequential_frontend_build.sh
  scripts/benchmarks/install_siege.sh
  scripts/benchmarks/memcache-benchmarks.md
  scripts/benchmarks/siege.sh
  scripts/benchmarks/siegerc
  scripts/benchmarks/wget_spider.sh
Labels: Core Application Team, Needs PO review

#5161 VACMS-4989: Delete deprecated audience vocab.
  composer.lock
  config/sync/core.entity_form_display.taxonomy_term.audience_tags.default.yml
  config/sync/core.entity_view_display.taxonomy_term.audience_tags.default.yml
  config/sync/taxonomy.vocabulary.audience_tags.yml
  tests/behat/drupal-spec-tool/content_model_bundles.feature
Labels: Product Support Team

#5208 VACMS-000 Make policy field_office allow reference show unpublished content
  config/sync/field.field.node.vamc_system_policies_page.field_office.yml
Labels: Product Support Team

#5220 VACMS-0000: Updates drupal/entity_clone to 1.0b6.
  composer.json
  composer.lock
Labels: Core Application Team

#5219 VACMS-5204 Add logging for Broken links
  composer.json
  composer.lock
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/AdvancedQueue/JobType/WebBuildJobType.php
Labels: Core Application Team

#5211 VACMS-5210: Create view of sections for administration.
  config/sync/views.view.section_export.yml
  tests/behat/drupal-spec-tool/views.feature
Labels: Product Support Team

#5199 VACMS-5193 Content Build Separation work
  .tugboat/config.yml
  composer.json
  composer.lock
  docroot/modules/custom/va_gov_build_trigger/src/Controller/FrontEndBranchAutocompleteController.php
  docroot/modules/custom/va_gov_build_trigger/src/WebBuildCommandBuilder.php
  docroot/sites/default/settings/settings.dev.php
  docroot/sites/default/settings/settings.prod.php
  docroot/sites/default/settings/settings.staging.php
  docroot/static
  tests/phpunit/FrontendBuild/WebBuildCommandBuilderTest.php
  web
Labels: Core Application Team, DO NOT MERGE

#5225 VACMS-0000: Updates drupal/path_redirect_import to 1.0.0-beta4.
  composer.json
  composer.lock
Labels: Core Application Team

#5212 VACMS-3263-5040-5041: Improve /admin/people page for user admin.
  config/sync/views.view.user_admin_people.yml
Labels: Product Support Team

#5239 VACMS-5224: Update drupal/metatag and drupal/inline_entity_form.
  composer.json
  composer.lock
Labels: Core Application Team

#5242 Content build log clean up
  composer.json
  composer.lock
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/AdvancedQueue/JobType/WebBuildJobType.php
  docroot/modules/custom/va_gov_build_trigger/src/WebBuildBrokenLinkChecker.php
  docroot/modules/custom/va_gov_build_trigger/src/WebBuildCommandBuilder.php
  docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.services.yml
  tests/phpunit/FrontendBuild/WebBuildCommandBuilderTest.php
Labels: Core Application Team

#5259 VACMS-4947: Add workaround repositories for certain modules.
  composer.json
  composer.lock
Labels: Core Application Team

#5261 VACMS 0000: Fix issue with status-error task II: The Regex Warrior
  tests.yml
Labels: Core Application Team

#5278 VACMS-5194: Change content-build repo to use source
  composer.json
  composer.lock
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/Block/ContentReleaseStatusBlock.php
Labels: Core Application Team

#4909 VACMS-4604: Change default field_administration to _none
  config/sync/field.field.node.documentation_page.field_administration.yml
  config/sync/field.field.node.full_width_banner_alert.field_administration.yml
  config/sync/field.field.node.nca_facility.field_administration.yml
  config/sync/field.field.node.support_service.field_administration.yml
  config/sync/field.field.node.va_form.field_administration.yml
  config/sync/field.field.node.vamc_operating_status_and_alerts.field_administration.yml
  config/sync/field.field.node.vba_facility.field_administration.yml
  config/sync/field.field.node.vet_center.field_administration.yml
  config/sync/field.field.node.vet_center_facility_health_servi.field_administration.yml
  config/sync/field.field.node.vet_center_locations_list.field_administration.yml
  config/sync/field.field.node.vet_center_mobile_vet_center.field_administration.yml
  config/sync/field.field.node.vet_center_outstation.field_administration.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  docroot/modules/custom/va_gov_user/src/Service/UserPermsService.php
  tests/behat/features/content_editing.feature
  tests/behavioral/cypress/integration/common/i_create_a_node.js
Labels: Product Support Team

#5277 VACMS-4846 No content type should show Submitted or Owner info
  config/sync/core.entity_view_display.node.basic_landing_page.default.yml
  config/sync/core.entity_view_display.node.checklist.default.yml
  config/sync/core.entity_view_display.node.faq_multiple_q_a.default.yml
  config/sync/core.entity_view_display.node.full_width_banner_alert.ief_table.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.ief_table.yml
  config/sync/core.entity_view_display.node.health_care_region_page.default.yml
  config/sync/core.entity_view_display.node.landing_page.default.yml
  config/sync/core.entity_view_display.node.media_list_images.default.yml
  config/sync/core.entity_view_display.node.media_list_videos.default.yml
  config/sync/core.entity_view_display.node.nca_facility.default.yml
  config/sync/core.entity_view_display.node.q_a.default.yml
  config/sync/core.entity_view_display.node.q_a.support_services_listing.yml
  config/sync/core.entity_view_display.node.step_by_step.default.yml
  config/sync/core.entity_view_display.node.support_resources_detail_page.default.yml
  config/sync/core.entity_view_display.node.vba_facility.default.yml
  config/sync/node.type.vet_center_cap.yml
Labels: Product Support Team

#5293 VACMS-5221: Add new visn items to scaffolding config.
  config/sync/menu_breadcrumb.settings.yml
  config/sync/node.type.event.yml
  config/sync/node.type.event_listing.yml
  config/sync/node.type.health_care_local_facility.yml
  config/sync/node.type.health_care_region_detail_page.yml
  config/sync/node.type.health_care_region_page.yml
  config/sync/node.type.health_services_listing.yml
  config/sync/node.type.leadership_listing.yml
  config/sync/node.type.locations_listing.yml
  config/sync/node.type.news_story.yml
  config/sync/node.type.person_profile.yml
  config/sync/node.type.press_release.yml
  config/sync/node.type.press_releases_listing.yml
  config/sync/node.type.publication_listing.yml
  config/sync/node.type.story_listing.yml
  config/sync/node.type.vamc_operating_status_and_alerts.yml
  config/sync/node.type.vamc_system_policies_page.yml
  config/sync/system.menu.va-ann-arbor-health-care.yml
  config/sync/system.menu.va-battle-creek-health-care.yml
  config/sync/system.menu.va-central-ohio-health-care.yml
  config/sync/system.menu.va-chillicothe-health-care.yml
  config/sync/system.menu.va-cincinnati-health-care.yml
  config/sync/system.menu.va-dayton-health-care.yml
  config/sync/system.menu.va-detroit-health-care.yml
  config/sync/system.menu.va-eastern-kansas-health-care.yml
  config/sync/system.menu.va-indiana-health-care.yml
  config/sync/system.menu.va-northeast-ohio-health-care.yml
  config/sync/system.menu.va-northern-indiana-health-care.yml
  config/sync/system.menu.va-saginaw-health-care.yml
Labels: Product Support Team

#5303 VACMS-5282: Replace button on user login form with get help link.
  docroot/modules/custom/va_gov_help_center/va_gov_help_center.module
  docroot/themes/custom/vagovadmin/assets/css/styles.css
  docroot/themes/custom/vagovadmin/assets/css/styles.css.map
  docroot/themes/custom/vagovadmin/assets/scss/styles.scss
  tests/behavioral/cypress/integration/help_center.feature
  tests/behavioral/cypress/integration/help_center/get_help.js
Labels: Product Support Team

#5307 VACMS-5110: Add destination parameter to dash links.
  docroot/modules/custom/va_gov_dashboards/templates/vc-dashboards-block.html.twig
Labels: Product Support Team

#5328 VACMS-4923: Add limiting logic to service dropdowns.
  docroot/modules/custom/va_gov_backend/css/limit_services_to_user_sections.css
  docroot/modules/custom/va_gov_backend/js/limit_services_to_user_sections.es6.js
  docroot/modules/custom/va_gov_backend/js/limit_services_to_user_sections.js
  docroot/modules/custom/va_gov_backend/va_gov_backend.libraries.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Product Support Team

#5330 VACMS-5321: Set default value for vc intro text field.
  config/sync/field.field.node.vet_center.field_intro_text.yml
  docroot/modules/custom/va_gov_db/va_gov_db.install
Labels: Product Support Team

#5341 VACMS-5334: Update staff profile config.
  config/sync/field.field.node.leadership_listing.field_leadership.yml
Labels: Product Support Team

#5381 VACMS-5237 Update javascript deps on vagovadmin theme
  docroot/themes/custom/vagovadmin/assets/css/styles.min.css
  docroot/themes/custom/vagovadmin/assets/css/styles.min.css.map
  docroot/themes/custom/vagovadmin/gulpfile.js
  docroot/themes/custom/vagovadmin/package-lock.json
  docroot/themes/custom/vagovadmin/package.json
Labels: Core Application Team, Product Support Team

#5396 VACMS-5296: Add three domains to link check whitelist.
  config/sync/node_link_report.settings.yml
Labels: Core Application Team, Product Support Team

#5383 VACMS-5234: Execute all steps of multi-step tasks and return errors appropriately.
  tasks-periodic.yml
Labels: Core Application Team

#5395 VACMS-4893: Fix spelling typo in word counseling.
  config/sync/field.storage.taxonomy_term.field_vet_center_type_of_care.yml
Labels: Product Support Team

#5389 VACMS-5045: Remove edit links on Nearby Vet Center field.
  config/sync/core.entity_form_display.node.vet_center_locations_list.default.yml
Labels: Product Support Team

#5394 VACMS-5390 Remove buttons validation logic.
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Product Support Team

#5398 VACMS-5371: Toughen entity reference validation behavioral test.
  tests/behavioral/cypress/integration/common/i_select_the_benefits_hub.js
  tests/behavioral/cypress/integration/entity_reference_validation.feature
Labels: Core Application Team

#5403 VACMS-4893: Remove deprecated counselling value from field.
  config/sync/field.storage.taxonomy_term.field_vet_center_type_of_care.yml
Labels: Product Support Team

#5356 VACMS-5201: Add vc types to preview exclusion list.
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Product Support Team

#5386 VACMS 4898: Send node count data to Prometheus
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/prometheus_exporter.settings.yml
  config/sync/user.role.anonymous.yml
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Core Application Team

#5392 VACMS-4923: Add service limiting logic to service dropdowns.
  config/sync/core.entity_form_display.node.health_care_local_health_service.default.yml
  docroot/modules/custom/va_gov_backend/css/limit_services_to_user_sections.css
  docroot/modules/custom/va_gov_backend/js/limit_services_to_user_sections.es6.js
  docroot/modules/custom/va_gov_backend/js/limit_services_to_user_sections.js
  docroot/modules/custom/va_gov_backend/va_gov_backend.libraries.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Product Support Team

#5359 VACMS-2383: Set pathauto for CLP.
  config/sync/pathauto.pattern.campaign_landing_page.yml
Labels: Product Support Team

#4894 VAGOV-4988: Menu governance for VAMC product.
  config/sync/core.extension.yml
  config/sync/user.role.content_admin.yml
  config/sync/va_gov_menu_access.settings.yml
  docroot/modules/custom/disable_node_menu_item/disable_node_menu_item.info.yml
  docroot/modules/custom/disable_node_menu_item/disable_node_menu_item.routing.yml
  docroot/modules/custom/va_gov_menu_access/js/va_gov_menu_access.es6.js
  docroot/modules/custom/va_gov_menu_access/js/va_gov_menu_access.js
  docroot/modules/custom/va_gov_menu_access/src/Access/RouteAccessChecks.php
  docroot/modules/custom/va_gov_menu_access/src/Form/VaGovMenuAccessConfigForm.php
  docroot/modules/custom/va_gov_menu_access/src/Routing/AdminRouteSubscriber.php
  docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
  docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.info.yml
  docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.libraries.yml
  docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.links.menu.yml
  docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
  docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.permissions.yml
  docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.routing.yml
  docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.services.yml
  docroot/modules/custom/va_gov_user/src/Service/UserPermsService.php
  tests/behat/features/content_editing.feature
  tests/behavioral/cypress/integration/common/i_create_a_node.js
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Product Support Team

#5360 VACMS-5347: Fix hub landing proofing pages.
  config/sync/core.entity_view_display.node.landing_page.default.yml
Labels: Product Support Team

#5302 VACMS-5301: Show only Vet Center services on Vet Center forms.
  config/sync/views.view.content_entity_reference_source.yml
  config/sync/views.view.health_care_service_names_and_descriptions.yml
  tests/behat/drupal-spec-tool/views.feature
Labels: Product Support Team
