Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2021-12, with the labels that each got.

#7107 VACMS-7070 out-of-box claro form style fixes
  docroot/themes/custom/vagovclaro/assets/css/proofing.css
  docroot/themes/custom/vagovclaro/assets/css/proofing.css.map
  docroot/themes/custom/vagovclaro/assets/css/styles.css
  docroot/themes/custom/vagovclaro/assets/css/styles.css.map
  docroot/themes/custom/vagovclaro/assets/css/user_guides.css.map
  docroot/themes/custom/vagovclaro/assets/css/wysiwyg.css.map
  docroot/themes/custom/vagovclaro/assets/scss/_buttons.scss
  docroot/themes/custom/vagovclaro/assets/scss/_media.scss
  docroot/themes/custom/vagovclaro/assets/scss/_mixins.scss
  docroot/themes/custom/vagovclaro/assets/scss/_paragraphs.scss
  docroot/themes/custom/vagovclaro/assets/scss/proofing.scss
  docroot/themes/custom/vagovclaro/assets/scss/styles.scss
  docroot/themes/custom/vagovclaro/templates/node-edit-form.html.twig
Labels: Sitewide CMS Team

#7024 VACMS-7016: remove status endpoints for the week of December 1 2021
  config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml
Labels: vsa-facilities, Sitewide CMS Team

#7066 VACMS-7011: Move help text below labels.
  docroot/modules/custom/va_gov_backend/js/help_text_treatments.es6.js
  docroot/modules/custom/va_gov_backend/js/help_text_treatments.js
  docroot/modules/custom/va_gov_backend/js/script.js
  docroot/modules/custom/va_gov_backend/va_gov_backend.libraries.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Sitewide CMS Team

#7055 VACMS-7019 - Create Promo Banner content type
  config/sync/core.base_field_override.node.promo_banner.promote.yml
  config/sync/core.base_field_override.node.promo_banner.title.yml
  config/sync/core.entity_form_display.node.promo_banner.default.yml
  config/sync/core.entity_view_display.node.promo_banner.default.yml
  config/sync/core.entity_view_display.node.promo_banner.teaser.yml
  config/sync/field.field.node.banner.field_alert_type.yml
  config/sync/field.field.node.promo_banner.field_administration.yml
  config/sync/field.field.node.promo_banner.field_link.yml
  config/sync/field.field.node.promo_banner.field_promo_type.yml
  config/sync/field.field.node.promo_banner.field_target_paths.yml
  config/sync/field.storage.node.field_promo_type.yml
  config/sync/node.type.banner.yml
  config/sync/node.type.promo_banner.yml
  config/sync/node_link_report.settings.yml
  config/sync/pathauto.pattern.promo_banner.yml
  config/sync/user.role.content_admin.yml
  config/sync/user.role.content_editor.yml
  config/sync/user.role.content_publisher.yml
  config/sync/user.role.content_reviewer.yml
  config/sync/workflows.workflow.editorial.yml
  docroot/modules/custom/va_gov_banner/src/EventSubscriber/EntityEventSubscriber.php
  tests/behat/drupal-spec-tool/content_model_alerts_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_bundles.feature
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Sitewide CMS Team, Needs PO review

#7045 VACMS-6449 Official and Common name field treatments on VC's
  config/sync/core.base_field_override.node.vet_center.title.yml
  config/sync/core.entity_form_display.node.vet_center.default.yml
  config/sync/field.field.node.vet_center.field_official_name.yml
  config/sync/node.type.vet_center.yml
  config/sync/node_link_report.settings.yml
  docroot/modules/custom/va_gov_backend/config/schema/va_gov_backend.schema.yml
  docroot/modules/custom/va_gov_backend/css/css_tooltip.css
  docroot/modules/custom/va_gov_backend/images/questionmark-disc-000000.svg
  docroot/modules/custom/va_gov_backend/src/Plugin/Field/FieldWidget/TooltipTextFieldFormatter.php
  docroot/modules/custom/va_gov_backend/va_gov_backend.services.yml
  docroot/modules/custom/va_gov_consumers/css/textfield_tooltip.css
  docroot/modules/custom/va_gov_consumers/va_gov_consumers.info.yml
  docroot/modules/custom/va_gov_consumers/va_gov_consumers.libraries.yml
  docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
  docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.services.yml
  docroot/themes/custom/vagovadmin/assets/css/proofing.css.map
  docroot/themes/custom/vagovadmin/assets/css/styles.css
  docroot/themes/custom/vagovadmin/assets/css/styles.css.map
  docroot/themes/custom/vagovadmin/assets/scss/styles.scss
  tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature
Labels: Sitewide CMS Team

#6985 VACMS-6639: autogenerate required service nodes for all vet centers
  docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_vet_center/src/Plugin/QueueWorker/CronRequiredService.php
  docroot/modules/custom/va_gov_vet_center/src/Plugin/QueueWorker/RequiredServiceBase.php
  docroot/modules/custom/va_gov_vet_center/src/Service/RequiredServices.php
  docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.module
  docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.services.yml
Labels: Sitewide CMS Team

#7122 VACMS-5492 - disable event cost field and update default value to free
  config/sync/core.entity_form_display.node.event.default.yml
  config/sync/field.field.node.event.field_event_cost.yml
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
Labels: Sitewide CMS Team

#7065 VACMS-6640: Show what Vet Center services are required in Vet Center form and prevent removal.
  config/sync/user.role.content_creator_vet_center.yml
  docroot/modules/custom/va_gov_vet_center/js/prevent_select_duplicates.es6.js
  docroot/modules/custom/va_gov_vet_center/js/prevent_select_duplicates.js
  docroot/modules/custom/va_gov_vet_center/js/set_ief_service_selects.es6.js
  docroot/modules/custom/va_gov_vet_center/js/set_ief_service_selects.js
  docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.services.yml
  docroot/themes/custom/vagovadmin/assets/css/styles.css
  docroot/themes/custom/vagovadmin/assets/css/styles.css.map
  docroot/themes/custom/vagovadmin/assets/scss/styles.scss
  docroot/themes/custom/vagovadmin/vagovadmin.theme
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Sitewide CMS Team, high priority

#7138 VACMS-6896 connect with us field
  config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_form_display.node.landing_page.default.yml
  config/sync/core.entity_form_display.taxonomy_term.administration.default.yml
  tests/behat/drupal-spec-tool/content_model_benefits_hubs_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_campaign_landing_page_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature
Labels: Sitewide CMS Team

#6468 VACMS-6417: Update email instance links.
  config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_form_display.node.vet_center.default.yml
  config/sync/core.entity_form_display.node.vet_center_mobile_vet_center.default.yml
  config/sync/core.entity_form_display.node.vet_center_outstation.default.yml
Labels: Sitewide CMS Team

#7139 VACMS-7119: Fix broken standalone page toggle handling on submission.
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Sitewide CMS Team

#7172 VACMS-7171: Disallow non admins vast data editing ability.
  docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
Labels: Sitewide CMS Team

#7178 VACMS-7073 help text placement in claro
  composer.json
  docroot/themes/custom/vagovclaro/vagovclaro.theme
Labels: Sitewide CMS Team

#7155 VACMS-7154 Expand url audit view.
  config/sync/views.view.content.yml
  config/sync/views.view.detail_page_url_audit_and_bulk_udpate.yml
Labels: vsa-facilities, Sitewide CMS Team

#7226 VACMS-0000: Patch claro + core css build to enable css vars support
  composer.json
  patches/claro-css-tweaks.patch
Labels: Design system, Drupal theming

#7248 VACMS-7230: Fix faulty facility help link.
  config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
Labels: Sitewide CMS Team

#7249 VACMS-000: updated vscode config for ddev.
  .vscode/launch.json
Labels: Platform CMS Team, Sitewide CMS Team

#7037 VACMS-6873: show related non-clinical services on top task edit forms…
  composer.json
  composer.lock
  config/sync/core.entity_form_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_form_display.node.vamc_system_medical_records_offi.default.yml
  config/sync/core.entity_form_display.node.vamc_system_register_for_care.default.yml
  config/sync/core.entity_view_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_view_display.node.vamc_system_billing_insurance.teaser.yml
  config/sync/core.entity_view_display.node.vamc_system_medical_records_offi.default.yml
  config/sync/core.entity_view_display.node.vamc_system_medical_records_offi.teaser.yml
  config/sync/core.entity_view_display.node.vamc_system_register_for_care.default.yml
  config/sync/core.entity_view_display.node.vamc_system_register_for_care.teaser.yml
  config/sync/core.extension.yml
  config/sync/field.field.node.vamc_system_billing_insurance.field_non_clinical_services.yml
  config/sync/field.field.node.vamc_system_medical_records_offi.field_non_clinical_services.yml
  config/sync/field.field.node.vamc_system_register_for_care.field_non_clinical_services.yml
  config/sync/field.storage.node.field_non_clinical_services.yml
  config/sync/views.view.non_clinical_services.yml
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
Labels: Sitewide CMS Team

#7164 VACMS-7146: Make tooltips screenreader accessible.
  docroot/modules/custom/va_gov_backend/css/css_tooltip.css
  docroot/modules/custom/va_gov_backend/src/Plugin/Field/FieldWidget/TooltipTextFieldFormatter.php
Labels: Sitewide CMS Team

#7173 VACMS-7145: Prevent closure of all ief forms on cancel.
  composer.json
Labels: Sitewide CMS Team

#7264 VACMS-7076 set up design tokens
  docroot/themes/custom/vagovclaro/README.md
  docroot/themes/custom/vagovclaro/assets/css/styles.css
  docroot/themes/custom/vagovclaro/assets/css/styles.css.map
  docroot/themes/custom/vagovclaro/assets/scss/_buttons.scss
  docroot/themes/custom/vagovclaro/assets/scss/_elements.scss
  docroot/themes/custom/vagovclaro/assets/scss/_layout.scss
  docroot/themes/custom/vagovclaro/assets/scss/_login-page.scss
  docroot/themes/custom/vagovclaro/assets/scss/_variables.scss
  docroot/themes/custom/vagovclaro/assets/scss/styles.scss
  docroot/themes/custom/vagovclaro/templates/layout/html.html.twig
Labels: Sitewide CMS Team

#7243 VACMS-7210 & VACMS-7217: Implement improved help text and fix help text duplication bug on service ief's
  config/sync/core.entity_form_display.node.vet_center_facility_health_servi.default.yml
  config/sync/core.entity_form_display.node.vet_center_facility_health_servi.inline_entity_form.yml
  config/sync/field.field.node.vet_center_facility_health_servi.field_body.yml
  config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_vet_center_service_descrip.yml
  config/sync/node_link_report.settings.yml
  docroot/modules/custom/va_gov_backend/css/health_service.css
  docroot/modules/custom/va_gov_backend/js/displayServiceDescriptions.es6.js
  docroot/modules/custom/va_gov_backend/js/displayServiceDescriptions.js
  docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  docroot/modules/custom/va_gov_backend/va_gov_backend.services.yml
  docroot/themes/custom/vagovadmin/templates/form/form-element--textarea.html.twig
Labels: Sitewide CMS Team

#7304 VACMS-7068 claro login page
  docroot/themes/custom/vagovclaro/assets/css/styles.css
  docroot/themes/custom/vagovclaro/assets/css/styles.css.map
  docroot/themes/custom/vagovclaro/assets/scss/_alerts.scss
  docroot/themes/custom/vagovclaro/assets/scss/_layout.scss
  docroot/themes/custom/vagovclaro/assets/scss/_login-page.scss
  docroot/themes/custom/vagovclaro/images/sc.jpg
  docroot/themes/custom/vagovclaro/templates/form/form-element--textarea.html.twig
  docroot/themes/custom/vagovclaro/templates/page/page--user--login.html.twig
  docroot/themes/custom/vagovclaro/vagovclaro.theme
Labels: Sitewide CMS Team

#7300 VACMS-7299 Removed skipped links from node link report.
  config/sync/node_link_report.settings.yml
Labels: Sitewide CMS Team

#7292 VACMS-6874: prepopulate entity reference fields on nonclinical service form when context is known
  composer.json
  composer.lock
  config/sync/core.entity_view_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_view_display.node.vamc_system_medical_records_offi.default.yml
  config/sync/core.entity_view_display.node.vamc_system_register_for_care.default.yml
  config/sync/core.extension.yml
  config/sync/field.field.node.vamc_system_billing_insurance.field_non_clinical_services.yml
  config/sync/field.field.node.vamc_system_medical_records_offi.field_non_clinical_services.yml
  config/sync/field.field.node.vamc_system_register_for_care.field_non_clinical_services.yml
  config/sync/field.field.node.vha_facility_nonclinical_service.field_administration.yml
  config/sync/field.field.node.vha_facility_nonclinical_service.field_service_name_and_descripti.yml
  config/sync/node_link_report.settings.yml
  config/sync/views.view.non_clinical_services.yml
Labels: Sitewide CMS Team

#7317 VACMS-7022 organize theme file structure
  docroot/themes/custom/vagovclaro/assets/css/proofing.css.map
  docroot/themes/custom/vagovclaro/assets/css/styles.css.map
  docroot/themes/custom/vagovclaro/assets/css/user_guides.css.map
  docroot/themes/custom/vagovclaro/assets/css/wysiwyg.css.map
  docroot/themes/custom/vagovclaro/assets/scss/components/_alerts.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_buttons.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_centralized_content.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_elements.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_external_content.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_layout.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_media.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_paragraphs.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_process_list.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_services.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_toolbar.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_tooltip.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_undo_field_styling.scss
  docroot/themes/custom/vagovclaro/assets/scss/pages/_kb-pages.scss
  docroot/themes/custom/vagovclaro/assets/scss/pages/_login-page.scss
  docroot/themes/custom/vagovclaro/assets/scss/proofing.scss
  docroot/themes/custom/vagovclaro/assets/scss/styles.scss
  docroot/themes/custom/vagovclaro/assets/scss/tokens/_mixins.scss
  docroot/themes/custom/vagovclaro/assets/scss/tokens/_variables.scss
  docroot/themes/custom/vagovclaro/assets/scss/user_guides.scss
  docroot/themes/custom/vagovclaro/assets/scss/wysiwyg.scss
  docroot/themes/custom/vagovclaro/templates/admin/menu--toolbar.html.twig
  docroot/themes/custom/vagovclaro/templates/block/big-pipe-interface-preview--block--node-link-report.html.twig
  docroot/themes/custom/vagovclaro/templates/field/field--field-text-expander.html.twig
  docroot/themes/custom/vagovclaro/templates/field/field--node--field-description.html.twig
  docroot/themes/custom/vagovclaro/templates/field/field--node--field-intro-text.html.twig
  docroot/themes/custom/vagovclaro/templates/field/field--node--field-meta-title.html.twig
  docroot/themes/custom/vagovclaro/templates/field/field--node--field-related-user-guides.html.twig
  docroot/themes/custom/vagovclaro/templates/field/field--node--page.html.twig
  docroot/themes/custom/vagovclaro/templates/form/fieldset.html.twig
  docroot/themes/custom/vagovclaro/templates/layout/taxonomy-term.html.twig
  docroot/themes/custom/vagovclaro/templates/node/node--documentation_page.html.twig
  docroot/themes/custom/vagovclaro/templates/node/node--external-content.html.twig
  docroot/themes/custom/vagovclaro/templates/node/node--full.html.twig
  docroot/themes/custom/vagovclaro/templates/node/node--health_care_local_health_service--teaser.html.twig
  docroot/themes/custom/vagovclaro/templates/node/node--landing-page--support-services-listing.html.twig
  docroot/themes/custom/vagovclaro/templates/node/node--landing-page--teaser.html.twig
  docroot/themes/custom/vagovclaro/templates/node/node--page.html.twig
  docroot/themes/custom/vagovclaro/templates/node/node--regional_health_care_service_des--teaser.html.twig
  docroot/themes/custom/vagovclaro/templates/node/node--support-service--support-services-listing.html.twig
  docroot/themes/custom/vagovclaro/templates/node/node--va-form--full.html.twig
  docroot/themes/custom/vagovclaro/templates/node/node--va_form--external-content.html.twig
  docroot/themes/custom/vagovclaro/templates/node/node-edit-form.html.twig
  docroot/themes/custom/vagovclaro/templates/page/page--help--search.html.twig
  docroot/themes/custom/vagovclaro/templates/page/page--node.html.twig
Labels: Sitewide CMS Team

#7356 VACMS-7340 Make toptask deduper fire on node publish.
  docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_vamc/src/Service/ContentHardeningDeduper.php
Labels: Sitewide CMS Team

#7354 VACMS-7022 refactor old theme code
  READMES/local.md
  docroot/themes/custom/vagovclaro/README.md
  docroot/themes/custom/vagovclaro/assets/css/proofing.css
  docroot/themes/custom/vagovclaro/assets/css/proofing.css.map
  docroot/themes/custom/vagovclaro/assets/css/styles.css
  docroot/themes/custom/vagovclaro/assets/css/styles.css.map
  docroot/themes/custom/vagovclaro/assets/css/user_guides.css
  docroot/themes/custom/vagovclaro/assets/css/user_guides.css.map
  docroot/themes/custom/vagovclaro/assets/css/whats_new.css.map
  docroot/themes/custom/vagovclaro/assets/css/wysiwyg.css.map
  docroot/themes/custom/vagovclaro/assets/scss/components/_alerts.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_buttons.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_centralized_content.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_elements.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_external_content.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_fields.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_media.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_process_list.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_services.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_toolbar.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_tooltip.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_undo_field_styling.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_views.scss
  docroot/themes/custom/vagovclaro/assets/scss/pages/_kb-pages.scss
  docroot/themes/custom/vagovclaro/assets/scss/pages/_node-view.scss
  docroot/themes/custom/vagovclaro/assets/scss/proofing.scss
  docroot/themes/custom/vagovclaro/assets/scss/styles.scss
  docroot/themes/custom/vagovclaro/assets/scss/tokens/_variables.scss
  docroot/themes/custom/vagovclaro/assets/scss/user_guides.scss
  docroot/themes/custom/vagovclaro/assets/scss/whats_new.scss
  docroot/themes/custom/vagovclaro/assets/scss/wysiwyg.scss
  docroot/themes/custom/vagovclaro/templates/block/node-link-report-block.html.twig
Labels: Sitewide CMS Team

#7374 VACMS-7373: Remove save and continue from edit form for temp fix.
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Sitewide CMS Team

#7332 VACMS-2043: Remove deprecated fields for Connect with us
  config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_form_display.taxonomy_term.administration.default.yml
  config/sync/core.entity_view_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_view_display.node.campaign_landing_page.teaser.yml
  config/sync/core.entity_view_display.taxonomy_term.administration.default.yml
  config/sync/core.entity_view_display.taxonomy_term.administration.full.yml
  config/sync/core.entity_view_display.taxonomy_term.administration.vet_center_dashboard.yml
  config/sync/field.field.node.campaign_landing_page.field_clp_connect_with_us.yml
  config/sync/field.field.node.campaign_landing_page.field_related_office.yml
  config/sync/field.field.node.landing_page.field_related_office.yml
  config/sync/field.field.taxonomy_term.administration.field_email_updates_link_text.yml
  config/sync/field.field.taxonomy_term.administration.field_email_updates_url.yml
  config/sync/field.field.taxonomy_term.administration.field_link.yml
  config/sync/field.field.taxonomy_term.administration.field_social_media_links.yml
  config/sync/field.storage.node.field_clp_connect_with_us.yml
  config/sync/field.storage.taxonomy_term.field_email_updates_link_text.yml
  config/sync/field.storage.taxonomy_term.field_email_updates_url.yml
  config/sync/field.storage.taxonomy_term.field_link.yml
  config/sync/field.storage.taxonomy_term.field_social_media_links.yml
  config/sync/views.view.content_entity_reference_source.yml
  tests/behat/drupal-spec-tool/content_model_benefits_hubs_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_campaign_landing_page_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature
  tests/behat/drupal-spec-tool/views.feature
Labels: Sitewide CMS Team

#7417 VACMS-7408 claro dropbuttons
  docroot/themes/custom/vagovclaro/assets/css/styles.css
  docroot/themes/custom/vagovclaro/assets/css/styles.css.map
  docroot/themes/custom/vagovclaro/assets/scss/components/_elements.scss
  docroot/themes/custom/vagovclaro/vagovclaro.info.yml
Labels: Sitewide CMS Team

#7383 VACMS-1269 homepage improvements
  docroot/themes/custom/vagovclaro/assets/css/styles.css
  docroot/themes/custom/vagovclaro/assets/css/styles.css.map
  docroot/themes/custom/vagovclaro/assets/js/login-toggle.js
  docroot/themes/custom/vagovclaro/assets/scss/components/_footer.scss
  docroot/themes/custom/vagovclaro/assets/scss/pages/_login-page.scss
  docroot/themes/custom/vagovclaro/assets/scss/styles.scss
  docroot/themes/custom/vagovclaro/images/icons/cms-pencil.svg
  docroot/themes/custom/vagovclaro/images/va-logo-white.png
  docroot/themes/custom/vagovclaro/templates/layout/footer.html.twig
  docroot/themes/custom/vagovclaro/templates/page/page--user--login.html.twig
  docroot/themes/custom/vagovclaro/vagovclaro.libraries.yml
  docroot/themes/custom/vagovclaro/vagovclaro.theme
Labels: Sitewide CMS Team

#7369 VACMS-7258 menu link content access check
  composer.json
  config/sync/user.role.content_api_consumer.yml
  docroot/modules/custom/va_gov_graphql/src/Access/MenuLinkContentAccessHandler.php
  docroot/modules/custom/va_gov_graphql/va_gov_graphql.module
  docroot/modules/custom/va_gov_graphql/va_gov_graphql.permissions.yml
  patches/drupal-core-menu-link-perm-mr-339.patch
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Platform CMS Team, Sitewide CMS Team

#7368 VACMS-5372 add favicon
  config/sync/environment_indicator.settings.yml
  config/sync/system.theme.global.yml
  docroot/themes/custom/vagovclaro/assets/css/styles.css
  docroot/themes/custom/vagovclaro/assets/css/styles.css.map
  docroot/themes/custom/vagovclaro/assets/scss/components/_toolbar.scss
  docroot/themes/custom/vagovclaro/favicon.ico
  docroot/themes/custom/vagovclaro/images/toolbar-logo.png
  docroot/themes/custom/vagovclaro/logo.svg
  docroot/themes/custom/vagovclaro/screenshot.png
  docroot/themes/custom/vagovclaro/vagovclaro.info.yml
  docroot/themes/custom/vagovclaro/vagovclaro.settings.yml
Labels: Sitewide CMS Team
