Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2021-11, with the labels that each got.

#6850 VACMS-6341: Update service type of care.
  config/sync/field.storage.taxonomy_term.field_service_type_of_care.yml
Labels: Sitewide CMS Team

#6866 VACMS-6341: Top task content types.
  config/sync/auto_entitylabel.settings.node.vha_facility_nonclinical_service.yml
  config/sync/core.base_field_override.node.vamc_system_medical_records_offi.title.yml
  config/sync/core.base_field_override.node.vha_facility_nonclinical_service.promote.yml
  config/sync/core.base_field_override.node.vha_facility_nonclinical_service.status.yml
  config/sync/core.entity_form_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_form_display.node.vamc_system_medical_records_offi.default.yml
  config/sync/core.entity_form_display.node.vamc_system_register_for_care.default.yml
  config/sync/core.entity_form_display.node.vha_facility_nonclinical_service.default.yml
  config/sync/core.entity_form_display.paragraph.react_widget.default.yml
  config/sync/core.entity_form_display.paragraph.service_location.default.yml
  config/sync/core.entity_form_display.taxonomy_term.health_care_service_taxonomy.default.yml
  config/sync/core.entity_view_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_view_display.node.vamc_system_billing_insurance.teaser.yml
  config/sync/core.entity_view_display.node.vamc_system_medical_records_offi.default.yml
  config/sync/core.entity_view_display.node.vamc_system_medical_records_offi.teaser.yml
  config/sync/core.entity_view_display.node.vamc_system_register_for_care.default.yml
  config/sync/core.entity_view_display.node.vamc_system_register_for_care.teaser.yml
  config/sync/core.entity_view_display.node.vet_center_locations_list.default.yml
  config/sync/core.entity_view_display.node.vha_facility_nonclinical_service.default.yml
  config/sync/core.entity_view_display.node.vha_facility_nonclinical_service.teaser.yml
  config/sync/core.entity_view_display.paragraph.react_widget.default.yml
  config/sync/core.entity_view_display.paragraph.service_location.default.yml
  config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.default.yml
  config/sync/field.field.node.vamc_system_billing_insurance.field_hours_for_copay_inquiries_.yml
  config/sync/field.field.node.vamc_system_billing_insurance.field_phone_number.yml
  config/sync/field.field.node.vamc_system_billing_insurance.field_service_name_and_descripti.yml
  config/sync/field.field.node.vamc_system_medical_records_offi.field_fax_number.yml
  config/sync/field.field.node.vamc_system_medical_records_offi.field_service_name_and_descripti.yml
  config/sync/field.field.node.vamc_system_medical_records_offi.field_vamc_med_records_mailing.yml
  config/sync/field.field.node.vamc_system_register_for_care.field_service_name_and_descripti.yml
  config/sync/field.field.node.vha_facility_nonclinical_service.field_administration.yml
  config/sync/field.field.node.vha_facility_nonclinical_service.field_facility_location.yml
  config/sync/field.field.node.vha_facility_nonclinical_service.field_service_location.yml
  config/sync/field.field.node.vha_facility_nonclinical_service.field_service_name_and_descripti.yml
  config/sync/field.field.paragraph.service_location_address.field_clinic_name.yml
  config/sync/field.storage.node.field_fax_number.yml
  config/sync/field.storage.node.field_hours_for_copay_inquiries_.yml
  config/sync/field.storage.node.field_vamc_med_records_mailing.yml
  config/sync/node.type.vha_facility_nonclinical_service.yml
  config/sync/views.view.health_care_service_names_and_descriptions.yml
  config/sync/views.view.non_clinical_services.yml
  tests/behat/drupal-spec-tool/content_model_bundles.feature
  tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
  tests/behat/drupal-spec-tool/views.feature
Labels: Sitewide CMS Team, DO NOT MERGE

#6813 VACMS-6812 Create audit tool for rich text fields
  config/sync/views.view.rich_text_field_audit.yml
  tests/behat/drupal-spec-tool/views.feature
Labels: Sitewide CMS Team

#6884 VACMS-6536: Show nationally standardized Services content in Vet Center and VAMC services forms.
  config/sync/core.entity_form_display.node.regional_health_care_service_des.default.yml
  config/sync/core.entity_form_display.node.vet_center_facility_health_servi.inline_entity_form.yml
  config/sync/field.field.node.regional_health_care_service_des.field_body.yml
  config/sync/field.field.node.regional_health_care_service_des.field_service_name_and_descripti.yml
  config/sync/field.field.node.vet_center.field_health_services.yml
  config/sync/field.field.node.vet_center_facility_health_servi.field_body.yml
  config/sync/field.field.node.vet_center_facility_health_servi.field_service_name_and_descripti.yml
  config/sync/node.type.regional_health_care_service_des.yml
  docroot/modules/custom/va_gov_backend/css/css_tooltip.css
  docroot/modules/custom/va_gov_backend/css/health_service.css
  docroot/modules/custom/va_gov_backend/js/displayServiceDescriptions.es6.js
  docroot/modules/custom/va_gov_backend/js/displayServiceDescriptions.js
  docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_backend/va_gov_backend.libraries.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.services.yml
  docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
  docroot/themes/custom/vagovadmin/assets/css/proofing.css.map
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature
Labels: Sitewide CMS Team

#6740 VACMS-6354: "Release content" button should work with GH actions on BRD environments as appropriate
  composer.json
  composer.lock
  docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentDiscovery.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRDGHA.php
  docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.info.yml
  docroot/modules/custom/va_gov_consumers/src/Git/GithubAdapter.php
  docroot/modules/custom/va_gov_consumers/src/Git/GithubFactory.php
  docroot/modules/custom/va_gov_consumers/src/Git/GithubInterface.php
  docroot/modules/custom/va_gov_consumers/va_gov_consumers.services.yml
  docroot/sites/default/settings/settings.dev.php
  docroot/sites/default/settings/settings.staging.php
  phpstan-baseline.neon
Labels: Platform CMS Team

#6904 VACMS-6809: add service filter and field to VAMC System Health Servic…
  config/sync/views.view.content.yml
Labels: Sitewide CMS Team

#6902 VACMS-6536: Update VAMC health service body help text.
  config/sync/field.field.node.regional_health_care_service_des.field_body.yml
Labels: Sitewide CMS Team

#6782 VACMS-6749 Update VHA Taxonomy Dashboard
  config/sync/views.view.vha_health_service_taxonomy.yml
Labels: Sitewide CMS Team

#6911 [DOCS] Add GovDelivery documentation.
  READMES/vamc-facilities.md
Labels: vsa-facilities, Unplanned work, documentation, Sitewide CMS Team

#6744 VACMS-6445: Make product field required.
  composer.json
  config/sync/field.field.node.documentation_page.field_products.yml
  tests/behat/drupal-spec-tool/content_model_user_guides_content_type_fields.feature
Labels: Sitewide CMS Team

#6906 VACMS-6844: Change Production manual content release to use Github Actions
  docroot/sites/default/settings/settings.prod.php
Labels: Platform CMS Team

#6851 VACMS-6630: Move any Vet Center specific logic from va_gov_backend to va_gov_vet_center
  docroot/modules/custom/va_gov_backend/js/script.es6.js
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  docroot/modules/custom/va_gov_backend/va_gov_backend.services.yml
  docroot/modules/custom/va_gov_vet_center/js/script.es6.js
  docroot/modules/custom/va_gov_vet_center/js/script.js
  docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.libraries.yml
  docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.module
Labels: Vet Center, Sitewide CMS Team

#6959 VACMS-6958: remove endpoints for VAMCs going to prod week of Nov 8 2021
  config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml
Labels: Sitewide CMS Team

#6889 VACMS-6456: script to remove leading care we provide h3 tags from VAM…
  scripts/content/VACMS-6456-remove-leading-care-we-provide-h3-tags.php
Labels: Sitewide CMS Team, DO NOT MERGE

#6776 VACMS-6700: Disable title editing for non admins and remove descriptions
  config/sync/node.type.event_listing.yml
  config/sync/node.type.health_services_listing.yml
  config/sync/node.type.leadership_listing.yml
  config/sync/node.type.locations_listing.yml
  config/sync/node.type.office.yml
  config/sync/node.type.press_releases_listing.yml
  config/sync/node.type.publication_listing.yml
  config/sync/node.type.story_listing.yml
  docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
Labels: Sitewide CMS Team

#6953 VACMS-6771: update migration CSV files to include data for Lovell
  docroot/modules/custom/va_gov_migrate/data/facility_health_care_service_final_6visns.csv
  docroot/modules/custom/va_gov_migrate/data/lovell-facility-services.csv
  docroot/modules/custom/va_gov_migrate/data/lovell-system-services.csv
  docroot/modules/custom/va_gov_migrate/data/regional-health-care-service-keyed-3.csv
Labels: Sitewide CMS Team

#6783 VACMS-5439: Update cta config and remove legacy validation code.
  composer.json
  composer.lock
  config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_form_display.node.checklist.default.yml
  config/sync/core.entity_form_display.node.faq_multiple_q_a.default.yml
  config/sync/core.entity_form_display.node.media_list_images.default.yml
  config/sync/core.entity_form_display.node.media_list_videos.default.yml
  config/sync/core.entity_form_display.node.q_a.default.yml
  config/sync/core.entity_form_display.node.step_by_step.default.yml
  config/sync/core.entity_form_display.node.support_resources_detail_page.default.yml
  config/sync/core.extension.yml
  config/sync/field.field.node.checklist.field_buttons.yml
  config/sync/field.field.node.faq_multiple_q_a.field_buttons.yml
  config/sync/field.field.node.media_list_images.field_buttons.yml
  config/sync/field.field.node.media_list_videos.field_buttons.yml
  config/sync/field.field.node.q_a.field_buttons.yml
  config/sync/field.field.node.step_by_step.field_buttons.yml
  config/sync/field.field.node.support_resources_detail_page.field_buttons.yml
  config/sync/field.field.paragraph.button.field_button_label.yml
  config/sync/field.field.paragraph.button.field_button_link.yml
  config/sync/paragraphs_features.settings.yml
  docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  tests/behat/drupal-spec-tool/content_model_lc_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature
  tests/behat/features/content_editing.feature
  tests/behat/features/save_and_continue.feature
  tests/behavioral/cypress/integration/common/i_create_a_node.js
Labels: Sitewide CMS Team

#6967 VACMS-6885 Claro admin theme proof of concept
  docroot/themes/custom/vagovclaro/assets/css/test.css
  docroot/themes/custom/vagovclaro/assets/css/wysiwyg.css
  docroot/themes/custom/vagovclaro/assets/js/anchor_links.es6.js
  docroot/themes/custom/vagovclaro/images/header-logo.png
  docroot/themes/custom/vagovclaro/logo.svg
  docroot/themes/custom/vagovclaro/templates/misc/status-messages.html.twig
  docroot/themes/custom/vagovclaro/templates/page/page--user--login.html.twig
  docroot/themes/custom/vagovclaro/vagovclaro.info.yml
  docroot/themes/custom/vagovclaro/vagovclaro.libraries.yml
  docroot/themes/custom/vagovclaro/vagovclaro.theme
Labels: Sitewide CMS Team

#6960 VACMS-6536: Make inline national taxonomy service descriptions visible on edit
  config/sync/field.field.node.vet_center.field_health_services.yml
  config/sync/field.field.node.vet_center_facility_health_servi.field_body.yml
  docroot/modules/custom/va_gov_backend/css/health_service.css
  docroot/modules/custom/va_gov_backend/js/displayServiceDescriptions.es6.js
  docroot/modules/custom/va_gov_backend/js/displayServiceDescriptions.js
  docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
  tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature
Labels: Sitewide CMS Team

#6986 VACMS-6942: Disable choices not in users workbench.
  docroot/modules/custom/va_gov_vamc/js/limit_vamcs_to_workbench.es6.js
  docroot/modules/custom/va_gov_vamc/js/limit_vamcs_to_workbench.js
  docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
Labels: Sitewide CMS Team

#6997 VACMS-6958C: remove endpoints for VAMCs going to prod week of Nov 15 2021
  config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml
Labels: Sitewide CMS Team

#6936 VACMS-5387: Add script to attach service location to health service nodes
  scripts/content/VACMS-5387-facility-services-add-service-location-2021-11.php
Labels: Sitewide CMS Team

#6903 VACMS-2041 - Update office content model with Connect with Us
  composer.json
  config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_form_display.node.landing_page.default.yml
  config/sync/core.entity_form_display.node.office.default.yml
  config/sync/core.entity_view_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_view_display.node.campaign_landing_page.teaser.yml
  config/sync/core.entity_view_display.node.landing_page.default.yml
  config/sync/core.entity_view_display.node.landing_page.support_services_listing.yml
  config/sync/core.entity_view_display.node.landing_page.teaser.yml
  config/sync/core.entity_view_display.node.office.default.yml
  config/sync/core.entity_view_display.node.office.teaser.yml
  config/sync/field.field.node.campaign_landing_page.field_related_office.yml
  config/sync/field.field.node.landing_page.field_related_office.yml
  config/sync/field.field.node.office.field_email_updates_link.yml
  config/sync/field.field.node.office.field_external_link.yml
  config/sync/field.field.node.office.field_social_media_links.yml
  config/sync/field.storage.node.field_email_updates_link.yml
  config/sync/field.storage.node.field_external_link.yml
  config/sync/field.storage.node.field_related_office.yml
  config/sync/field.storage.node.field_social_media_links.yml
  docroot/themes/custom/vagovadmin/assets/js/anchor_links.es6.js
  docroot/themes/custom/vagovadmin/assets/js/anchor_links.js
  tests/behat/drupal-spec-tool/content_model_benefits_hubs_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_campaign_landing_page_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_outreach_hub_content_type_fields.feature
  tests/behavioral/cypress/integration/common/i_click_the_vertical_tab.js
  tests/behavioral/cypress/integration/google_tag_manager.feature
Labels: Sitewide CMS Team

#7028 VAMCS-5167: Date should be required on event nodes.
  composer.json
  config/sync/field.field.node.event.field_datetime_range_timezone.yml
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
Labels: Sitewide CMS Team

#6928 VACMS-6629: Moving vamc logic from va gov backend module file to vamc…
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  docroot/modules/custom/va_gov_vamc/va_gov_vamc.module
Labels: Sitewide CMS Team

#6974 VACMS-6875: Apply winnower to VAMC Facility Non-clinical Service.
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Sitewide CMS Team
