Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2021-07, with the labels that each got.

#5760 VACMS-5739: Set vamc and vc terms to 0 in hook and in subsequnt saves.
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  docroot/modules/custom/va_gov_db/va_gov_db.install
Labels: Product Support Team

#5765 VACMS-5764: Restore moderation widget on op status form.
  config/sync/core.entity_form_display.node.vamc_operating_status_and_alerts.default.yml
Labels: Product Support Team

#5752 VACMS-5086: Add redirect on login for one section users.
  docroot/modules/custom/va_gov_user/va_gov_user.module
Labels: Product Support Team

#5749 VACMS-5696: Remove erie, eastern OK, and lebanon facility status endpoints.
  config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml
Labels: DO NOT MERGE, Product Support Team

#5758 Sets tooltip button type to "button".
  docroot/modules/custom/va_gov_backend/src/Plugin/field_group/FieldGroupFormatter/Tooltip.php
Labels: Core Application Team

#5780 VACMS-000: Remove VAMC Detail page from alias unlock array.
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Product Support Team

#5667 VACMS 1948: Upgrade to Drupal 9.1.x
  .gitignore
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/field.storage.node.field_office_hours.yml
  config/sync/rest.settings.yml
  config/sync/serialization.settings.yml
  config/sync/views.view.glossary.yml
  docroot/modules/custom/va_gov_backend/css/tippy_popover_theme.css
  docroot/modules/custom/va_gov_backend/js/field_group_tooltip.es6.js
  docroot/modules/custom/va_gov_backend/js/field_group_tooltip.js
  docroot/modules/custom/va_gov_backend/js/toolbar.es6.js
  docroot/modules/custom/va_gov_backend/js/toolbar.js
  docroot/modules/custom/va_gov_workflow_assignments/src/Plugin/Block/EntityMetaDisplay.php
  docroot/robots.txt
  docroot/sites/default/default.services.yml
  docroot/sites/default/default.settings.php
  docroot/sites/default/settings.php
  docroot/themes/custom/vagovadmin/templates/layout/html.html.twig
  docroot/update.php
  scripts/queue_runner/queue_runner.sh
  tests/behat/Drupal/FeatureContext.php
  tests/behat/features/content_editing.feature
  tests/behat/features/decoupled.feature
  tests/behavioral/cypress/integration/common/i_create_a_node.js
  tests/phpunit/Content/DownloadableFileTest.php
  tests/phpunit/Security/AdminDashboardTest.php
  tests/traits/GroupTrait.php
Labels: Core Application Team, DevOps, Drupal engineering, Product Support Team

#5794 VACMS-0000: Changes KernelTests to ExistingSiteBase tests.
  tests/phpunit/FrontendBuild/Brd/BrdEnvironmentTest.php
  tests/phpunit/FrontendBuild/Brd/BuildTimeRecorderTest.php
  tests/phpunit/FrontendBuild/Brd/JenkinsClientTest.php
  tests/phpunit/FrontendBuild/Brd/SystemsManagerClientTest.php
Labels: Core Application Team

#5690 [Merge for July 13 deploy] VACMS-5669: Update URL patterns for Leadership Listing nodes.
  config/sync/pathauto.pattern.health_care_region_detail_page.yml
  config/sync/pathauto.pattern.leadership_listing.yml
  docroot/modules/custom/va_gov_db/va_gov_db.install
Labels: DO NOT MERGE, Product Support Team

#5829 VACMS-5776: Add char count to featured content paragraphs.
  config/sync/core.entity_form_display.paragraph.featured_content.default.yml
  tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature
Labels: Product Support Team

#5854 VACMS-5725: Add help page to menu based alias pattern.
  config/sync/pathauto.pattern.documentation.yml
  config/sync/pathauto.pattern.health_care_region_detail_page.yml
Labels: Product Support Team

#5833 VACMS-5785: Add confirm step to vbo.
  config/sync/views.view.content.yml
Labels: Product Support Team

#5786 VACMS-5774: Add vc facility listing block to node view and form.
  config/sync/core.entity_form_display.node.vet_center.default.yml
  config/sync/core.entity_form_display.node.vet_center_locations_list.default.yml
  config/sync/field.field.node.vet_center_locations_list.field_nearby_mobile_vet_centers.yml
  config/sync/views.view.vet_center_facility_listing.yml
  docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.module
  tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature
  tests/behat/drupal-spec-tool/views.feature
Labels: Product Support Team

#5852 VACMS-5744: Repair incorrectly-cloned nodes.
  scripts/content/vacms-5744/library.php
  scripts/content/vacms-5744/print_report.php
  scripts/content/vacms-5744/repair_all_nodes.php
  scripts/content/vacms-5744/repair_single_node.php
  scripts/content/vacms-5744/serialize_single_node.php
Labels: Core Application Team

#5853 VACMS-5713 - turn on animated gifs
  composer.json
  composer.lock
  config/sync/core.extension.yml
Labels: Product Support Team

#5787 VACMS-5784: Remove weight set on VISN titles items.
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Product Support Team

#5468 VACMS-4932: Add VAMC menu block to VAMC node view (proofing) pages.
  config/sync/block.block.burialsandmemorialsbenefitshub.yml
  config/sync/block.block.careersemploymentbenefitshub.yml
  config/sync/block.block.disabilitybenefitshub.yml
  config/sync/block.block.educationbenefitshub.yml
  config/sync/block.block.healthcarebenefitshub.yml
  config/sync/block.block.housingassistancebenefitshub.yml
  config/sync/block.block.lifeinsurancebenefitshub.yml
  config/sync/block.block.outreachandevents.yml
  config/sync/block.block.pensionbenefitshub.yml
  config/sync/block.block.recordsbenefitshub.yml
  config/sync/block.block.sidebarmenusblock.yml
  config/sync/block.block.vaaltoonahealthcare.yml
  config/sync/block.block.vabutlerhealthcare.yml
  config/sync/block.block.vacoatesvillehealthcare.yml
  config/sync/block.block.vaeriehealthcare.yml
  config/sync/block.block.vagovadmin_login.yml
  config/sync/block.block.valebanon.yml
  config/sync/block.block.vaphiladelphiahealthcare.yml
  config/sync/block.block.vapittsburghhealthcare.yml
  config/sync/block.block.vawilkesbarrehealthcare.yml
  config/sync/block.block.vawilmingtonhealthcare.yml
  config/sync/core.entity_form_display.node.regional_health_care_service_des.inline_entity_form.yml
  docroot/modules/custom/va_gov_backend/src/Plugin/Block/SidebarMenusBlock.php
Labels: IA, Product Support Team

#5859 VACMS-5848: Remove home crumb for Knowledge Base pages.
  config/sync/core.extension.yml
  docroot/modules/custom/va_gov_user_guide/va_gov_user_guide.info.yml
  docroot/modules/custom/va_gov_user_guide/va_gov_user_guide.module
Labels: Product Support Team

#5898 VACMS-5884 Allow vamc facility menu roots to show.
  config/sync/va_gov_menu_access.settings.yml
  docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
Labels: Product Support Team

#5831 VACMS-5781: Remove 4 visn endpoints on JULY 21.
  config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml
Labels: Product Support Team

#5897 VACMS-5873: Make user history more readable.
  config/sync/views.view.user_history.yml
Labels: Product Support Team

#5906 VACMS-5887: Adding workaround for core issue related to block lazy loading
  config/sync/block.block.sidebarmenusblock.yml
  docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
  docroot/themes/custom/vagovadmin/templates/layout/page--node.html.twig
Labels: Product Support Team

#5929 VACMS-5376: Creates a filter to populate node link attributes and trigger Linkit.
  config/sync/filter.format.rich_text.yml
  config/sync/filter.format.rich_text_limited.yml
  docroot/modules/custom/va_gov_backend/src/Plugin/Filter/NodeLinkEnforcementFilter.php
Labels: Core Application Team

#5904 [docs] Create SECURITY.md
  SECURITY.md
Labels: Core Application Team, Needs PO review, Product Support Team

#5940 VACMS-5921: Update metas to correct patterns.
  config/sync/auto_entitylabel.settings.node.vamc_operating_status_and_alerts.yml
  config/sync/metatag.metatag_defaults.node__campaign_landing_page.yml
  config/sync/metatag.metatag_defaults.node__health_care_local_facility.yml
  config/sync/metatag.metatag_defaults.node__health_care_region_page.yml
  config/sync/metatag.metatag_defaults.node__health_services_listing.yml
  config/sync/metatag.metatag_defaults.node__locations_listing.yml
  config/sync/metatag.metatag_defaults.node__outreach_asset.yml
  config/sync/metatag.metatag_defaults.node__press_releases_listing.yml
  config/sync/metatag.metatag_defaults.node__story_listing.yml
  config/sync/metatag.metatag_defaults.node__vamc_operating_status_and_alerts.yml
  config/sync/metatag.metatag_defaults.node__vamc_system_policies_page.yml
  config/sync/metatag.metatag_defaults.node__vet_center_locations_list.yml
Labels: Product Support Team

#5956 VACMS-5952: patch graphql to make the explorer work when layout_builder is enabled
  composer.json
  composer.lock
  patches/graphql_8x3x_layout_builder_incompat.patch
Labels: Core Application Team

#5955 VACMS-5878: Replace old email address with new.
  config/sync/system.site.yml
  config/sync/webform.webform.request_cms_user.yml
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRD.php
  docroot/modules/custom/va_gov_user/src/Plugin/Block/UserSections.php
Labels: Product Support Team

#5949 VACMS-5864: Correct vc tooltip text.
  config/sync/core.entity_form_display.node.vet_center.default.yml
  config/sync/core.entity_view_display.node.vet_center.default.yml
Labels: Product Support Team

#5939 Remove references to (soon to be) deprecated drupal_get_path
  docroot/modules/custom/va_gov_govdelivery/va_gov_govdelivery.module
  docroot/modules/custom/va_gov_migrate/va_gov_migrate.install
Labels: Core Application Team

#5832 VACMS-5781: Remove 5 visn endpoints on JULY 28. [merge July 26]
  config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml
Labels: Product Support Team, vsa-facilities

#5970 VACMS-5917: Create remaining vc location listings.
  docroot/modules/custom/va_gov_db/va_gov_db.install
Labels: Product Support Team

#5957 VACMS-5805: Replace user guides and help center verbiage with Knowledge Base.
  config/sync/core.entity_view_mode.media.user_guides.yml
  config/sync/paragraphs.paragraphs_type.lists_of_links.yml
  docroot/modules/custom/va_gov_help_center/va_gov_help_center.info.yml
  docroot/modules/custom/va_gov_help_center/va_gov_help_center.module
  docroot/modules/custom/va_gov_user_guide/va_gov_user_guide.info.yml
  docroot/modules/custom/va_gov_user_guide/va_gov_user_guide.module
  tests/behat/drupal-spec-tool/content_model_bundles.feature
Labels: Product Support Team

#5909 VACMS-5908: Test tasks should return an exit code on failure, depending on a flag.
  .lando.yml
  tests.yml
Labels: Core Application Team

#5915 VACMS-5888: Hide existing VC services from option list to prevent duplicates.
  docroot/modules/custom/va_gov_backend/js/script.es6.js
  docroot/modules/custom/va_gov_backend/js/script.js
  docroot/modules/custom/va_gov_vet_center/css/prevent_select_duplicates.css
  docroot/modules/custom/va_gov_vet_center/js/prevent_select_duplicates.es6.js
  docroot/modules/custom/va_gov_vet_center/js/prevent_select_duplicates.js
  docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.libraries.yml
  docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.module
Labels: Product Support Team

#5932 VACMS-5911: Add vamc custom module and op status ief banner auto governance
  config/sync/core.entity_form_display.node.full_width_banner_alert.inline_entity_form.yml
  config/sync/core.extension.yml
  docroot/modules/custom/va_gov_vamc/js/set_ief_administration_select.es6.js
  docroot/modules/custom/va_gov_vamc/js/set_ief_administration_select.js
  docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_vamc/va_gov_vamc.info.yml
  docroot/modules/custom/va_gov_vamc/va_gov_vamc.libraries.yml
  docroot/modules/custom/va_gov_vamc/va_gov_vamc.module
  docroot/modules/custom/va_gov_vamc/va_gov_vamc.services.yml
  tests/behat/features/content_editing.feature
Labels: Product Support Team

#5989 Make sure the logic to get the commit is correct
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Core Application Team

#5943 VACMS-5871 vamc health service migrations
  config/sync/migrate_plus.migration.facility_health_care_service_covid.yml
  config/sync/migrate_plus.migration.facility_health_care_service_final_6visns.yml
  config/sync/migrate_plus.migration.regional_health_care_service_covid.yml
  config/sync/migrate_plus.migration.regional_health_care_service_region_keyed_3.yml
  config/sync/migrate_plus.migration.va_node_facility_vet_centers_status.yml
  config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.facility_health_care_service_covid.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.facility_health_care_service_final_6visns.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.regional_health_care_service_covid.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.regional_health_care_service_region_keyed_3.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers_status.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_form.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml
  docroot/modules/custom/va_gov_migrate/data/facility_health_care_service_final_6visns.csv
  docroot/modules/custom/va_gov_migrate/data/lovell-facility-services.csv
  docroot/modules/custom/va_gov_migrate/data/lovell-system-services.csv
  docroot/modules/custom/va_gov_migrate/data/regional-health-care-service-keyed-3.csv
Labels: Migration, Product Support Team, VAMC system, vsa-facilities, vsa-vamc-upgrade
