Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2022-07, with the labels that each got.

#9604 VACMS-9591: Augment html_tag_usage filtering
  composer.json
Labels: ⭐️ Sitewide CMS

#9648 Migrate to FedRamped Datadog instance.
  .tugboat/config.yml
  READMES/downstream_dependencies.md
  READMES/upstream-dependencies.md
  docroot/modules/custom/va_gov_backend/src/Service/Datadog.php
Labels: DevOps, Platform CMS Team

#9565 VACMS-9560: Fix claro handling of non admin cc content.
  docroot/themes/custom/vagovclaro/assets/scss/components/_centralized_content.scss
Labels: ⭐️ Sitewide CMS

#9720 VACMS-9700: Patch smart_date for recurrence bug identified in d.o issue #3294350
  composer.json
  composer.lock
Labels: Drupal engineering, ⭐️ Public Websites, ⭐️ Sitewide CMS

#9710 VACMS-9696: Create phone number audit.
  config/sync/views.view.rich_text_field_audit.yml
  tests/behat/drupal-spec-tool/views.feature
Labels: ⭐️ Sitewide CMS

#9751 VACMS-9511 update maintenance page styles
  docroot/sites/default/maintenance.html
Labels: ⭐️ Sitewide CMS

#9736 VACMS-9637: add geocoder (lat/long) field to facilities
  config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_form_display.node.health_care_local_facility.inline_entity_form.yml
  config/sync/core.entity_form_display.node.nca_facility.default.yml
  config/sync/core.entity_form_display.node.vba_facility.default.yml
  config/sync/core.entity_form_display.node.vet_center.default.yml
  config/sync/core.entity_form_display.node.vet_center_outstation.default.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.external_content.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.ief_table.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.teaser.yml
  config/sync/core.entity_view_display.node.nca_facility.default.yml
  config/sync/core.entity_view_display.node.nca_facility.teaser.yml
  config/sync/core.entity_view_display.node.vba_facility.default.yml
  config/sync/core.entity_view_display.node.vba_facility.teaser.yml
  config/sync/core.entity_view_display.node.vet_center.default.yml
  config/sync/core.entity_view_display.node.vet_center.external_content.yml
  config/sync/core.entity_view_display.node.vet_center.ief_table.yml
  config/sync/core.entity_view_display.node.vet_center.teaser.yml
  config/sync/core.entity_view_display.node.vet_center_outstation.default.yml
  config/sync/core.entity_view_display.node.vet_center_outstation.external_content.yml
  config/sync/core.entity_view_display.node.vet_center_outstation.teaser.yml
  config/sync/field.field.node.health_care_local_facility.field_geolocation.yml
  config/sync/field.field.node.nca_facility.field_geolocation.yml
  config/sync/field.field.node.vba_facility.field_geolocation.yml
  config/sync/field.field.node.vet_center.field_geolocation.yml
  config/sync/field.field.node.vet_center_outstation.field_geolocation.yml
  config/sync/geocoder.geocoder_provider.mapbox.yml
  docroot/themes/custom/vagovclaro/assets/scss/components/_fields.scss
  tests/behat/drupal-spec-tool/content_model_nca_facility_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_vba_facility_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature
Labels: ⭐️ Facilities

#9873 VACMS-9872: core 9.3.19 update.
  composer.lock
Labels: Platform CMS Team, ⭐️ Sitewide CMS

#9877 Vacms 9872 cleanup
  .gitignore
  READMES/local.md
  docroot/sites/default/default.settings.php
  docroot/sites/default/settings/settings.local.php
  docroot/sites/development.services.yml
  docroot/sites/example.local.services.yml
Labels: Platform CMS Team, ⭐️ Sitewide CMS

#9798 VACMS-9670 update error message text to plainer language
  docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventAbsoluteCmsLinks.php
  tests/cypress/integration/behavioral/text_validation.feature
Labels: ⭐️ Sitewide CMS

#9875 VACMS-7392: Create new date format for revision date of va forms.
  config/sync/core.date_format.month_and_year.yml
  config/sync/core.entity_view_display.node.va_form.external_content.yml
Labels: ⭐️ Sitewide CMS

#9869 VACMS-9612: fetch lat/long from facility API for all VHA facilities
  config/sync/migrate_plus.migration.va_node_facility_nca.yml
  config/sync/migrate_plus.migration.va_node_facility_vba.yml
  config/sync/migrate_plus.migration.va_node_facility_vet_centers.yml
  config/sync/migrate_plus.migration.va_node_facility_vet_centers_os.yml
  config/sync/migrate_plus.migration.va_node_health_care_local_facility.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_nca.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vba.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers_os.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility.yml
Labels: ⭐️ Facilities

#9866 ddev cleanups
  .ddev/config.yaml
  composer.json
Labels: Platform CMS Team

#9931 VACMS-0000 update site alert to not print empty h2, fix static shield transparency
  docroot/sites/default/maintenance.html
  docroot/themes/custom/vagovclaro/templates/misc/sitewide-alert.html.twig
Labels: ⭐️ Sitewide CMS
