Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2022-11, with the labels that each got.

#11387 VACMS-10793: new table audit
  .tugboat/config.yml
  composer.json
  composer.lock
  config/sync/views.view.tables.yml
  docroot/modules/custom/va_gov_backend/src/EventSubscriber/TableAuditViewsEventSubscriber.php
  docroot/modules/custom/va_gov_backend/va_gov_backend.services.yml
  tests/behat/drupal-spec-tool/views.feature
Labels: ⭐️ Sitewide CMS

#11356 VACMS-11069: lovell listing page parity enforcement
  docroot/modules/custom/va_gov_lovell/src/Plugin/Validation/Constraint/LovellSectionListParity.php
  docroot/modules/custom/va_gov_lovell/src/Plugin/Validation/Constraint/LovellSectionListParityValidator.php
  docroot/modules/custom/va_gov_lovell/va_gov_lovell.module
Labels: ⭐️ Facilities

#11416 VACMS-11289: updated filters
  config/sync/views.view.content.yml
Labels: ⭐️ Sitewide CMS

#11409 VACMS-9923: fix display for Lovell sub-sections in user section block
  docroot/modules/custom/va_gov_user/src/Plugin/Block/UserSections.php
Labels: ⭐️ Facilities

#11446 VACMS-11421: add tricare description to service taxonomy
  config/sync/core.entity_form_display.taxonomy_term.health_care_service_taxonomy.default.yml
  config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.default.yml
  config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_tricare_description.yml
  config/sync/field.storage.taxonomy_term.field_tricare_description.yml
  tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature
Labels: ⭐️ Facilities

#11412 VACMS-10739: Cache preventing options from showing
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  docroot/modules/custom/va_gov_user/src/Service/UserPermsService.php
Labels: ⭐️ Facilities

#11441 VACMS-10870: php testing
  .github/actions/post-checkout/action.yml
  .tugboat/config.yml
  composer.json
  composer.lock
  docroot/modules/custom/va_gov_workflow/src/Service/Flagger.php
  docroot/themes/custom/vagovclaro/vagovclaro.theme
Labels: ⭐️ Sitewide CMS

#11483 VACMS-11473: Adds VBA-related view display and field label configuration
  config/sync/field.field.node.vba_facility_service.field_body.yml
  config/sync/field.field.node.vba_facility_service.field_service_name_and_descripti.yml
  config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_also_known_as.yml
  config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_vba_com_conditions.yml
  config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_vba_friendly_name.yml
  config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_vba_service_descrip.yml
  config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_vha_healthservice_stopcode.yml
  config/sync/views.view.health_care_service_names_and_descriptions.yml
  tests/behat/drupal-spec-tool/content_model_vba_facility_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature
Labels: ⭐️ Facilities

#11499 VACMS-11471: Fix error for table audit
  config/sync/views.view.tables.yml
  docroot/modules/custom/va_gov_backend/src/EventSubscriber/TableAuditViewsEventSubscriber.php
Labels: ⭐️ Sitewide CMS

#11552 VACMS-11503: add vamc non-clinical services and vba services to workb…
  config/sync/workbench_access.access_scheme.section.yml
Labels: ⭐️ Facilities

#11486 VACMS-8671: Removes problematic behavioral test.
  docroot/modules/custom/va_gov_backend/modules/va_gov_backend_http_client/src/VaGovBackendHttpClient.php
  docroot/modules/custom/va_gov_backend/modules/va_gov_backend_http_client/va_gov_backend_http_client.info.yml
  docroot/modules/custom/va_gov_backend/modules/va_gov_backend_http_client/va_gov_backend_http_client.services.yml
  docroot/modules/custom/va_gov_workflow_assignments/src/Plugin/Block/EntityMetaDisplay.php
  docroot/modules/custom/va_gov_workflow_assignments/src/Service/SectionHierarchyBreadcrumb.php
  docroot/modules/custom/va_gov_workflow_assignments/src/Service/SectionHierarchyBreadcrumbInterface.php
  docroot/modules/custom/va_gov_workflow_assignments/va_gov_workflow_assignments.services.yml
  tests/behat/Drupal/ContextBase.php
  tests/behat/features/content_editing.feature
  tests/cypress/integration/behavioral/common/i_create_a_node.js
  tests/cypress/integration/behavioral/ewa_block.feature
  tests/phpunit/Content/EntityMetaDisplayTest.php
  tests/phpunit/Content/SectionHierarchyBreadcrumbTest.php
Labels: ⭐️ Sitewide CMS

#11638 VACMS-11435: removed old table audit
  config/sync/views.view.table_audit.yml
  config/sync/views.view.tables.yml
  tests/behat/drupal-spec-tool/views.feature
Labels: ⭐️ Sitewide CMS

#11657 [DOCS] Adds VBA DB migration instructions
  READMES/migrations-facility.md
Labels: ⭐️ Facilities

#11693 VACMS-10588: omit TRICARE facilities from nightly removed from source scan
  docroot/modules/custom/va_gov_migrate/src/Commands/Commands.php
Labels: ⭐️ Facilities

#11703 VACMS-11698: Last-touched-by-an-editor field not always reflecting updates
  docroot/modules/custom/va_gov_backend/src/EventSubscriber/LastEditorSaveEventSubscriber.php
Labels: Defect, ⭐️ Sitewide CMS

#11729 VACMS-10046: update link colors to meet WCAG 2.0 AAA contrast requirements
  docroot/design-system/components/tokens/_variables.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_buttons.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_elements.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_footer.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_layout.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_links.scss
  docroot/themes/custom/vagovclaro/assets/scss/styles.scss
Labels: ⭐️ Sitewide CMS
