Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2022-08, with the labels that each got.

#10025 VACMS-9948 Lovell Tricare menu
  config/sync/menu_breadcrumb.settings.yml
  config/sync/system.menu.lovell-tricare-health-care.yml
  tests/behat/drupal-spec-tool/menus.feature
Labels: ⭐️ Facilities

#10039 VACMS-10040: Correct promo banner allowed types to match expected sing…
  config/sync/field.storage.node.field_promo_type.yml
Labels: ⭐️ Public Websites

#10050 VACMS 10049: Updates text in Cypress test.
  tests/cypress/integration/behavioral/navigation.feature
Labels: ⭐️ Sitewide CMS

#10056 Adds endpoint config patch from Geocoder module
  composer.json
  config/sync/geocoder.geocoder_provider.mapbox.yml
Labels: ⭐️ Facilities

#10101 Changes config to erase geocoding on failed look-up
  config/sync/field.field.node.vet_center_cap.field_geolocation.yml
Labels: ⭐️ Facilities, Needs PO review

#10082 VACMS-9943: block lighthouse updates for Lovell Tricare section
  docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityBase.php
  docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityService.php
  docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php
  tests/phpunit/Content/FacilityStatusQueueTest.php
Labels: ⭐️ Facilities

#10109 VACMS-10093 Updates instruction from 'Owner' to 'Section'
  config/sync/core.entity_form_display.node.health_care_local_health_service.default.yml
Labels: ⭐️ Facilities

#10044 VACMS-9714: add scripts to update crisis number to 988
  scripts/content/VACMS-9714-paragraphs-crisis-to-988.php
  scripts/content/VACMS-9714-vamc-detail-page-crisis-to-988.php
  scripts/content/VACMS-9714-vamc-system-operating-status-crisis-to-988.php
  scripts/content/script-library.php
  scripts/content/vacms-5744/library.php
Labels: ⭐️ Facilities

#10174 Add business hours calculation to all duration metrics
  config/sync/prometheus_exporter.settings.yml
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/MetricsCollector/BaseContentReleaseMetricsCollector.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/MetricsCollector/TimeSinceLastContentRelease.php
  tests/phpunit/FrontendBuild/BuildMetricsTest.php
Labels: Platform CMS Team

#10110 VACMS-9956: add new section field to lovell menu items
  config/sync/core.entity_form_display.menu_link_content.lovell-federal-health-care.default.yml
  config/sync/core.entity_view_display.menu_link_content.lovell-federal-health-care.default.yml
  config/sync/core.extension.yml
  config/sync/field.field.menu_link_content.lovell-federal-health-care.field_menu_section.yml
  config/sync/field.storage.menu_link_content.field_menu_section.yml
  docroot/modules/custom/va_gov_lovell/src/EventSubscriber/LovellEventSubscriber.php
  docroot/modules/custom/va_gov_lovell/va_gov_lovell.info.yml
  docroot/modules/custom/va_gov_lovell/va_gov_lovell.services.yml
Labels: ⭐️ Facilities

#10291 VACMS-10290: Upgrades Drupal to 9.3.21 [Security]
  composer.lock
Labels: security, ⭐️ Sitewide CMS

#10287 VACMS-10249: Upgrade graphql explorer packages (undici and dset).
  docroot/modules/custom/va_gov_graphql/assets/explorer/package-lock.json
Labels: ⭐️ Sitewide CMS

#10264 VACMS 9996: Reëvaluate packages with composer repository overrides
  composer.json
  composer.lock
Labels: ⭐️ Sitewide CMS, Quality Assurance

#10250 VACMS-10184 Buttons reset selected fields on new content
  docroot/modules/custom/va_gov_backend/js/limit_services_to_user_sections.es6.js
  docroot/modules/custom/va_gov_backend/js/limit_services_to_user_sections.js
  docroot/modules/custom/va_gov_vet_center/js/limit_vet_services_to_user_sections.es6.js
  docroot/modules/custom/va_gov_vet_center/js/limit_vet_services_to_user_sections.js
Labels: ⭐️ Facilities

#10367 VACMS-10366: Removes no-reply@va.gov from Update Manager preferences.
  config/sync/update.settings.yml
Labels: ⭐️ Sitewide CMS

#10395 VACMS-10394 Adds config for Table Audit to be in the menu
  config/sync/views.view.table_audit.yml
Labels: ⭐️ Facilities

#10377 VACMS-7600: Release content continuously during business hours
  docroot/modules/custom/va_gov_build_trigger/src/Commands/ContentReleaseCommands.php
  docroot/modules/custom/va_gov_build_trigger/src/EventSubscriber/ContentReleaseErrorSubscriber.php
  docroot/modules/custom/va_gov_build_trigger/src/EventSubscriber/ContinuousReleaseSubscriber.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/MetricsCollector/ContentReleaseAttemptsSinceLastSuccess.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/MetricsCollector/TimeSinceLastContentReleaseError.php
  docroot/modules/custom/va_gov_build_trigger/src/Service/BuildScheduler.php
  docroot/modules/custom/va_gov_build_trigger/src/Traits/RunsDuringBusinessHours.php
  docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.services.yml
  tests/phpunit/FrontendBuild/BuildStateEventSubscriberTest.php
  tests/phpunit/Support/Mock/SpecifiedTime.php
Labels: Platform CMS Team

#10381 VACMS-10277: enhance facility services reports with additional fields
  config/sync/views.view.facility_services.yml
Labels: ⭐️ Facilities

#10463 VACMS-10460: remove unused Lovell Tricare menu
  config/sync/system.menu.lovell-tricare-health-care.yml
  tests/behat/drupal-spec-tool/menus.feature
Labels: ⭐️ Facilities

#10294 VACMS-8166: Upgrade to Drupal 9.4.5
  composer.json
  composer.lock
  config/sync/core.entity_view_display.media.document.default.yml
  config/sync/core.entity_view_display.media.document_external.media_library.yml
  config/sync/core.entity_view_display.media.image.default.yml
  config/sync/core.entity_view_display.media.image.embedded.yml
  config/sync/core.entity_view_display.media.image.media_library.yml
  config/sync/core.entity_view_display.media.image.thumbnail.yml
  config/sync/core.entity_view_display.media.video.default.yml
  config/sync/core.entity_view_display.media.video.thumbnail.yml
  config/sync/core.extension.yml
  config/sync/editor.editor.rich_text.yml
  config/sync/editor.editor.rich_text_limited.yml
  config/sync/node_link_report.settings.yml
  config/sync/views.view.knowledge_base_search_results.yml
  config/sync/views.view.media.yml
  config/sync/views.view.media_library.yml
  config/sync/views.view.search.yml
  docroot/modules/custom/va_gov_notifications/va_gov_notifications.install
  docroot/sites/default/default.settings.php
  package.json
Labels: ⭐️ Sitewide CMS

#10365 VACMS-9920: Update the main CMS toolbar to meet accessibility standards
  docroot/modules/custom/va_gov_backend/css/toolbar.css
  docroot/modules/custom/va_gov_backend/images/content-release-tooltip-gray.svg
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  docroot/sites/default/settings/settings.prod.php
  docroot/sites/default/settings/settings.staging.php
  docroot/sites/default/settings/settings.tugboat.php
  docroot/themes/custom/vagovclaro/assets/scss/components/_toolbar.scss
  docroot/themes/custom/vagovclaro/images/icons/212121/hamburger.svg
  docroot/themes/custom/vagovclaro/images/icons/212121/pencil.svg
  docroot/themes/custom/vagovclaro/images/icons/212121/person.svg
  docroot/themes/custom/vagovclaro/images/icons/212121/questionmark-disc.svg
  docroot/themes/custom/vagovclaro/images/icons/212121/sections.svg
Labels: ⭐️ Sitewide CMS

#10522 VACMS-9905: Temporarily increase CreateMediaTest threshold.
  tests/phpunit/Content/CreateMediaTest.php
Labels: ⭐️ Sitewide CMS
