Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2022-09, with the labels that each got.

#10571 VACMS-10570: Protect `content-build-gql` against concurrent content builds
  composer.json
Labels: ⭐️ Sitewide CMS

#10574 VACMS-9649: Reset location values on toggle of event location type.
  docroot/modules/custom/va_gov_events/js/eventFormHelpers.es6.js
  docroot/modules/custom/va_gov_events/js/eventFormHelpers.js
Labels: ⭐️ Facilities

#10582 VACMS-9905: Increase time limits on other performance tests.
  tests/phpunit/Performance/CreateNodeTest.php
  tests/phpunit/Performance/CreateTaxonomyTermTest.php
  tests/phpunit/Performance/EditNodeTest.php
  tests/phpunit/Performance/LoginTest.php
  tests/phpunit/Performance/PreviewTest.php
Labels: ⭐️ Sitewide CMS

#10541 VACMS-10053: Move PHPUnit unit tests to separate GitHub Action.
  .github/workflows/phpunit-unit-tests.yml
  tests.yml
  tests/phpunit/API/BannerEndpointTest.php
  tests/phpunit/API/GraphQLTest.php
  tests/phpunit/API/PostApiQueueTest.php
  tests/phpunit/Content/AliasesTest.php
  tests/phpunit/Content/BulletinQueueTest.php
  tests/phpunit/Content/ContentModerationTest.php
  tests/phpunit/Content/CreateMediaTest.php
  tests/phpunit/Content/DownloadableFileTest.php
  tests/phpunit/Content/FacilityStatusQueueTest.php
  tests/phpunit/Content/MetaTagTest.php
  tests/phpunit/Content/PreventAbsoluteCmsLinksValidatorTest.php
  tests/phpunit/Content/PreventLocalFileLinksValidatorTest.php
  tests/phpunit/Controller/ContentReleaseStatusControllerTest.php
  tests/phpunit/Deploy/DeployServiceTest.php
  tests/phpunit/Deploy/Plugins/HealthCheckTest.php
  tests/phpunit/FrontendBuild/BuildMetricsTest.php
  tests/phpunit/FrontendBuild/BuildRequesterTest.php
  tests/phpunit/FrontendBuild/BuildSchedulerTest.php
  tests/phpunit/FrontendBuild/BuildStateEventSubscriberTest.php
  tests/phpunit/FrontendBuild/BuildTriggerFormTest.php
  tests/phpunit/FrontendBuild/EntityEventSubscriberTest.php
  tests/phpunit/FrontendBuild/ReleaseStateManagerTest.php
  tests/phpunit/Logging/DatadogApmProcessorTest.php
  tests/phpunit/Migration/VaFormMigrationTest.php
  tests/phpunit/Migration/VaHealthCareLocalFacilityMigrationTest.php
  tests/phpunit/Migration/VaHealthCareLocalFacilityStatusMigrationTest.php
  tests/phpunit/Ops/DatadogTest.php
  tests/phpunit/Ops/MetricsTest.php
  tests/phpunit/Performance/CreateNodeTest.php
  tests/phpunit/Performance/CreateTaxonomyTermTest.php
  tests/phpunit/Performance/EditNodeTest.php
  tests/phpunit/Performance/LoginTest.php
  tests/phpunit/Performance/PreviewTest.php
  tests/phpunit/Performance/ScalabilityCreateNodeTest.php
  tests/phpunit/Security/AdminDashboardTest.php
  tests/phpunit/Security/CreateNodeTest.php
  tests/phpunit/Security/GraphQLTest.php
  tests/phpunit/Security/NodeEditTabsTest.php
  tests/phpunit/Security/RoleCheckTest.php
  tests/phpunit/Security/RolesPermissionsTest.php
  tests/phpunit/Security/SectionAccessTest.php
  tests/phpunit/Security/WorkflowTest.php
  tests/phpunit/Service/EditorialWorkflowContentRepositoryServiceTest.php
  tests/phpunit/Service/ExclusionTypesServiceTest.php
  tests/phpunit/Service/ModerationActionsServiceTest.php
  tests/phpunit/Service/VaGovUrlServiceTest.php
Labels: ⭐️ Sitewide CMS

#10589 VACMS-10502: Adds `composer validate` GitHub Action.
  .github/workflows/composer-validate.yml
Labels: ⭐️ Sitewide CMS

#10595 VACMS-8084: Move `revision_log` field check into GitHub Actions.
  .github/workflows/check-revision-log-fields.yml
  tests.yml
Labels: ⭐️ Sitewide CMS

#10597 VACMS-10596: Move `check-cer` test into GitHub Actions.
  .github/workflows/check-cer-fields.yml
  tests.yml
Labels: ⭐️ Sitewide CMS

#10593 VACMS-8742: Removes $GITHUB_WORKSPACE workaround from GitHub Actions.
  .github/workflows/php_codesniffer.yml
  .github/workflows/phpcs.yml
  .github/workflows/stylelint-modules.yml
  .github/workflows/stylelint-themes.yml
Labels: ⭐️ Sitewide CMS

#10623 VACMS-10622: added eslint-plugin-yml to package.json
  package.json
Labels: ⭐️ Sitewide CMS

#10508 VACMS-7240: Link validation for protocol-relative links.
  docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventProtocolRelativeLinks.php
  docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventProtocolRelativeLinksValidator.php
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  tests/phpunit/Content/PreventProtocolRelativeLinksValidatorTest.php
Labels: ⭐️ Sitewide CMS

#10625 VACMS-10099: Place Q&As Modal in the CMS is not available with keyboard
  composer.json
  composer.lock
  docroot/themes/custom/vagovclaro/assets/js/modal_accessibility.es6.js
  docroot/themes/custom/vagovclaro/assets/js/modal_accessibility.js
  docroot/themes/custom/vagovclaro/vagovclaro.libraries.yml
Labels: ⭐️ Sitewide CMS

#10618 VACMS 10046: Update Link color across the CMS to meet WCAG 2.0 AAA contrast requirement
  docroot/design-system/components/tokens/_variables.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_links.scss
  docroot/themes/custom/vagovclaro/assets/scss/tokens/_mixins.scss
Labels: ⭐️ Sitewide CMS

#10641 VACMS-9992: removed behat-seo-contexts package, updated password_strength module
  composer.json
  composer.lock
  tests/behat/behat.yml
Labels: ⭐️ Sitewide CMS

#10629 VACMS-10418: Wrap CMS build stage in a retry block
  Jenkinsfile.cd
Labels: Platform CMS Team

#10650 VACMS-10649: Disables Update Manager module.
  config/sync/core.extension.yml
  config/sync/update.settings.yml
Labels: ⭐️ Sitewide CMS

#10357 VACMS-9483-Adds-Vet-Centers-to-VA-Locator
  config/sync/views.view.content_entity_reference_source.yml
Labels: ⭐️ Sitewide CMS

#9701 VACMS-9395 Change facility migration timing.
  READMES/migrations-facility.md
  tasks-periodic.yml
Labels: ⭐️ Facilities, Migration, DO NOT MERGE

#10679 VACMS-10422 Add VBA fields to migration
  config/sync/core.entity_view_display.node.vba_facility.default.yml
  config/sync/core.entity_view_display.node.vba_facility.external_content.yml
  config/sync/core.entity_view_display.node.vba_facility.ief_table.yml
  config/sync/migrate_plus.migration.va_node_facility_vba.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vba.yml
  docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php
Labels: ⭐️ Facilities

#10738 VACMS-10652: Update inline alt text guidance string in CMS
  docroot/modules/custom/va_gov_media/va_gov_media.module
Labels: ⭐️ Sitewide CMS

#10745 VACMS-10116: Radio Button labels on CMS Revision page
  composer.json
  composer.lock
  docroot/themes/custom/vagovclaro/assets/scss/pages/_revisions.scss
  docroot/themes/custom/vagovclaro/assets/scss/styles.scss
Labels: ⭐️ Sitewide CMS

#10733 VACMS-10281 Changes Facilities view table caption
  config/sync/views.view.facility_services.yml
Labels: ⭐️ Facilities

#10753 VACMS-9801 Add flysystem
  composer.json
  composer.lock
  config/sync/core.extension.yml
  docroot/sites/default/settings.php
  docroot/sites/default/settings/settings.flysystem.php
Labels: Platform CMS Team, ⭐️ Sitewide CMS

#10704 VACMS-10643: php 8.1 related issues
  composer.json
  composer.lock
  docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
Labels: ⭐️ Sitewide CMS

#10783 VACMS-9799 Ingest broken link report from content-build
  config/sync/core.extension.yml
  docroot/modules/custom/va_gov_links/src/EventSubscriber/ContentReleaseBrokenLinksIngestion.php
  docroot/modules/custom/va_gov_links/va_gov_links.info.yml
  docroot/modules/custom/va_gov_links/va_gov_links.services.yml
  docroot/sites/default/settings.php
  docroot/sites/default/settings/settings.prod.php
  docroot/sites/default/settings/settings.tugboat.php
Labels: ⭐️ Sitewide CMS

#10918 VACMS-4306: Stop Deploying to Dev Environment
  Jenkinsfile.cd
Labels: Platform CMS Team

#10951 Drupal Core Critical update SA-CORE-2022-016
  composer.lock
  docroot/sites/default/default.services.yml
Labels: ⭐️ Sitewide CMS

#10773 VACMS-10766: Inline Guidance groundwork and setup
  composer.json
  composer.lock
  config/sync/core.entity_form_display.node.banner.default.yml
  config/sync/core.extension.yml
  docroot/modules/custom/va_gov_backend/src/EventSubscriber/ThemeEventSubscriber.php
  docroot/modules/custom/va_gov_backend/src/Plugin/field_group/FieldGroupFormatter/InlineGuidance.php
  docroot/modules/custom/va_gov_backend/va_gov_backend.services.yml
  docroot/modules/custom/va_gov_media/va_gov_media.module
  docroot/themes/custom/vagovclaro/assets/js/inline_guidance.es6.js
  docroot/themes/custom/vagovclaro/assets/js/inline_guidance.js
  docroot/themes/custom/vagovclaro/assets/scss/components/_elements.scss
  docroot/themes/custom/vagovclaro/components/inline-guidance/button.twig
  docroot/themes/custom/vagovclaro/components/inline-guidance/text-box.twig
  docroot/themes/custom/vagovclaro/images/icons/004795/carrot.svg
  docroot/themes/custom/vagovclaro/templates/content-edit/file-managed-file.html.twig
  docroot/themes/custom/vagovclaro/templates/content-edit/file-widget-multiple.html.twig
  docroot/themes/custom/vagovclaro/templates/content-edit/image-widget.html.twig
  docroot/themes/custom/vagovclaro/templates/field-group/field-group-html-element--node-banner-form--group-paths-group.html.twig
  docroot/themes/custom/vagovclaro/templates/field-group/field-group-html-element.html.twig
  docroot/themes/custom/vagovclaro/templates/form/form-element.html.twig
  docroot/themes/custom/vagovclaro/vagovclaro.info.yml
  docroot/themes/custom/vagovclaro/vagovclaro.libraries.yml
Labels: ⭐️ Sitewide CMS
