Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2022-01, with the labels that each got.

#7455 VACMS-7433: Update pathauto for events to use nid instead of title.
  config/sync/pathauto.pattern.event.yml
Labels: Sitewide CMS Team

#7378 VACMS-7277: improve nodeview and paths for nonclinical health services
  config/sync/core.entity_view_display.node.vha_facility_nonclinical_service.default.yml
  config/sync/pathauto.pattern.vamc_facility_non_clinical_service.yml
Labels: Sitewide CMS Team

#7362 VACMS-7337: Rename sections and update behat tests.
  docroot/modules/custom/va_gov_db/va_gov_db.install
  tests/behat/features/content_editing.feature
  tests/behavioral/cypress/integration/common/i_create_a_media.js
  tests/behavioral/cypress/integration/common/i_create_a_node.js
  tests/behavioral/cypress/integration/user_login.feature
  tests/phpunit/Security/SectionAccessTest.php
Labels: Sitewide CMS Team

#7462 VACMS-7420 configure claro footer menu
  composer.json
  config/sync/block.block.footer_menu.yml
  config/sync/block.block.vagovclaro_breadcrumbs.yml
  config/sync/block.block.vagovclaro_burialsandmemorialsbenefitshub.yml
  config/sync/block.block.vagovclaro_careersemploymentbenefitshub.yml
  config/sync/block.block.vagovclaro_cmsuserguides.yml
  config/sync/block.block.vagovclaro_content.yml
  config/sync/block.block.vagovclaro_disabilitybenefitshub.yml
  config/sync/block.block.vagovclaro_educationbenefitshub.yml
  config/sync/block.block.vagovclaro_entitymetadisplay.yml
  config/sync/block.block.vagovclaro_healthcarebenefitshub.yml
  config/sync/block.block.vagovclaro_help.yml
  config/sync/block.block.vagovclaro_housingassistancebenefitshub.yml
  config/sync/block.block.vagovclaro_knowledge_base_search_form.yml
  config/sync/block.block.vagovclaro_lifeinsurancebenefitshub.yml
  config/sync/block.block.vagovclaro_local_actions.yml
  config/sync/block.block.vagovclaro_login.yml
  config/sync/block.block.vagovclaro_messages.yml
  config/sync/block.block.vagovclaro_node_link_report.yml
  config/sync/block.block.vagovclaro_outreachandevents.yml
  config/sync/block.block.vagovclaro_page_title.yml
  config/sync/block.block.vagovclaro_pensionbenefitshub.yml
  config/sync/block.block.vagovclaro_primary_local_tasks.yml
  config/sync/block.block.vagovclaro_recordsbenefitshub.yml
  config/sync/block.block.vagovclaro_secondary_local_tasks.yml
  config/sync/block.block.vagovclaro_sidebarmenusblock.yml
  config/sync/block.block.vagovclaro_sitealert.yml
  config/sync/block.block.vagovclaro_user_sections.yml
  config/sync/block.block.vagovclaro_views_block__right_sidebar_latest_revision_block_1.yml
  config/sync/block.block.vagovclaro_views_block__services_block_1.yml
  config/sync/block.block.vagovclaro_wheredoesthisappear.yml
  config/sync/core.entity_view_display.menu_link_content.footer.default.yml
  config/sync/core.extension.yml
  config/sync/system.menu.footer.yml
  docroot/themes/custom/vagovclaro/assets/css/styles.css
  docroot/themes/custom/vagovclaro/assets/css/styles.css.map
  docroot/themes/custom/vagovclaro/assets/scss/components/_footer.scss
  docroot/themes/custom/vagovclaro/templates/layout/footer.html.twig
  docroot/themes/custom/vagovclaro/vagovclaro.info.yml
  tests/behat/drupal-spec-tool/menus.feature
Labels: Sitewide CMS Team

#7466 VACMS-7074 KB theme in vagovclaro
  docroot/modules/custom/va_gov_help_center/va_gov_help_center.module
  docroot/themes/custom/vagovclaro/assets/css/styles.css
  docroot/themes/custom/vagovclaro/assets/css/styles.css.map
  docroot/themes/custom/vagovclaro/assets/css/user_guides.css
  docroot/themes/custom/vagovclaro/assets/css/user_guides.css.map
  docroot/themes/custom/vagovclaro/assets/scss/pages/_kb-pages.scss
  docroot/themes/custom/vagovclaro/assets/scss/pages/_node-view.scss
  docroot/themes/custom/vagovclaro/assets/scss/user_guides.scss
  docroot/themes/custom/vagovclaro/templates/node/node--documentation-page.html.twig
  docroot/themes/custom/vagovclaro/templates/page/page--documentation-page.html.twig
  docroot/themes/custom/vagovclaro/vagovclaro.theme
Labels: Sitewide CMS Team

#7473 VACMS-7422 vagovclaro homepage tweaks
  docroot/themes/custom/vagovclaro/assets/css/styles.css
  docroot/themes/custom/vagovclaro/assets/css/styles.css.map
  docroot/themes/custom/vagovclaro/assets/js/login-toggle.es6.js
  docroot/themes/custom/vagovclaro/assets/js/login-toggle.js
  docroot/themes/custom/vagovclaro/assets/scss/pages/_login-page.scss
  docroot/themes/custom/vagovclaro/templates/layout/footer.html.twig
  docroot/themes/custom/vagovclaro/templates/page/page--front.html.twig
  docroot/themes/custom/vagovclaro/templates/page/page--user--login.html.twig
  docroot/themes/custom/vagovclaro/vagovclaro.theme
Labels: Sitewide CMS Team

#7460 VACMS-7309: Disallow HTML characters from character count on text fields
  config/sync/core.entity_form_display.node.banner.default.yml
  config/sync/core.entity_form_display.node.basic_landing_page.default.yml
  config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_form_display.node.centralized_content.default.yml
  config/sync/core.entity_form_display.node.checklist.default.yml
  config/sync/core.entity_form_display.node.faq_multiple_q_a.default.yml
  config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_form_display.node.health_care_local_health_service.default.yml
  config/sync/core.entity_form_display.node.landing_page.default.yml
  config/sync/core.entity_form_display.node.media_list_images.default.yml
  config/sync/core.entity_form_display.node.media_list_videos.default.yml
  config/sync/core.entity_form_display.node.nca_facility.default.yml
  config/sync/core.entity_form_display.node.office.default.yml
  config/sync/core.entity_form_display.node.page.default.yml
  config/sync/core.entity_form_display.node.promo_banner.default.yml
  config/sync/core.entity_form_display.node.q_a.default.yml
  config/sync/core.entity_form_display.node.step_by_step.default.yml
  config/sync/core.entity_form_display.node.support_resources_detail_page.default.yml
  config/sync/core.entity_form_display.node.vet_center.default.yml
  config/sync/core.entity_form_display.node.vet_center_cap.default.yml
  config/sync/core.entity_form_display.paragraph.checklist_item.default.yml
  config/sync/core.entity_form_display.paragraph.featured_content.default.yml
  config/sync/core.entity_form_display.paragraph.q_a_group.default.yml
Labels: Sitewide CMS Team

#7535 VACMS-7162: Update section dashboard layout to remove extra titles and products
  config/sync/core.entity_view_display.taxonomy_term.administration.default.yml
  config/sync/node_link_report.settings.yml
  docroot/themes/custom/vagovadmin/templates/taxonomy-term.html.twig
  docroot/themes/custom/vagovclaro/templates/layout/taxonomy-term.html.twig
Labels: ⭐️ Content ops, Sitewide CMS Team

#7544 VACMS-6158 Update flag styling
  docroot/themes/custom/vagovadmin/assets/css/styles.css
  docroot/themes/custom/vagovadmin/assets/css/styles.css.map
  docroot/themes/custom/vagovadmin/assets/scss/_flags.scss
Labels: Sitewide CMS Team

#7556 VACMS-0000: Updates json-schema to 0.4.0
  package-lock.json
  package.json
Labels: security, Platform CMS Team

#7550 VACMS-7274 do not allow empty media refs
  config/sync/field.field.paragraph.link_teaser_with_image.field_media.yml
  config/sync/field.field.paragraph.media.field_media.yml
  tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature
Labels: ⭐️ Content ops, Sitewide CMS Team

#7553 VACMS-7520 vagovclaro alert updates
  docroot/themes/custom/vagovclaro/assets/css/styles.css
  docroot/themes/custom/vagovclaro/assets/css/styles.css.map
  docroot/themes/custom/vagovclaro/assets/js/login-toggle.js
  docroot/themes/custom/vagovclaro/assets/js/tabledrag.es6.js
  docroot/themes/custom/vagovclaro/assets/js/tabledrag.js
  docroot/themes/custom/vagovclaro/assets/scss/components/_alerts.scss
  docroot/themes/custom/vagovclaro/assets/scss/pages/_login-page.scss
  docroot/themes/custom/vagovclaro/assets/scss/tokens/_variables.scss
  docroot/themes/custom/vagovclaro/templates/block/node-link-report-block.html.twig
  docroot/themes/custom/vagovclaro/templates/components/_alert.html.twig
  docroot/themes/custom/vagovclaro/templates/misc/status-messages.html.twig
  docroot/themes/custom/vagovclaro/vagovclaro.libraries.yml
Labels: Sitewide CMS Team

#7533 VACMS-7102 AWS Gateway POC Work
  READMES/openapi/aws/dsva-cms-api-poc.yaml
  READMES/openapi/aws/lambda.js
  READMES/openapi/aws/openapi_aws.yml
  composer.json
  composer.lock
  config/sync/core.extension.yml
  scripts/fix_openapi_for_aws.sh
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Platform CMS Team

#7526 VACMS-7525 update paragraph entity browser styles
  docroot/themes/custom/vagovclaro/assets/css/styles.css
  docroot/themes/custom/vagovclaro/assets/css/styles.css.map
  docroot/themes/custom/vagovclaro/assets/scss/components/_paragraphs.scss
  docroot/themes/custom/vagovclaro/assets/scss/tokens/_variables.scss
Labels: ⭐️ CMS experience, Sitewide CMS Team

#7541 VACMS-7487: Hide operations button from office hours widget
  docroot/themes/custom/vagovadmin/assets/css/styles.css
  docroot/themes/custom/vagovadmin/assets/css/styles.css.map
  docroot/themes/custom/vagovadmin/assets/scss/styles.scss
  docroot/themes/custom/vagovclaro/assets/css/styles.css
  docroot/themes/custom/vagovclaro/assets/css/styles.css.map
  docroot/themes/custom/vagovclaro/assets/scss/components/_fields.scss
Labels: Sitewide CMS Team

#7581 VACMS-7574: Enable faq section behavior field in form view
  config/sync/core.entity_form_display.paragraph.q_a_section.default.yml
  tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature
Labels: Sitewide CMS Team

#7411 VACMS-7244: Send our prometheus metrics to Datadog
  docroot/modules/custom/va_gov_backend/src/Service/Datadog.php
  docroot/modules/custom/va_gov_backend/src/Service/Metrics.php
  docroot/modules/custom/va_gov_backend/va_gov_backend.info.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.services.yml
  docroot/sites/default/settings/settings.brd_common.php
  docroot/sites/default/settings/settings.ddev.php
  docroot/sites/default/settings/settings.lando.php
  docroot/sites/default/settings/settings.tugboat.php
  tests/phpunit/Ops/DatadogTest.php
  tests/phpunit/Ops/MetricsTest.php
Labels: Platform CMS Team

#7635 VACMS-7578: Remove preview option from all content types.
  config/sync/node.type.banner.yml
  config/sync/node.type.campaign_landing_page.yml
  config/sync/node.type.centralized_content.yml
  config/sync/node.type.faq_multiple_q_a.yml
  config/sync/node.type.full_width_banner_alert.yml
  config/sync/node.type.health_care_local_health_service.yml
  config/sync/node.type.outreach_asset.yml
  config/sync/node.type.press_release.yml
  config/sync/node.type.promo_banner.yml
  config/sync/node.type.step_by_step.yml
  config/sync/node.type.va_form.yml
  config/sync/node.type.vamc_operating_status_and_alerts.yml
  config/sync/node.type.vamc_system_billing_insurance.yml
  config/sync/node.type.vamc_system_medical_records_offi.yml
  config/sync/node.type.vamc_system_policies_page.yml
  config/sync/node.type.vamc_system_register_for_care.yml
  config/sync/node.type.vet_center_cap.yml
  config/sync/node.type.vet_center_facility_health_servi.yml
  config/sync/node.type.vet_center_locations_list.yml
  config/sync/node.type.vet_center_mobile_vet_center.yml
  config/sync/node.type.vet_center_outstation.yml
Labels: ⭐️ Content ops, Sitewide CMS Team

#7659 VACMS-7658: Add feature flag for care we provide.
  config/sync/feature_toggle.features.yml
Labels: ⭐️ Content ops, Sitewide CMS Team

#7672 VACMS-7670: Updates Drupal to 9.2.11.
  composer.json
  composer.lock
Labels: security

#7694 VACMS-7649 add patch for text counter behavior in claro
  composer.json
  docroot/themes/custom/vagovclaro/assets/css/styles.css
  docroot/themes/custom/vagovclaro/assets/css/styles.css.map
  docroot/themes/custom/vagovclaro/assets/scss/components/_elements.scss
Labels: Sitewide CMS Team

#7639 VACMS-7519 claro paragraphs functionality
  composer.json
  docroot/themes/custom/vagovclaro/assets/css/styles.css
  docroot/themes/custom/vagovclaro/assets/css/styles.css.map
  docroot/themes/custom/vagovclaro/assets/scss/components/_paragraphs.scss
  docroot/themes/custom/vagovclaro/vagovclaro.theme
  phpstan.neon
Labels: Sitewide CMS Team

#7740 VACMS-7536: Update paths field logic to include promo banner type.
  docroot/modules/custom/va_gov_banner/src/EventSubscriber/EntityEventSubscriber.php
Labels: Sitewide CMS Team

#7564 VACMS-7552 update theme build process
  .ddev/config.yaml
  .gitignore
  .lando.yml
  .tugboat/config.yml
  READMES/local.md
  composer.json
  docroot/themes/custom/vagovadmin/assets/css/proofing.css
  docroot/themes/custom/vagovadmin/assets/css/proofing.css.map
  docroot/themes/custom/vagovadmin/assets/css/styles.css
  docroot/themes/custom/vagovadmin/assets/css/styles.css.map
  docroot/themes/custom/vagovadmin/assets/css/styles.min.css
  docroot/themes/custom/vagovadmin/assets/css/styles.min.css.map
  docroot/themes/custom/vagovadmin/assets/css/user_guides.css
  docroot/themes/custom/vagovadmin/assets/css/user_guides.css.map
  docroot/themes/custom/vagovadmin/assets/css/whats_new.css
  docroot/themes/custom/vagovadmin/assets/css/whats_new.css.map
  docroot/themes/custom/vagovadmin/assets/css/wysiwyg.css
  docroot/themes/custom/vagovadmin/assets/css/wysiwyg.css.map
  docroot/themes/custom/vagovadmin/assets/js/anchor_links.js
  docroot/themes/custom/vagovadmin/assets/scss/_toolbar.scss
  docroot/themes/custom/vagovadmin/assets/scss/styles.scss
  docroot/themes/custom/vagovadmin/assets/scss/user_guides.scss
  docroot/themes/custom/vagovadmin/assets/scss/whats_new.scss
  docroot/themes/custom/vagovadmin/gulpfile.es6.js
  docroot/themes/custom/vagovadmin/gulpfile.js
  docroot/themes/custom/vagovadmin/package-lock.json
  docroot/themes/custom/vagovadmin/package.json
  docroot/themes/custom/vagovadmin/vagovadmin.info.yml
  docroot/themes/custom/vagovadmin/vagovadmin.libraries.yml
  docroot/themes/custom/vagovadmin/yarn.lock
  docroot/themes/custom/vagovclaro/README.md
  docroot/themes/custom/vagovclaro/assets/css/proofing.css
  docroot/themes/custom/vagovclaro/assets/css/proofing.css.map
  docroot/themes/custom/vagovclaro/assets/css/styles.css
  docroot/themes/custom/vagovclaro/assets/css/styles.css.map
  docroot/themes/custom/vagovclaro/assets/css/user_guides.css
  docroot/themes/custom/vagovclaro/assets/css/user_guides.css.map
  docroot/themes/custom/vagovclaro/assets/css/whats_new.css
  docroot/themes/custom/vagovclaro/assets/css/whats_new.css.map
  docroot/themes/custom/vagovclaro/assets/css/wysiwyg.css
  docroot/themes/custom/vagovclaro/assets/css/wysiwyg.css.map
  docroot/themes/custom/vagovclaro/assets/js/tabledrag.js
  docroot/themes/custom/vagovclaro/assets/scss/components/_media.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_toolbar.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_tooltip.scss
  docroot/themes/custom/vagovclaro/gulpfile.es6.js
  docroot/themes/custom/vagovclaro/gulpfile.js
  docroot/themes/custom/vagovclaro/package-lock.json
  docroot/themes/custom/vagovclaro/package.json
  docroot/themes/custom/vagovclaro/vagovclaro.info.yml
  docroot/themes/custom/vagovclaro/vagovclaro.libraries.yml
  docroot/themes/custom/vagovclaro/yarn.lock
Labels: Platform CMS Team, Sitewide CMS Team, DO NOT MERGE

#7748 VACMS-7662: Add field_body text format batching script.
  scripts/content/VACMS-7662-node-regional_health_care_service_des-force-limited-rich-text.php
Labels: Sitewide CMS Team

#7691 VACMS-7597: CMS announcement init and styling
  config/sync/block.block.cmsannouncementblock.yml
  config/sync/block.block.vagovclaro_content.yml
  config/sync/block.block.vagovclaro_local_actions.yml
  config/sync/block.block.vagovclaro_node_link_report.yml
  config/sync/block.block.vagovclaro_user_sections.yml
  config/sync/block.block.vagovclaro_views_block__services_block_1.yml
  config/sync/block.block.vagovclaro_wheredoesthisappear.yml
  docroot/themes/custom/vagovclaro/assets/scss/components/_announcement.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_flags.scss
  docroot/themes/custom/vagovclaro/assets/scss/pages/_login-page.scss
  docroot/themes/custom/vagovclaro/assets/scss/styles.scss
  docroot/themes/custom/vagovclaro/assets/scss/tokens/_variables.scss
  docroot/themes/custom/vagovclaro/templates/block/block--cmsannouncementblock.html.twig
Labels: ⭐️ Content ops, Sitewide CMS Team

#7684 VACMS-7582: Updates Tugboat, Lando, and DDEV to use PHP 7.4.
  .ddev/config.yaml
  .lando.yml
  .tugboat/config.yml
Labels: Platform CMS Team

#7759 VACMS-7649 claro mob session issues
  docroot/themes/custom/vagovclaro/assets/scss/components/_centralized_content.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_elements.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_fields.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_layout.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_media.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_paragraphs.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_services.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_views.scss
  docroot/themes/custom/vagovclaro/assets/scss/pages/_node-view.scss
  docroot/themes/custom/vagovclaro/assets/scss/pages/_proofing.scss
  docroot/themes/custom/vagovclaro/assets/scss/styles.scss
  docroot/themes/custom/vagovclaro/assets/scss/tokens/_mixins.scss
  docroot/themes/custom/vagovclaro/assets/scss/tokens/_variables.scss
  docroot/themes/custom/vagovclaro/templates/layout/html.html.twig
  docroot/themes/custom/vagovclaro/templates/node/node--page.html.twig
  docroot/themes/custom/vagovclaro/templates/page/page--user--login.html.twig
  docroot/themes/custom/vagovclaro/vagovclaro.libraries.yml
Labels: Sitewide CMS Team

#7675 VACMS-7256 Automate flag setting on va_form.
  config/sync/core.entity_view_display.node.va_form.external_content.yml
  config/sync/core.entity_view_display.node.va_form.teaser.yml
  config/sync/views.view.flagged_content.yml
  docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_workflow/src/Service/Flagger.php
Labels: DO NOT MERGE

#7778 VACMS-7741 claro login updates
  docroot/themes/custom/vagovclaro/assets/js/login-toggle.es6.js
  docroot/themes/custom/vagovclaro/assets/js/login-toggle.js
  docroot/themes/custom/vagovclaro/assets/scss/components/_elements.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_footer.scss
  docroot/themes/custom/vagovclaro/assets/scss/pages/_login-page.scss
  docroot/themes/custom/vagovclaro/assets/scss/tokens/_mixins.scss
  docroot/themes/custom/vagovclaro/assets/scss/tokens/_variables.scss
  docroot/themes/custom/vagovclaro/images/VAlogo.svg
  docroot/themes/custom/vagovclaro/images/va-logo-white.png
  docroot/themes/custom/vagovclaro/templates/layout/footer.html.twig
  docroot/themes/custom/vagovclaro/templates/page/page--user--login.html.twig
  docroot/themes/custom/vagovclaro/vagovclaro.theme
Labels: Sitewide CMS Team
