Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2022-10, with the labels that each got.

#10744 VACMS-10661: Create report of outdated content currently in the CMS
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/views.view.content.yml
  tests/behat/drupal-spec-tool/views.feature
Labels: ⭐️ Sitewide CMS

#11048 VACMS-11045: fix for inline guidance bug with existing images
  docroot/themes/custom/vagovclaro/assets/js/inline_guidance.es6.js
  docroot/themes/custom/vagovclaro/assets/js/inline_guidance.js
  docroot/themes/custom/vagovclaro/templates/content-edit/file-managed-file.html.twig
Labels: ⭐️ Sitewide CMS

#11059 VACMS-9821: Remove hidden edit link in main content listing
  config/sync/views.view.content.yml
  config/sync/views.view.facility_services.yml
  config/sync/views.view.flagged_content.yml
  config/sync/views.view.media.yml
  config/sync/views.view.rich_text_field_audit.yml
  config/sync/views.view.table_audit.yml
  config/sync/views.view.taxonomy_term.yml
  config/sync/views.view.va_forms.yml
Labels: ⭐️ Sitewide CMS

#11063 VACMS-10866: updated color for pending url
  docroot/modules/custom/va_gov_workflow_assignments/css/ewa_style.css
Labels: ⭐️ Sitewide CMS

#11065 VACMS-11064: install ga module, initial config for ga4
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/google_analytics.settings.yml
  config/sync/user.role.authenticated.yml
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: ⭐️ Sitewide CMS

#11091 Revert "VACMS-11064: install ga module, initial config for ga4 (#11065)"
  config/sync/core.extension.yml
  config/sync/google_analytics.settings.yml
  config/sync/user.role.authenticated.yml
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: ⭐️ Sitewide CMS

#11113 VACMS-11109: fix for inline guidance widget
  docroot/modules/custom/va_gov_backend/src/Plugin/field_group/FieldGroupFormatter/InlineGuidance.php
Labels: ⭐️ Sitewide CMS

#10491 VACMS-9656: Integration-Lovell
  config/sync/core.entity_view_display.menu_link_content.lovell-federal-health-care.default.yml
  docroot/modules/custom/va_gov_backend/src/Plugin/Block/SidebarMenusBlock.php
  docroot/modules/custom/va_gov_lovell/src/Event/BreadcrumbPreprocessEvent.php
  docroot/modules/custom/va_gov_lovell/src/EventSubscriber/LovellEventSubscriber.php
  docroot/modules/custom/va_gov_lovell/src/Factory/BreadcrumbPreprocessEventFactory.php
  docroot/modules/custom/va_gov_lovell/src/LovellMenuLinkTreeManipulators.php
  docroot/modules/custom/va_gov_lovell/src/LovellOps.php
  docroot/modules/custom/va_gov_lovell/src/Variables/BreadcrumbEventVariables.php
  docroot/modules/custom/va_gov_lovell/va_gov_lovell.info.yml
  docroot/modules/custom/va_gov_lovell/va_gov_lovell.services.yml
  docroot/modules/custom/va_gov_workflow_assignments/src/Plugin/Block/EntityMetaDisplay.php
  docroot/modules/custom/va_gov_workflow_assignments/va_gov_workflow_assignments.info.yml
Labels: ⭐️ Facilities, DO NOT MERGE, Awaiting Official Launch, VA Lovell

#11127 VACMS-11121: Add inline guidance into existing nodes
  docroot/themes/custom/vagovclaro/templates/field-group/field-group-html-element--node--banner--group-paths-group.html.twig
Labels: ⭐️ Sitewide CMS

#11111 VACMS-10667 show additional vet centers
  config/sync/views.view.vet_center_facility_listing.yml
  docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.module
  docroot/themes/custom/vagovclaro/assets/scss/components/_views.scss
  tests/behat/drupal-spec-tool/views.feature
Labels: ⭐️ Facilities

#9575 VACMS-9936: Linky PoC and scripts, etc
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/editor.editor.rich_text.yml
  config/sync/entity_usage.settings.yml
  config/sync/filter.format.rich_text.yml
  config/sync/filter.format.rich_text_limited.yml
  config/sync/linky.settings.yml
  config/sync/linkychecker.settings.yml
  config/sync/linkyreplacer.settings.yml
  config/sync/views.view.managed_links.yml
  scripts/content/VACMS-9936-linky-wrapper.sh
  scripts/content/VACMS-9936-linky.php
  tests/behat/drupal-spec-tool/views.feature
Labels: ⭐️ Sitewide CMS

#11228 VACMS-10923: updated filters for outdated content report
  config/sync/views.view.content.yml
Labels: ⭐️ Sitewide CMS

#11232 VACMS-10528: clear conditional fields that are hidden on node save
  docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
Labels: ⭐️ Facilities

#11200 VACMS-10870: Upgrade Tugboat and Composer from PHP 7.4 to 8.1.
  .ddev/php/zzz-va-overrides.ini
  .tugboat/config.yml
  composer.json
  composer.lock
Labels: Unplanned work, Platform CMS Team

#11299 VACMS-11137 Add VBA fields VA service taxonomy
  config/sync/core.entity_form_display.taxonomy_term.health_care_service_taxonomy.default.yml
  config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.default.yml
  config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_show_for_vamc_facilities.yml
  config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_show_for_vba_facilities.yml
  config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_show_for_vet_centers.yml
  config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_vba_com_conditions.yml
  config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_vba_friendly_name.yml
  config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_vba_service_descrip.yml
  config/sync/field.storage.taxonomy_term.field_show_for_vamc_facilities.yml
  config/sync/field.storage.taxonomy_term.field_show_for_vba_facilities.yml
  config/sync/field.storage.taxonomy_term.field_show_for_vet_centers.yml
  config/sync/field.storage.taxonomy_term.field_vba_com_conditions.yml
  config/sync/field.storage.taxonomy_term.field_vba_friendly_name.yml
  config/sync/field.storage.taxonomy_term.field_vba_service_descrip.yml
  tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature
Labels: ⭐️ Facilities

#11366 VACMS-9754: update facility content audit download to include all fie…
  config/sync/views.view.facility_services.yml
Labels: ⭐️ Facilities

#11394 VACMS-10793: enable views event dispatcher module
  config/sync/core.extension.yml
Labels: ⭐️ Sitewide CMS
