Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2022-06, with the labels that each got.

#9292 VACMS-9290: fix ordering issue with Billing and Insurance copay fields
  config/sync/core.entity_form_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_view_display.node.vamc_system_billing_insurance.default.yml
Labels: ⭐️ Facilities

#9347 VACMS-9326: Change billing and insurance hours field from select to html5 picker.
  config/sync/field.storage.node.field_hours_for_copay_inquiries_.yml
Labels: ⭐️ Facilities

#9372 VACMS-9360: Add hidden office hours field to billing.
  config/sync/core.entity_form_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_view_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_view_display.node.vamc_system_billing_insurance.teaser.yml
  config/sync/field.field.node.vamc_system_billing_insurance.field_office_hours.yml
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
Labels: ⭐️ Facilities

#9379 VACMS-9309 update block placement config for recurring events block
  config/sync/block.block.recurringeventsannouncement.yml
Labels: ⭐️ Sitewide CMS

#9383 VACMS-9361: Add field script.
  scripts/content/VACMS-9361-sync-hours-fields.php
Labels: ⭐️ Facilities

#9356 VAGOV-9295: [devops] Add slack_channel for CMS build job to notify of failures
  Jenkinsfile.cd
Labels: DevOps

#9409 VACMS-9364: Remove copay hours from billing.
  composer.json
  composer.lock
  config/sync/core.entity_form_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_view_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_view_display.node.vamc_system_billing_insurance.teaser.yml
  config/sync/field.field.node.vamc_system_billing_insurance.field_hours_for_copay_inquiries_.yml
  config/sync/field.storage.node.field_hours_for_copay_inquiries_.yml
  docroot/modules/custom/va_gov_db/va_gov_db.install
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
Labels: ⭐️ Facilities

#9275 VACMS-9015: Updates unit tests for content release.
  tests/phpunit/FrontendBuild/EntityEventSubscriberTest.php
  tests/phpunit/Support/Mock/SpecifiedTime.php
Labels: Platform CMS Team

#9401 VACMS-8588: Convert all remaining lando references to ddev
  .ddev/commands/web/pre-commit
  .ddev/config.yaml
  .ddev/docker-compose.web-env.yaml
  .devcontainer/devcontainer.json
  .devcontainer/post-create.sh
  .devcontainer/post-start.sh
  .env.example
  .env.lando
  .gitignore
  .lando.local.yml.example
  .lando.yml
  .lando/scripts/behat.sh
  .lando/scripts/blackfire-init.sh
  .lando/zzz-lando-my-custom.ini
  .vscode/launch.json
  READMES/blackfire.md
  READMES/codespaces.md
  READMES/debugging.md
  READMES/drupal-memcache.md
  READMES/environment-variables.md
  READMES/environments.md
  READMES/ewa-rules-of-engagement.md
  READMES/getting-started.md
  READMES/https.md
  READMES/local.md
  READMES/migrations-facility.md
  READMES/testing.md
  READMES/unity.md
  READMES/workflow.md
  composer.json
  composer.lock
  docroot/modules/custom/va_gov_backend/src/Service/Metrics.php
  docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentDiscovery.php
  docroot/modules/custom/va_gov_build_trigger/src/Form/LocalBuildTriggerForm.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Local.php
  docroot/modules/custom/va_gov_build_trigger/src/Service/BuildFrontend.php
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_form.yml
  docroot/modules/custom/va_gov_preview/src/EventSubscriber/DeployStatusMessagesSubscriber.php
  docroot/sites/default/settings.php
  docroot/sites/default/settings/settings.ddev.php
  docroot/sites/default/settings/settings.eks.php
  docroot/sites/default/settings/settings.local.php
  docroot/sites/default/settings/settings.prod.php
  docroot/sites/default/settings/settings.staging.php
  docroot/themes/custom/vagovadmin/gulpfile.es6.js
  docroot/themes/custom/vagovadmin/gulpfile.js
  docroot/themes/custom/vagovclaro/README.md
  docroot/themes/custom/vagovclaro/gulpfile.es6.js
  docroot/themes/custom/vagovclaro/gulpfile.js
  drush/drushrc.local.php
  drush/drushrc.php
  hooks/git/pre-commit
  scripts/composer/EnvironmentHandler.php
  scripts/content/VACMS-3450-testing.sh
  scripts/precommit.sh
  scripts/sync-db.sh
  tests/phpunit/FrontendBuild/BuildFrontendTest.php
  tests/phpunit/FrontendBuild/BuildTriggerFormTest.php
  tests/phpunit/Ops/MetricsTest.php
Labels: Platform CMS Team

#9349 VACMS-9097 facility title change notification
  config/sync/core.entity_view_display.message.va_facility_title_change.default.yml
  config/sync/core.entity_view_display.message.va_facility_title_change.mail_body.yml
  config/sync/core.entity_view_display.message.va_facility_title_change.mail_subject.yml
  config/sync/core.entity_view_display.message.vet_center_official_name_change.default.yml
  config/sync/core.entity_view_display.message.vet_center_official_name_change.mail_body.yml
  config/sync/core.entity_view_display.message.vet_center_official_name_change.mail_subject.yml
  config/sync/field.field.message.va_facility_title_change.field_target_entity.yml
  config/sync/field.field.message.va_facility_title_change.field_target_node_title.yml
  config/sync/field.field.message.vet_center_official_name_change.field_target_entity.yml
  config/sync/field.field.message.vet_center_official_name_change.field_target_node_title.yml
  config/sync/message.template.va_facility_title_change.yml
  config/sync/message.template.vet_center_official_name_change.yml
  docroot/modules/custom/va_gov_notifications/src/Service/NotificationsManager.php
  docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
Labels: ⭐️ Sitewide CMS

#9480 VACMS-9479 Prevent message Flags from showing in IEF.
  config/sync/flag.flag.email_node.yml
  config/sync/flag.flag.email_term.yml
  config/sync/flag.flag.email_user.yml
  config/sync/flag.flag.subscribe_node.yml
  config/sync/flag.flag.subscribe_term.yml
  config/sync/flag.flag.subscribe_user.yml
Labels: ⭐️ Facilities

#9521 VACMS-9304: Show am/pm on start and end in recurring events UI
  config/sync/smart_date.smart_date_format.compact.yml
  config/sync/smart_date.smart_date_format.default.yml
Labels: ⭐️ Facilities, ⭐️ Public Websites

#9562 [DOCS] Drupal spec tool edits
  READMES/workflow.md
Labels: ⭐️ Sitewide CMS

#9583 VACMS-9574: Update Drupal to 9.3.17. [SECURITY]
  composer.json
  composer.lock
  tests/cypress/integration/behavioral/content_release.feature
Labels: security, Platform CMS Team, ⭐️ Sitewide CMS

#9386 VACMS-9358: add audit opening hours comments field script
  scripts/content/VACMS-9358-audit-opening-hours-comments.php
Labels: ⭐️ Facilities

#9593 VACMS-9410: Clear event registration info when toggling states.
  docroot/modules/custom/va_gov_events/js/eventFormHelpers.es6.js
  docroot/modules/custom/va_gov_events/js/eventFormHelpers.js
Labels: ⭐️ Public Websites

#9595 VACMS-0000: Enable twig debugging for local development.
  docroot/sites/development.services.yml
Labels: Drupal engineering

#9586 VACMS-9510 add drush command patch, export config for sitewide alerts
  composer.json
  composer.lock
  config/sync/core.entity_form_display.sitewide_alert.sitewide_alert.default.yml
  config/sync/core.entity_view_display.sitewide_alert.sitewide_alert.default.yml
  config/sync/core.extension.yml
  config/sync/field.field.sitewide_alert.sitewide_alert.field_alert_title.yml
  config/sync/field.storage.sitewide_alert.field_alert_title.yml
  config/sync/sitewide_alert.settings.yml
Labels: ⭐️ Sitewide CMS

#9598 VACMS-6528: archive related services/events when a facility is archived
  .github/ISSUE_TEMPLATE/runbook-facility-closed.md
  docroot/modules/custom/va_gov_facilities/src/EventSubscriber/FacilitiesSubscriber.php
  docroot/modules/custom/va_gov_facilities/va_gov_facilities.services.yml
Labels: ⭐️ Facilities
