Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2022-03, with the labels that each got.

#8226 VACMS-8168: Uses a Cypress logging statement to force timeouts in too-long-running tests.
  tests/accessibility/cypress/integration/nodeCreationAccessibility.spec.js
Labels: Platform CMS Team, Sitewide CMS Team

#8220 VACMS-4503 disable PIV certain tugboat envs with tests
  .ddev/config.yaml
  .lando.yml
  .tugboat/.env.j2
  docroot/sites/default/settings/settings.tugboat.php
  docroot/themes/custom/vagovclaro/vagovclaro.theme
  package.json
  tests/behat/README.md
  tests/behat/features/user.feature
  tests/behavioral/cypress/integration/user_login.feature
Labels: Platform CMS Team, Sitewide CMS Team, DO NOT MERGE

#8314 VACMS-0000: Ignores AWS PHP SDK patch updates.
  .github/dependabot.yml
Labels: Platform CMS Team, Sitewide CMS Team

#8250 VACMS-8048: Allow authenticated users to export CSV of users
  config/sync/views.view.user_admin_people.yml
  tests/behat/drupal-spec-tool/views.feature
Labels: ⭐️ Content ops

#8276 VACMS-8274 clean up media menu
  config/sync/core.menu.static_menu_link_overrides.yml
  config/sync/views.view.files.yml
  config/sync/views.view.media.yml
  config/sync/views.view.media_images.yml
  config/sync/views.view.pdf_audit.yml
  tests/behat/drupal-spec-tool/views.feature
Labels: ⭐️ Content ops

#8369 VACMS-0000: Updates Drupal to 9.3.8.
  composer.lock
Labels: security, Platform CMS Team, Sitewide CMS Team

#8352 VACMS-8329: Unlink content type label in section view.
  config/sync/views.view.taxonomy_term.yml
Labels: ⭐️ Content ops

#8109 VACMS-6645: Create table audit view.
  config/sync/views.view.table_audit.yml
  tests/behat/drupal-spec-tool/views.feature
Labels: ⭐️ Content ops

#8450 VACMS-8405: Style views export button.
  docroot/themes/custom/vagovclaro/assets/scss/components/_views.scss
  docroot/themes/custom/vagovclaro/templates/views/views-view.html.twig
Labels: ⭐️ Content ops

#8381 VACMS-8257: Adjust content admin role permissions
  config/sync/user.role.content_admin.yml
  config/sync/user.role.content_editor.yml
  config/sync/user.role.content_publisher.yml
  config/sync/user.role.content_reviewer.yml
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: ⭐️ Content ops

#8332 VACMS-8327: Install HTML tag usage module to audit <em> tags.
  .gitignore
  composer.json
  composer.lock
  docroot/modules/custom/va_gov_db/va_gov_db.install
Labels: ⭐️ Content ops

#8339 VACMS-7557: Enable allow only one on health services.
  config/sync/core.entity_form_display.taxonomy_term.health_care_service_taxonomy.default.yml
  config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.default.yml
  config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_enforce_unique_combo_servi.yml
  config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_health_service_api_id.yml
  config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_owner.yml
  config/sync/field.storage.taxonomy_term.field_enforce_unique_combo_servi.yml
  docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
  tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature
  tests/behat/features/content_editing.feature
Labels: Sitewide CMS Team

#8438 VACMS-8404 Button audit
  config/sync/views.view.rich_text_field_audit.yml
  docroot/themes/custom/vagovclaro/assets/scss/components/_views.scss
  tests/behat/drupal-spec-tool/views.feature
Labels: ⭐️ Content ops

#8482 VACMS 8346 storybook + design system infrastructure, take 3
  .ddev/docker-compose.storybook.yaml
  .gitignore
  .storybook/403-error-document.j2.html
  .storybook/README.md
  .storybook/artur-pokusin-unsplash.jpg
  .tugboat/config.yml
  .tugboat/vhost-storybook.conf
  .tugboat/vhost-web.conf
  .web/README.md
  composer.json
  composer.lock
  config/sync/core.extension.yml
  docroot/design-system/.babelrc.json
  docroot/design-system/.storybook/claro.css
  docroot/design-system/.storybook/cssVariables.js
  docroot/design-system/.storybook/cssVariables.json
  docroot/design-system/.storybook/main.js
  docroot/design-system/.storybook/preview.js
  docroot/design-system/.storybook/storybook-styles.scss
  docroot/design-system/.storybook/twing-environment.js
  docroot/design-system/DrupalAttribute/index.js
  docroot/design-system/README.md
  docroot/design-system/components/alert/alert.scss
  docroot/design-system/components/alert/alert.stories.js
  docroot/design-system/components/alert/alert.twig
  docroot/design-system/components/alert/index.js
  docroot/design-system/components/block/block.scss
  docroot/design-system/components/block/block.stories.js
  docroot/design-system/components/block/block.twig
  docroot/design-system/components/block/index.js
  docroot/design-system/components/design-system.js
  docroot/design-system/components/index.js
  docroot/design-system/components/tokens/_variables.css
  docroot/design-system/components/tokens/colors.twig
  docroot/design-system/components/tokens/index.js
  docroot/design-system/components/tokens/spacing.twig
  docroot/design-system/components/tokens/tokens.stories.js
  docroot/design-system/components/tokens/typography.twig
  docroot/design-system/img/favicons/favicon-57.png
  docroot/design-system/img/icon-dot-gov.svg
  docroot/design-system/img/icon-https.svg
  docroot/design-system/package.json
  docroot/design-system/stories/Introduction.stories.mdx
  docroot/design-system/stories/changelog.stories.mdx
  docroot/design-system/stories/starting.stories.mdx
  docroot/design-system/webpack.config.js
  docroot/design-system/yarn.lock
  docroot/themes/custom/vagovclaro/templates/misc/status-messages.html.twig
  docroot/themes/custom/vagovclaro/vagovclaro.info.yml
  docroot/themes/custom/vagovclaro/vagovclaro.libraries.yml
  scripts/lando-precommit.sh
Labels: Sitewide CMS Team

#8479 VACMS-8475: Broaden styles to target all field_office hours widgets.
  docroot/themes/custom/vagovclaro/assets/scss/components/_fields.scss
Labels: Sitewide CMS Team

#8356 VACMS-8298 VAMC facility accordion audit
  config/sync/node_link_report.settings.yml
  config/sync/views.view.facility_services.yml
  tests/behat/drupal-spec-tool/views.feature
Labels: ⭐️ Content ops

#8515 VACMS-8485 office hours upgrade et
  composer.json
  composer.lock
Labels: Sitewide CMS Team

#8316 VACMS-2509: Remove old blobby content model for Facility health services
  config/sync/core.entity_form_display.node.health_care_local_health_service.default.yml
  config/sync/core.entity_form_display.node.health_care_local_health_service.inline_entity_form.yml
  config/sync/core.entity_view_display.node.health_care_local_health_service.default.yml
  config/sync/core.entity_view_display.node.health_care_local_health_service.ief_table.yml
  config/sync/core.entity_view_display.node.health_care_local_health_service.teaser.yml
  config/sync/field.field.node.health_care_local_health_service.field_body.yml
  docroot/modules/custom/va_gov_vamc/va_gov_vamc.install
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
Labels: Sitewide CMS Team

#8527 VACMS-8525: Fix issues deleting node revisions.
  composer.json
  composer.lock
Labels: ⭐️ Content ops, Platform CMS Team

#7979 VACMS-7969: Create office connect with us view mode and display in node view
  composer.json
  config/sync/core.entity_view_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_view_display.node.landing_page.default.yml
  config/sync/core.entity_view_display.node.office.connect_with_us.yml
  config/sync/core.entity_view_mode.node.connect_with_us.yml
  docroot/themes/custom/vagovadmin/templates/node/node--external-content.html.twig
  docroot/themes/custom/vagovadmin/templates/node/node--health_care_local_health_service--teaser.html.twig
  docroot/themes/custom/vagovadmin/templates/node/node--landing-page--support-services-listing.html.twig
  docroot/themes/custom/vagovadmin/templates/node/node--landing-page--teaser.html.twig
  docroot/themes/custom/vagovadmin/templates/node/node--office--connect-with-us.html.twig
  docroot/themes/custom/vagovadmin/templates/node/node--regional_health_care_service_des--teaser.html.twig
  docroot/themes/custom/vagovadmin/templates/node/node--support-service--support-services-listing.html.twig
  docroot/themes/custom/vagovadmin/templates/node/node--va-form--full.html.twig
  docroot/themes/custom/vagovadmin/templates/node/node--va_form--external-content.html.twig
  docroot/themes/custom/vagovclaro/templates/node/node--office--connect-with-us.html.twig
Labels: ⭐️ Content ops
