Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2022-04, with the labels that each got.

#8558 VACMS-6702: Improvements to Drupal -> Syslog.
  config/prod/syslog.settings.yml
  config/stg/syslog.settings.yml
  docroot/sites/default/settings.php
Labels: Platform CMS Team

#8694 VACMS-0000: Update SAML Login Error Report Page Email Address
  simplesamlphp-config-metadata/config/config.php
Labels: Unplanned work

#8720 VACMS-8672: Create Cypress step definitions for feature parity with Behat
  package-lock.json
  package.json
  tests/behavioral/cypress.json
  tests/behavioral/cypress/integration/common/i_create_a_taxonomy_term.js
  tests/behavioral/cypress/integration/common/i_fill_in_field_with_value.js
  tests/behavioral/cypress/integration/common/i_publish_the_node.js
  tests/behavioral/cypress/integration/common/i_select_option_from_dropdown.js
  tests/behavioral/cypress/integration/common/i_select_the_radio_button.js
  tests/behavioral/cypress/integration/common/i_set_the_status_of_the_node_to_status.js
  tests/behavioral/cypress/integration/common/i_should_see.js
  tests/behavioral/cypress/integration/common/i_trigger_a_content_release.js
  tests/behavioral/cypress/integration/common/i_visit_the_node.js
  tests/behavioral/cypress/integration/common/the_element_should_contain_string.js
  tests/behavioral/cypress/integration/common/the_element_should_have_attribute.js
  tests/behavioral/cypress/integration/common/the_option_from_dropdown_should_be_selected.js
  tests/behavioral/cypress/integration/common/the_radio_button_should_be_selected.js
  tests/behavioral/cypress/integration/step_definitions.feature
  tests/behavioral/cypress/support/commands.js
Labels: Platform CMS Team

#8739 VACMS-8741: Adds Git "safe directory" for project to allow GitHub Actions to run.
  .github/workflows/phpcs.yml
  .github/workflows/stylelint-modules.yml
  .github/workflows/stylelint-themes.yml
Labels: Platform CMS Team

#8771 VACMS-8719 remove the outdated login page announcement
  config/sync/block.block.cmsannouncementblock.yml
Labels: ⭐️ CMS experience

#8759 VACMS-8735: Update all behat tests for new formatting/ordering.
  tests/behat/drupal-spec-tool/access_control.feature
  tests/behat/drupal-spec-tool/content_model_alerts_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_benefits_hubs_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_bundles.feature
  tests/behat/drupal-spec-tool/content_model_campaign_landing_page_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_custom_block_fields.feature
  tests/behat/drupal-spec-tool/content_model_lc_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_media_fields.feature
  tests/behat/drupal-spec-tool/content_model_nca_facility_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_outreach_hub_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature
  tests/behat/drupal-spec-tool/content_model_user_guides_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_va_common_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_va_forms_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_vba_facility_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature
  tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature
  tests/behat/drupal-spec-tool/media.feature
  tests/behat/drupal-spec-tool/menus.feature
  tests/behat/drupal-spec-tool/views.feature
  tests/behat/drupal-spec-tool/workflow.feature
Labels: ⭐️ Content ops

#8717 VACMS-8684: Rename VHA Services taxonomy to VA services.
  config/sync/node_link_report.settings.yml
  config/sync/taxonomy.vocabulary.health_care_service_taxonomy.yml
  config/sync/views.view.vha_health_service_taxonomy.yml
  docroot/modules/custom/va_gov_db/va_gov_db.install
  tests/behat/drupal-spec-tool/content_model_bundles.feature
  tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature
  tests/behat/drupal-spec-tool/views.feature
Labels: ⭐️ Content ops

#8804 Bump content build to 0.0.2990
  composer.json
  composer.lock
Labels: Platform CMS Team

#8795 Disable content build dispatch in local, dev, and staging because they do not currently work
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRDGHA.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Lando.php
Labels: Platform CMS Team

#8798 Rename shouldTriggerFrontendBuild to contentEditsShouldTriggerFrontentBuild
  docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentDiscovery.php
  docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentInterface.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRD.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRDGHA.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Lando.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Tugboat.php
  docroot/modules/custom/va_gov_build_trigger/src/Service/BuildFrontend.php
  tests/phpunit/FrontendBuild/BuildFrontendTest.php
Labels: Platform CMS Team

#8799 Remove the full rebuild param. It is not actually used for anything.
  docroot/modules/custom/va_gov_build_trigger/src/Commands/WebBuildCommands.php
  docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentDiscovery.php
  docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentInterface.php
  docroot/modules/custom/va_gov_build_trigger/src/Form/TugboatBuildTriggerForm.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRD.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRDGHA.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Lando.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Tugboat.php
  docroot/modules/custom/va_gov_build_trigger/src/Service/BuildFrontend.php
  docroot/modules/custom/va_gov_build_trigger/src/Service/BuildFrontendInterface.php
  docroot/modules/custom/va_gov_build_trigger/src/Service/JenkinsClient.php
  docroot/modules/custom/va_gov_build_trigger/src/Service/JenkinsClientInterface.php
  tests/phpunit/FrontendBuild/BuildFrontendTest.php
Labels: Platform CMS Team

#8816 Run test tasks in parallel
  .tugboat/config.yml
  tests.yml
Labels: Platform CMS Team, DO NOT MERGE

#8824 VACMS-8519: Adds test coverage for file upload.
  tests/behavioral/cypress/integration/common/i_create_a_node.js
  tests/behavioral/cypress/integration/common/i_should_see.js
  tests/behavioral/cypress/integration/file_upload.feature
Labels: Platform CMS Team

#8832 Only run graphql queries instead of the full content build
  .tugboat/config.yml
  composer.json
  composer.lock
  tests.yml
  tests/behat/features/decoupled.feature
  tugboat.yml
Labels: Platform CMS Team

#8789 Move graphql caching stuff to va_gov_graphql where it belongs
  docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.module
  docroot/modules/custom/va_gov_graphql/src/GraphQLEntityQuery.php
  docroot/modules/custom/va_gov_graphql/va_gov_graphql.module
Labels: Platform CMS Team

#8788 Remove all legacy BRD code
  .tugboat/config.yml
  READMES/cms-content-release.md
  composer.json
  docroot/modules/custom/va_gov_backend/src/Service/Metrics.php
  docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentDiscovery.php
  docroot/modules/custom/va_gov_build_trigger/src/Exception/JenkinsClientException.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRD.php
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRDGHA.php
  docroot/modules/custom/va_gov_build_trigger/src/Service/JenkinsClient.php
  docroot/modules/custom/va_gov_build_trigger/src/Service/JenkinsClientInterface.php
  docroot/modules/custom/va_gov_build_trigger/src/Service/MiddlewareFactory.php
  docroot/modules/custom/va_gov_build_trigger/src/Service/SystemsManagerClient.php
  docroot/modules/custom/va_gov_build_trigger/src/Service/SystemsManagerClientInterface.php
  docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.services.yml
  docroot/sites/default/settings/settings.dev.php
  docroot/sites/default/settings/settings.prod.php
  docroot/sites/default/settings/settings.staging.php
  scripts/tests/cypress.sh
  tests.yml
  tests/phpunit/FrontendBuild/Brd/BrdEnvironmentTest.php
  tests/phpunit/FrontendBuild/Brd/JenkinsClientTest.php
  tests/phpunit/FrontendBuild/Brd/SystemsManagerClientTest.php
  tests/phpunit/Ops/MetricsTest.php
Labels: Platform CMS Team

#8551 VACMS-8550: hide old service location field_facility_service_hours
  config/sync/core.entity_form_display.paragraph.service_location.default.yml
  config/sync/core.entity_view_display.paragraph.service_location.default.yml
  config/sync/views.view.non_clinical_services.yml
  docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature
Labels: DO NOT MERGE, Blocked

#8851 VACMS-0000: Skip certain tests on BRD.
  tests/cypress/integration/behavioral/content_release.feature
Labels: Platform CMS Team

#8831 VCMS-8808 Add vha facility url export.
  config/sync/views.view.facility_services.yml
  tests/behat/drupal-spec-tool/views.feature
Labels: ⭐️ Facilities

#8736 VACMS-8709: remove field_facility_service_hours from service_location…
  config/sync/core.entity_form_display.paragraph.service_location.default.yml
  config/sync/core.entity_view_display.paragraph.service_location.default.yml
  config/sync/field.field.paragraph.service_location.field_facility_service_hours.yml
  config/sync/field.storage.paragraph.field_facility_service_hours.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.install
  tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature
Labels: ⭐️ Facilities

#8898 VACMS-8844: Install and configure Monolog, and append Datadog APM trace info to log output.
  composer.json
  composer.lock
  config/dev/raven.settings.yml
  config/dev/syslog.settings.yml
  config/sync/config_split.config_split.dev.yml
  config/sync/core.extension.yml
  docroot/modules/custom/va_gov_backend/src/Logger/Processor/DatadogApmProcessor.php
  docroot/modules/custom/va_gov_backend/src/Service/DatadogContextProvider.php
  docroot/modules/custom/va_gov_backend/src/Service/DatadogContextProviderInterface.php
  docroot/modules/custom/va_gov_backend/va_gov_backend.services.yml
  docroot/modules/custom/va_gov_migrate/src/Commands/Commands.php
  docroot/sites/default/services/services.dev.yml
  docroot/sites/default/services/services.monolog.yml
  docroot/sites/default/services/services.prod.yml
  docroot/sites/default/services/services.staging.yml
  docroot/sites/default/settings.php
  tests/phpunit/Logging/DatadogApmProcessorTest.php
Labels: Platform CMS Team

#8929 VACMS-7657: update script from 7662 to update text format to apply fo…
  scripts/content/VACMS-7662-node-regional_health_care_service_des-force-limited-rich-text.php
Labels: ⭐️ Facilities
