Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2022-05, with the labels that each got.

#8936 Add every minute task
  tasks-periodic.yml
Labels: Platform CMS Team

#7661 VACMS-6828 convert vamc service desc to rich text limited [5/3]
  config/sync/field.field.node.regional_health_care_service_des.field_body.yml
Labels: Content ops, Sitewide crew, DO NOT MERGE, Awaiting Official Launch

#7421 VACMS-7341 Generate top task pages.
  config/sync/user.role.content_editor.yml
  config/sync/user.role.content_publisher.yml
  config/sync/user.role.content_reviewer.yml
  docroot/modules/custom/va_gov_vamc/va_gov_vamc.install
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: DO NOT MERGE, Awaiting Official Launch

#8961 VACMS-8518: Exclude parent item menu from accessibility tests.
  tests/cypress/integration/accessibility/nodeCreationAccessibility.spec.js
Labels: Automated testing, Platform CMS Team, ⭐️ Sitewide CMS

#8951 VACMS-8942 fix button placement for content deploy form
  docroot/modules/custom/va_gov_build_trigger/css/build_trigger_form.css
Labels: ⭐️ Sitewide CMS

#8963 VACMS-8956: Add new covid status taxonomy.
  config/sync/core.entity_form_display.taxonomy_term.facility_supplemental_status.default.yml
  config/sync/core.entity_view_display.node.landing_page.default.yml
  config/sync/core.entity_view_display.taxonomy_term.facility_supplemental_status.default.yml
  config/sync/field.field.taxonomy_term.facility_supplemental_status.field_administration.yml
  config/sync/field.field.taxonomy_term.facility_supplemental_status.field_enforce_unique_id.yml
  config/sync/field.field.taxonomy_term.facility_supplemental_status.field_guidance.yml
  config/sync/field.field.taxonomy_term.facility_supplemental_status.field_status_id.yml
  config/sync/field.storage.taxonomy_term.field_administration.yml
  config/sync/field.storage.taxonomy_term.field_enforce_unique_id.yml
  config/sync/field.storage.taxonomy_term.field_guidance.yml
  config/sync/field.storage.taxonomy_term.field_status_id.yml
  config/sync/node_link_report.settings.yml
  config/sync/taxonomy.vocabulary.facility_supplemental_status.yml
  tests/behat/drupal-spec-tool/content_model_bundles.feature
  tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature
Labels: ⭐️ Facilities, vsa-facilities

#8999 VACMS-8949: Add covid status er select field.
  config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_form_display.node.health_care_local_facility.inline_entity_form.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.external_content.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.ief_table.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.teaser.yml
  config/sync/field.field.node.health_care_local_facility.field_operating_status_facility.yml
  config/sync/field.field.node.health_care_local_facility.field_operating_status_more_info.yml
  config/sync/field.field.node.health_care_local_facility.field_supplemental_status.yml
  config/sync/field.storage.node.field_supplemental_status.yml
  config/sync/views.view.health_care_service_names_and_descriptions.yml
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
  tests/behat/drupal-spec-tool/views.feature
Labels: VAMC, ⭐️ Facilities

#9040 VACMS-9039: remove care we provide feature flag
  config/sync/feature_toggle.features.yml
Labels: ⭐️ Facilities

#9038 add no-op placeholder routes for content release notifications
  docroot/modules/custom/va_gov_build_trigger/src/Controller/PlaceholderController.php
  docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.routing.yml
Labels: Platform CMS Team

#9051 VACMS-9047 facility status dupes
  config/sync/views.view.facility_services.yml
Labels: ⭐️ Facilities

#8994 VACMS-8682 storybook button + inputs examples
  docroot/design-system/.storybook/claro.css
  docroot/design-system/.storybook/claro.scss
  docroot/design-system/.storybook/cssVariables.json
  docroot/design-system/.storybook/preview.js
  docroot/design-system/.storybook/storybook-styles.scss
  docroot/design-system/components/block/block.scss
  docroot/design-system/components/block/block.stories.js
  docroot/design-system/components/block/block.twig
  docroot/design-system/components/button/button.scss
  docroot/design-system/components/button/button.stories.js
  docroot/design-system/components/button/index.js
  docroot/design-system/components/button/sb-buttons.twig
  docroot/design-system/components/design-system.js
  docroot/design-system/components/icon/icons.stories.js
  docroot/design-system/components/icon/index.js
  docroot/design-system/components/input/index.js
  docroot/design-system/components/input/input.scss
  docroot/design-system/components/input/input.stories.js
  docroot/design-system/components/input/sb-inputs.twig
  docroot/design-system/components/tokens/_variables.scss
  docroot/design-system/components/tokens/sb-colors.twig
  docroot/design-system/stories/starting.stories.mdx
  docroot/themes/custom/vagovclaro/assets/scss/components/_buttons.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_elements.scss
  docroot/themes/custom/vagovclaro/assets/scss/tokens/_variables.scss
Labels: ⭐️ Sitewide CMS

#9121 VACMS-9117: Update sup status filters.
  config/sync/views.view.facility_services.yml
Labels: ⭐️ Facilities

#9095 Switch to using repository dispatch instead of workflow dispatch
  composer.json
  docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRD.php
  docroot/modules/custom/va_gov_consumers/src/Git/GithubAdapter.php
  docroot/modules/custom/va_gov_consumers/src/Git/GithubInterface.php
Labels: Platform CMS Team

#9167 Enable basic auth for placeholder routes
  docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.info.yml
  docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.routing.yml
Labels: Platform CMS Team

#9224 VACMS-7726: push VA system's health connect phone number to Facility …
  docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php
  docroot/modules/custom/va_gov_post_api/va_gov_post_api.module
  tests/phpunit/Content/FacilityStatusQueueTest.php
Labels: ⭐️ Facilities

#9205 [docs] VACMS-9084: Created content-audit.md issue template for PW team
  .github/ISSUE_TEMPLATE/content-audit.md
Labels: ⭐️ Public Websites

#9244 VACMS-9160: Add covid status preview to facility form.
  config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
  config/sync/node_link_report.settings.yml
  docroot/modules/custom/va_gov_vamc/css/set_covid_term_text.css
  docroot/modules/custom/va_gov_vamc/js/set_covid_term_text.es6.js
  docroot/modules/custom/va_gov_vamc/js/set_covid_term_text.js
  docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_vamc/va_gov_vamc.libraries.yml
  docroot/modules/custom/va_gov_vamc/va_gov_vamc.services.yml
Labels: ⭐️ Facilities

#9257 VACMS-9249: Add publish function for update hooks.
  docroot/modules/custom/va_gov_db/va_gov_db.install
Labels: ⭐️ Sitewide CMS

#9245 VACMS-4101: Add some debugging information to drupalSettings for nodes to make JSON:API development easier.
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Platform CMS Team

#9266 VACMS-9207: Remove deprecated hours field.
  config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_form_display.node.health_care_local_facility.inline_entity_form.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.external_content.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.ief_table.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.teaser.yml
  config/sync/field.field.node.health_care_local_facility.field_facility_hours.yml
  config/sync/field.storage.node.field_facility_hours.yml
  docroot/modules/custom/va_gov_db/va_gov_db.install
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
Labels: ⭐️ Facilities

#9163 VACMS-8682 re-add SB stuff that was reverted. no performance hit
  docroot/design-system/.storybook/claro.css
  docroot/design-system/.storybook/claro.scss
  docroot/design-system/.storybook/cssVariables.json
  docroot/design-system/.storybook/preview.js
  docroot/design-system/.storybook/storybook-styles.scss
  docroot/design-system/components/block/block.scss
  docroot/design-system/components/block/block.stories.js
  docroot/design-system/components/block/block.twig
  docroot/design-system/components/button/button.scss
  docroot/design-system/components/button/button.stories.js
  docroot/design-system/components/button/index.js
  docroot/design-system/components/button/sb-buttons.twig
  docroot/design-system/components/design-system.js
  docroot/design-system/components/icon/index.js
  docroot/design-system/components/input/index.js
  docroot/design-system/components/input/input.scss
  docroot/design-system/components/input/input.stories.js
  docroot/design-system/components/input/sb-inputs.twig
  docroot/design-system/components/tokens/_variables.scss
  docroot/design-system/components/tokens/sb-colors.twig
  docroot/design-system/stories/starting.stories.mdx
  docroot/themes/custom/vagovclaro/assets/scss/components/_buttons.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_elements.scss
  docroot/themes/custom/vagovclaro/assets/scss/tokens/_variables.scss
Labels: ⭐️ Sitewide CMS

#9264 VACMS-9196: Add EFF field to top of billing page.
  config/sync/core.entity_form_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_view_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_view_display.node.vamc_system_billing_insurance.teaser.yml
  config/sync/field.field.node.vamc_system_billing_insurance.field_cc_above_top_of_page.yml
  config/sync/field.storage.node.field_cc_above_top_of_page.yml
  docroot/themes/custom/vagovclaro/assets/scss/components/_fields.scss
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
Labels: ⭐️ Facilities

#9271 VACMS-8935: Add script to remove tz in hours comments.
  scripts/content/VACMS-8935-scrub-tz-in-hours-field-comment.php
Labels: ⭐️ Facilities
