Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2022-02, with the labels that each got.

#7868 VACMS-6948: Adds patch to explicitly set menu-link bundle. [DO NOT MERGE]
  composer.json
  composer.lock
Labels: Platform CMS Team, Sitewide CMS Team, DO NOT MERGE

#7828 VACMS-7809: Update values in EHR system field to support Cerner in Staging.
  config/sync/field.storage.node.field_vamc_ehr_system.yml
Labels: Sitewide CMS Team

#7831 VACMS-7072 claro text hierarchy
  docroot/themes/custom/vagovclaro/assets/scss/components/_buttons.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_elements.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_layout.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_services.scss
  docroot/themes/custom/vagovclaro/assets/scss/styles.scss
  docroot/themes/custom/vagovclaro/assets/scss/tokens/_mixins.scss
  docroot/themes/custom/vagovclaro/assets/scss/tokens/_typography.scss
  docroot/themes/custom/vagovclaro/assets/scss/tokens/_variables.scss
Labels: Sitewide CMS Team

#7866 VACMS-7746 updated claro color tokens
  docroot/themes/custom/vagovclaro/assets/scss/components/_alerts.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_announcement.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_buttons.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_centralized_content.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_elements.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_flags.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_footer.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_layout.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_paragraphs.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_process_list.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_services.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_toolbar.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_tooltip.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_undo_field_styling.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_views.scss
  docroot/themes/custom/vagovclaro/assets/scss/pages/_kb-pages.scss
  docroot/themes/custom/vagovclaro/assets/scss/pages/_login-page.scss
  docroot/themes/custom/vagovclaro/assets/scss/pages/_node-view.scss
  docroot/themes/custom/vagovclaro/assets/scss/pages/_proofing.scss
  docroot/themes/custom/vagovclaro/assets/scss/pages/_vc-dashboard.scss
  docroot/themes/custom/vagovclaro/assets/scss/tokens/_mixins.scss
  docroot/themes/custom/vagovclaro/assets/scss/tokens/_variables.scss
  docroot/themes/custom/vagovclaro/assets/scss/user_guides.scss
  docroot/themes/custom/vagovclaro/assets/scss/whats_new.scss
  docroot/themes/custom/vagovclaro/assets/scss/wysiwyg.scss
  docroot/themes/custom/vagovclaro/vagovclaro.theme
Labels: Sitewide CMS Team

#7895 VAMCS-7746 more claro mob session fixes
  READMES/debugging.md
  docroot/themes/custom/vagovadmin/package.json
  docroot/themes/custom/vagovadmin/yarn.lock
  docroot/themes/custom/vagovclaro/assets/scss/components/_alerts.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_buttons.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_layout.scss
  docroot/themes/custom/vagovclaro/assets/scss/pages/_kb-pages.scss
  docroot/themes/custom/vagovclaro/assets/scss/tokens/_variables.scss
  docroot/themes/custom/vagovclaro/package.json
  docroot/themes/custom/vagovclaro/templates/components/_alert.html.twig
  docroot/themes/custom/vagovclaro/yarn.lock
Labels: Sitewide CMS Team

#7909 VACMS-7905: Fix broken textarea desriptions.
  docroot/themes/custom/vagovadmin/templates/form/form-element--textarea.html.twig
Labels: Sitewide CMS Team

#7959 VACMS-7957: Update top task tooltip text.
  config/sync/core.entity_form_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_form_display.node.vamc_system_medical_records_offi.default.yml
  config/sync/core.entity_form_display.node.vamc_system_policies_page.default.yml
  config/sync/core.entity_form_display.node.vamc_system_register_for_care.default.yml
  config/sync/core.entity_view_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_view_display.node.vamc_system_medical_records_offi.default.yml
  config/sync/core.entity_view_display.node.vamc_system_policies_page.default.yml
  config/sync/core.entity_view_display.node.vamc_system_register_for_care.default.yml
Labels: Sitewide CMS Team

#7952 VACMS-4541: Limit VC selector to admin option.
  docroot/modules/custom/va_gov_vet_center/js/limit_vet_services_to_user_sections.es6.js
  docroot/modules/custom/va_gov_vet_center/js/limit_vet_services_to_user_sections.js
  docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.libraries.yml
Labels: Sitewide CMS Team

#7947 VACMS-5522: Prevent outputting empty clp panels on node view.
  config/sync/core.extension.yml
  docroot/modules/custom/va_gov_clp/va_gov_clp.info.yml
  docroot/modules/custom/va_gov_clp/va_gov_clp.module
Labels: Sitewide CMS Team

#7940 VACMS-6696: Prevent previews and url links on no bio staff pages.
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  docroot/modules/custom/va_gov_workflow_assignments/src/Plugin/Block/EntityMetaDisplay.php
Labels: Sitewide CMS Team

#7953 VACMS-7245 test dependency updates & vagovclaro test fixes
  docroot/modules/custom/va_gov_backend/js/script.es6.js
  docroot/modules/custom/va_gov_backend/js/script.js
  docroot/modules/custom/va_gov_vet_center/js/script.es6.js
  docroot/modules/custom/va_gov_vet_center/js/script.js
  docroot/themes/custom/vagovclaro/assets/js/anchor_links.es6.js
  docroot/themes/custom/vagovclaro/assets/js/anchor_links.js
  docroot/themes/custom/vagovclaro/assets/js/login-toggle.js
  docroot/themes/custom/vagovclaro/assets/scss/components/_elements.scss
  docroot/themes/custom/vagovclaro/vagovclaro.theme
  package-lock.json
  package.json
  tests/behat/features/user.feature
  tests/behavioral/cypress.json
  tests/behavioral/cypress/integration/common/i_click_the_edit_tab.js
  tests/behavioral/cypress/integration/common/i_create_a_node.js
  tests/behavioral/cypress/integration/common/i_log_back_in.js
  tests/behavioral/cypress/support/commands.js
Labels: Platform CMS Team, Sitewide CMS Team

#8064 VACMS-7539: Reenable tokens in node view for destination path.
  config/sync/views.view.vet_center_facility_listing.yml
Labels: Sitewide CMS Team

#8089 VACMS-000: Change alert link color to black.
  docroot/themes/custom/vagovadmin/assets/scss/styles.scss
Labels: Sitewide CMS Team

#8041 VACMS-5119: Disable the menu option of the "media_list_videos" content type
  config/sync/node.type.media_list_videos.yml
Labels: ⭐️ Content ops

#8072 VACMS-4787: Disable "Administer media" permission for "Content Admin" role
  config/sync/user.role.content_admin.yml
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Sitewide CMS Team

#8063 VACMS-7888: Append system name to facility in autocomplete.
  docroot/modules/custom/va_gov_vamc/src/Controller/EntityAutocompleteController.php
  docroot/modules/custom/va_gov_vamc/src/EntityAutocompleteMatcher.php
  docroot/modules/custom/va_gov_vamc/src/Routing/AutocompleteRouteSubscriber.php
  docroot/modules/custom/va_gov_vamc/va_gov_vamc.services.yml
Labels: Sitewide CMS Team

#8055 VACMS-7744 enable claro [2/22]
  READMES/development-best-practices.md
  READMES/project-conventions.md
  config/sync/system.theme.yml
  docroot/themes/custom/vagovclaro/README.md
  tests/behavioral/cypress.json
Labels: Awaiting Official Launch

#8117 Removes platform-overrides section from composer.lock
  composer.lock
Labels: Platform CMS Team, Sitewide CMS Team

#8022 Adds field_office_id and field_parent_office to Office content type
  config/sync/core.entity_form_display.node.office.default.yml
  config/sync/core.entity_view_display.node.office.default.yml
  config/sync/core.entity_view_display.node.office.teaser.yml
  config/sync/field.field.node.office.field_office_id.yml
  config/sync/field.field.node.office.field_parent_office.yml
  config/sync/field.storage.node.field_office_id.yml
  config/sync/field.storage.node.field_parent_office.yml
  tests/behat/drupal-spec-tool/content_model_outreach_hub_content_type_fields.feature
Labels: ⭐️ Offices

#8137 VACMS-7995: Disable Entity Embed module in Rich Text editor
  config/sync/filter.format.rich_text.yml
Labels: ⭐️ Content ops

#8021 VACMS-6860: Update media view to include alt text.
  config/sync/views.view.media.yml
  config/sync/views.view.media_images.yml
  tests/behat/drupal-spec-tool/views.feature
Labels: ⭐️ Content ops

#8030 Office csv import
  config/sync/migrate_plus.migration.office.yml
  config/sync/migrate_plus.migration_group.office.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.office.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration_group.office.yml
  docroot/modules/custom/va_gov_migrate/data/office-salesforce.csv
Labels: DO NOT MERGE, ⭐️ Offices

#8013 VACMS-6980: Add PDF audit view.
  config/sync/views.view.pdf_audit.yml
  tests/behat/drupal-spec-tool/views.feature
Labels: ⭐️ Content ops

#7987 VACMS-7092: Cleanup node module permissions
  config/sync/user.role.content_admin.yml
  config/sync/user.role.content_creator_vet_center.yml
  config/sync/user.role.content_editor.yml
  config/sync/user.role.content_publisher.yml
  config/sync/user.role.content_reviewer.yml
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: ⭐️ Content ops

#8110 VACMS-7660: Unhide EHR and VA Health Connect fields.
  config/sync/core.entity_form_display.node.health_care_region_page.default.yml
  config/sync/core.entity_view_display.node.health_care_region_page.default.yml
  config/sync/core.entity_view_display.node.health_care_region_page.external_content.yml
  config/sync/field.field.node.health_care_region_page.field_va_health_connect_phone.yml
  config/sync/field.field.node.health_care_region_page.field_vamc_ehr_system.yml
  config/sync/field.storage.node.field_vamc_ehr_system.yml
  docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
  docroot/themes/custom/vagovclaro/assets/scss/components/_external_content.scss
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
Labels: Sitewide CMS Team

#8169 VACMS-7995: Remove "Entity Embed" module from code base
  composer.json
  composer.lock
Labels: ⭐️ Content ops
