Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2022-12, with the labels that each got.

#11751 VACMS-11726: make VAMC alert checkbox list alpha sort and cleanup
  config/sync/views.view.vamc_operating_statuses.yml
Labels: ⭐️ Facilities

#11763 VACMS-11072: Disables search block
  config/sync/block.block.vagovclaro_knowledge_base_search_form.yml
Labels: ⭐️ Facilities

#11696 VACMS-11516 vba show services description facility view
  config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.vba_facility_service.yml
  config/sync/core.entity_view_mode.taxonomy_term.vba_facility_service.yml
  config/sync/core.extension.yml
  docroot/modules/custom/va_gov_vba_facility/css/vba_facility_service.css
  docroot/modules/custom/va_gov_vba_facility/src/EventSubscriber/VbaFacilitySubscriber.php
  docroot/modules/custom/va_gov_vba_facility/va_gov_vba_facility.info.yml
  docroot/modules/custom/va_gov_vba_facility/va_gov_vba_facility.libraries.yml
  docroot/modules/custom/va_gov_vba_facility/va_gov_vba_facility.module
  docroot/modules/custom/va_gov_vba_facility/va_gov_vba_facility.services.yml
Labels: ⭐️ Facilities

#11769 VACMS-000: Delete .composer-cache directory
  .composer-cache/README.md
Labels: Platform CMS Team

#11879 VACMS-11049: Fix 'attributes' error.
  docroot/themes/custom/vagovclaro/templates/field/field--node--field-products.html.twig
Labels: ⭐️ Sitewide CMS

#11899 VACMS-11506: updated outdated content report
  composer.json
  composer.lock
  config/sync/views.view.content.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  tests/behat/drupal-spec-tool/views.feature
Labels: ⭐️ Sitewide CMS

#11888 VACMS-11850: lovell federal health care system should not be editable…
  docroot/modules/custom/va_gov_lovell/src/EventSubscriber/LovellEventSubscriber.php
Labels: ⭐️ Facilities

#11920 VACMS-11744: external link status report view added
  config/sync/views.view.managed_links.yml
  tests/behat/drupal-spec-tool/views.feature
Labels: ⭐️ Sitewide CMS

#11925 VACMS-11425: orphaned paragraphs report
  config/sync/views.view.orphaned_paragraphs.yml
  docroot/modules/custom/va_gov_backend/src/EventSubscriber/OrphansReportViewsEventSubscriber.php
  docroot/modules/custom/va_gov_backend/src/EventSubscriber/TableAuditViewsEventSubscriber.php
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  docroot/modules/custom/va_gov_backend/va_gov_backend.services.yml
  tests/behat/drupal-spec-tool/views.feature
Labels: ⭐️ Sitewide CMS

#11944 VACMS-11924: Admin/content displays "Outdated Content" h1 and breadcrumb
  composer.json
  composer.lock
  config/sync/views.view.content.yml
  tests/behat/drupal-spec-tool/views.feature
Labels: ⭐️ Sitewide CMS

#11949 Update GHA to new output syntax.
  .github/actions/post-checkout/action.yml
  .github/workflows/contextual-advice.yml
  .github/workflows/default-branch-datadog-metrics.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/s3-backup-retention.yml
Labels: Platform CMS Team, ⭐️ Sitewide CMS

#12037 VACMS-12035: Last-saved-by-an-editor block rampaging unchecked throughout CMS
  docroot/themes/custom/vagovclaro/templates/page/page--node.html.twig
Labels: ⭐️ Sitewide CMS

#12121 VACMS-9396: fixes related articles section of kb articles
  config/sync/core.entity_view_display.node.documentation_page.default.yml
  config/sync/field.field.node.documentation_page.field_related_user_guides.yml
  docroot/themes/custom/vagovclaro/assets/scss/user_guides.scss
  docroot/themes/custom/vagovclaro/templates/field/field--node--field-related-user-guides.html.twig
  docroot/themes/custom/vagovclaro/templates/page/page--documentation-page.html.twig
  tests/behat/drupal-spec-tool/content_model_user_guides_content_type_fields.feature
Labels: ⭐️ Sitewide CMS
