Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2023-09, with the labels that each got.

#14841 VACMS-10111: Adds configurable heading functionality to views pagers
  composer.json
  composer.lock
  tests/cypress/integration/features/platform/configurable_pager_heading.feature
Labels: CMS Team

#15094 VACMS-00000: update simplsamlphp to 1.19
  composer.json
  composer.lock
Labels: DevOps, Drupal engineering, Critical defect, CMS Team

#15121 VACMS-15134: locked graphql to v3.1.0
  composer.json
  composer.lock
Labels: Drupal engineering, CMS Team

#15132 VACMS-14149: Add Vet Center facility services push
  docroot/modules/custom/va_gov_post_api/src/Form/VaGovFacilityForceQueueForm.php
  docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityServiceBase.php
  docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityServiceVamc.php
  docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityServiceVetCenter.php
  docroot/modules/custom/va_gov_post_api/va_gov_post_api.module
  docroot/modules/custom/va_gov_post_api/va_gov_post_api.services.yml
Labels: Facilities

#15289 VACMS-15287: upgrade storybook
  docroot/design-system/package-lock.json
  docroot/design-system/package.json
  scripts/compile-theme.sh
Labels: CMS Team

#15293 VACMS-0000: Resync stray config changes to code
  config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_form_display.node.checklist.default.yml
  config/sync/core.entity_form_display.node.media_list_images.default.yml
  config/sync/core.entity_form_display.node.media_list_videos.default.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
  config/sync/node_link_report.settings.yml
  config/sync/views.view.date_fields.yml
  config/sync/views.view.detail_page_url_audit_and_bulk_udpate.yml
  config/sync/views.view.flagged_content_va_forms.yml
  config/sync/views.view.image_style_warmer_warmup_files.yml
  config/sync/views.view.knowledge_base_article_administration.yml
  config/sync/views.view.media.yml
  config/sync/views.view.section_export.yml
Labels: Drupal engineering

#15311 VACMS-15298: fix theme not compiling
  scripts/compile-theme.sh
Labels: Drupal engineering, CMS Team

#15334 VACMS-15332: upgrade drupal core
  composer.json
  composer.lock
Labels: Drupal engineering, CMS Team

#15343 VACMS-00000: added CMS-SSOi-IA doc to repo
  project-documents/CMS_SSOi_IA.docx
  project-documents/README.md
Labels: CMS Team

#15274 VACMS-15062 add field_administration back to jsonapi responses
  config/sync/jsonapi_extras.jsonapi_resource_config.node--banner.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.node--full_width_banner_alert.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.node--news_story.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.node--person_profile.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.node--promo_banner.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.node--story_listing.yml
Labels: Accelerated Publishing, CMS Team

#15046 Updating Research Runbook templates
  .github/ISSUE_TEMPLATE/ap-defect.md
  .github/ISSUE_TEMPLATE/research-plan-and-conversation-guide.md
  .github/ISSUE_TEMPLATE/research-readout-and-documentation.md
  .github/ISSUE_TEMPLATE/research-recruitment-and-scheduling.md
  .github/ISSUE_TEMPLATE/research-review-cycle.md
  .github/ISSUE_TEMPLATE/research-sessions.md
  .github/ISSUE_TEMPLATE/research-synthesis-and-topline-summary.md
  .github/ISSUE_TEMPLATE/runbook---ux-research.md
Labels: Research, UX

#15356 VACMS-14703: VBA facility service changes
  config/sync/core.entity_form_display.node.vba_facility_service.default.yml
  config/sync/core.entity_form_display.node.vba_facility_service.inline_entity_form.yml
  config/sync/core.entity_view_display.node.vba_facility_service.default.yml
  config/sync/core.entity_view_display.node.vba_facility_service.search_index.yml
  config/sync/core.entity_view_display.node.vba_facility_service.teaser.yml
  config/sync/field.field.node.vba_facility_service.field_body.yml
  config/sync/field.field.node.vba_facility_service.field_service_location.yml
  docroot/modules/custom/va_gov_facilities/css/css_tooltip.css
  docroot/modules/custom/va_gov_facilities/css/health_service.css
  docroot/modules/custom/va_gov_facilities/js/displayServiceDescriptions.es6.js
  docroot/modules/custom/va_gov_facilities/js/displayServiceDescriptions.js
  docroot/modules/custom/va_gov_facilities/src/EventSubscriber/FacilitiesSubscriber.php
  docroot/modules/custom/va_gov_vba_facility/src/EventSubscriber/VbaFacilitySubscriber.php
Labels: Facilities

#15421 VACMS-11230: Follow up to remove debugging code
  docroot/modules/custom/va_gov_block_types/va_gov_block_types.module
Labels: Public Websites

#15193 VACMS-15055: Accelerated Publishing Install and enable computed_breadcrumbs.
  READMES/jsonapi.md
  composer.json
  composer.lock
  config/sync/core.entity_view_display.node.banner.default.yml
  config/sync/core.entity_view_display.node.basic_landing_page.default.yml
  config/sync/core.entity_view_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_view_display.node.centralized_content.default.yml
  config/sync/core.entity_view_display.node.checklist.default.yml
  config/sync/core.entity_view_display.node.documentation_page.default.yml
  config/sync/core.entity_view_display.node.event.default.yml
  config/sync/core.entity_view_display.node.event_listing.default.yml
  config/sync/core.entity_view_display.node.faq_multiple_q_a.default.yml
  config/sync/core.entity_view_display.node.full_width_banner_alert.default.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_view_display.node.health_care_local_health_service.default.yml
  config/sync/core.entity_view_display.node.health_care_region_detail_page.default.yml
  config/sync/core.entity_view_display.node.health_care_region_page.default.yml
  config/sync/core.entity_view_display.node.health_services_listing.default.yml
  config/sync/core.entity_view_display.node.landing_page.default.yml
  config/sync/core.entity_view_display.node.leadership_listing.default.yml
  config/sync/core.entity_view_display.node.locations_listing.default.yml
  config/sync/core.entity_view_display.node.media_list_images.default.yml
  config/sync/core.entity_view_display.node.media_list_videos.default.yml
  config/sync/core.entity_view_display.node.nca_facility.default.yml
  config/sync/core.entity_view_display.node.news_story.default.yml
  config/sync/core.entity_view_display.node.office.default.yml
  config/sync/core.entity_view_display.node.outreach_asset.default.yml
  config/sync/core.entity_view_display.node.page.default.yml
  config/sync/core.entity_view_display.node.person_profile.default.yml
  config/sync/core.entity_view_display.node.press_release.default.yml
  config/sync/core.entity_view_display.node.press_releases_listing.default.yml
  config/sync/core.entity_view_display.node.promo_banner.default.yml
  config/sync/core.entity_view_display.node.publication_listing.default.yml
  config/sync/core.entity_view_display.node.q_a.default.yml
  config/sync/core.entity_view_display.node.regional_health_care_service_des.default.yml
  config/sync/core.entity_view_display.node.service_region.default.yml
  config/sync/core.entity_view_display.node.step_by_step.default.yml
  config/sync/core.entity_view_display.node.story_listing.default.yml
  config/sync/core.entity_view_display.node.support_resources_detail_page.default.yml
  config/sync/core.entity_view_display.node.support_service.default.yml
  config/sync/core.entity_view_display.node.va_form.default.yml
  config/sync/core.entity_view_display.node.vamc_operating_status_and_alerts.default.yml
  config/sync/core.entity_view_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_view_display.node.vamc_system_medical_records_offi.default.yml
  config/sync/core.entity_view_display.node.vamc_system_policies_page.default.yml
  config/sync/core.entity_view_display.node.vamc_system_register_for_care.default.yml
  config/sync/core.entity_view_display.node.vba_facility.default.yml
  config/sync/core.entity_view_display.node.vba_facility_service.default.yml
  config/sync/core.entity_view_display.node.vet_center.default.yml
  config/sync/core.entity_view_display.node.vet_center_cap.default.yml
  config/sync/core.entity_view_display.node.vet_center_facility_health_servi.default.yml
  config/sync/core.entity_view_display.node.vet_center_locations_list.default.yml
  config/sync/core.entity_view_display.node.vet_center_mobile_vet_center.default.yml
  config/sync/core.entity_view_display.node.vet_center_outstation.default.yml
  config/sync/core.entity_view_display.node.vha_facility_nonclinical_service.default.yml
  config/sync/core.extension.yml
  config/sync/easy_breadcrumb.settings.yml
Labels: Accelerated Publishing

#15441 VACMS-9919: Fixes visual focus styles on node edit form unlock button
  docroot/themes/custom/vagovclaro/assets/scss/components/_buttons.scss
Labels: CMS Team

#15451 VACMS-15447: fixed php error in orphans report
  config/sync/views.view.orphaned_paragraphs.yml
  docroot/modules/custom/va_gov_backend/src/EventSubscriber/OrphansReportViewsEventSubscriber.php
Labels: Defect, CMS Team
