Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2023-08, with the labels that each got.

#14583 VACMS-14405 add patches for jsonapi
  composer.json
  composer.lock
Labels: Accelerated Publishing, CMS Team

#14808 VACMS-11001: Updates custom module va_gov_db to be D10-compliant
  docroot/modules/custom/va_gov_db/va_gov_db.install
Labels: CMS Team

#14867 VACMS-14857: Adds force push argument upstream. Moves log file creation.
  docroot/modules/custom/va_gov_post_api/src/Form/VaGovFacilityForceQueueForm.php
  docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityService.php
  docroot/modules/custom/va_gov_post_api/va_gov_post_api.module
Labels: Facilities

#14873 VACMS-14779: jsonapi banners
  READMES/jsonapi.md
  config/sync/jsonapi_extras.jsonapi_resource_config.block_content--cms_announcement.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.cm_document--cm_document.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.entity_view_display--entity_view_display.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.flagging--awaiting_csv.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.flagging--awaiting_editor.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.flagging--awaiting_redirect.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.flagging--changed_filename.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.flagging--changed_name.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.flagging--changed_title.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.flagging--deleted.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.flagging--edited.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.flagging--email_node.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.flagging--email_term.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.flagging--email_user.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.flagging--new.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.flagging--new_form.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.flagging--removed_from_source.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.flagging--subscribe_node.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.flagging--subscribe_term.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.flagging--subscribe_user.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.media--image.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.message--va_facility_new_facility.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.message--va_facility_removed_from_source.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.message--va_facility_title_change.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.message--va_form_changed_title.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.message--va_form_changed_url.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.message--va_form_deleted.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.message--va_form_new_form.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.message--va_outdated_content.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.message--vamc_outdated_content.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.message--vet_center_official_name_change.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.message--vet_center_outdated_content.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.message_template--message_template.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.node--banner.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.node--full_width_banner_alert.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.node--news_story.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.node--person_profile.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.node--promo_banner.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.node--story_listing.yml
  docroot/modules/custom/va_gov_api/src/Resources/BannerAlerts.php
Labels: Accelerated Publishing, CMS Team

#14905 VACMS-14902: Adds config for logging and timeout.
  config/sync/post_api.settings.yml
  docroot/modules/custom/va_gov_post_api/config/install/va_gov_post_api.settings.yml
  docroot/modules/custom/va_gov_post_api/src/Form/VaGovPostApiSettingsForm.php
  docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityBase.php
  docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityService.php
Labels: Facilities

#14949 VACMS-13980: Excludes archived facilities from 2 views
  config/sync/views.view.content_entity_reference_source.yml
  config/sync/views.view.local_facilities_entity_reference_view.yml
Labels: Facilities

#14989 VACMS-14961: fix for remaining deprecations in custom code
  docroot/modules/custom/va_gov_db/va_gov_db.install
  docroot/modules/custom/va_gov_preview/src/Encoder/StaticEncoder.php
  docroot/modules/custom/va_gov_preview/src/StaticServiceProvider.php
  docroot/themes/custom/vagovclaro/assets/js/inline_guidance.es6.js
  docroot/themes/custom/vagovclaro/assets/js/inline_guidance.js
  docroot/themes/custom/vagovclaro/templates/node/node--full.html.twig
  docroot/themes/custom/vagovclaro/templates/node/node--health_care_local_health_service--teaser.html.twig
  docroot/themes/custom/vagovclaro/templates/node/node--landing-page--support-services-listing.html.twig
  docroot/themes/custom/vagovclaro/templates/node/node--landing-page--teaser.html.twig
  docroot/themes/custom/vagovclaro/templates/node/node--office--connect-with-us.html.twig
  docroot/themes/custom/vagovclaro/templates/node/node--page.html.twig
  docroot/themes/custom/vagovclaro/templates/node/node--regional_health_care_service_des--teaser.html.twig
  docroot/themes/custom/vagovclaro/templates/node/node--support-service--support-services-listing.html.twig
  docroot/themes/custom/vagovclaro/templates/node/node--va-form--full.html.twig
  docroot/themes/custom/vagovclaro/vagovclaro.info.yml
  docroot/themes/custom/vagovclaro/vagovclaro.libraries.yml
Labels: Drupal engineering, CMS Team

#14956 VACMS-13679: Sunset COVID health status in Drupal
  config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
  docroot/modules/custom/va_gov_vamc/src/EventSubscriber/VAMCEntityEventSubscriber.php
  scripts/content/VACMS-13679-wipe-out-covid-status-data.php
  scripts/content/script-library.php
  tests/cypress/integration/features/content_type/health_care_local_facility.feature
Labels: Facilities

#15008 VACMS-14702: Add VBA related fields to service taxonomy
  config/sync/core.entity_form_display.taxonomy_term.health_care_service_taxonomy.default.yml
  config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.default.yml
  config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.vamc_facility_service.yml
  config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.vba_facility_service.yml
  config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.vet_center_service.yml
  config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_online_self_service.yml
  config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_vba_type_of_care.yml
  config/sync/field.field.taxonomy_term.va_benefits_taxonomy.field_va_benefit_eligibility_ov.yml
  config/sync/field.storage.taxonomy_term.field_online_self_service.yml
  config/sync/field.storage.taxonomy_term.field_vba_type_of_care.yml
Labels: Facilities
