Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2023-10, with the labels that each got.

#15464 VACMS-000 Remove Pittsburgh VAMC as default value on VAMC operating status node
  config/sync/field.field.node.vamc_operating_status_and_alerts.field_office.yml
Labels: VAMC, Drupal engineering, Facilities

#15487 15471 Implement Snyk security scanning
  LICENSE.txt
  docroot/design-system/package.json
  docroot/themes/custom/vagovclaro/package.json
  package.json
Labels: DevOps, Drupal engineering, CMS Team

#15361 VACMS-15245: Set up user and role for Next/Drupal CMS Preview.
  config/sync/system.action.user_add_role_action.next_js.yml
  config/sync/system.action.user_remove_role_action.next_js.yml
  config/sync/user.role.next_js.yml
Labels: Accelerated Publishing

#15466 VACMS-15088: Removes the covid_url from payload
  docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php
Labels: VAMC, Facilities, COVID-19

#15528 VACMS-14699: Adding a Entity Field Fetch fields for VBA Centralized content
  config/sync/core.entity_form_display.node.vba_facility.default.yml
  config/sync/core.entity_view_display.node.nca_facility.default.yml
  config/sync/core.entity_view_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_view_display.node.vba_facility.default.yml
  config/sync/core.entity_view_display.node.vba_facility.external_content.yml
  config/sync/core.entity_view_display.node.vba_facility.ief_table.yml
  config/sync/core.entity_view_display.node.vba_facility.teaser.yml
  config/sync/core.entity_view_display.node.vba_facility_service.default.yml
  config/sync/field.field.node.vba_facility.field_cc_benefit_office_hours_va.yml
  config/sync/field.field.node.vba_facility.field_cc_benefits_hotline.yml
  config/sync/field.field.node.vba_facility.field_cc_cant_find_benefits.yml
  config/sync/field.field.node.vba_facility.field_cc_get_updates_from_vba.yml
  config/sync/field.field.node.vba_facility.field_cc_national_spotlight_1.yml
  config/sync/field.field.node.vba_facility.field_cc_national_spotlight_2.yml
  config/sync/field.field.node.vba_facility.field_cc_national_spotlight_3.yml
  config/sync/field.field.node.vba_facility.field_cc_vba_facility_overview.yml
  config/sync/field.storage.node.field_cc_benefit_office_hours_va.yml
  config/sync/field.storage.node.field_cc_benefits_hotline.yml
  config/sync/field.storage.node.field_cc_cant_find_benefits.yml
  config/sync/field.storage.node.field_cc_get_updates_from_vba.yml
  config/sync/field.storage.node.field_cc_national_spotlight_1.yml
  config/sync/field.storage.node.field_cc_national_spotlight_2.yml
  config/sync/field.storage.node.field_cc_national_spotlight_3.yml
  config/sync/field.storage.node.field_cc_vba_facility_overview.yml
Labels: Facilities

#15600 VACMS-15597 Add field_diagram to CMDocument.
  config/sync/core.entity_form_display.cm_document.cm_document.default.yml
  config/sync/core.entity_view_display.cm_document.cm_document.default.yml
  config/sync/field.field.cm_document.cm_document.field_diagram.yml
  config/sync/field.storage.cm_document.field_diagram.yml
Labels: Facilities

#15599 VACMS-14704: Adding service location fields
  config/sync/core.entity_form_display.paragraph.service_location.default.yml
  config/sync/core.entity_view_display.paragraph.service_location.default.yml
  config/sync/field.field.paragraph.service_location.field_service_delivery_options.yml
  config/sync/field.field.paragraph.service_location.field_service_location_descripti.yml
  config/sync/field.field.paragraph.service_location.field_task_oriented_header.yml
  config/sync/field.storage.paragraph.field_service_delivery_options.yml
  config/sync/field.storage.paragraph.field_service_location_descripti.yml
  config/sync/field.storage.paragraph.field_task_oriented_header.yml
  config/sync/language.content_settings.taxonomy_term.service_delivery_options.yml
  config/sync/taxonomy.vocabulary.service_delivery_options.yml
Labels: Facilities, Needs PO review

#15727 VACMS-11267 - Create Taxonomy runbooks
  .github/ISSUE_TEMPLATE/taxonomy-add-term.yml
Labels: Facilities, VA services taxonomy, VA Benefits Taxonomy

#15716 VACMS-15422: Makes Vet Center - Outstation names more like Vet Center
  config/sync/core.base_field_override.node.vet_center_outstation.title.yml
  config/sync/core.entity_form_display.node.vet_center_outstation.default.yml
  config/sync/core.entity_view_display.node.vet_center_outstation.default.yml
  config/sync/core.entity_view_display.node.vet_center_outstation.external_content.yml
  config/sync/core.entity_view_display.node.vet_center_outstation.teaser.yml
  config/sync/field.field.node.vet_center_outstation.field_official_name.yml
  config/sync/migrate_plus.migration.va_node_facility_vet_centers_os.yml
  config/sync/node.type.vet_center_outstation.yml
  docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers_os.yml
  docroot/modules/custom/va_gov_migrate/va_gov_migrate.module
  docroot/modules/custom/va_gov_vet_center/js/script.es6.js
  docroot/modules/custom/va_gov_vet_center/js/script.js
  docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
  scripts/content/VACMS-15422-vet-center-outstation-copy-title.php
Labels: Facilities

#15761 VACMS-15641 national outreach checkbox
  config/sync/core.entity_form_display.node.event.default.yml
  config/sync/core.entity_view_display.node.event.default.yml
  config/sync/core.entity_view_display.node.event.teaser.yml
  config/sync/feature_toggle.features.yml
  config/sync/field.field.node.event.field_additional_listings.yml
  config/sync/field.field.node.event.field_publish_to_outreach_cal.yml
  config/sync/field.storage.node.field_additional_listings.yml
  config/sync/field.storage.node.field_publish_to_outreach_cal.yml
  docroot/modules/custom/va_gov_events/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_events/va_gov_events.services.yml
  docroot/themes/custom/vagovclaro/assets/scss/components/_fields.scss
  tests/cypress/integration/features/content_type/event.feature
  tests/cypress/integration/features/platform/file_upload.feature
  tests/cypress/integration/step_definitions/common/i_create_a_node.js
  tests/cypress/integration/step_definitions/common/i_set_a_feature_toggle.js
  tests/cypress/support/commands.js
Labels: DO NOT MERGE

#15790 VACMS-13639: Fixes content lock operation on Reusable Q&A Content Type
  config/sync/core.entity_form_display.node.q_a.default.yml
Labels: CMS Team

#15429 VACMS-15240 Stand up running next-build server per tugboat instance
  .gitignore
  .next/403-error-document.j2.html
  .next/503-error-document.j2.html
  .next/README.md
  .next/artur-pokusin-unsplash.jpg
  .tugboat/config.yml
  .tugboat/vhost-next.conf
  composer.json
  scripts/next-build.sh
  scripts/next-install.sh
  scripts/next-start.sh
  tugboat.yml
Labels: Accelerated Publishing, CMS Team
