Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2023-04, with the labels that each got.

#13151 VACMS-13150 Remove path alias truncation in core.path
  composer.json
  composer.lock
Labels: Facilities

#13153 VACMS-13152: Reënable CodeQL test.
  .github/workflows/continuous_integration.yml
Labels: CMS Team

#13198 VACMS-13150 Update to more recent core truncation patch.
  composer.json
  composer.lock
Labels: Facilities

#13162 [DOCS] VACMS-13109: Adds new runbook and changes other runbooks.
  .github/ISSUE_TEMPLATE/redirect-request-facility-url.md
  .github/ISSUE_TEMPLATE/runbook-facility-url-change.md
  .github/ISSUE_TEMPLATE/runbook-vamc-facility-duplicate-or-section-change.md
  .github/ISSUE_TEMPLATE/runbook-vamc-facility-name-change.md
  .github/ISSUE_TEMPLATE/runbook-vamc-facility-new.md
  .github/ISSUE_TEMPLATE/runbook-vamc-system-name-change.md
  .github/ISSUE_TEMPLATE/runbook-vet-center-cap-to-outstation.md
  .github/ISSUE_TEMPLATE/runbook-vet-center-name-change.md
  .github/ISSUE_TEMPLATE/runbook-vet-center-new.md
  .github/ISSUE_TEMPLATE/runbook-vet-center-outstation-to-vet-center.md
Labels: Facilities

#13294 VACMS-13226: explicitly set webhost for links in notification email
  docroot/modules/custom/va_gov_notifications/templates/message--va-outdated-content--mail-body.html.twig
  docroot/modules/custom/va_gov_notifications/va_gov_notifications.module
  docroot/sites/default/settings/settings.dev.php
  docroot/sites/default/settings/settings.local.php
  docroot/sites/default/settings/settings.prod.php
  docroot/sites/default/settings/settings.staging.php
  docroot/sites/default/settings/settings.tugboat.php
Labels: CMS Team

#13287 VACMS-13120: Add check and cleanup string to status moreinfo push.
  docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php
Labels: Facilities

#13323 VACMS-13317: Fix saving taxonomy terms, other things.
  docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventAbsoluteCmsLinksValidator.php
  docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventAbsoluteUrlsAsPathsInLinksValidator.php
  docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventDomainsAsPathsInLinksValidator.php
  docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventProtocolRelativeLinksValidator.php
  docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventVaGovDomainsAsPathsInLinksValidator.php
  docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/Traits/TextValidatorTrait.php
Labels: CMS Team

#13367 VACMS-13366: sa-core-2023-005 update drupal core
  composer.lock
  docroot/sites/default/default.settings.php
Labels: CMS Team

#13333 VACMS-13296: D10 with GraphQL v3 Palyground
  composer.json
  composer.lock
  docroot/modules/custom/va_gov_flags/src/Controller/VaGovFlagsController.php
  docroot/modules/custom/va_gov_graphql/assets/explorer/dist/bundle.min.js
  docroot/modules/custom/va_gov_graphql/assets/explorer/package-lock.json
  docroot/modules/custom/va_gov_graphql/assets/explorer/src/index.js
  docroot/modules/custom/va_gov_graphql/assets/explorer/webpack.config.babel.js
  docroot/modules/custom/va_gov_graphql/src/Controller/ExplorerController.php
  docroot/modules/custom/va_gov_graphql/va_gov_graphql.libraries.yml
  new.json
  old.json
  package-lock.json
  patches/VACMS-12252-fix-deprecation-for-d10.patch
  patches/graphql3-libraryv14.patch
Labels: DO NOT MERGE, CMS Team

#13054 VACMS-12994: Install node and npm on DDEV and Tugboat
  .ddev/config.yaml
  .nvmrc
  .tugboat/config.yml
  composer.json
  composer.lock
  scripts/install-nvm.sh
  scripts/web-install.sh
Labels: CMS Team

#13028 VACMS-12930: Retool vagovclaro to use webpack, remove gulp
  composer.json
  docroot/themes/custom/vagovclaro/.nvmrc
  docroot/themes/custom/vagovclaro/package-lock.json
  docroot/themes/custom/vagovclaro/package.json
  docroot/themes/custom/vagovclaro/webpack.config.js
  docroot/themes/custom/vagovclaro/yarn.lock
  scripts/compile-theme.sh
Labels: CMS Team

#13335 VACMS-12783: set up monthly cron for outdated content notifications
  tasks-periodic.yml
Labels: CMS Team

#13311 VACMS-10845 Facilities runbook updates
  .github/ISSUE_TEMPLATE/runbook-facility-url-change.md
  .github/ISSUE_TEMPLATE/runbook-vamc-facility-closed.md
  .github/ISSUE_TEMPLATE/runbook-vamc-facility-duplicate-or-section-change.md
  .github/ISSUE_TEMPLATE/runbook-vamc-facility-name-change.md
  .github/ISSUE_TEMPLATE/runbook-vamc-facility-new.md
  .github/ISSUE_TEMPLATE/runbook-vamc-system-name-change.md
  .github/ISSUE_TEMPLATE/runbook-vba-facility-closed.md
  .github/ISSUE_TEMPLATE/runbook-vba-facility-name-change.md
  .github/ISSUE_TEMPLATE/runbook-vba-facility-new.md
  .github/ISSUE_TEMPLATE/runbook-vet-center-cap-to-outstation.md
  .github/ISSUE_TEMPLATE/runbook-vet-center-closed.md
  .github/ISSUE_TEMPLATE/runbook-vet-center-name-change.md
  .github/ISSUE_TEMPLATE/runbook-vet-center-new.md
  .github/ISSUE_TEMPLATE/runbook-vet-center-outstation-to-vet-center.md
Labels: Facilities

#13486 VACMS-13017: tools updated to use npm
  composer.json
  docroot/design-system/package-lock.json
  docroot/design-system/yarn.lock
  scripts/compile-theme.sh
Labels: CMS Team

#13495 VACMS-13494: added nvm commands to web:build and web:install
  scripts/web-build.sh
  scripts/web-install.sh
Labels: CMS Team

#13514 VACMS-13489: Address `loadtest` vulnerability alerts.
  tests/loadtest/Cargo.lock
  tests/loadtest/Cargo.toml
Labels: CMS Team

#13471 VACMS-12640: Updates GHA Syntax
  .github/workflows/continuous_integration.yml
  .github/workflows/cypress.yml
  .github/workflows/default-branch-datadog-metrics.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/pull-request-labels.yml
  .github/workflows/s3-backup-retention.yml
  .github/workflows/set-tugboat-tests-pending.yml
Labels: CMS Team
