Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2023-01, with the labels that each got.

#11988 VACMS-11526: Table audit displays tables that no longer exist on the current node
  config/sync/views.view.tables.yml
  docroot/modules/custom/va_gov_backend/src/EventSubscriber/TableAuditViewsEventSubscriber.php
  docroot/modules/custom/va_gov_backend/va_gov_backend.install
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  docroot/modules/custom/va_gov_backend/va_gov_backend.services.yml
Labels: ⭐️ Sitewide CMS

#11981 VACMS-11980: Winnows Lovell VA distinct from Lovell TRICARE
  docroot/modules/custom/va_gov_backend/js/limit_services_to_user_sections.es6.js
  docroot/modules/custom/va_gov_backend/js/limit_services_to_user_sections.js
  docroot/modules/custom/va_gov_lovell/js/limit_lovell.es6.js
  docroot/modules/custom/va_gov_lovell/js/limit_lovell.js
  docroot/modules/custom/va_gov_lovell/js/remove_lovell_federal.js
  docroot/modules/custom/va_gov_lovell/va_gov_lovell.libraries.yml
  docroot/modules/custom/va_gov_lovell/va_gov_lovell.module
  docroot/themes/custom/vagovclaro/assets/js/modal_accessibility.js
  tests/cypress/integration/behavioral/common/i_am_logged_in_as_a_user_with_the_roles.js
  tests/cypress/integration/behavioral/common/option_from_dropdown_visible.js
  tests/cypress/integration/behavioral/content_editing_vamc_facility_service.feature
  tests/cypress/support/commands.js
Labels: ⭐️ Facilities

#12168 VACMS-11397: fix for help text color and size
  docroot/design-system/components/tokens/_variables.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_elements.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_services.scss
Labels: ⭐️ Sitewide CMS

#12177 VACMS-12108: lovell federal list pages should show urls with links
  docroot/modules/custom/va_gov_backend/src/Service/VaGovUrl.php
  docroot/modules/custom/va_gov_backend/src/Service/VaGovUrlInterface.php
  docroot/modules/custom/va_gov_workflow_assignments/src/Plugin/Block/EntityMetaDisplay.php
  tests/phpunit/Content/EntityMetaDisplayTest.php
  tests/phpunit/Service/VaGovUrlServiceTest.php
Labels: ⭐️ Facilities

#12254 VACMS-11455: change text color for field_label
  docroot/themes/custom/vagovclaro/assets/scss/pages/_proofing.scss
Labels: ⭐️ Sitewide CMS

#12312 Use Drupal package, not source.
  composer.json
Labels: Platform CMS Team, ⭐️ Sitewide CMS

#12283 VACMS-12250: drupal 9.5.2 upgrade
  composer.json
  composer.lock
  docroot/robots.txt
  docroot/sites/default/default.services.yml
  docroot/sites/default/default.settings.php
  docroot/sites/example.settings.local.php
  docroot/web.config
  patches/claro-css-tweaks.patch
  tests/cypress/integration/behavioral/step_definitions.feature
Labels: ⭐️ Sitewide CMS

#12332 VACMS-12286 Add content_model_documentation module and enable.
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/views.view.content_model_fields.yml
  tests/behat/drupal-spec-tool/views.feature
Labels: documentation, CMS Team

#12328 VACMS-12234 Refactor for Lovell name change
  docroot/modules/custom/va_gov_lovell/js/limit_lovell.es6.js
  docroot/modules/custom/va_gov_lovell/js/limit_lovell.js
  docroot/modules/custom/va_gov_lovell/src/EventSubscriber/LovellEventSubscriber.php
  docroot/modules/custom/va_gov_lovell/src/LovellOps.php
  tests/cypress/integration/behavioral/content_editing_vamc_facility_service.feature
Labels: Facilities, DO NOT MERGE

#12344 VACMS-11609: Update cypress definitions for see exist & visible
  tests/cypress/integration/behavioral/common/i_should_see.js
  tests/cypress/integration/behavioral/common/option_from_dropdown_visible.js
  tests/cypress/integration/behavioral/common/should_exist.js
  tests/cypress/integration/behavioral/content_editing.feature
  tests/cypress/integration/behavioral/content_editing_vamc_facility_service.feature
  tests/cypress/integration/behavioral/content_release.feature
  tests/cypress/integration/behavioral/entity_reference_validation.feature
  tests/cypress/integration/behavioral/file_upload.feature
  tests/cypress/integration/behavioral/help_center.feature
  tests/cypress/integration/behavioral/help_center/get_help.js
  tests/cypress/integration/behavioral/help_center/jsd_widget.js
  tests/cypress/integration/behavioral/password_policy.feature
  tests/cypress/integration/behavioral/permissions.feature
  tests/cypress/integration/behavioral/step_definitions.feature
  tests/cypress/integration/behavioral/user_login.feature
Labels: DO NOT MERGE

#12380 VACMS-12379: Adds lovell paths for menu access
  config/sync/va_gov_menu_access.settings.yml
Labels: Facilities
