Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2023-11, with the labels that each got.

#15927 VACMS-15721: added description field for alert blocks view and browser
  config/sync/views.view.custom_block_entity_browsers.yml
  config/sync/views.view.va_blocks_admin.yml
Labels: Drupal engineering, CMS Team

#15450 VACMS-15276: Adds YouTube field
  config/sync/core.entity_form_display.node.health_care_region_page.default.yml
  config/sync/core.entity_view_display.node.health_care_region_page.default.yml
  config/sync/core.entity_view_display.node.health_care_region_page.external_content.yml
  config/sync/core.entity_view_display.node.health_care_region_page.teaser.yml
  config/sync/field.field.node.health_care_region_page.field_youtube.yml
  config/sync/field.storage.node.field_youtube.yml
Labels: Facilities, DO NOT MERGE, Awaiting Official Launch

#15872 VACMS-11334: Implement VBA permissions and Restricted archive workflow
  config/sync/system.action.user_add_role_action.content_creator_vba.yml
  config/sync/system.action.user_remove_role_action.content_creator_vba.yml
  config/sync/user.role.administrator.yml
  config/sync/user.role.admnistrator_users.yml
  config/sync/user.role.content_admin.yml
  config/sync/user.role.content_creator_vba.yml
  config/sync/user.role.content_creator_vet_center.yml
  config/sync/user.role.content_editor.yml
  config/sync/user.role.content_publisher.yml
  config/sync/user.role.content_reviewer.yml
  config/sync/user.role.homepage_manager.yml
  config/sync/user.role.next_js.yml
  config/sync/user.role.redirect_administrator.yml
  config/sync/user.role.translation_manager.yml
  config/sync/workflows.workflow.editorial.yml
  config/sync/workflows.workflow.restricted_archive.yml
  tests/cypress/integration/features/facilities/facilities_api.feature
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: Facilities

#15948 VACMS-15882: Adds default pager heading
  composer.json
  composer.lock
Labels: CMS Team

#15980 VACMS-15979: fix for reusable documents
  config/sync/core.entity_form_display.media.document.default.yml
Labels: Drupal engineering, CMS Team

#16025 VACMS-16024: image export changed to batch for alt text audit
  config/sync/views.view.media.yml
Labels: Drupal engineering, CMS Team

#15936 VACMS-15798 / 15791 / 15795 next preview configs + oauth key handling
  .gitignore
  .tugboat/config.yml
  config/sync/next.next_site.next_build_preview_server.yml
  config/sync/next.settings.yml
  config/sync/simple_oauth.settings.yml
  config/sync/user.role.next_js.yml
  docroot/sites/default/settings/settings.tugboat.php
Labels: Accelerated Publishing, CMS Team

#16060 VACMS-15515: Updates to Metatag 2.0.
  composer.json
  composer.lock
  config/sync/jsonapi_extras.jsonapi_resource_config.node--news_story.yml
Labels: Accelerated Publishing

#16086 VACMS-10356 Add content validator for Preview URL links (#10356)
  docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventPreviewUrlLinks.php
  docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventPreviewUrlLinksValidator.php
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  tests/phpunit/Content/PreventPreviewUrlLinksValidatorTest.php
Labels: CMS Team

#16104 VACMS-15953 Regenerate phpstan baselines
  phpstan-baseline.neon
Labels: CMS Team

#16070 VACMS-16061: updated graphql to v3.4
  composer.json
  composer.lock
Labels: Drupal engineering, Facilities, Accelerated Publishing, CMS Team

#16161 VACMS-15977: Adds accordion to VBA Facility Prepare for your visit
  config/sync/core.entity_form_display.node.vba_facility.default.yml
  config/sync/core.entity_view_display.node.vba_facility.default.yml
  config/sync/core.entity_view_display.node.vba_facility.external_content.yml
  config/sync/core.entity_view_display.node.vba_facility.ief_table.yml
  config/sync/core.entity_view_display.node.vba_facility.teaser.yml
  config/sync/field.field.node.vba_facility.field_prepare_for_visit.yml
Labels: Facilities

#16076 VACMS-14700: Adds banner to VBA Facility
  config/sync/core.entity_form_display.node.vba_facility.default.yml
  config/sync/core.entity_view_display.node.vba_facility.default.yml
  config/sync/core.entity_view_display.node.vba_facility.external_content.yml
  config/sync/core.entity_view_display.node.vba_facility.ief_table.yml
  config/sync/core.entity_view_display.node.vba_facility.teaser.yml
  config/sync/field.field.node.vba_facility.field_alert_type.yml
  config/sync/field.field.node.vba_facility.field_banner_content.yml
  config/sync/field.field.node.vba_facility.field_banner_title.yml
  config/sync/field.field.node.vba_facility.field_banner_types_description.yml
  config/sync/field.field.node.vba_facility.field_dismissible_option.yml
  config/sync/field.field.node.vba_facility.field_show_banner.yml
  config/sync/field.storage.node.field_banner_content.yml
  config/sync/field.storage.node.field_banner_title.yml
  config/sync/field.storage.node.field_banner_types_description.yml
  config/sync/field.storage.node.field_dismissible_option.yml
  config/sync/field.storage.node.field_show_banner.yml
  docroot/modules/custom/va_gov_vba_facility/js/set_banner_fields_to_required.es6.js
  docroot/modules/custom/va_gov_vba_facility/js/set_banner_fields_to_required.js
  docroot/modules/custom/va_gov_vba_facility/src/EventSubscriber/VbaFacilitySubscriber.php
  docroot/modules/custom/va_gov_vba_facility/src/Plugin/Validation/Constraint/VbaFacilityRequiredFieldsConstraint.php
  docroot/modules/custom/va_gov_vba_facility/src/Plugin/Validation/Constraint/VbaFacilityRequiredFieldsConstraintValidator.php
  docroot/modules/custom/va_gov_vba_facility/va_gov_vba_facility.libraries.yml
  docroot/modules/custom/va_gov_vba_facility/va_gov_vba_facility.module
Labels: Facilities

#16199 Add command for running PHP Code Beautifier and Fixer (phpcbf)
  composer.json
Labels: CMS Team

#16225 VACMS-10119: Updates Column Order on Node Pages
  docroot/themes/custom/vagovclaro/templates/page/page--node.html.twig
Labels: CMS Team

#16244 VACMS-00000: turned on gzip and aggregation
  docroot/sites/default/settings/settings.prod.php
Labels: CMS Team
