Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2023-02, with the labels that each got.

#12395 VACMS-12394: Prevent links with VA.gov domains as first path segment.
  docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventVaGovDomainsAsPathsInLinks.php
  docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventVaGovDomainsAsPathsInLinksValidator.php
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  tests/phpunit/Content/PreventVaGovDomainsAsPathsInLinksValidatorTest.php
Labels: CMS Team

#12434 VACMS-12433: Adds Lovell check for exact string to hide systems
  docroot/modules/custom/va_gov_lovell/js/limit_lovell.es6.js
  docroot/modules/custom/va_gov_lovell/js/limit_lovell.js
  tests/cypress/integration/behavioral/content_editing_vamc_system_service.feature
Labels: Facilities

#12441 VACMS-12433: Removes Lovell Federal health care from Section dropdown (restored functionality)
  docroot/modules/custom/va_gov_lovell/js/limit_lovell.es6.js
  docroot/modules/custom/va_gov_lovell/js/limit_lovell.js
  docroot/modules/custom/va_gov_lovell/js/remove_lovell_federal.js
  tests/cypress/integration/behavioral/content_editing_vamc_facility_service.feature
  tests/cypress/integration/behavioral/content_editing_vamc_system_service.feature
Labels: Facilities

#12419 VACMS-11895: Adds Cypress support for counting Watchdog log messages.
  tests/cypress/integration/behavioral/common/i_check_the_watchdog_log.js
  tests/cypress/integration/behavioral/common/i_create_a_media.js
  tests/cypress/integration/behavioral/common/i_create_a_node.js
  tests/cypress/integration/behavioral/common/watchdog_log.js
  tests/cypress/integration/behavioral/permissions.feature
  tests/cypress/support/commands.js
Labels: CMS Team

#12422 VACMS-11961: Move DownloadableFileTest tests into Cypress.
  tests/cypress/integration/behavioral/common/i_add_a_main_content_block.js
  tests/cypress/integration/behavioral/common/i_create_a_media.js
  tests/cypress/integration/behavioral/common/i_create_a_node.js
  tests/cypress/integration/behavioral/common/i_should_see.js
  tests/cypress/integration/behavioral/media.feature
  tests/phpunit/Content/DownloadableFileTest.php
Labels: CMS Team

#12520 VACMS-12513: Prevents relative links that start with `/www.`.
  docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventDomainsAsPathsInLinks.php
  docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventDomainsAsPathsInLinksValidator.php
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  tests/phpunit/Content/PreventDomainsAsPathsInLinksValidatorTest.php
Labels: CMS Team

#12432 VACMS-12287 Add content model documentation entity.
  composer.lock
  config/sync/content_model_documentation.settings.yml
  config/sync/views.view.content_model_documents.yml
  docroot/modules/custom/va_gov_db/va_gov_db.install
  tests/behat/drupal-spec-tool/views.feature
Labels: documentation, CMS Team

#12511 VACMS-12500: Reformats Cypress files.
  .github/workflows/continuous_integration.yml
  scripts/precommit.sh
  tests/cypress/integration/behavioral/common/i_am_logged_in_as_a_user_with_the_role.js
  tests/cypress/integration/behavioral/common/i_am_logged_in_as_a_user_with_the_role_and_password.js
  tests/cypress/integration/behavioral/common/i_am_logged_in_as_a_user_with_the_roles.js
  tests/cypress/integration/behavioral/common/i_clear_field.js
  tests/cypress/integration/behavioral/common/i_click_the_button.js
  tests/cypress/integration/behavioral/common/i_click_the_edit_tab.js
  tests/cypress/integration/behavioral/common/i_click_the_link.js
  tests/cypress/integration/behavioral/common/i_click_the_revisions_tab.js
  tests/cypress/integration/behavioral/common/i_create_a_taxonomy_term.js
  tests/cypress/integration/behavioral/common/i_delete_the_derivative_of_the_media_image.js
  tests/cypress/integration/behavioral/common/i_fill_in_ckeditor_field_with_value.js
  tests/cypress/integration/behavioral/common/i_fill_in_field_with_value.js
  tests/cypress/integration/behavioral/common/i_log_back_in.js
  tests/cypress/integration/behavioral/common/i_publish_the_node.js
  tests/cypress/integration/behavioral/common/i_save_the_node.js
  tests/cypress/integration/behavioral/common/i_select_option_from_dropdown.js
  tests/cypress/integration/behavioral/common/i_select_the_benefits_hub.js
  tests/cypress/integration/behavioral/common/i_set_the_status_of_the_node_to_status.js
  tests/cypress/integration/behavioral/common/i_should_be_at_url.js
  tests/cypress/integration/behavioral/common/i_should_receive_status_code_when_i_request_url.js
  tests/cypress/integration/behavioral/common/i_view_the_derivative_of_the_media_image.js
  tests/cypress/integration/behavioral/common/i_visit_the_node.js
  tests/cypress/integration/behavioral/common/my_workbench_access_sections_are_not_set.js
  tests/cypress/integration/behavioral/common/my_workbench_access_sections_are_set_to.js
  tests/cypress/integration/behavioral/common/option_from_dropdown_visible.js
  tests/cypress/integration/behavioral/common/should_be_empty.js
  tests/cypress/integration/behavioral/common/should_be_visible.js
  tests/cypress/integration/behavioral/common/should_exist.js
  tests/cypress/integration/behavioral/common/the_checkbox_should_be_selected.js
  tests/cypress/integration/behavioral/common/the_derivative_of_the_media_image_should_match_the_fixture.js
  tests/cypress/integration/behavioral/common/the_element_should_contain_string.js
  tests/cypress/integration/behavioral/common/the_element_should_have_attribute.js
  tests/cypress/integration/behavioral/common/the_option_from_dropdown_should_be_selected.js
  tests/cypress/integration/behavioral/common/the_path_should_contain.js
  tests/cypress/integration/behavioral/common/the_radio_button_should_be_selected.js
  tests/cypress/integration/behavioral/common/the_url_for_link_with_text_should_contain.js
  tests/cypress/integration/behavioral/common/watchdog_log.js
  tests/cypress/integration/behavioral/content_release/i_initiate_a_content_release.js
  tests/cypress/integration/behavioral/content_release/i_initiate_a_content_release_from_the_command_line.js
  tests/cypress/integration/behavioral/content_release/i_initiate_a_content_release_with_the_branch.js
  tests/cypress/integration/behavioral/content_release/i_process_the_content_release_queue.js
  tests/cypress/integration/behavioral/content_release/i_reset_the_content_release_frontend_version.js
  tests/cypress/integration/behavioral/content_release/i_reset_the_content_release_state.js
  tests/cypress/integration/behavioral/google_tag_manager/the_gtm_data_layer_user_id_should_be_correctly_hashed.js
  tests/cypress/integration/behavioral/google_tag_manager/the_gtm_data_layer_value_for_key_should_be_set.js
  tests/cypress/integration/behavioral/google_tag_manager/the_gtm_data_layer_value_for_key_should_be_set_correctly.js
  tests/cypress/integration/behavioral/google_tag_manager/the_gtm_data_layer_value_for_key_should_be_set_to_value.js
  tests/cypress/integration/behavioral/google_tag_manager/the_gtm_data_layer_value_for_key_should_be_unset.js
  tests/cypress/integration/behavioral/help_center/get_help.js
  tests/cypress/integration/behavioral/help_center/jsd_widget.js
  tests/cypress/integration/behavioral/password_policy/i_disable_the_password_policy.js
  tests/cypress/integration/behavioral/password_policy/i_enable_the_password_policy.js
  tests/cypress/plugins/index.js
  tests/cypress/support/commands.js
Labels: CMS Team

#12502 VACMS-12396: Incorporates heading violation check into tugboat content-build.
  scripts/build-frontend.sh
  tugboat.yml
Labels: CMS Team

#12550 VACMS-12303: add menu section for lovell menu items in parent list
  docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
Labels: Facilities

#12421 VACMS-10735: Daily Form Migration CSV validation checks
  scripts/tasks/VACMS-10735-Forms-CSV-migration-validation.php
  tasks-periodic.yml
Labels: Public Websites, CMS Team

#12563 VACMS-12378: updated styling for textfield counter warning and over
  docroot/design-system/components/tokens/_variables.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_textfield_counter.scss
  docroot/themes/custom/vagovclaro/assets/scss/styles.scss
Labels: CMS Team

#12590 VACMS-12215: Reënable status-error test.
  .github/workflows/set-tugboat-tests-pending.yml
Labels: CMS Team

#12615 VACMS-12614: Refactor Cypress log-specific code out of `commands.js`
  tests/cypress/support/commands.js
  tests/cypress/support/index.js
  tests/cypress/support/log.js
Labels: CMS Team

#12613 VACMS-12612: Prevent Cypress failing tests on uncaught application exceptions.
  tests/cypress/support/commands.js
Labels: CMS Team

#12653 VACMS-12585: add tricare service name field to va services taxonomy
  config/sync/core.entity_form_display.taxonomy_term.health_care_service_taxonomy.default.yml
  config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.default.yml
  config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.vamc_facility_service.yml
  config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.vba_facility_service.yml
  config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.vet_center_service.yml
  config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_tricare_name.yml
  config/sync/field.storage.taxonomy_term.field_tricare_name.yml
  tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature
Labels: Facilities

#12692 VACMS-12627: Expand metrics for header violations.
  scripts/build-frontend.sh
Labels: CMS Team

#12720 VACMS-12586: support tricare service names & descriptions...
  config/sync/core.entity_form_display.taxonomy_term.health_care_service_taxonomy.default.yml
  config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.default.yml
  config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.vamc_facility_service.yml
  config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.vba_facility_service.yml
  config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.vet_center_service.yml
  config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_tricare_name.yml
  config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_tricare_specific_service.yml
  config/sync/field.storage.taxonomy_term.field_tricare_specific_service.yml
  config/sync/views.view.health_care_service_names_and_descriptions.yml
  docroot/modules/custom/va_gov_backend/js/displayServiceDescriptions.es6.js
  docroot/modules/custom/va_gov_backend/js/displayServiceDescriptions.js
  docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_backend/va_gov_backend.libraries.yml
  docroot/modules/custom/va_gov_lovell/js/winnowServiceNamesTricare.es6.js
  docroot/modules/custom/va_gov_lovell/js/winnowServiceNamesTricare.js
  docroot/modules/custom/va_gov_lovell/src/EventSubscriber/LovellEventSubscriber.php
  docroot/modules/custom/va_gov_lovell/va_gov_lovell.libraries.yml
  tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature
  tests/cypress/integration/content_editing_vamc_system_service.feature
Labels: Facilities
