Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2023-05, with the labels that each got.

#13549 VACMS-12783: uncommented line for outdated content monthly task
  tasks-periodic.yml
Labels: CMS Team

#13573 VACMS-13467: Updated notification for vet center outdated content
  config/sync/core.entity_view_display.message.vamc_outdated_content.default.yml
  config/sync/core.entity_view_display.message.vamc_outdated_content.mail_body.yml
  config/sync/core.entity_view_display.message.vamc_outdated_content.mail_subject.yml
  config/sync/core.entity_view_display.message.vet_center_outdated_content.default.yml
  config/sync/core.entity_view_display.message.vet_center_outdated_content.mail_body.yml
  config/sync/core.entity_view_display.message.vet_center_outdated_content.mail_subject.yml
  config/sync/field.field.message.vamc_outdated_content.field_editor_username.yml
  config/sync/field.field.message.vamc_outdated_content.field_subject.yml
  config/sync/field.field.message.vet_center_outdated_content.field_editor_username.yml
  config/sync/field.field.message.vet_center_outdated_content.field_subject.yml
  config/sync/mailsystem.settings.yml
  config/sync/message.template.vamc_outdated_content.yml
  config/sync/message.template.vet_center_outdated_content.yml
  docroot/modules/custom/va_gov_notifications/src/Service/OutdatedContent.php
  docroot/modules/custom/va_gov_notifications/templates/message--vamc-outdated-content--mail-body.html.twig
  docroot/modules/custom/va_gov_notifications/templates/message--vet-center-outdated-content--mail-body.html.twig
  docroot/modules/custom/va_gov_notifications/va_gov_notifications.module
Labels: CMS Team

#13648 VACMS-13487: Upgrade storybook
  docroot/design-system/.babelrc.json
  docroot/design-system/.storybook/main.js
  docroot/design-system/.storybook/manager.js
  docroot/design-system/.storybook/preview.js
  docroot/design-system/.storybook/storybook-styles.scss
  docroot/design-system/package-lock.json
  docroot/design-system/package.json
  docroot/design-system/stories/Introduction.stories.mdx
  docroot/design-system/stories/changelog.stories.mdx
  docroot/design-system/stories/starting.stories.mdx
  docroot/design-system/webpack.config.js
Labels: CMS Team

#13669 Updates and cleanup for Github action syntax deprecations
  .github/actions/post-checkout/action.yml
  .github/dependabot.yml
  .github/workflows/actions-metrics.yml
  .github/workflows/contextual-advice.yml
  .github/workflows/continuous_integration.yml
  .github/workflows/cypress.yml
  .github/workflows/default-branch-datadog-metrics.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/pull-request-labels.yml
  .github/workflows/s3-backup-retention.yml
  .github/workflows/set-tugboat-tests-pending.yml
Labels: CMS Team

#13696 VACMS-7260 Remove facility status migration
  READMES/alerts.md
  READMES/migrations-facility.md
  READMES/upstream-dependencies.md
  READMES/vamc-facilities.md
  config/sync/migrate_plus.migration.va_node_facility_vet_centers_status.yml
  config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
  config/sync/migrate_plus.migration_group.facility_status.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers_status.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml
  docroot/modules/custom/va_gov_migrate/data/vet-center-facility-status.csv
  docroot/modules/custom/va_gov_migrate/va_gov_migrate.install
  tasks-periodic.yml
  tests/phpunit/Migration/VaHealthCareLocalFacilityStatusMigrationTest.php
Labels: Blocked, Awaiting Official Launch

#9344 VACMS-7279: add facility_url and Lovell overrides to Facility API
  docroot/modules/custom/va_gov_lovell/src/LovellOps.php
  docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityBase.php
  docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php
Labels: Facilities, Lighthouse Facility API

#13776 VACMS-13613 and 8017 Add PostFacilityBase methods
  docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityBase.php
  docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php
Labels: Facilities, Lighthouse Facility API

#13788 VACMS-12549: Update focus state on admin tool bar in CMS
  docroot/design-system/components/tokens/_variables.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_elements.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_toolbar.scss
Labels: CMS Team

#13818 VACMS-13278: patch to address menu link being too short
  composer.json
  composer.lock
  patches/3106205-length-menu-tree-too-short.patch
Labels: CMS Team

#13833 [docs] Replace ddev migrate-sync with ddev composer va:migrate:sync
  READMES/migrations-facility.md
Labels: Facilities

#13859 VACMS-13468: updated copy for vamc notification
  docroot/modules/custom/va_gov_notifications/templates/message--vamc-outdated-content--mail-body.html.twig
Labels: CMS Team
