Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2023-03, with the labels that each got.

#12403 VACMS-12217: Update wysiwyg from user behavior
  config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_form_display.node.health_care_local_facility.inline_entity_form.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.external_content.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.ief_table.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.teaser.yml
  config/sync/field.field.node.health_care_local_facility.field_supplemental_status.yml
  config/sync/field.field.node.health_care_local_facility.field_supplemental_status_more_i.yml
  config/sync/field.storage.node.field_supplemental_status_more_i.yml
  config/sync/views.view.facility_services.yml
  docroot/modules/custom/va_gov_vamc/css/set_covid_term_text.css
  docroot/modules/custom/va_gov_vamc/js/set_covid_term_text.es6.js
  docroot/modules/custom/va_gov_vamc/js/set_covid_term_text.js
  docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
  docroot/themes/custom/vagovclaro/assets/scss/components/_views.scss
  tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
  tests/cypress/integration/common/i_select_the_radio_button.js
  tests/cypress/integration/common/i_should_see.js
  tests/cypress/integration/content_editing_vamc_facility.feature
  tests/cypress/support/commands.js
Labels: Facilities, DO NOT MERGE

#12821 VACMS-12217: Ignoring test for now
  tests/cypress/integration/content_editing_vamc_facility.feature
Labels: Facilities

#12658 VACMS-12449 Make revision_log message required on all node content types.
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  docroot/modules/custom/va_gov_db/va_gov_db.install
  docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_workflow/va_gov_workflow.module
  docroot/modules/custom/va_gov_workflow/va_gov_workflow.services.yml
  tests/behat/features/content_editing.feature
  tests/behat/features/personal_content_flags.feature
  tests/cypress/integration/common/i_create_a_node.js
  tests/cypress/integration/common/i_publish_the_node.js
  tests/cypress/integration/content_editing.feature
  tests/cypress/integration/entity_reference_validation.feature
  tests/cypress/integration/google_tag_manager.feature
  tests/cypress/integration/media.feature
  tests/cypress/integration/text_validation.feature
Labels: DO NOT MERGE, Awaiting Official Launch

#12856 VACMS-12845: Adds outdated-content prometheus exporter plugin.
  docroot/modules/custom/va_gov_backend/src/Plugin/MetricsCollector/OutdatedContent.php
Labels: CMS Team

#12547 VACMS-12450: updates for outdated content report
  config/sync/views.view.content.yml
Labels: CMS notifications, CMS Team

#12873 VACMS-00000: remove topfloor/composer-cleanup-vcs-dirs
  composer.json
  composer.lock
Labels: CMS Team

#12820 VACMS-126703: Outdated Content Notifications
  READMES/drush.md
  composer.json
  composer.lock
  config/sync/advancedqueue.advancedqueue_queue.outdated_content_notification.yml
  config/sync/core.entity_view_display.message.va_outdated_content.default.yml
  config/sync/core.entity_view_display.message.va_outdated_content.mail_body.yml
  config/sync/core.entity_view_display.message.va_outdated_content.mail_subject.yml
  config/sync/core.extension.yml
  config/sync/field.field.message.va_outdated_content.field_editor_username.yml
  config/sync/field.field.message.va_outdated_content.field_subject.yml
  config/sync/field.storage.message.field_editor_username.yml
  config/sync/field.storage.message.field_subject.yml
  config/sync/mailsystem.settings.yml
  config/sync/message.template.va_outdated_content.yml
  config/sync/mimemail.settings.yml
  docroot/modules/custom/va_gov_notifications/assets/outdated-content-email-banner.png
  docroot/modules/custom/va_gov_notifications/src/Plugin/AdvancedQueue/JobType/OutdatedContentNotification.php
  docroot/modules/custom/va_gov_notifications/src/Service/OutdatedContent.php
  docroot/modules/custom/va_gov_notifications/src/Service/OutdatedContentInterface.php
  docroot/modules/custom/va_gov_notifications/templates/message--va-outdated-content--mail-body.html.twig
  docroot/modules/custom/va_gov_notifications/va_gov_notifications.module
  docroot/modules/custom/va_gov_notifications/va_gov_notifications.services.yml
  docroot/themes/custom/vagovclaro/templates/mail/mimemail-message--message-notify--va-outdated-content.html.twig
Labels: CMS Team

#12902 VACMS-11575: Outdated Content Tool - Match CSV export columns to audit tool columns
  config/sync/views.view.content.yml
Labels: CMS Team

#12892 Patch that allows redirect_options module to work with content_transl…
  composer.json
  composer.lock
Labels: CMS Team

#12914 VACMS-12831: update facility service location script to maintain mode…
  scripts/content/VACMS-5387-facility-services-add-service-location-2021-11.php
Labels: Facilities

#12865 VACMS-12619: Add field validation facility health services
  docroot/modules/custom/va_gov_vamc/src/Plugin/Validation/Constraint/SectionMatcher.php
  docroot/modules/custom/va_gov_vamc/src/Plugin/Validation/Constraint/SectionMatcherValidator.php
  docroot/modules/custom/va_gov_vamc/va_gov_vamc.module
Labels: Facilities

#12940 VACMS-12708: translation access
  config/sync/system.action.user_add_role_action.translation_manager.yml
  config/sync/system.action.user_remove_role_action.translation_manager.yml
  config/sync/user.role.content_admin.yml
  config/sync/user.role.translation_manager.yml
  tests/cypress/integration/translation.feature
  tests/phpunit/Security/RoleCheckTest.php
  tests/phpunit/Security/RolesPermissionsTest.php
  tests/scripts/behat-tests.sh
Labels: CMS Team

#13008 VACMS-12928: update for design system dependencies, fixed deprecations
  docroot/design-system/.nvmrc
  docroot/design-system/.storybook/cssVariables.js
  docroot/design-system/.storybook/cssVariables.json
  docroot/design-system/package.json
  docroot/design-system/yarn.lock
Labels: CMS Team

#13027 VACMS-13025: Adds null check
  docroot/modules/custom/va_gov_vamc/src/Plugin/Validation/Constraint/SectionMatcherValidator.php
  tests/cypress/integration/content_editing_vamc_facility_service.feature
Labels: Facilities

#12979 VACMS-12977: Updates Drupal to 9.5.5
  composer.lock
  docroot/.ht.router.php
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: CMS Team

#13005 VACMS-13003: Replaces search form element in KB search results.
  config/sync/block.block.knowledge_base_search_form.yml
Labels: CMS Team

#13066 VACMS-12787 Move facility events to the appropriate facility modules.
  docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_backend/va_gov_backend.libraries.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.services.yml
  docroot/modules/custom/va_gov_facilities/js/displayServiceDescriptions.es6.js
  docroot/modules/custom/va_gov_facilities/js/displayServiceDescriptions.js
  docroot/modules/custom/va_gov_facilities/src/EventSubscriber/FacilitiesSubscriber.php
  docroot/modules/custom/va_gov_facilities/va_gov_facilities.libraries.yml
  docroot/modules/custom/va_gov_facilities/va_gov_facilities.services.yml
  docroot/modules/custom/va_gov_vamc/src/EventSubscriber/VAMCEntityEventSubscriber.php
  docroot/modules/custom/va_gov_vamc/va_gov_vamc.services.yml
Labels: Facilities

#13022 VACMS-12897 Populate CAP to Outstation issue template.
  .github/ISSUE_TEMPLATE/runbook-vet-center-cap-to-outstation.md
Labels: Facilities, User support

#13090 VACMS-12898: Updates runbook Outstation becomes Vet Center
  .github/ISSUE_TEMPLATE/runbook-vet-center-outstation-to-vet-center.md
Labels: Facilities, User support

#13118 [DOCS] Updates VAMC facility duplicate db script
  .github/ISSUE_TEMPLATE/runbook-vamc-facility-duplicate-or-section-change.md
Labels: Facilities

#13132 VACMS-13087: update outdated content notifications
  READMES/drush.md
  config/sync/advancedqueue.advancedqueue_queue.vamc_outdated_content.yml
  config/sync/advancedqueue.advancedqueue_queue.vet_center_outdated_content.yml
  docroot/modules/custom/va_gov_notifications/src/Service/OutdatedContent.php
  docroot/modules/custom/va_gov_notifications/src/Service/OutdatedContentInterface.php
  docroot/modules/custom/va_gov_notifications/va_gov_notifications.install
Labels: CMS Team
