Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2023-07, with the labels that each got.

#14211 VACMS-14032: Autoarchive Outstation and Mobiles and clears data
  docroot/modules/custom/va_gov_facilities/src/FacilityOps.php
  docroot/modules/custom/va_gov_migrate/src/Commands/Commands.php
Labels: Facilities

#14048 VACMS-11039: Updates form and adds hook_update_n
  config/sync/core.entity_form_display.node.full_width_banner_alert.default.yml
  config/sync/field.field.node.full_width_banner_alert.field_body.yml
  docroot/modules/custom/va_gov_vamc/va_gov_vamc.install
Labels: Facilities, Needs PO review

#11331 VACMS-11040: limit number of VAMC system Banner Alerts
  config/sync/core.entity_form_display.node.full_width_banner_alert.default.yml
  config/sync/core.entity_form_display.node.full_width_banner_alert.inline_entity_form.yml
  config/sync/core.entity_view_display.node.full_width_banner_alert.default.yml
  config/sync/core.entity_view_display.node.full_width_banner_alert.ief_table.yml
  config/sync/core.entity_view_display.node.full_width_banner_alert.teaser.yml
  config/sync/field.field.node.full_width_banner_alert.field_enforce_unique_combo.yml
Labels: VAMC, Facilities

#14181 VACMS-8141 Prevent re-use of VAMC banner alerts.
  docroot/modules/custom/va_gov_facilities/src/FacilityOps.php
  docroot/modules/custom/va_gov_vamc/src/EventSubscriber/VAMCEntityPreventReuse.php
  docroot/modules/custom/va_gov_vamc/va_gov_vamc.module
  docroot/modules/custom/va_gov_vamc/va_gov_vamc.services.yml
  tests/cypress/integration/common/i_check_the_checkbox.js
  tests/cypress/integration/common/should_exist.js
  tests/cypress/integration/content_editing_vamc_banner_reuse.feature
Labels: VAMC, Facilities

#14169 VACMS-13768: Adds other vet centers and restores status call
  docroot/modules/custom/va_gov_post_api/src/Form/VaGovFacilityForceQueueForm.php
Labels: Facilities

#14312 VACMS-14175: updates to pdf report, fixes access for POs
  config/sync/views.view.pdf_audit.yml
  docroot/modules/custom/va_gov_backend/src/Plugin/views/access/PdfAuditAccess.php
  scripts/compile-theme.sh
Labels: CMS Team

#14392 VACMS-10154: Add role="presentation" to description field
  docroot/themes/custom/vagovclaro/templates/field/field--node--field-description.html.twig
  docroot/themes/custom/vagovclaro/templates/field/field--node--field-meta-title.html.twig
Labels: CMS Team

#14401 VACMS-12453: Change to Samlauth from simplesamlphp_auth
  .tugboat/.env.j2
  composer.json
  composer.lock
  config/local/samlauth.authentication.yml
  config/local/simplesamlphp_auth.settings.yml
  config/prod/samlauth.authentication.yml
  config/prod/simplesamlphp_auth.settings.yml
  config/stg/samlauth.authentication.yml
  config/stg/simplesamlphp_auth.settings.yml
  config/sync/config_split.config_split.dev.yml
  config/sync/config_split.config_split.local.yml
  config/sync/config_split.config_split.prod.yml
  config/sync/config_split.config_split.stg.yml
  config/sync/config_split.config_split.tugboat.yml
  config/sync/core.extension.yml
  config/sync/samlauth.authentication.yml
  config/sync/views.view.samlauth_map.yml
  config/tugboat/samlauth.authentication.yml
  config/tugboat/simplesamlphp_auth.settings.yml
  docroot/modules/custom/va_gov_login/js/login-toggle.es6.js
  docroot/modules/custom/va_gov_login/js/login-toggle.js
  docroot/modules/custom/va_gov_login/va_gov_login.info.yml
  docroot/modules/custom/va_gov_login/va_gov_login.module
  docroot/modules/custom/va_gov_user/src/EventSubscriber/UserImport.php
  tests/cypress/integration/user_login.feature
Labels: DevOps, CMS Team

#14484 Revert "VACMS-12453: Change to Samlauth from simplesamlphp_auth (#14401)"
  .tugboat/.env.j2
  composer.json
  composer.lock
  config/local/samlauth.authentication.yml
  config/local/simplesamlphp_auth.settings.yml
  config/prod/samlauth.authentication.yml
  config/prod/simplesamlphp_auth.settings.yml
  config/stg/samlauth.authentication.yml
  config/stg/simplesamlphp_auth.settings.yml
  config/sync/config_split.config_split.dev.yml
  config/sync/config_split.config_split.local.yml
  config/sync/config_split.config_split.prod.yml
  config/sync/config_split.config_split.stg.yml
  config/sync/config_split.config_split.tugboat.yml
  config/sync/core.extension.yml
  config/sync/samlauth.authentication.yml
  config/sync/views.view.samlauth_map.yml
  config/tugboat/samlauth.authentication.yml
  config/tugboat/simplesamlphp_auth.settings.yml
  docroot/modules/custom/va_gov_login/js/login-toggle.es6.js
  docroot/modules/custom/va_gov_login/js/login-toggle.js
  docroot/modules/custom/va_gov_login/va_gov_login.info.yml
  docroot/modules/custom/va_gov_login/va_gov_login.module
  docroot/modules/custom/va_gov_user/src/EventSubscriber/UserImport.php
  tests/cypress/integration/user_login.feature
Labels: CMS Team

#14562 VACMS-14462: added POs to access list
  docroot/modules/custom/va_gov_backend/src/Plugin/views/access/PdfAuditAccess.php
Labels: CMS Team

#14558 VACMS-10118: Assigns aria-label values to otherwise ambiguous asides
  docroot/themes/custom/vagovclaro/templates/page/page--node.html.twig
Labels: CMS Team
