Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2023-12, with the labels that each got.

#16266 VACMS-16232: Removes Legacy Patch Causing Double Spacing
  composer.json
  composer.lock
Labels: CMS Team

#16281 VACMS-16015: Adds export view for VAMC facilities
  config/sync/views.view.vamc_facilities_by_system.yml
Labels: Facilities

#16277 VACMS-15715 Create and publish VA police pages.
  composer.json
  composer.lock
  config/sync/core.extension.yml
  docroot/modules/custom/va_gov_vamc/va_gov_vamc.deploy.php
  docroot/modules/custom/va_gov_vamc/va_gov_vamc.install
Labels: Facilities

#16332 [docs] Update research-discovery.md based on sprint 98
  .github/ISSUE_TEMPLATE/research-discovery.md
Labels: Facilities, Public Websites

#16352 VACMS-16231: Updates Taxonomy term view filter
  config/sync/views.view.taxonomy_term.yml
Labels: Facilities

#16373 VACMS-16262: Unexpected Value in CSV Export
  config/sync/views.view.user_admin_people.yml
Labels: Drupal engineering, CMS Team

#16412 VACMS-16378: Remove content moderation widget from Term View on VA Services Taxonomy
  config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.default.yml
Labels: Facilities

#16433 VACMS-16249: update to drupal core v10.1.7
  composer.json
  composer.lock
Labels: Drupal engineering, CMS Team

#16431 VACMS-16241: Post-D10 Cleanup
  README.md
  READMES/upstream-dependencies.md
  composer.json
  composer.lock
  config/sync/core.extension.yml
  docroot/modules/custom/va_gov_build_trigger/js/content_release_status_block.js
  docroot/modules/custom/va_gov_build_trigger/src/Controller/FrontEndBranchAutocompleteController.php
  docroot/modules/custom/va_gov_preview/src/Encoder/StaticEncoder.php
  docroot/modules/custom/va_gov_views/src/EventSubscriber/ViewsBulkOpsSubscriber.php
  docroot/modules/custom/va_gov_views/va_gov_views.libraries.yml
  docroot/modules/custom/va_gov_views/va_gov_views.module
Labels: Drupal engineering, CMS Team

#16454 VACMS-9135: json api UI e
  READMES/jsonapi.md
  composer.json
  composer.lock
  config/sync/core.extension.yml
  docroot/modules/custom/va_gov_api/js/json-schemas-table-filter.js
  docroot/modules/custom/va_gov_api/src/Plugin/openapi/OpenApiGenerator/VaGovOpenApiGenerator.php
  docroot/modules/custom/va_gov_api/va_gov_api.libraries.yml
  docroot/modules/custom/va_gov_api/va_gov_api.module
  tests/phpunit/API/JsonApiExplorerUiTest.php
Labels: Accelerated Publishing, CMS Team

#16471 VACMS-16241: post launch D10 cleanup, remove ckeditor 4
  composer.json
  composer.lock
Labels: Drupal engineering, CMS Team

#16326 VACMS-16152: Adds new view and export
  config/sync/views.view.facility_services.yml
Labels: Facilities

#16395 VACMS-14000: Adds and populates meta tags on VBA Facility
  config/sync/core.entity_form_display.node.service_region.default.yml
  config/sync/core.entity_form_display.node.vba_facility.default.yml
  config/sync/core.entity_view_display.node.vba_facility.default.yml
  config/sync/field.field.node.vba_facility.field_cc_meta_tags.yml
  config/sync/field.storage.node.field_cc_meta_tags.yml
  config/sync/metatag.metatag_defaults.node__vba_facility.yml
  scripts/content/VACMS-14000-vba-facility-meta-tags.php
Labels: Facilities

#16253 Documentation updates
  README.md
  READMES/alerts.md
  READMES/blackfire.md
  READMES/codeowners.md
  READMES/comparing-graphql-output.md
  READMES/getting-started.md
  READMES/github-workflows.md
  READMES/historical/analytics.md
  READMES/https.md
  READMES/images/macos-keychains.png
  READMES/interfaces.md
  READMES/qa.md
  READMES/security.md
  READMES/sentry.md
  READMES/workflow.md
Labels: CMS Team

#16531 VACMS-16481: Moves audit views into the menu
  config/sync/views.view.centralized_content_paragraphs.yml
  config/sync/views.view.detail_page_url_audit_and_bulk_udpate.yml
  config/sync/views.view.facility_services.yml
  config/sync/views.view.section_export.yml
  config/sync/views.view.vamc_top_task_page_revisions.yml
Labels: Facilities

#16279 Minimize PR overhead for non-code changes
  .github/workflows/continuous_integration.yml
  .github/workflows/set-tests-statuses.yml
  .github/workflows/set-tugboat-tests-pending.yml
  .github/workflows/tugboat-pr-closed.yml
  .github/workflows/tugboat-pr-opened.yml
  .github/workflows/tugboat-pr-updated.yml
  .github/workflows/tugboat-refresh-cache.yml
  tests.yml
Labels: CMS Team

#16562 Refresh Tugboat Preview ID cache from PR cache scope
  .github/workflows/tugboat-refresh-cache-dispatch.yml
  .github/workflows/tugboat-refresh-cache-responder.yml
Labels: CMS Team
