Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2023-06, with the labels that each got.

#13894 Set up UX languages changes for TMGMT.
  composer.json
  composer.lock
  config/sync/core.extension.yml
  docroot/design-system/components/alert/alert.scss
  docroot/design-system/components/alert/alert.twig
  docroot/modules/custom/va_gov_multilingual/modules/va_gov_multilingual_tmgmt/src/EventSubscriber/FormEventSubscriber.php
  docroot/modules/custom/va_gov_multilingual/modules/va_gov_multilingual_tmgmt/va_gov_multilingual_tmgmt.info.yml
  docroot/modules/custom/va_gov_multilingual/modules/va_gov_multilingual_tmgmt/va_gov_multilingual_tmgmt.services.yml
  docroot/modules/custom/va_gov_multilingual/va_gov_multilingual.info.yml
  patches/tmgmt_language_changes.patch
Labels: CMS Team

#13858 VACMS-13362: Adds migration for NCA Facilities API data.
  config/sync/migrate_plus.migration.va_node_facility_nca.yml
  docroot/modules/custom/va_gov_facilities/src/FacilityOps.php
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_nca.yml
  docroot/modules/custom/va_gov_migrate/src/Commands/Commands.php
Labels: Facilities

#13953 VACMS-13526 Add timezone to Facilities (and hide flags)
  config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_form_display.node.health_care_local_facility.inline_entity_form.yml
  config/sync/core.entity_form_display.node.vba_facility.default.yml
  config/sync/core.entity_form_display.node.vet_center.default.yml
  config/sync/core.entity_form_display.node.vet_center_cap.default.yml
  config/sync/core.entity_form_display.node.vet_center_cap.inline_entity_form.yml
  config/sync/core.entity_form_display.node.vet_center_mobile_vet_center.default.yml
  config/sync/core.entity_form_display.node.vet_center_outstation.default.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.external_content.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.ief_table.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.teaser.yml
  config/sync/core.entity_view_display.node.nca_facility.default.yml
  config/sync/core.entity_view_display.node.nca_facility.teaser.yml
  config/sync/core.entity_view_display.node.vba_facility.default.yml
  config/sync/core.entity_view_display.node.vba_facility.external_content.yml
  config/sync/core.entity_view_display.node.vba_facility.ief_table.yml
  config/sync/core.entity_view_display.node.vba_facility.teaser.yml
  config/sync/core.entity_view_display.node.vet_center.default.yml
  config/sync/core.entity_view_display.node.vet_center.external_content.yml
  config/sync/core.entity_view_display.node.vet_center.ief_table.yml
  config/sync/core.entity_view_display.node.vet_center.teaser.yml
  config/sync/core.entity_view_display.node.vet_center_cap.default.yml
  config/sync/core.entity_view_display.node.vet_center_cap.external_content.yml
  config/sync/core.entity_view_display.node.vet_center_cap.ief_table.yml
  config/sync/core.entity_view_display.node.vet_center_cap.teaser.yml
  config/sync/core.entity_view_display.node.vet_center_mobile_vet_center.default.yml
  config/sync/core.entity_view_display.node.vet_center_mobile_vet_center.external_content.yml
  config/sync/core.entity_view_display.node.vet_center_mobile_vet_center.teaser.yml
  config/sync/core.entity_view_display.node.vet_center_outstation.default.yml
  config/sync/core.entity_view_display.node.vet_center_outstation.external_content.yml
  config/sync/core.entity_view_display.node.vet_center_outstation.teaser.yml
  config/sync/field.field.node.health_care_local_facility.field_timezone.yml
  config/sync/field.field.node.vba_facility.field_timezone.yml
  config/sync/field.field.node.vet_center.field_timezone.yml
  config/sync/field.field.node.vet_center_cap.field_timezone.yml
  config/sync/field.field.node.vet_center_mobile_vet_center.field_timezone.yml
  config/sync/field.field.node.vet_center_outstation.field_timezone.yml
  config/sync/migrate_plus.migration.va_node_facility_vba.yml
  config/sync/migrate_plus.migration.va_node_facility_vet_centers.yml
  config/sync/migrate_plus.migration.va_node_facility_vet_centers_mvc.yml
  config/sync/migrate_plus.migration.va_node_facility_vet_centers_os.yml
  config/sync/migrate_plus.migration.va_node_health_care_local_facility.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vba.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers_mvc.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers_os.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility.yml
Labels: Facilities

#13991 VACMS-13815: pdf audit for VHA DM
  config/sync/entity_usage.settings.yml
  config/sync/views.view.pdf_audit.yml
  docroot/modules/custom/va_gov_backend/src/Plugin/views/access/PdfAuditAccess.php
Labels: CMS Team

#13988 VACMS-13672: Adds system banner image
  config/sync/views.view.facility_services.yml
Labels: Facilities

#14007 VACMS-0000: Fixes issue identified by Sentry
  docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityWithoutStatus.php
Labels: Facilities

#14039 VACMS-13583: Unable to alter field values by Views Bulk Operation
  composer.json
  composer.lock
Labels: CMS Team

#14043 VACMS-13806: hide counters on text fields when editing translations.
  config/sync/core.extension.yml
  docroot/modules/custom/va_gov_multilingual/va_gov_multilingual.module
  tests/cypress/integration/common/i_fill_in_field_with_n_chars.js
  tests/cypress/integration/translation.feature
Labels: CMS Team

#14035 VACMS-13649: Multi-time pattern passthrough
  docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php
Labels: Facilities

#14058 VACMS-13956: Updates office_hours module, removes patch
  composer.json
  composer.lock
Labels: Facilities

#14122 VACMS-000 upgrade migration tools module
  composer.json
  composer.lock
  config/sync/migrate_plus.migration.va_node_health_care_local_facility.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility.yml
Labels: Drupal engineering, Facilities, Migration

#14026 VACMS-13478: contrib module updates for d10 readiness
  composer.json
  composer.lock
  config/sync/blazy.settings.yml
  config/sync/core.extension.yml
  config/sync/filter.format.rich_text.yml
  config/sync/filter.format.rich_text_limited.yml
  docroot/modules/custom/va_gov_backend/js/set_body_to_required.es6.js
  docroot/modules/custom/va_gov_backend/js/set_body_to_required.js
  docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_backend/va_gov_backend.libraries.yml
  docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/ConvertBoolean.php
  docroot/modules/custom/va_gov_migrate/src/Plugin/migrate_plus/data_parser/Csv.php
  docroot/modules/custom/va_gov_user/src/EventSubscriber/UserImport.php
  patches/3290964-add-drush-commands-2.patch
  patches/3338408-fix-access-check-error.patch
  patches/3358123-explicit-access-check.patch
  patches/3364925-added-explicit-access-check.patch
  tests/behat/features/perms.feature
Labels: CMS Team

#14139 VACMS-00000: fix for patch on sitewide_alert
  composer.json
  composer.lock
  patches/3290964-add-drush-commands-2.patch
Labels: Defect, CMS Team

#14145 VACMS-00000: update form simplesamlphp library
  composer.lock
Labels: Critical defect, CMS Team

#14159 VACMS-14148: fix for facilites migration, patch migrate_plus
  composer.json
  composer.lock
  patches/3368310-str-replace-throws-php-error.patch
  patches/combined-patches-for-migrate-plus.patch
Labels: Defect, CMS Team

#14193 VACMS-00000: disable flysystem modules
  config/sync/core.extension.yml
Labels: CMS Team

#14230 VACMS-00000: remove drupal/flysystem modules
  composer.json
  composer.lock
  docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.services.yml
  docroot/sites/default/settings.php
  docroot/sites/default/settings/settings.flysystem.php
Labels: CMS Team
