Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2024-09, with the labels that each got.

#18956 VACMS-18703: Updating core to 10.3.2.
  composer.json
  composer.lock
  docroot/modules/custom/va_gov_backend/src/Logger/Processor/DatadogApmProcessor.php
  docroot/modules/custom/va_gov_eca/src/Plugin/Action/CreateAdvancedQueueJob.php
  docroot/modules/custom/va_gov_eca/src/Plugin/ECA/Condition/ViewsResultCondition.php
  docroot/sites/default/default.services.yml
  docroot/sites/default/default.settings.php
  docroot/sites/default/settings.php
  docroot/sites/development.services.yml
  docroot/sites/example.sites.php
  patches/2893933-queue_lease_time-11.x-75.patch
  patches/2942404-65-11.x.patch
  patches/3333401-configurable-pager-heading-default-h2.patch
  patches/text_module-3229493-12.patch
  tests/cypress/support/commands.js
  tests/phpunit/FrontendBuild/BuildMetricsTest.php
  tests/phpunit/FrontendBuild/BuildRequesterTest.php
  tests/phpunit/FrontendBuild/BuildSchedulerTest.php
  tests/phpunit/FrontendBuild/BuildStateEventSubscriberTest.php
  tests/phpunit/FrontendBuild/ReleaseStateManagerTest.php
  tests/phpunit/Support/Mock/SpecifiedTime.php
  tests/phpunit/va_gov_content_release/unit/FrontendVersion/FrontendVersionTest.php
Labels: CMS Team, Drupal upgrade

#18908 VACMS-18821: implement script to move unattached pdfs from drupal into s3 bucket
  .tugboat/.env.j2
  composer.json
  composer.lock
  docroot/modules/custom/va_gov_eca/src/Plugin/ECA/Condition/ViewsResultCondition.php
  docroot/modules/custom/va_gov_media/src/Service/VamcPdfDeleteInterface.php
  docroot/modules/custom/va_gov_media/src/Service/VamcPdfDeleteService.php
  docroot/modules/custom/va_gov_media/va_gov_media.info.yml
  docroot/modules/custom/va_gov_media/va_gov_media.services.yml
  docroot/sites/default/settings/settings.prod.php
  docroot/sites/default/settings/settings.staging.php
  docroot/sites/default/settings/settings.tugboat.php
  phpstan-baseline.neon
Labels: CMS Team

#19126 VACMS-17477: Updated character counter on News Releases
  config/sync/core.entity_form_display.node.press_release.default.yml
  config/sync/field.field.node.press_release.field_intro_text.yml
  config/sync/node.type.press_release.yml
Labels: Facilities, sitewide, News release

#19130 VACMS-18953: Vet Center table of contents
  config/sync/core.entity_form_display.node.vet_center.default.yml
  config/sync/field.field.node.vet_center.field_table_of_contents.yml
Labels: Facilities, Vet Center, sitewide

#19178 VACMS-18998: Update pathauto module.
  composer.json
  composer.lock
Labels: CMS Team

#19158 VACMS-18997: Update openapi jsonapi module.
  composer.json
  composer.lock
Labels: CMS Team

#18937 VACMS-18544: next build feature flags
  READMES/images/next-entity-type-config.png
  READMES/next-build.md
  config/sync/feature_toggle.features.yml
  config/sync/next.next_entity_type_config.node.event.yml
  config/sync/next.next_entity_type_config.node.event_listing.yml
  config/sync/next.next_entity_type_config.node.press_release.yml
  config/sync/next.next_entity_type_config.node.press_releases_listing.yml
  config/sync/next.next_entity_type_config.node.vet_center.yml
  config/sync/next.next_site.next_build_preview_server.yml
  docroot/modules/custom/va_gov_flags/src/Export/ExportFeature.php
  docroot/modules/custom/va_gov_preview/src/EventSubscriber/PreviewEventSubscriber.php
  docroot/modules/custom/va_gov_preview/va_gov_preview.services.yml
Labels: CMS Team

#19038 DO NOT MERGE VACMS-17860: Updates staff phone field to paragraph field
  .ddev/nginx_full/nginx-site.conf
  .github/CODEOWNERS
  composer.json
  composer.lock
  config/sync/codit_batch_operations.settings.yml
  config/sync/core.entity_form_display.node.person_profile.default.yml
  config/sync/core.entity_form_display.node.person_profile.inline_entity_form.yml
  config/sync/core.entity_view_display.node.person_profile.default.yml
  config/sync/core.entity_view_display.node.person_profile.teaser.yml
  config/sync/core.extension.yml
  config/sync/field.field.node.person_profile.field_telephone.yml
  config/sync/field.storage.node.field_telephone.yml
  config/sync/language/es/views.view.batch_operation_logs.yml
  config/sync/views.view.batch_operation_logs.yml
  config/sync/views.view.rich_text_field_audit.yml
  docroot/modules/custom/va_gov_batch/README.md
  docroot/modules/custom/va_gov_batch/src/cbo_scripts/MigratePhoneFieldToParagraph.php
  docroot/modules/custom/va_gov_batch/va_gov_batch.info.yml
  docroot/modules/custom/va_gov_profile/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_profile/va_gov_profile.deploy.php
  tests/cypress/integration/features/content_type/person_profile.feature
  tests/phpunit/va_gov_batch/unit/Class/MigratePhoneFieldToParagraphTest.php
Labels: DO NOT MERGE

#19200 VACMS-19188: Update seckit..
  composer.lock
Labels: CMS Team

#19120 VACMS-19071: Implement redesign for kb search results page.
  docroot/themes/custom/vagovclaro/assets/scss/pages/_kb-pages.scss
  docroot/themes/custom/vagovclaro/templates/page/page--help--search.html.twig
Labels: CMS Team

#19014 VACMS-19013: Adding Vet Center services
  config/sync/views.view.facility_services.yml
Labels: Facilities

#19230 VACMS-19177: remove pii from cms logging
  composer.json
  composer.lock
  docroot/modules/custom/va_gov_notifications/src/Plugin/AdvancedQueue/JobType/OutdatedContentNotification.php
  docroot/modules/custom/va_gov_notifications/src/Service/OutdatedContent.php
  patches/VACMS-19177-patch_for_user_module_to_log_uid.patch
  patches/VACMS-19177-removing_username_from_logging_for_externalauth.patch
Labels: CMS Team

#18811 VAGOV-TEAM-87958: Integration branch for Form Engine POC
  config/sync/core.base_field_override.node.digital_form.promote.yml
  config/sync/core.base_field_override.node.digital_form.title.yml
  config/sync/core.entity_form_display.node.digital_form.default.yml
  config/sync/core.entity_form_display.paragraph.digital_form_name_and_date_of_bi.default.yml
  config/sync/core.entity_view_display.node.digital_form.default.yml
  config/sync/core.entity_view_display.node.digital_form.external_content.yml
  config/sync/core.entity_view_display.node.digital_form.teaser.yml
  config/sync/core.entity_view_display.paragraph.digital_form_name_and_date_of_bi.default.yml
  config/sync/core.entity_view_display.paragraph.digital_form_name_and_date_of_bi.user_guides.yml
  config/sync/field.field.node.digital_form.field_administration.yml
  config/sync/field.field.node.digital_form.field_chapters.yml
  config/sync/field.field.node.digital_form.field_last_saved_by_an_editor.yml
  config/sync/field.field.node.digital_form.field_meta_tags.yml
  config/sync/field.field.node.digital_form.field_omb_number.yml
  config/sync/field.field.node.digital_form.field_va_form_number.yml
  config/sync/field.field.paragraph.digital_form_name_and_date_of_bi.field_include_date_of_birth.yml
  config/sync/field.field.paragraph.digital_form_name_and_date_of_bi.field_title.yml
  config/sync/field.storage.node.field_chapters.yml
  config/sync/field.storage.node.field_omb_number.yml
  config/sync/field.storage.paragraph.field_include_date_of_birth.yml
  config/sync/language.content_settings.node.digital_form.yml
  config/sync/node.type.digital_form.yml
  config/sync/paragraphs.paragraphs_type.digital_form_name_and_date_of_bi.yml
  config/sync/paragraphs_browser.paragraphs_browser_type.digital_forms.yml
  config/sync/prometheus_exporter.settings.yml
  config/sync/workflows.workflow.editorial.yml
  docroot/modules/custom/va_gov_content_types/src/Entity/DigitalForm.php
  docroot/modules/custom/va_gov_content_types/va_gov_content_types.module
  docroot/themes/custom/vagovclaro/images/screenshots/name-and-dob.png
  scripts/content/digital-forms.php
  scripts/content/script-library.php
  scripts/content/vacms-17969/VACMS-17969-vba-test-data-processor.php
  tests/phpunit/va_gov_content_types/functional/Entity/DigitalFormTest.php
Labels: CMS Team

#19293 VACMS-18996: Update drupal admin toolbar.
  composer.json
  composer.lock
Labels: CMS Team

#19234 VACMS-17862: Moves VACMS facility Mental health phone number from field to paragraph
  config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_form_display.node.health_care_local_facility.inline_entity_form.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.external_content.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.ief_table.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.teaser.yml
  config/sync/field.field.node.health_care_local_facility.field_telephone.yml
  config/sync/views.view.rich_text_field_audit.yml
  docroot/modules/custom/va_gov_batch/src/cbo_scripts/MigrateVamcFacilityMentalHealthPhoneFieldToParagraph.php
  docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php
  docroot/modules/custom/va_gov_vamc/src/EventSubscriber/VAMCEntityEventSubscriber.php
  tests/cypress/integration/features/content_type/facilities/vamc/health_care_local_facility.feature
Labels: Facilities

#19338 VACMS-19175: new monolog current user processor
  docroot/modules/custom/va_gov_user/src/Logger/Processor/VaGovUserCurrentUserProcessor.php
  docroot/modules/custom/va_gov_user/va_gov_user.services.yml
  docroot/sites/default/services/services.dev.yml
  docroot/sites/default/services/services.monolog.yml
  docroot/sites/default/services/services.prod.yml
  docroot/sites/default/services/services.staging.yml
Labels: CMS Team

#19264 VACMS-17861: Replace VAMC Billing and Insurance telephone field with telephone paragraph
  config/sync/core.entity_form_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_view_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_view_display.node.vamc_system_billing_insurance.search_index.yml
  config/sync/core.entity_view_display.node.vamc_system_billing_insurance.teaser.yml
  config/sync/field.field.node.vamc_system_billing_insurance.field_telephone.yml
  config/sync/node.type.vamc_system_billing_insurance.yml
  docroot/modules/custom/va_gov_batch/src/cbo_scripts/MigrateVamcBillingInsurancePhoneFieldToParagraph.php
  docroot/modules/custom/va_gov_vamc/src/EventSubscriber/VAMCEntityEventSubscriber.php
Labels: Facilities
