Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2024-08, with the labels that each got.

#18531 VACMS-18003: Vet center services view
  config/sync/core.entity_form_display.node.vet_center.default.yml
  config/sync/core.entity_view_display.node.vet_center.default.yml
  config/sync/field.field.node.vet_center_facility_health_servi.field_administration.yml
  config/sync/field.field.node.vet_center_facility_health_servi.field_office.yml
  config/sync/views.view.knowledge_base_search_results.yml
  config/sync/views.view.vet_center_services.yml
  docroot/modules/custom/va_gov_dashboards/src/Plugin/Derivative/VcDashboardsBlock.php
  docroot/modules/custom/va_gov_facilities/src/EventSubscriber/FacilitiesSubscriber.php
  docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.libraries.yml
  docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.module
Labels: Facilities, DO NOT MERGE

#18890 VACMS-18723 Exported and added configs to git for Mission Explainer
  config/sync/core.entity_form_display.node.vet_center.default.yml
  config/sync/core.entity_view_display.node.vet_center.default.yml
  config/sync/core.entity_view_display.node.vet_center.external_content.yml
  config/sync/core.entity_view_display.node.vet_center.ief_table.yml
  config/sync/core.entity_view_display.node.vet_center.teaser.yml
  config/sync/field.field.node.vet_center.field_mission_explainer.yml
  config/sync/field.storage.node.field_mission_explainer.yml
Labels: Facilities

#18972 VACMS-18709: Adds Vet Center banner image through centralized content
  config/sync/core.entity_form_display.node.vet_center.default.yml
  config/sync/core.entity_view_display.node.vet_center.default.yml
  config/sync/core.entity_view_display.node.vet_center.external_content.yml
  config/sync/core.entity_view_display.node.vet_center.ief_table.yml
  config/sync/core.entity_view_display.node.vet_center.teaser.yml
  config/sync/field.field.node.vet_center.field_vet_center_banner_image.yml
  config/sync/field.storage.node.field_vet_center_banner_image.yml
Labels: CMS Team

#19042 VACMS-19041: removing samlauth module
  composer.json
  composer.lock
Labels: CMS Team

#19059 VACMS-18706:Update smart date, reroll patch and test.
  composer.json
  composer.lock
  patches/smart_date-undefined_value_in_validation-3260965-24-reroll.patch
Labels: CMS Team

#19024 VACMS-18805: Configurations for updating KB search.
  config/sync/search_api.index.knowledge_base_search.yml
Labels: CMS Team

#19046 Vacms 18705 update memcache modules and reroll patch 3
  composer.json
  composer.lock
  patches/memcache-persistent-connections-memcached-3058121-18.patch
Labels: CMS Team

#19080 VACMS-19079: Adds default value config
  config/sync/field.field.node.vet_center.field_mission_explainer.yml
  config/sync/field.field.node.vet_center.field_vet_center_banner_image.yml
Labels: Facilities

#19085 VACMS-18995: Update drupal metatag module.
  composer.lock
Labels: CMS Team

#19089 VACMS-18821: install s3fs module
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/s3fs.settings.yml
Labels: CMS Team
