Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2024-01, with the labels that each got.

#16552 OpenAPI UI Hook to Event Subscriber
  docroot/modules/custom/va_gov_api/js/json-schemas-table-filter.js
  docroot/modules/custom/va_gov_api/src/EventSubscriber/AddJsEventSubscriber.php
  docroot/modules/custom/va_gov_api/va_gov_api.module
  docroot/modules/custom/va_gov_api/va_gov_api.services.yml
Labels: Accelerated Publishing, CMS Team

#16654 VACMS-16642 Remove Drush launcher in preparation for upgrade to drush 12
  .tugboat/config.yml
Labels: Drupal engineering, CMS Team

#16724 VACMS-16543: turn off Create for simplesamlphp_auth, prevent ghost accounts
  config/local/simplesamlphp_auth.settings.yml
  config/prod/simplesamlphp_auth.settings.yml
  config/stg/simplesamlphp_auth.settings.yml
  config/tugboat/simplesamlphp_auth.settings.yml
Labels: Drupal engineering, CMS Team

#16542 VACMS-16457: Update/patch entity_browser module
  composer.json
  composer.lock
  patches/3408217-error-call-to-member-function-getstorage-on-null.patch
  tests/cypress/integration/features/platform/entity_reference_validation.feature
Labels: Drupal engineering, Facilities, Public Websites, CMS Team

#16663 VACMS-15901: Removes facilities not in user sections
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  tests/cypress/integration/features/content_type/vba_facility_service.feature
Labels: Facilities

#15787 VACMS-15785: alt text validation
  composer.json
  composer.lock
  config/sync/clientside_validation.settings.yml
  config/sync/clientside_validation_jquery.settings.yml
  config/sync/core.entity_form_display.media.image.default.yml
  config/sync/core.extension.yml
  docroot/design-system/components/input/input.scss
  docroot/design-system/components/tokens/_variables.scss
  docroot/modules/custom/va_gov_backend/src/EventSubscriber/ThemeEventSubscriber.php
  docroot/modules/custom/va_gov_media/js/alt_text_validation.es6.js
  docroot/modules/custom/va_gov_media/js/alt_text_validation.js
  docroot/modules/custom/va_gov_media/src/Controller/AltTextValidationController.php
  docroot/modules/custom/va_gov_media/src/EventSubscriber/MediaEventSubscriber.php
  docroot/modules/custom/va_gov_media/va_gov_media.info.yml
  docroot/modules/custom/va_gov_media/va_gov_media.libraries.yml
  docroot/modules/custom/va_gov_media/va_gov_media.module
  docroot/modules/custom/va_gov_media/va_gov_media.routing.yml
  docroot/modules/custom/va_gov_media/va_gov_media.services.yml
  docroot/themes/custom/vagovclaro/assets/scss/components/_fields.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_media.scss
  docroot/themes/custom/vagovclaro/templates/content-edit/file-managed-file.html.twig
  patches/2949540-31.patch
  phpstan-baseline.neon
  tests/cypress/integration/features/platform/alt_text_validation.feature
  tests/cypress/integration/step_definitions/common/i_create_an_image_with_alt_text.js
  tests/cypress/integration/step_definitions/common/i_save_an_image_with_alt_text.js
Labels: CMS Team

#16779 VACMS-16522: Move VAMC System pages to restricted_archive workflow
  config/sync/core.entity_form_display.node.health_care_region_page.default.yml
  config/sync/core.entity_form_display.node.locations_listing.default.yml
  config/sync/core.entity_form_display.node.vamc_operating_status_and_alerts.default.yml
  config/sync/core.entity_form_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_form_display.node.vamc_system_medical_records_offi.default.yml
  config/sync/core.entity_form_display.node.vamc_system_policies_page.default.yml
  config/sync/core.entity_form_display.node.vamc_system_register_for_care.default.yml
  config/sync/core.entity_form_display.node.vamc_system_va_police.default.yml
  config/sync/workflows.workflow.editorial.yml
  config/sync/workflows.workflow.restricted_archive.yml
  docroot/modules/custom/va_gov_workflow/va_gov_workflow.install
Labels: Facilities

#16737 VACMS-16146 Add VBA banner cypress test.
  tests/cypress/integration/features/content_type/facilities/facilities_api.feature
  tests/cypress/integration/features/content_type/facilities/vamc/full_width_banner_alert.feature
  tests/cypress/integration/features/content_type/facilities/vamc/health_care_local_facility.feature
  tests/cypress/integration/features/content_type/facilities/vamc/health_care_local_health_service.feature
  tests/cypress/integration/features/content_type/facilities/vamc/health_care_region_detail_page.feature
  tests/cypress/integration/features/content_type/facilities/vamc/regional_health_care_service_des.feature
  tests/cypress/integration/features/content_type/facilities/vamc/vamc_lovell.feature
  tests/cypress/integration/features/content_type/facilities/vamc/vamc_operating_status_and_alerts.feature
  tests/cypress/integration/features/content_type/facilities/vba/vba_facility.feature
  tests/cypress/integration/features/content_type/vba_facility.feature
  tests/cypress/integration/weights.json
Labels: Facilities

#15585 VACMS-9717 Make CMS the source of truth for VAMC mental health phone
  config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_form_display.node.health_care_local_facility.inline_entity_form.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.external_content.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.ief_table.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.teaser.yml
  config/sync/field.field.node.health_care_local_facility.field_mental_health_contact_phon.yml
  config/sync/field.field.node.health_care_local_facility.field_mental_health_phone.yml
  config/sync/field.field.node.health_care_local_facility.field_phone_number.yml
  config/sync/field.storage.node.field_mental_health_contact_phon.yml
Labels: VAMC, Facilities, Lighthouse Facility API, refresh-tugboat-cache

#16620 VACMS-16591: Update Drupal Core to v10.2
  composer.json
  composer.lock
  docroot/robots.txt
  docroot/sites/default/default.services.yml
  docroot/sites/default/default.settings.php
  docroot/sites/example.settings.local.php
  patches/3106205-length-menu-tree-too-short-48.patch
Labels: Drupal engineering, Facilities, CMS Team

#16820 VACMS-14623: Staff profile has no alias on publish
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: Facilities

#16899 VACMS-16898: upgrade drupal core to 10.2.2
  composer.json
  composer.lock
Labels: CMS Team

#16807 Update character count status message on "Centralized content" content type - purpose field
  config/sync/core.entity_form_display.node.centralized_content.default.yml
Labels: Facilities, CMS design system, CMS design, Drupal Site Building

#16946 VACMS_16449: updated date formats
  config/sync/views.view.user_admin_people.yml
Labels: Drupal engineering, CMS Team

#16975 VAMC-16959: editors can't save detail pages under Work with us
  docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
Labels: Defect, Drupal engineering, CMS Team

#16839 VACMS-16289 bump next-build preview secret timer
  config/sync/next.settings.yml
Labels: Accelerated Publishing

#16994 VACMS-17018 Resolve VAMC menu assignment issues.
  docroot/modules/custom/va_gov_media/va_gov_media.module
  docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
  docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
Labels: Facilities, CMS Team

#17017 VACMS-16348: Add fields to service location
  config/sync/core.entity_form_display.paragraph.service_location.default.yml
  config/sync/core.entity_view_display.paragraph.service_location.default.yml
  config/sync/field.field.paragraph.service_location.field_appt_intro_text_custom.yml
  config/sync/field.field.paragraph.service_location.field_appt_intro_text_type.yml
  config/sync/field.field.paragraph.service_location.field_office_visits.yml
  config/sync/field.field.paragraph.service_location.field_online_scheduling_avail.yml
  config/sync/field.field.paragraph.service_location.field_other_phone_numbers.yml
  config/sync/field.field.paragraph.service_location.field_service_delivery_options.yml
  config/sync/field.field.paragraph.service_location.field_use_facility_phone_number.yml
  config/sync/field.field.paragraph.service_location.field_virtual_support.yml
  config/sync/field.storage.paragraph.field_appt_intro_text_custom.yml
  config/sync/field.storage.paragraph.field_appt_intro_text_type.yml
  config/sync/field.storage.paragraph.field_office_visits.yml
  config/sync/field.storage.paragraph.field_online_scheduling_avail.yml
  config/sync/field.storage.paragraph.field_other_phone_numbers.yml
  config/sync/field.storage.paragraph.field_service_delivery_options.yml
  config/sync/field.storage.paragraph.field_use_facility_phone_number.yml
  config/sync/field.storage.paragraph.field_virtual_support.yml
Labels: Facilities

#16808 [DOCS] Add steps for fixing aliases and names in the CMS for term changes
  .github/ISSUE_TEMPLATE/taxonomy-update-term.yml
Labels: Facilities

#16883 Add event subscriber to include situation updates for full banner width alerts
  docroot/modules/custom/va_gov_api/src/Controller/BannerAlertsController.php
  docroot/modules/custom/va_gov_api/src/Resources/BannerAlerts.php
  docroot/modules/custom/va_gov_api/va_gov_api.routing.yml
  docroot/modules/custom/va_gov_api/va_gov_api.services.yml
  tests/phpunit/API/BannerEndpointTest.php
Labels: Accelerated Publishing, CMS Team, refresh-tugboat-cache

#16425 VACMS-16077: Sets Views Pager Heading Default to H2
  composer.json
  composer.lock
  config/sync/views.view.content.yml
  config/sync/views.view.orphaned_paragraphs.yml
  patches/3333401-configurable-pager-heading-default-h2.patch
Labels: CMS Team
