Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2024-12, with the labels that each got.

#19981 VACMS-19912: Updating document upload help text.
  config/sync/field.field.media.document.field_document.yml
Labels: CMS Team

#20026 VACMS-20024: update simplesamlphp and saml2
  composer.lock
Labels: CMS Team

#20032 VACMS-20023: update header_no_cache for simplesamlphp config
  config/local/simplesamlphp_auth.settings.yml
  config/prod/simplesamlphp_auth.settings.yml
  config/stg/simplesamlphp_auth.settings.yml
  config/tugboat/simplesamlphp_auth.settings.yml
Labels: CMS Team

#20010 VACMS-16461: Fixes phone export and adds new fields
  config/sync/views.view.rich_text_field_audit.yml
Labels: Facilities

#20062 VACMS-20021: patch simplesamlphp auth to fix login issue that leaves user anonymous
  composer.json
  composer.lock
  patches/3127628-simplesamlphp-auth-fix-redirection-issue.patch
Labels: CMS Team

#19607 VACMS-19512: Drupal UX for phone numbers
  config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_form_display.node.person_profile.default.yml
  config/sync/core.entity_form_display.node.vamc_system_billing_insurance.default.yml
  config/sync/field.field.node.health_care_local_facility.field_mental_health_phone.yml
  config/sync/field.field.node.health_care_local_facility.field_telephone.yml
  docroot/themes/custom/vagovclaro/assets/scss/components/_fields.scss
  tests/cypress/integration/features/content_type/person_profile.feature
Labels: sitewide

#20094 VACMS-19375: Fix for undefined anchor links.
  docroot/themes/custom/vagovclaro/assets/js/anchor_links.js
Labels: CMS Team

#20118 VACMS-20092: db update to truncate table, uninstall danse modules an …
  config/sync/core.extension.yml
  config/sync/views.view.danse_user_notifications.yml
  docroot/modules/custom/va_gov_db/va_gov_db.install
Labels: CMS Team

#20119 VACMS-20022: Creating GA4 term glossary for README.
  READMES/ga4-glossary.md
  READMES/images/ga4-collection.png
  READMES/images/ga4-filter.png
  READMES/images/ga4-home.png
  READMES/images/ga4-library.png
  READMES/images/ga4-reports.png
Labels: CMS Team

#20121 VACMS-19805: Adds new statuses (#19881)
  config/sync/field.field.node.nca_facility.field_operating_status_more_info.yml
  config/sync/field.field.node.vet_center.field_operating_status_more_info.yml
  config/sync/field.field.node.vet_center_cap.field_operating_status_more_info.yml
  config/sync/field.field.node.vet_center_outstation.field_operating_status_facility.yml
  config/sync/field.field.node.vet_center_outstation.field_operating_status_more_info.yml
  config/sync/field.storage.node.field_operating_status_facility.yml
Labels: Facilities

#20088 VACMS-20086: Adds code for Manila VA Clinic and removes unused code.
  docroot/modules/custom/va_gov_manila/src/EventSubscriber/ManilaEventSubscriber.php
  tests/cypress/integration/features/content_type/facilities/manila.feature
  tests/cypress/integration/step_definitions/common/i_should_be_at_url.js
Labels: Facilities

#20068 VACMS-19227: Adds Philippines as a US state for facility purposes
  config/sync/core.extension.yml
  config/sync/field.field.node.press_release.field_address.yml
  docroot/modules/custom/va_gov_address/src/EventSubscriber/AddPhilippinesAsStateSubscriber.php
  docroot/modules/custom/va_gov_address/va_gov_address.info.yml
  docroot/modules/custom/va_gov_address/va_gov_address.services.yml
  tests/phpunit/va_gov_address/unit/EventSubscriber/AddPhilippinesAsStateSubscriberTest.php
Labels: Facilities, CMS Team

#20078 VACMS-19369: Adds messaging to Slack, following established pattern
  docroot/modules/custom/va_gov_post_api/src/EventSubscriber/QueueItemProcessedEventSubscriber.php
Labels: Facilities

#20131 VACMS-20126: update composer based dependencies
  composer.json
  composer.lock
  docroot/modules/custom/va_gov_backend/css/toolbar.css
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  docroot/robots.txt
  docroot/themes/custom/vagovclaro/assets/scss/components/_toolbar.scss
  package-lock.json
  patches/3463201-fix-for-change-in-class-for-toolbar.patch
  patches/VACMS-20126-fix-for-change-in-class-for-toolbar.patch
Labels: CMS Team

#20025 VACMS-19814: Update npm dependencies
  .nvmrc
  package-lock.json
  package.json
  tests/phpunit/va_gov_address/unit/EventSubscriber/AddPhilippinesAsStateSubscriberTest.php
Labels: CMS Team
