Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2024-03, with the labels that each got.

#17402 VACMS-13214: Alphabetize all services and identify archived and draft services
  docroot/modules/custom/va_gov_vamc/css/set_vamc_system_health_service.css
  docroot/modules/custom/va_gov_vamc/src/EventSubscriber/VAMCEntityEventSubscriber.php
  docroot/modules/custom/va_gov_vamc/va_gov_vamc.libraries.yml
Labels: Facilities

#17451 VACMS-17323: Updates module with fixes for button
  composer.lock
  config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.external_content.yml
  config/sync/core.entity_view_display.node.nca_facility.default.yml
  config/sync/core.entity_view_display.node.nca_facility.external_content.yml
  config/sync/core.entity_view_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_view_display.node.vamc_system_billing_insurance.search_index.yml
  config/sync/core.entity_view_display.node.vba_facility.default.yml
  config/sync/core.entity_view_display.node.vba_facility.external_content.yml
  config/sync/core.entity_view_display.node.vba_facility.ief_table.yml
  config/sync/core.entity_view_display.node.vet_center.default.yml
  config/sync/core.entity_view_display.node.vet_center.external_content.yml
  config/sync/core.entity_view_display.node.vet_center_cap.default.yml
  config/sync/core.entity_view_display.node.vet_center_mobile_vet_center.default.yml
  config/sync/core.entity_view_display.node.vet_center_mobile_vet_center.external_content.yml
  config/sync/core.entity_view_display.node.vet_center_outstation.external_content.yml
  config/sync/core.entity_view_display.paragraph.service_location.default.yml
  config/sync/views.view.non_clinical_services.yml
Labels: Facilities

#17393 VACMS-14083: Upgrades address module to version 2.0
  composer.json
  composer.lock
  config/sync/field.field.node.event.field_address.yml
  config/sync/field.field.node.health_care_local_facility.field_address.yml
  config/sync/field.field.node.nca_facility.field_address.yml
  config/sync/field.field.node.nca_facility.field_mailing_address.yml
  config/sync/field.field.node.press_release.field_address.yml
  config/sync/field.field.node.vamc_system_medical_records_offi.field_vamc_med_records_mailing.yml
  config/sync/field.field.node.vba_facility.field_address.yml
  config/sync/field.field.node.vet_center.field_address.yml
  config/sync/field.field.node.vet_center_cap.field_address.yml
  config/sync/field.field.node.vet_center_mobile_vet_center.field_address.yml
  config/sync/field.field.node.vet_center_outstation.field_address.yml
  config/sync/field.field.paragraph.address.field_address.yml
  config/sync/field.field.paragraph.service_location_address.field_address.yml
Labels: Facilities, CMS Team

#17484 Revert hook event dispatcher update
  composer.json
  composer.lock
Labels: CMS Team

#17464 VACMS-16417: Aging Content Notifications: Expired Full Width Alert (FWB)
  config/sync/advancedqueue.advancedqueue_queue.aging_content.yml
  config/sync/core.entity_form_display.message.aging_content_expired_fwb.default.yml
  config/sync/core.entity_view_display.message.aging_content_expired_fwb.default.yml
  config/sync/core.entity_view_display.message.aging_content_expired_fwb.mail_body.yml
  config/sync/core.entity_view_display.message.aging_content_expired_fwb.mail_subject.yml
  config/sync/core.extension.yml
  config/sync/eca.eca.aging_content_expired_fwb.yml
  config/sync/eca.eca.expiring_fwb.yml
  config/sync/field.field.message.aging_content_expired_fwb.field_expired_date.yml
  config/sync/field.field.message.aging_content_expired_fwb.field_target_entity.yml
  config/sync/field.field.message.aging_content_expired_fwb.field_target_node_title.yml
  config/sync/field.storage.message.field_expired_date.yml
  config/sync/language/en/message.template.aging_content_expired_fwb.yml
  config/sync/language/es/views.view.eca_log.yml
  config/sync/mailsystem.settings.yml
  config/sync/message.template.aging_content_expired_fwb.yml
  config/sync/views.view.aging_content.yml
  docroot/modules/custom/va_gov_eca/src/Plugin/Action/CreateAdvancedQueueJob.php
  docroot/modules/custom/va_gov_notifications/src/JobTypeMessageNotifyBase.php
  docroot/modules/custom/va_gov_notifications/src/JobTypeMessageNotifyBaseInterface.php
  docroot/modules/custom/va_gov_notifications/src/Plugin/AdvancedQueue/JobType/AgingContentNotification.php
  docroot/modules/custom/va_gov_notifications/templates/message--aging-content-expired-fwb--mail-body.html.twig
  docroot/modules/custom/va_gov_notifications/va_gov_notifications.module
Labels: Facilities

#17517 VACMS-17501: Fix service locations hours error
  docroot/modules/custom/va_gov_backend/js/service_location_hours.es6.js
  docroot/modules/custom/va_gov_backend/js/service_location_hours.js
Labels: Facilities

#17266 Specify default JSON:API Extras enhancers link fields globally
  READMES/jsonapi.md
  composer.json
  composer.lock
  config/sync/jsonapi_extras.jsonapi_field_type_config.yml
  patches/field-type-enhancer-3025283-3.patch
  tests/phpunit/API/JsonApiRequestTest.php
Labels: Accelerated Publishing, CMS Team

#17449 VACMS-16732: Removes border color related to text-counter
  docroot/themes/custom/vagovclaro/assets/scss/components/_textfield_counter.scss
Labels: Facilities, CMS Team

#17537 VACMS-17476-Update core from 10.2.2 to 10.2.4
  composer.json
  composer.lock
  docroot/sites/default/default.settings.php
  docroot/sites/example.sites.php
Labels: Drupal engineering, CMS Team

#17536 VACMS-17501: Shows and hides hours appropriately
  docroot/modules/custom/va_gov_backend/js/service_location_hours.es6.js
  docroot/modules/custom/va_gov_backend/js/service_location_hours.js
Labels: Facilities

#17548 VACMS-17073-upgrade-allowed-formats-module.
  composer.json
  composer.lock
Labels: CMS Team

#17579 VACMS-12666: Removes duplicate sections on system health service pages.
  config/sync/core.entity_view_display.node.health_care_local_health_service.system_services_listings.yml
  config/sync/core.entity_view_display.node.regional_health_care_service_des.default.yml
  config/sync/core.entity_view_mode.node.system_services_listings.yml
Labels: Facilities

#17635 VACMS-17073: Removing allowed formats module from composer.
  composer.json
  composer.lock
Labels: CMS Team

#17637 VACMS-17587: Fixes revision squashing during migrate
  docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_workflow/src/EventSubscriber/MigrateEventSubscriber.php
  docroot/modules/custom/va_gov_workflow/src/Service/Flagger.php
  docroot/modules/custom/va_gov_workflow/va_gov_workflow.services.yml
Labels: Facilities, CMS Team

#17650 add allowed_formats back into composer
  composer.json
  composer.lock
Labels: CMS Team
