Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2024-05, with the labels that each got.

#18034 VACMS-17872: Linkit fix for unpublished nodes.
  composer.json
  composer.lock
Labels: CMS Team

#17755 VACMS-17718: fix pdf audit view to correctly show all pdf usage data
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/views.view.pdf_audit.yml
  docroot/modules/custom/va_gov_backend/src/Plugin/views/access/PdfAuditAccess.php
  docroot/modules/custom/va_gov_media/src/EventSubscriber/VaGovMediaAddRouteSubscriber.php
  docroot/modules/custom/va_gov_media/va_gov_media.services.yml
  docroot/themes/custom/vagovclaro/assets/scss/components/_views.scss
  patches/3000184-resolve_the_paragraph_URL_to_parent_entity.patch
  patches/3443270-Check-Access-entity-usage-statistics-perms-in-linkedUsage-method.patch
Labels: CMS Team

#15622 DO NOT MERGE: VACMS-14683: Updating service locations paragraph
  config/sync/core.entity_form_display.node.health_care_local_health_service.default.yml
  config/sync/core.entity_form_display.node.service_region.default.yml
  config/sync/core.entity_form_display.node.vba_facility_service.default.yml
  config/sync/core.entity_form_display.node.vba_facility_service.inline_entity_form.yml
  config/sync/core.entity_form_display.node.vha_facility_nonclinical_service.default.yml
  config/sync/core.entity_form_display.paragraph.service_location.default.yml
  config/sync/core.entity_view_display.node.health_care_local_health_service.default.yml
  config/sync/core.entity_view_display.node.service_region.default.yml
  config/sync/core.entity_view_display.node.service_region.full.yml
  config/sync/core.entity_view_display.node.service_region.teaser.yml
  config/sync/core.entity_view_display.node.vba_facility_service.default.yml
  config/sync/core.entity_view_display.node.vba_facility_service.search_index.yml
  config/sync/core.entity_view_display.node.vba_facility_service.teaser.yml
  config/sync/core.entity_view_display.node.vha_facility_nonclinical_service.default.yml
  config/sync/core.entity_view_display.node.vha_facility_nonclinical_service.search_index.yml
  config/sync/core.entity_view_display.node.vha_facility_nonclinical_service.teaser.yml
  config/sync/core.entity_view_display.paragraph.service_location.default.yml
  config/sync/field.field.node.service_region.field_vba_serv_reg_appt_default.yml
  config/sync/field.field.node.vba_facility_service.field_vba_fac_serv_appt_default.yml
  config/sync/field.field.node.vha_facility_nonclinical_service.field_vamc_nonclin_appt_default.yml
  config/sync/field.field.paragraph.service_location.field_appt_intro_text_custom.yml
  config/sync/field.field.paragraph.service_location.field_appt_intro_text_type.yml
  config/sync/field.field.paragraph.service_location.field_office_visits.yml
  config/sync/field.field.paragraph.service_location.field_online_scheduling_avail.yml
  config/sync/field.field.paragraph.service_location.field_other_phone_numbers.yml
  config/sync/field.field.paragraph.service_location.field_use_facility_phone_number.yml
  config/sync/field.field.paragraph.service_location.field_virtual_support.yml
  config/sync/field.storage.node.field_vamc_nonclin_appt_default.yml
  config/sync/field.storage.node.field_vba_fac_serv_appt_default.yml
  config/sync/field.storage.node.field_vba_serv_reg_appt_default.yml
  config/sync/field.storage.paragraph.field_appt_intro_text_custom.yml
  config/sync/field.storage.paragraph.field_appt_intro_text_type.yml
  config/sync/field.storage.paragraph.field_office_visits.yml
  config/sync/field.storage.paragraph.field_online_scheduling_avail.yml
  config/sync/field.storage.paragraph.field_other_phone_numbers.yml
  config/sync/field.storage.paragraph.field_use_facility_phone_number.yml
  config/sync/field.storage.paragraph.field_virtual_support.yml
  config/sync/views.view.right_sidebar_latest_revision.yml
  config/sync/views.view.service_locations_audit.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  docroot/modules/custom/va_gov_facilities/src/EventSubscriber/FacilitiesSubscriber.php
  docroot/modules/custom/va_gov_facilities/va_gov_facilities.info.yml
  docroot/modules/custom/va_gov_facilities/va_gov_facilities.module
  docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityServiceVamc.php
  docroot/modules/custom/va_gov_vamc/src/EventSubscriber/VAMCEntityEventSubscriber.php
  docroot/modules/custom/va_gov_vamc/src/ServiceLocationMigration.php
  docroot/modules/custom/va_gov_vamc/va_gov_vamc.deploy.php
  docroot/modules/custom/va_gov_vamc/va_gov_vamc.install
  scripts/content/VACMS-15559-migrate-service-location-from-node-to-paragraph.php
  scripts/content/script-library.php
  tests/cypress/integration/features/content_type/facilities/vamc/health_care_local_health_service.feature
Labels: VAMC, Facilities, DO NOT MERGE, Awaiting Official Launch, VBA

#18169 VACMS-17515: Hiding service options and appointments on Non-clinical services
  docroot/modules/custom/va_gov_vamc/va_gov_vamc.module
Labels: Facilities

#18201 Removed flaky json api explorer unit test
  tests/phpunit/API/JsonApiExplorerUiTest.php
Labels: CMS Team

#18238 VACMS-17515: Adds condition for new nonclinical service
  docroot/modules/custom/va_gov_vamc/va_gov_vamc.module
Labels: Facilities

#18241 Create events-api
  READMES/events-api
Labels: CMS Team

#18250 VACMS-18070: Adding a check for response header for files to pull from s3 buckets.
  .ddev/mutagen/mutagen.yml
  docroot/sites/default/settings.php
  docroot/sites/default/settings/settings.local.php
  docroot/sites/default/settings/settings.prod.php
  docroot/sites/default/settings/settings.staging.php
  docroot/sites/default/settings/settings.tugboat.php
Labels: CMS Team

#18258 VACMS-18244: comment out access chagnes for add media forms
  docroot/modules/custom/va_gov_media/src/EventSubscriber/VaGovMediaAddRouteSubscriber.php
Labels: CMS Team

#18210 VACMS-18064: Drupal Events json api for OPIA.
  config/sync/views.view.events_data.yml
Labels: CMS Team
