Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2024-02, with the labels that each got.

#17007 Revert GHA Tugboat integration
  .github/workflows/continuous_integration.yml
  .github/workflows/set-tests-statuses.yml
  .github/workflows/set-tugboat-tests-pending.yml
  .github/workflows/tugboat-pr-closed.yml
  .github/workflows/tugboat-pr-opened.yml
  .github/workflows/tugboat-pr-updated.yml
  .github/workflows/tugboat-refresh-cache-dispatch.yml
  .github/workflows/tugboat-refresh-cache-responder.yml
  README.md
  READMES/tugboat.md
  tests.yml
Labels: CMS Team

#17132 VACMS-16469: Updates widget to radio buttons
  config/sync/core.entity_form_display.node.nca_facility.default.yml
  config/sync/core.entity_form_display.node.vba_facility.default.yml
  config/sync/core.entity_form_display.node.vet_center.default.yml
  config/sync/core.entity_form_display.node.vet_center_cap.default.yml
  config/sync/core.entity_form_display.node.vet_center_outstation.default.yml
  config/sync/field.field.node.vet_center_outstation.field_operating_status_facility.yml
Labels: Facilities

#17160 VACMS-16641: Test restricted archive workflow
  tests/cypress/integration/features/content_type/facilities/vba/vba_facility.feature
Labels: Facilities

#17156 VACMS-16327: Update VBA facility post review feedback
  config/sync/core.entity_form_display.node.vba_facility.default.yml
  config/sync/core.entity_form_display.paragraph.basic_accordion.default.yml
  config/sync/core.entity_view_display.node.vba_facility.default.yml
  config/sync/core.entity_view_display.node.vba_facility.external_content.yml
  config/sync/core.entity_view_display.node.vba_facility.ief_table.yml
  config/sync/core.entity_view_display.node.vba_facility.teaser.yml
  config/sync/field.field.node.vba_facility.field_banner_types_description.yml
  config/sync/field.field.node.vba_facility.field_intro_text.yml
  config/sync/field.field.node.vba_facility.field_media.yml
  config/sync/field.field.node.vba_facility.field_operating_status_facility.yml
  config/sync/field.field.node.vba_facility.field_operating_status_more_info.yml
  config/sync/field.field.node.vba_facility.field_table_of_contents.yml
  config/sync/field.field.paragraph.basic_accordion.field_header.yml
  config/sync/field.field.paragraph.basic_accordion.field_rich_wysiwyg.yml
  config/sync/field.field.paragraph.button.field_button_label.yml
  config/sync/field.field.paragraph.button.field_button_link.yml
  config/sync/field.field.paragraph.featured_content.field_description.yml
  config/sync/field.field.paragraph.featured_content.field_section_header.yml
  docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
  docroot/themes/custom/vagovclaro/assets/scss/components/_centralized_content.scss
  docroot/themes/custom/vagovclaro/assets/scss/components/_external_content.scss
Labels: Facilities

#17222 VACMS-17221: Restore field_intro_text
  config/sync/field.field.node.vba_facility.field_intro_text.yml
Labels: Facilities

#17154 VACMS-16853: next build branches ftw
  .tugboat/config.yml
  READMES/cms-content-release.md
  config/sync/next.next_site.next_build_preview_server.yml
  docroot/modules/custom/va_gov_content_release/README.md
  docroot/modules/custom/va_gov_content_release/src/Form/NextGitForm.php
  docroot/modules/custom/va_gov_content_release/src/FrontendVersionSearch/FrontendVersionSearch.php
  docroot/modules/custom/va_gov_content_release/va_gov_content_release.module
  docroot/modules/custom/va_gov_content_release/va_gov_content_release.routing.yml
  docroot/modules/custom/va_gov_content_release/va_gov_content_release.services.yml
  docroot/modules/custom/va_gov_git/src/BranchSearch/Factory/BranchSearchFactory.php
  docroot/modules/custom/va_gov_git/src/BranchSearch/Factory/BranchSearchFactoryInterface.php
  docroot/modules/custom/va_gov_git/src/Repository/Factory/RepositoryFactory.php
  docroot/modules/custom/va_gov_git/src/Repository/Factory/RepositoryFactoryInterface.php
  docroot/modules/custom/va_gov_git/src/Repository/Settings/RepositorySettings.php
  docroot/modules/custom/va_gov_git/src/Repository/Settings/RepositorySettingsInterface.php
  docroot/modules/custom/va_gov_git/va_gov_git.services.yml
  docroot/modules/custom/va_gov_github/src/Api/Client/Factory/ApiClientFactory.php
  docroot/modules/custom/va_gov_github/src/Api/Client/Factory/ApiClientFactoryInterface.php
  docroot/modules/custom/va_gov_github/va_gov_github.services.yml
  docroot/sites/default/settings.php
  docroot/sites/default/settings/settings.tugboat.php
  scripts/next-build-frontend.sh
  scripts/next-build.sh
  scripts/next-install.sh
  scripts/queue_runner/next_queue_runner.sh
  tests/phpunit/va_gov_git/functional/Repository/Settings/RepositorySettingsTest.php
  tests/phpunit/va_gov_git/unit/Repository/Settings/RepositorySettingsTest.php
Labels: Accelerated Publishing, CMS Team

#17293 VACMS-17289: added patch to fix core bug fro Unable to update operating status
  composer.json
  composer.lock
Labels: CMS Team

#17303 VACMS-14667: Fixes remaining character count on Staff Profile form.
  config/sync/core.entity_form_display.node.person_profile.default.yml
Labels: Facilities

#17348 VACMS-14136: Editors should not be able to rename VAMC facility services.
  docroot/modules/custom/va_gov_vamc/src/EventSubscriber/VAMCEntityEventSubscriber.php
  docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
  tests/cypress/integration/features/content_type/facilities/vamc/health_care_local_health_service.feature
  tests/cypress/integration/features/content_type/facilities/vet_center/vet_center_facility_service.feature
Labels: Facilities

#17161 VACMS-15686: Swaps mental health phone fields
  config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_form_display.node.health_care_local_facility.inline_entity_form.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.external_content.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.ief_table.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.teaser.yml
  config/sync/field.field.node.health_care_local_facility.field_mental_health_contact_phon.yml
  config/sync/field.field.node.health_care_local_facility.field_mental_health_phone.yml
  config/sync/field.storage.node.field_mental_health_contact_phon.yml
  config/sync/migrate_plus.migration.va_node_health_care_local_facility.yml
  docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility.yml
  docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php
Labels: Facilities, Awaiting Official Launch

#17213 VACMS-17114: Service location fields lighthouse push
  docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityServiceVamc.php
Labels: Facilities
