Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2024-07, with the labels that each got.

#18414 VACMS-17977: Updates the VBA-related code for launch
  docroot/modules/custom/va_gov_content_types/src/Interfaces/IsFacilityInterface.php
  docroot/modules/custom/va_gov_facilities/src/FacilityOps.php
  tests/phpunit/va_gov_content_types/functional/Traits/IsFacilityTraitTest.php
  tests/phpunit/va_gov_content_types/unit/Traits/IsFacilityTraitTest.php
Labels: Facilities

#18442 VACMS-17885: Create facility services links on VBA Facility page
  config/sync/core.entity_form_display.node.vba_facility.default.yml
  config/sync/field.field.node.vba_facility_service.field_administration.yml
  config/sync/field.field.node.vba_facility_service.field_office.yml
  docroot/modules/custom/va_gov_vba_facility/src/EventSubscriber/VbaFacilitySubscriber.php
Labels: Facilities

#18472 VACMS-18306: Upgraded Drupal diff and fixed two patches.
  composer.json
  composer.lock
Labels: CMS Team

#18509 VACMS-17885 close link tag
  docroot/modules/custom/va_gov_vba_facility/src/EventSubscriber/VbaFacilitySubscriber.php
Labels: Facilities

#18495 VACMS-15737 Rework help text for operating status
  config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
  config/sync/field.field.node.health_care_local_facility.field_operating_status_more_info.yml
Labels: VAMC, Drupal engineering, Facilities, sitewide, Drupal Site Building

#18490 VACMS-18451: create rates editor role
  config/sync/system.action.user_add_role_action.business_line_editor.yml
  config/sync/system.action.user_remove_role_action.business_line_editor.yml
  config/sync/user.role.business_line_editor.yml
Labels: CMS Team

#18694 VACMS-18693: removing package.json packages from dependabot
  .github/dependabot.yml
Labels: CMS Team

#18542 VACMS-18281 Added character counters & help text to phone paragraph type
  config/sync/core.entity_form_display.paragraph.phone_number.default.yml
  config/sync/field.field.paragraph.phone_number.field_phone_extension.yml
  config/sync/field.field.paragraph.phone_number.field_phone_label.yml
  config/sync/field.field.paragraph.phone_number.field_phone_number.yml
  config/sync/field.field.paragraph.phone_number.field_phone_number_type.yml
Labels: Facilities, sitewide

#18707 VACMS-18701: updated composer dependencies
  composer.json
  composer.lock
  config/sync/system.action.message_delete_action.yml
  patches/3463201-fix-for-change-in-class-for-toolbar.patch
Labels: CMS Team

#18717 VATEAM-87711: Add Digital Form content type
  config/sync/core.base_field_override.node.digital_form.promote.yml
  config/sync/core.base_field_override.node.digital_form.title.yml
  config/sync/core.entity_form_display.node.digital_form.default.yml
  config/sync/core.entity_view_display.node.digital_form.default.yml
  config/sync/core.entity_view_display.node.digital_form.external_content.yml
  config/sync/core.entity_view_display.node.digital_form.teaser.yml
  config/sync/field.field.node.digital_form.field_administration.yml
  config/sync/field.field.node.digital_form.field_last_saved_by_an_editor.yml
  config/sync/field.field.node.digital_form.field_meta_tags.yml
  config/sync/field.field.node.digital_form.field_omb_number.yml
  config/sync/field.field.node.digital_form.field_va_form_number.yml
  config/sync/field.storage.node.field_omb_number.yml
  config/sync/language.content_settings.node.digital_form.yml
  config/sync/node.type.digital_form.yml
  config/sync/prometheus_exporter.settings.yml
  config/sync/workflows.workflow.editorial.yml
  docroot/modules/custom/va_gov_content_types/src/Entity/DigitalForm.php
  docroot/modules/custom/va_gov_content_types/va_gov_content_types.module
  tests/phpunit/va_gov_content_types/functional/Entity/DigitalFormTest.php
Labels: CMS Team

#18809 VACMS-18807: updated geo modules
  composer.lock
Labels: CMS Team
