Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2024-10, with the labels that each got.

#19388 VAMCS-19329: filter unexpected log messages containing pii
  config/dev/syslog.settings.yml
  config/prod/syslog.settings.yml
  config/stg/syslog.settings.yml
  docroot/modules/custom/va_gov_backend/src/Logger/Processor/DatadogLevelProcessor.php
  docroot/modules/custom/va_gov_backend/src/Service/TestLogging.php
  docroot/modules/custom/va_gov_backend/src/Service/TestLoggingInterface.php
  docroot/modules/custom/va_gov_backend/va_gov_backend.services.yml
  docroot/sites/default/services/services.dev.yml
  docroot/sites/default/services/services.monolog.yml
  docroot/sites/default/services/services.prod.yml
  docroot/sites/default/services/services.staging.yml
Labels: CMS Team

#19129 VACMS-19128: adding patch for eca module
  composer.json
  composer.lock
  patches/3472437-instatiate-against-file-system-interface.patch
Labels: CMS Team

#19472 VACMS-17854: Add feature toggle to display old/new telephone fields conditionally
  composer.json
  composer.lock
  config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_form_display.node.health_care_local_facility.inline_entity_form.yml
  config/sync/core.entity_form_display.node.person_profile.default.yml
  config/sync/core.entity_form_display.node.person_profile.inline_entity_form.yml
  config/sync/core.entity_form_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_form_display.taxonomy_term.va_benefits_taxonomy.default.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_view_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_view_display.taxonomy_term.va_benefits_taxonomy.default.yml
  config/sync/feature_toggle.features.yml
  config/sync/field.field.taxonomy_term.va_benefits_taxonomy.field_application_process.yml
  config/sync/field.storage.taxonomy_term.field_application_process.yml
  config/sync/views.view.rich_text_field_audit.yml
  docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php
  docroot/modules/custom/va_gov_post_api/va_gov_post_api.services.yml
  docroot/modules/custom/va_gov_profile/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_profile/va_gov_profile.services.yml
  docroot/modules/custom/va_gov_vamc/src/EventSubscriber/VAMCEntityEventSubscriber.php
  docroot/modules/custom/va_gov_vamc/va_gov_vamc.services.yml
  tests/cypress/integration/features/content_type/facilities/vamc/health_care_local_facility.feature
  tests/cypress/integration/features/content_type/person_profile.feature
Labels: Facilities

#19493 VACMS-19463: Install, enable, and configure ga4 module.
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/ga4_google_analytics.config.yml
Labels: CMS Team

#19401 VACMS-19199: Adds Manila VA Clinic to Menu Breadcrumbs
  config/sync/menu_breadcrumb.settings.yml
  config/sync/system.menu.manila-va-clinic.yml
  config/sync/va_gov_menu_access.settings.yml
Labels: Facilities

#19225 VACMS-17860: Telephone Migrations Integration
  .ddev/mutagen/mutagen.yml
  .ddev/nginx_full/nginx-site.conf
  .github/CODEOWNERS
  composer.json
  composer.lock
  config/sync/codit_batch_operations.settings.yml
  config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_form_display.node.health_care_local_facility.inline_entity_form.yml
  config/sync/core.entity_form_display.node.person_profile.default.yml
  config/sync/core.entity_form_display.node.person_profile.inline_entity_form.yml
  config/sync/core.entity_form_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.external_content.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.ief_table.yml
  config/sync/core.entity_view_display.node.health_care_local_facility.teaser.yml
  config/sync/core.entity_view_display.node.person_profile.default.yml
  config/sync/core.entity_view_display.node.person_profile.teaser.yml
  config/sync/core.entity_view_display.node.vamc_system_billing_insurance.default.yml
  config/sync/core.entity_view_display.node.vamc_system_billing_insurance.search_index.yml
  config/sync/core.entity_view_display.node.vamc_system_billing_insurance.teaser.yml
  config/sync/core.extension.yml
  config/sync/feature_toggle.features.yml
  config/sync/field.field.node.health_care_local_facility.field_telephone.yml
  config/sync/field.field.node.person_profile.field_telephone.yml
  config/sync/field.field.node.vamc_system_billing_insurance.field_telephone.yml
  config/sync/field.storage.node.field_telephone.yml
  config/sync/language/es/views.view.batch_operation_logs.yml
  config/sync/views.view.batch_operation_logs.yml
  config/sync/views.view.rich_text_field_audit.yml
  docroot/modules/custom/va_gov_batch/README.md
  docroot/modules/custom/va_gov_batch/src/cbo_scripts/MigratePhoneFieldToParagraph.php
  docroot/modules/custom/va_gov_batch/src/cbo_scripts/MigrateVamcBillingInsurancePhoneFieldToParagraph.php
  docroot/modules/custom/va_gov_batch/src/cbo_scripts/MigrateVamcFacilityMentalHealthPhoneFieldToParagraph.php
  docroot/modules/custom/va_gov_batch/va_gov_batch.info.yml
  docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php
  docroot/modules/custom/va_gov_post_api/va_gov_post_api.services.yml
  docroot/modules/custom/va_gov_profile/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_profile/va_gov_profile.services.yml
  docroot/modules/custom/va_gov_vamc/src/EventSubscriber/VAMCEntityEventSubscriber.php
  docroot/modules/custom/va_gov_vamc/va_gov_vamc.services.yml
  tests/cypress/integration/features/content_type/person_profile.feature
  tests/phpunit/va_gov_batch/unit/Class/MigratePhoneFieldToParagraphTest.php
Labels: Facilities, CMS Team

#19522 VACMS-19101: Adds pattern for VBA Facility service
  config/sync/pathauto.pattern.vba_facility_service.yml
Labels: Facilities

#19524 VACMS-19477: catching fopen error, moed temp location of csv
  docroot/modules/custom/va_gov_media/src/Service/VamcPdfDeleteService.php
Labels: CMS Team

#19568 VACMS-19567: remove duplicate block revisions tab
  composer.json
  composer.lock
  patches/3406627-duplicate-blocks-revisions-tabs.patch
Labels: CMS Team

#19585 VAMCS-12554: Fix for accessibility issue on CM documents search.
  docroot/themes/custom/vagovclaro/templates/form/form-element--views--content-model-documents--cm-documents--for.html.twig
  docroot/themes/custom/vagovclaro/templates/form/form-element-label--views--content-model-documents--cm-documents--for.html.twig
Labels: CMS Team

#19603 VACMS-18728: Update drush devel and webflo and update logger.
  composer.json
  composer.lock
  docroot/modules/custom/va_gov_build_trigger/src/Commands/ContentReleaseCommands.php
Labels: CMS Team

#19604 VACMS-19496: Installation and enabling of content_sync module with settings, a README, and an exported piece of content.
  composer.json
  composer.lock
  content/sync/README.md
  content/sync/node.campaign_landing_page.e5098165-e0d3-4ecb-817d-9b979878ce09.yml
  docroot/sites/default/settings.php
Labels: CMS Team

#19681 VACMS-19675: updated deploy shield message
  docroot/sites/default/maintenance.html
Labels: CMS Team
