Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2025-01, with the labels that each got.

#20109 VACMS-19098: VBA Facility Workflow Notifications
  config/sync/advancedqueue.advancedqueue_queue.content_worfkow.yml
  config/sync/core.entity_form_display.message.vba_facility_draft_content.default.yml
  config/sync/core.entity_view_display.message.vba_facility_draft_content.default.yml
  config/sync/core.entity_view_display.message.vba_facility_draft_content.mail_body.yml
  config/sync/core.entity_view_display.message.vba_facility_draft_content.mail_subject.yml
  config/sync/core.extension.yml
  config/sync/eca.eca.workflow_vba_facility_as_draft.yml
  config/sync/field.field.message.vba_facility_draft_content.field_last_updated_by_editor.yml
  config/sync/field.field.message.vba_facility_draft_content.field_target_node_path.yml
  config/sync/field.field.message.vba_facility_draft_content.field_target_node_title.yml
  config/sync/field.storage.message.field_last_updated_by_editor.yml
  config/sync/field.storage.message.field_target_node_path.yml
  config/sync/language/en/message.template.vba_facility_draft_content.yml
  config/sync/mailsystem.settings.yml
  config/sync/message.template.vba_facility_draft_content.yml
  docroot/modules/custom/va_gov_notifications/src/JobTypeMessageNotifyBase.php
  docroot/modules/custom/va_gov_notifications/src/Plugin/AdvancedQueue/JobType/WorkflowContentNotification.php
  docroot/modules/custom/va_gov_notifications/templates/message--vba-facility-draft-content--mail-body.html.twig
  docroot/modules/custom/va_gov_notifications/va_gov_notifications.module
  tests/phpunit/va_gov_notifications/kernel/JobTypeMessageNotifyBaseTest.php
Labels: Needs PO review

#20218 VACMS-19623: Phone label should not show in some forms
  docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_profile/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_vamc/src/EventSubscriber/VAMCEntityEventSubscriber.php
  tests/cypress/integration/features/content_type/person_profile.feature
Labels: Facilities

#20141 VACMS-20140: patch to fix warning about accepting cookies in the browser
  composer.json
  composer.lock
  core
  patches/3397718-must-accept-cookies.patch
Labels: CMS Team

#20275 VACMS-17896: Allows all forms or selected forms.
  composer.json
  composer.lock
  config/sync/clientside_validation.settings.yml
  patches/2949540-allow-all-forms-selected-forms.patch
  tests/cypress/integration/features/content_type/facilities/manila.feature
  tests/cypress/integration/step_definitions/common/i_create_a_node.js
Labels: Facilities, CMS Team

#20301 VACMS-19974: Adds help text to general field
  config/sync/field.field.block_content.connect_with_us.field_external_link.yml
Labels: Facilities

#20303 VACMS-19794: Removes Connect with us tech debt
  config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_form_display.node.landing_page.default.yml
  config/sync/core.entity_form_display.node.office.default.yml
  config/sync/core.entity_view_display.node.campaign_landing_page.default.yml
  config/sync/core.entity_view_display.node.campaign_landing_page.teaser.yml
  config/sync/core.entity_view_display.node.landing_page.default.yml
  config/sync/core.entity_view_display.node.landing_page.support_services_listing.yml
  config/sync/core.entity_view_display.node.landing_page.teaser.yml
  config/sync/core.entity_view_display.node.office.connect_with_us.yml
  config/sync/core.entity_view_display.node.office.default.yml
  config/sync/core.entity_view_display.node.office.teaser.yml
  config/sync/core.entity_view_mode.node.connect_with_us.yml
  config/sync/field.field.node.campaign_landing_page.field_related_office.yml
  config/sync/field.field.node.landing_page.field_related_office.yml
  config/sync/field.field.node.office.field_email_updates_link.yml
  config/sync/field.field.node.office.field_external_link.yml
  config/sync/field.field.node.office.field_social_media_links.yml
  config/sync/field.storage.node.field_email_updates_link.yml
  config/sync/field.storage.node.field_external_link.yml
  config/sync/field.storage.node.field_related_office.yml
  config/sync/field.storage.node.field_social_media_links.yml
  config/sync/views.view.content_entity_reference_source.yml
  docroot/themes/custom/vagovclaro/templates/node/node--office--connect-with-us.html.twig
Labels: Facilities

#20309 VACMS-8251: Updates FWB help text, removing op status
  config/sync/node.type.full_width_banner_alert.yml
Labels: Facilities

#20321 VACMS-20320: adds CSS for better browser validation UX
  docroot/themes/custom/vagovclaro/assets/scss/components/_elements.scss
Labels: CMS Team

#20341 Set page cache from one day to one hour.
  config/sync/system.performance.yml
Labels: CMS Team

#20362 VACMS-20262: Adds JS change to remove VBA service descriptions
  docroot/modules/custom/va_gov_facilities/js/displayServiceDescriptions.es6.js
  docroot/modules/custom/va_gov_facilities/js/displayServiceDescriptions.js
  docroot/modules/custom/va_gov_lovell/js/winnowServiceNamesTricare.es6.js
  docroot/modules/custom/va_gov_lovell/js/winnowServiceNamesTricare.js
Labels: Facilities
