Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2025-05, with the labels that each got.

#21310 VACMS-21301: VAMC Facility Health Service bug for facilities with no existing services
  docroot/modules/custom/va_gov_facilities/va_gov_facilities.module
Labels: CMS Team

#21302 initial tests for JSON API
  READMES/testing.md
  tests/cypress/integration/features/api/event.feature
  tests/cypress/integration/features/api/event_listing.feature
Labels: CMS Team

#21318 VACMS-21087: create view for recently changed content
  config/sync/views.view.content.yml
  docroot/themes/custom/vagovclaro/assets/scss/components/_buttons.scss
Labels: Drupal engineering, CMS Team

#21325 VACMS-21274: update va-gov/content-build
  composer.json
  composer.lock
Labels: Drupal engineering, CMS Team

#21324 VACMS-21096: Adds a test for insecure_uploads and a runtime setting.
  docroot/sites/default/settings.php
  tests/phpunit/Security/AllowInsecureUploadsTest.php
Labels: CMS Team

#21340 VACMS-21275: update content-build
  composer.json
  composer.lock
Labels: Drupal engineering, CMS Team

#21355 bring phpunit test up to psr4 standard
  tests/phpunit/Deploy/DeployServiceTest.php
  tests/phpunit/Deploy/Plugins/HealthCheckTest.php
  tests/phpunit/Logging/DatadogApmProcessorTest.php
  tests/phpunit/va_gov_form_builder/functional/Form/IntroductionTest.php
  tests/phpunit/va_gov_form_builder/functional/pages/AddressInfoTest.php
  tests/phpunit/va_gov_form_builder/functional/pages/ContactInfoTest.php
  tests/phpunit/va_gov_form_builder/functional/pages/HomeTest.php
  tests/phpunit/va_gov_form_builder/functional/pages/IdentificationInfoTest.php
  tests/phpunit/va_gov_form_builder/functional/pages/LayoutTest.php
  tests/phpunit/va_gov_form_builder/functional/pages/NameAndDobTest.php
  tests/phpunit/va_gov_form_builder/functional/pages/ReviewAndSignTest.php
  tests/phpunit/va_gov_form_builder/functional/pages/ViewFormTest.php
  tests/phpunit/va_gov_form_builder/unit/Traits/EntityReferenceRevisionsOperationsTest.php
  tests/phpunit/va_gov_git/functional/Repository/RepositoryTest.php
Labels: Drupal engineering, CMS Team

#21341 VACMS-20423: Fix featured field automation bug
  config/sync/views.view.content.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
Labels: CMS Team

#21392 VACMS-20787: catalog all tasks being run by jenkins for cms
  READMES/devops/jenkins-jobs.md
Labels: DevOps, CMS Team
