Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2025-03, with the labels that each got.

#20730 VACMS-20371: Clean up extensions
  docroot/modules/custom/va_gov_batch/src/cbo_scripts/RemoveNonNumericalCharactersFromExtensions.php
  docroot/modules/custom/va_gov_batch/src/cbo_scripts/SplitExtensionWithTwoNumbers.php
Labels: Facilities

#20758 VACMS-20750: updated content-build
  composer.json
  composer.lock
Labels: CMS Team

#20651 VACMS-17863: Adds validation to ext field in phone paragraph.
  docroot/modules/custom/va_gov_backend/js/phone_extension.es6.js
  docroot/modules/custom/va_gov_backend/js/phone_extension.js
  docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/ValidNumeric.php
  docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/ValidNumericValidator.php
  docroot/modules/custom/va_gov_backend/va_gov_backend.libraries.yml
  docroot/modules/custom/va_gov_backend/va_gov_backend.module
  tests/cypress/integration/features/content_type/person_profile.feature
  tests/phpunit/Content/ValidNumericValidatorTest.php
Labels: Facilities, DO NOT MERGE

#20845 VACMS-20844: refactored cron jobs to address syntax changes
  tasks-periodic.yml
Labels: CMS Team

#20866 VACMS-20606: Adds VA Manila health care menu
  config/sync/menu_breadcrumb.settings.yml
  config/sync/node.type.event.yml
  config/sync/node.type.event_listing.yml
  config/sync/node.type.health_care_local_facility.yml
  config/sync/node.type.health_care_region_detail_page.yml
  config/sync/node.type.health_care_region_page.yml
  config/sync/node.type.health_services_listing.yml
  config/sync/node.type.leadership_listing.yml
  config/sync/node.type.locations_listing.yml
  config/sync/node.type.news_story.yml
  config/sync/node.type.person_profile.yml
  config/sync/node.type.press_release.yml
  config/sync/node.type.press_releases_listing.yml
  config/sync/node.type.publication_listing.yml
  config/sync/node.type.story_listing.yml
  config/sync/node.type.vamc_operating_status_and_alerts.yml
  config/sync/node.type.vamc_system_billing_insurance.yml
  config/sync/node.type.vamc_system_medical_records_offi.yml
  config/sync/node.type.vamc_system_policies_page.yml
  config/sync/node.type.vamc_system_register_for_care.yml
  config/sync/node.type.vamc_system_va_police.yml
  config/sync/system.menu.va-manila-health-care.yml
Labels: Facilities

#20803 added openID connect module
  composer.json
  composer.lock
  config/sync/core.extension.yml
  config/sync/openid_connect.settings.facebook.yml
  config/sync/openid_connect.settings.generic.yml
  config/sync/openid_connect.settings.github.yml
  config/sync/openid_connect.settings.google.yml
  config/sync/openid_connect.settings.linkedin.yml
  config/sync/openid_connect.settings.okta.yml
  config/sync/openid_connect.settings.yml
Labels: CMS Team

#20939 VACMS-20937: update content-build
  composer.json
  composer.lock
Labels: CMS Team

#20887 VACMS-20606: revert manila
  config/sync/core.extension.yml
  config/sync/va_gov_menu_access.settings.yml
  docroot/modules/custom/va_gov_batch/src/cbo_scripts/ChangeManilaMenuContent.php
  docroot/modules/custom/va_gov_batch/src/cbo_scripts/ChangeManilaTermLabel.php
  docroot/modules/custom/va_gov_facilities/va_gov_facilities.install
  docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php
  tests/cypress/integration/features/content_type/facilities/manila.feature
Labels: Facilities

#20967 updated content-build to 0.0.3710
  composer.json
  composer.lock
Labels: CMS Team

#20968 VACMS-20928: Updated Drupal Core to version 10.3.14
  composer.lock
Labels: CMS Team

#21044 VACMS-20902: Content-build-dependency_20250331
  composer.json
  composer.lock
Labels: CMS Team
