Repository department-of-veterans-affairs/va.gov-cms, pull requests merged in 2025-09, with the labels that each got.

#22139 VACMS-20443: Adds API cypress test for VAMC System
  tests/cypress/integration/features/api/vamc_police.feature
  tests/cypress/integration/features/api/vamc_system.feature
Labels: CMS Team

#22151 VACMS-20461: Adds cypress test for locations listing
  tests/cypress/integration/features/api/locations_listing.feature
Labels: CMS Team

#22105 VACMS-22068: Adds modal for entities with usage
  config/sync/user.role.admnistrator_users.yml
  config/sync/user.role.content_admin.yml
  config/sync/user.role.content_creator_benefits_hubs.yml
  config/sync/user.role.content_creator_resources_and_support.yml
  config/sync/user.role.content_creator_vba.yml
  config/sync/user.role.content_creator_vet_center.yml
  config/sync/user.role.content_editor.yml
  config/sync/user.role.content_publisher.yml
  config/sync/user.role.content_reviewer.yml
  config/sync/user.role.form_builder_user.yml
  config/sync/user.role.homepage_manager.yml
  config/sync/user.role.office_content_creator.yml
  config/sync/user.role.rates_editor.yml
  config/sync/user.role.redirect_administrator.yml
  config/sync/user.role.translation_manager.yml
  config/sync/user.role.vamc_content_creator.yml
  docroot/modules/custom/va_gov_workflow/js/modal.js
  docroot/modules/custom/va_gov_workflow/js/restore-scroll.js
  docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php
  docroot/modules/custom/va_gov_workflow/src/Service/WorkflowContentControl.php
  docroot/modules/custom/va_gov_workflow/va_gov_workflow.info.yml
  docroot/modules/custom/va_gov_workflow/va_gov_workflow.install
  docroot/modules/custom/va_gov_workflow/va_gov_workflow.libraries.yml
  docroot/modules/custom/va_gov_workflow/va_gov_workflow.module
  docroot/modules/custom/va_gov_workflow/va_gov_workflow.services.yml
  docroot/themes/custom/vagovclaro/assets/scss/components/_elements.scss
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: DO NOT MERGE, CMS Team

#22202 VACMS -21855: update dockerfile for apache
  docker/apache/Dockerfile
  docker/apache/docker-conf-files/install-va-certs.sh
Labels: CMS Team

#22206 VACMS-22129: module updates
  composer.json
  composer.lock
  patches/3111456-resolve-language-issues.patch
Labels: CMS Team

#22279 VACMS-22188: rename opcache conf file so it loads in correct order
  docker/apache/Dockerfile
Labels: CMS Team

#22236 VACMS-21277: add google analytics code
  composer.lock
  config/sync/ga4_google_analytics.config.yml
  docroot/modules/custom/va_gov_media/js/google_analytics.es6.js
  docroot/modules/custom/va_gov_media/js/google_analytics.js
  docroot/modules/custom/va_gov_media/va_gov_media.libraries.yml
  docroot/modules/custom/va_gov_media/va_gov_media.module
  tests/phpunit/Security/RolesPermissionsTest.php
Labels: CMS Team

#22322 VACMS-20738: Remove "closed" operating status from Drupal
  config/sync/field.storage.node.field_operating_status_facility.yml
  docroot/modules/custom/va_gov_migrate/src/Commands/Commands.php
Labels: Facilities
